import { SpeakArticle } from './articles-w01'

export const W53_ARTICLES: SpeakArticle[] = [
  {
    topic: 'New Beginnings',
    title: 'The Threshold',
    wordCount: 301,
    text: `<p>A threshold is not a wall. It is the narrow space between what has ended and what has not yet begun. Standing there can feel unexpectedly quiet. After a year of daily practice, you may expect completion to feel dramatic, but it often arrives gently. It may be nothing more than the realization that you kept returning through busy weeks and ordinary moods until English became part of the rhythm of your year.</p><p>A threshold marks a real difference between one space and another. On one side are the things that have become familiar: the words you practiced, the mistakes you learned from, and the abilities built through repetition. On the other side is what has not yet been decided. You do not need to know exactly what comes next; you only need to recognize that you are no longer standing where you began. People often cross important thresholds without pausing to notice them, carrying the same assumptions forward without choosing them. A pause is not unnecessary sentiment. It creates a moment of clarity, allowing you to ask what deserves to come with you and what should remain behind.</p><p>For speaking practice, use the idea of a threshold to describe your present moment. What are you finishing? What are you beginning? Which skills, habits, or beliefs do you want to carry forward, and what are you ready to leave behind? Speaking honestly about change in a second language requires reflection, emotional vocabulary, and the confidence to describe a life that is still unfolding. A threshold does not demand a grand declaration; it asks only for one honest step. Over the past year, you returned after interruptions and spoke when you were uncertain, even when your sentences were imperfect. What crosses the threshold with you is the ability you built by returning.</p>`,
    textZh: `<p>門檻不是一道牆，而是介於一件事已經結束、另一件事尚未開始之間的狹窄空間。站在那裡時，感覺可能出乎意料地安靜。經過一整年的每日練習，你也許以為完成時應該有某種戲劇性的感受，但它往往只是輕輕到來。也許你只是突然意識到，自己走過了忙碌的星期與平凡的心情，仍然一次次回來，直到英文成為這一年生活節奏的一部分。</p><p>門檻標示著兩個空間之間真實的差異。這一側，是逐漸熟悉的一切：練習過的詞語、從錯誤中學到的事，以及透過反覆累積而來的能力；另一側，則是尚未被決定的未來。你不需要現在就知道接下來會發生什麼，只需要看見，自己已經不再站在最初出發的位置。人們常在沒有真正停下來的情況下，跨過人生中重要的門檻，把原本的假設全都帶了過去，卻沒有重新選擇。停頓並不是多餘的感傷；它是一個讓自己看清楚的時刻，讓你有機會問：哪些東西值得繼續帶著？哪些東西可以留在原地？</p><p>練習口說時，可以用「門檻」這個概念描述自己現在的位置。你正在完成什麼？準備開始什麼？哪些能力、習慣或信念想繼續帶著，又有哪些東西已經可以放下？用第二語言誠實說出人生中的轉變，需要反思、情緒詞彙，以及描述一段仍在展開的人生時所需的信心。門檻不要求宏大的宣言，只需要一個誠實的步伐。過去一年裡，你在中斷後重新回來，在不確定時仍然開口，即使句子不夠完美也繼續練習。真正跟著你跨過門檻的，是你一次次回來時逐漸建立起來的能力。</p>`,
    vocabulary: [
      { word: 'threshold', definition: '門檻；轉折點', example: 'A threshold is the narrow space between what has ended and what has not yet begun.' },
      { word: 'completion', definition: '完成；結束', example: 'Completion often arrives gently instead of feeling dramatic.' },
      { word: 'declaration', definition: '宣告；聲明', example: 'Crossing a threshold does not demand a grand declaration.' },
      { word: 'imperfect', definition: '不完美的', example: 'You kept speaking even when your sentences were imperfect.' },
      { word: 'unfold', definition: '逐漸展開', example: 'It takes confidence to describe a life that is still unfolding.' },
    ],
  },
  {
    topic: 'New Beginnings',
    title: 'Letting Go to Move Forward',
    wordCount: 288,
    text: `<p>Moving forward requires more than making new plans. It also requires letting certain things go. Some parts of the past year deserve to come with you: discipline, patience, useful expressions, and a stronger voice. Other things do not. Guilt about missed practice, comparison with faster learners, and the belief that progress must be perfect before it counts can all be left behind. You can acknowledge what they revealed without continuing to carry their weight.</p><p>Letting go is not the same as forgetting. You can release the guilt of missing a week without pretending the interruption never happened. You can stop punishing yourself for a conversation that went badly while still keeping the lesson it taught you. The difference lies in whether you use the past as information or as evidence against yourself. Language learners may have several things worth releasing: comparison with people who improve more quickly, memories of embarrassing mistakes in front of fluent speakers, or an old belief that learning another language is simply not something they can do. These experiences do not have to become part of your permanent identity.</p><p>For speaking practice, describe one thing you are choosing to leave behind. You might say, "I have decided to stop measuring my progress against other people," or "I have learned what I needed to learn from that period." These sentences are simple, but they require honesty and conviction. Letting go creates space, but choosing what to carry forward matters just as much. The past year has also given you things worth keeping: a larger vocabulary, quicker responses, and a learning habit that survived interruption. You are not beginning again with nothing. You are moving forward with everything you have practiced, learned, and chosen to keep.</p>`,
    textZh: `<p>往前走，不只是訂出新的計畫，也需要放下一些東西。過去這一年裡，有些部分值得繼續帶著，例如自律、耐心、實用的表達，以及逐漸更有力量的聲音；另一些則不必再同行。對中斷練習的內疚、和進步較快的人比較，以及「只有完美的進步才算數」的想法，都可以留在身後。你可以承認它們曾經讓你看見什麼，卻不必繼續承受它們的重量。</p><p>放下並不等於遺忘。你可以不再為中斷一週而責怪自己，同時承認那次中斷確實發生過；也可以停止因一場不順利的對話懲罰自己，卻仍保留其中學到的事。差別在於，你是把過去當成資訊，還是拿它作為否定自己的證據。對語言學習者來說，也許有幾件事特別值得放下：和進步更快的人比較、在流利使用者面前出糗的記憶，或是那個「我就是學不會另一種語言」的舊信念。這些經驗不必成為永久的自我認定。</p><p>練習口說時，可以描述一件自己決定不再帶著走的事。你可以說：「I have decided to stop measuring my progress against other people.」或「I have learned what I needed to learn from that period.」這些句子不複雜，卻需要誠實與堅定。放下會創造空間，但選擇要帶走什麼同樣重要。過去這一年也留下了許多值得保留的東西：更充足的詞彙、更快的反應，以及即使中斷後仍能重新回來的學習習慣。你不是從一無所有重新開始；你帶著所有練習過、學會了，也決定留下的能力繼續前進。</p>`,
    vocabulary: [
      { word: 'release', definition: '釋放；放下', example: 'You can release old guilt without pretending the interruption never happened.' },
      { word: 'comparison', definition: '比較', example: 'Comparison with faster learners is one thing worth leaving behind.' },
      { word: 'conviction', definition: '堅定的信念', example: 'Saying what you will no longer carry requires honesty and conviction.' },
      { word: 'embarrassing', definition: '令人尷尬的', example: 'An embarrassing mistake does not have to become part of your identity.' },
      { word: 'punish', definition: '懲罰', example: 'Stop punishing yourself for a conversation that went badly.' },
    ],
  },
  {
    topic: 'New Beginnings',
    title: 'Designing the Year Ahead',
    wordCount: 292,
    text: `<p>Designing the year ahead is different from trying to control it. Control assumes that life will follow the plan if the plan is detailed enough. Design is more realistic. It asks what conditions will help good choices survive ordinary disruptions: tired days, family responsibilities, demanding work, travel, disappointment, and boredom. A useful plan provides anchors without becoming a set of chains. Good design begins with constraints rather than wishes.</p><p>Before deciding what to add to the coming year, identify what is already fixed: work responsibilities that cannot be moved, family commitments that require time, and seasons when your energy is usually lower. These realities are not flaws in the plan; they are the structure within which the plan must work. Planning English practice requires particular honesty about time. How many minutes can you realistically maintain, including during tired evenings and disrupted weeks? A shorter routine repeated several times a week is often easier to sustain than one long session that happens only occasionally. The best schedule is not the most ambitious one; it is the one that remains usable in real life.</p><p>For speaking practice, explain your plan aloud for two minutes. Describe your goal, the approach you intend to use, the obstacles you already expect, and one form of support that could help you continue. Speaking through a plan in English forces you to make it more specific and may reveal weak points before daily life exposes them. A designed year is not a controlled year, and unexpected events will still arrive. What matters is whether the plan has enough flexibility to absorb them without disappearing. Design for an ordinary week rather than your most energetic one. A plan that can live inside ordinary weeks is far more likely to endure.</p>`,
    textZh: `<p>設計未來一年，和試圖控制未來一年並不相同。控制是假設只要計畫夠詳細，生活就會照著安排前進；設計則更貼近現實。它會問：面對疲憊的日子、家庭責任、繁重工作、旅行、失望與無聊時，哪些條件能幫助好的選擇繼續存在？真正有用的計畫會提供穩定的支點，而不是把人綁住的鎖鏈。好的設計會先從限制條件開始，而不是只從願望開始。</p><p>決定明年要增加什麼以前，先辨認哪些事情已經固定：無法移動的工作責任、需要投入時間的家庭安排，以及自己通常精力較低的時期。這些現實算不上計畫中的缺陷，它們是所有安排都必須容納的基本結構。安排英文練習時，更需要誠實看待自己的時間。即使把疲憊的晚上與行程被打亂的星期算進去，你每天究竟能長期維持幾分鐘？比起偶爾進行一次很長的練習，一週重複幾次的短時間安排，通常更容易持續。最好的行程，是真正能放進現實生活裡的那一個，而不是最有企圖心的。</p><p>練習口說時，可以用兩分鐘大聲說明自己的計畫。描述你的目標、準備採取的方法、已經預想到的阻礙，以及一種能讓你持續下去的支持方式。用英文把計畫說出來，會迫使你把內容變得更具體，也可能在日常生活揭露問題以前，先讓你發現其中的缺口。經過設計的一年，仍然不會是一個完全受控的一年，意外仍然會發生。真正重要的是，計畫是否具有足夠的彈性，能承受變化而不至於整個消失。請依照一個普通星期來設計，而不是依照自己狀態最好的一週。能在平常日子裡繼續運作的計畫，才最可能長久維持。</p>`,
    vocabulary: [
      { word: 'constraint', definition: '限制；約束', example: 'Good design begins with constraints rather than wishes.' },
      { word: 'disruption', definition: '中斷；干擾', example: 'A useful plan helps good choices survive ordinary disruptions.' },
      { word: 'absorb', definition: '吸收；承受', example: 'A flexible plan can absorb unexpected events without disappearing.' },
      { word: 'endure', definition: '持久；撐過', example: 'A plan built for ordinary weeks is far more likely to endure.' },
      { word: 'sustain', definition: '維持；支撐', example: 'A short routine you can sustain beats a long one you keep skipping.' },
    ],
  },
  {
    topic: 'New Beginnings',
    title: 'The Last Day and the First Step',
    wordCount: 320,
    text: `<p>The final day of a course is also the first day of learning without the course guiding every step. That transition can bring both pride and uncertainty. For a year, the path was prepared for you: one date, one topic, one article, and one opportunity to speak. Tomorrow, the structure becomes lighter. That is not a loss; it is the purpose of learning: to carry the voice you developed into situations no lesson could predict.</p><p>The outside world does not suddenly change when a structured program ends. You wake up in the same home and meet the same people; the change happens inside. The support structure is removed, and you begin to see what you can now do on your own. Some learners find they are more confident than they realized; others find the routine supported them more than they knew. Both insights are valuable because they show what the next stage of learning needs. The first step after a course ends does not need to be ambitious. It only needs to keep your connection with English alive: one message written in English, or one word looked up out of genuine curiosity. These small actions may not feel like achievements, but they are how ability is maintained.</p><p>For the final speaking exercise, describe what you are taking with you and what you will do during the first week after the course. Keep the answer specific. What skill, habit, or attitude do you want to continue? What is one realistic action you will take? A clear plan spoken aloud is more useful than a vague promise. The value of 365 lessons is revealed by what they make possible afterward. Vocabulary begins to appear in real emails, and returning to English becomes part of how you communicate. What you built this year is not a finished result; it is a foundation that can continue growing whenever you use it. Take one small step.</p>`,
    textZh: `<p>一門課的最後一天，也是你開始不再依靠課程逐步引導、自己繼續學習的第一天。這個轉換可能同時帶來成就感與不確定。過去一年裡，學習路徑已經替你安排好：每天一個日期、一個主題、一篇文章，以及一次開口練習的機會。明天開始，外在結構會變得比較少。這並不是失去，而正是學習的目的：把自己逐漸建立起來的聲音，帶進任何課程都無法事先預測的情境中。</p><p>有結構的計畫結束時，常會帶來一種奇特的感覺，因為外在生活並不會突然改變。你仍然在同一個地方醒來、面對熟悉的人，真正的改變發生在內在。原本支撐學習的架構逐漸退場，而你開始看見，自己已經能獨立完成哪些事。有些學習者會發現，自己其實比想像中更有自信；也有人會察覺，原本的固定安排提供了比預期更多的支持。這兩種體悟都很重要，因為它們能幫助你看清下一個學習階段需要什麼。課程結束後的第一步不需要很有企圖心，只要能讓你和英文之間的連結繼續存在：用英文寫一則訊息，或因為真的好奇而查一個單字。這些小行動也許不像成就，卻正是維持能力的方式。</p><p>最後一次口說練習，可以描述你想從這門課帶走什麼，以及課程結束後的第一週準備做什麼。回答時盡量具體：你想延續哪一項能力、習慣或態度？你會採取哪一個實際可行的行動？把清楚的計畫說出口，會比模糊地告訴自己「以後要繼續」更有幫助。三百六十五堂課真正的價值，會表現在課程結束後它們讓哪些事情成為可能。學過的單字開始進入真實郵件，每天回到英文的習慣也逐漸成為你溝通的一部分。這一年建立的能力並不是已經完成的成果；它更像一個能在持續使用中繼續成長的基礎。先踏出一個小小的步驟。</p>`,
    vocabulary: [
      { word: 'transition', definition: '過渡；轉換', example: 'The transition from guided lessons to independent learning brings pride and uncertainty.' },
      { word: 'insight', definition: '洞察；體悟', example: 'Both insights are valuable because they show what the next stage needs.' },
      { word: 'maintain', definition: '維持', example: 'Small daily actions are how ability is maintained.' },
      { word: 'pride', definition: '自豪；驕傲', example: 'Finishing the course brings a quiet sense of pride.' },
      { word: 'attitude', definition: '態度', example: 'Decide which skill, habit, or attitude you want to carry into next year.' },
    ],
  },
]
