import { SpeakArticle } from './articles-w01'

export const W41_ARTICLES: SpeakArticle[] = [
  {
    dateKey: '2026-10-05',
    topic: 'Values & Beliefs',
    title: 'What We Stand For: Values, Principles, and Beliefs',
    wordCount: 515,
    text: '<p>There is something about what we stand for: values, principles, and beliefs that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of what we stand for: values, principles, and beliefs that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with what we stand for: values, principles, and beliefs, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate what we stand for: values, principles, and beliefs well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about what we stand for: values, principles, and beliefs in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於What We Stand For: Values, Principles, and Beliefs，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。What We Stand For: Values, Principles, and Beliefs中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與What We Stand For: Values, Principles, and Beliefs有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對What We Stand For: Values, Principles, and Beliefs的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對What We Stand For: Values, Principles, and Beliefs得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'core value', definition: '一個人真正想守住、而且會影響選擇的核心價值', example: 'What surprised her most about core value was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'guiding principle', definition: '幫助一個人在複雜情況裡判斷方向的基本原則', example: 'The conversation shifted when she introduced the idea of guiding principle and everyone in the room went quiet.' },
      { word: 'moral instinct', definition: '一個人對對錯、合不合適的直覺感受', example: 'Once she started paying attention to moral instinct, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'value conflict', definition: '兩個重要價值同時成立，卻彼此拉扯的狀態', example: 'Once she started paying attention to value conflict, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'loyalty pressure', definition: '因為在意關係或立場，而不敢說真話的壓力', example: 'She finally understood what loyalty pressure meant when she had to apply it under real pressure at work.' }
    ],
  },
  {
    dateKey: '2026-10-06',
    topic: 'Values & Beliefs',
    title: 'Where Our Values Come From',
    wordCount: 500,
    text: '<p>There is something about where our values come from that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of where our values come from that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with where our values come from, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate where our values come from well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about where our values come from in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於Where Our Values Come From，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。Where Our Values Come From中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與Where Our Values Come From有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對Where Our Values Come From的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對Where Our Values Come From得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'family script', definition: '從家庭裡學到、後來默默影響選擇和反應的內在腳本', example: 'After months of ignoring it, he realized that family script was the piece he had been missing all along.' },
      { word: 'social inheritance', definition: '從家庭、環境和文化裡默默承接下來的觀念與反應', example: 'His approach to social inheritance changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'inherited belief', definition: '不是自己重新思考後形成，而是先從他人那裡接下來的信念', example: 'They discovered that inherited belief was not a fixed thing but something that shifted depending on context and energy.' },
      { word: 'early message', definition: '一個人在成長初期反覆接收到、後來影響很深的訊息', example: 'It took a difficult year before he genuinely appreciated what early message could do for the way he worked.' },
      { word: 'cultural norm', definition: '在某個家庭或文化裡被視為理所當然的常見做法', example: 'The conversation shifted when she introduced the idea of cultural norm and everyone in the room went quiet.' }
    ],
  },
  {
    dateKey: '2026-10-07',
    topic: 'Values & Beliefs',
    title: 'When Beliefs Start to Change',
    wordCount: 500,
    text: '<p>There is something about when beliefs start to change that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of when beliefs start to change that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with when beliefs start to change, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate when beliefs start to change well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about when beliefs start to change in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於When Beliefs Start to Change，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。When Beliefs Start to Change中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與When Beliefs Start to Change有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對When Beliefs Start to Change的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對When Beliefs Start to Change得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'belief revision', definition: '原本相信的東西開始被重新檢查和調整的過程', example: 'He described belief revision as the thing that made the difference between a good plan and one that actually worked.' },
      { word: 'certainty crack', definition: '原本很篤定的信念開始出現裂縫的瞬間', example: 'She finally understood what certainty crack meant when she had to apply it under real pressure at work.' },
      { word: 'worldview shift', definition: '一個人看世界的整體方式開始發生轉變', example: 'After months of ignoring it, he realized that worldview shift was the piece he had been missing all along.' },
      { word: 'contradictory evidence', definition: '和原本相信的內容明顯不一致的新證據', example: 'The conversation shifted when she introduced the idea of contradictory evidence and everyone in the room went quiet.' },
      { word: 'identity defense', definition: '當信念被挑戰時，為了保護自我感而出現的防衛反應', example: 'Once she started paying attention to identity defense, she noticed it coming up in conversations she had thought were about something else entirely.' }
    ],
  },
  {
    dateKey: '2026-10-08',
    topic: 'Values & Beliefs',
    title: 'Living According to What You Believe',
    wordCount: 505,
    text: '<p>There is something about living according to what you believe that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of living according to what you believe that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with living according to what you believe, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate living according to what you believe well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about living according to what you believe in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於Living According to What You Believe，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。Living According to What You Believe中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與Living According to What You Believe有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對Living According to What You Believe的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對Living According to What You Believe得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'lived alignment', definition: '一個人的行動和信念大致一致、不是只停在口頭上的狀態', example: 'Once she started paying attention to lived alignment, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'convenience test', definition: '一件事是否還守得住原則，常常要看它不方便時的反應', example: 'After months of ignoring it, he realized that convenience test was the piece he had been missing all along.' },
      { word: 'private behavior', definition: '不是做給別人看，而是私底下真正反覆出現的行為模式', example: 'His approach to private behavior changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'value gap', definition: '口中重視的東西和實際行動之間慢慢拉開的落差', example: 'The conversation shifted when she introduced the idea of value gap and everyone in the room went quiet.' },
      { word: 'repeated choice', definition: '不是一次性的決定，而是日復一日累積方向的反覆選擇', example: 'Once she started paying attention to repeated choice, she noticed it coming up in conversations she had thought were about something else entirely.' }
    ],
  },
  {
    dateKey: '2026-10-09',
    topic: 'Values & Beliefs',
    title: 'Disagreeing with People You Respect',
    wordCount: 500,
    text: '<p>There is something about disagreeing with people you respect that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of disagreeing with people you respect that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with disagreeing with people you respect, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate disagreeing with people you respect well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about disagreeing with people you respect in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於Disagreeing with People You Respect，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。Disagreeing with People You Respect中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與Disagreeing with People You Respect有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對Disagreeing with People You Respect的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對Disagreeing with People You Respect得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'respectful disagreement', definition: '即使立場不同，仍然努力保留尊重的分歧方式', example: 'They discovered that respectful disagreement was not a fixed thing but something that shifted depending on context and energy.' },
      { word: 'shared respect', definition: '即使不同意，仍然承認對方有其價值與尊嚴的基礎尊重', example: 'He described shared respect as the thing that made the difference between a good plan and one that actually worked.' },
      { word: 'listening stance', definition: '不是只等著反駁，而是真正準備接住對方的傾聽姿態', example: 'The conversation shifted when she introduced the idea of listening stance and everyone in the room went quiet.' },
      { word: 'honest tension', definition: '彼此不完全舒服，但仍願意真實面對差異的張力', example: 'Once she started paying attention to honest tension, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'non-negotiable point', definition: '一個人明確知道自己不能退讓的核心立場', example: 'They discovered that non-negotiable point was not a fixed thing but something that shifted depending on context and energy.' }
    ],
  },
  {
    dateKey: '2026-10-10',
    topic: 'Values & Beliefs',
    title: 'What You Refuse to Compromise On',
    wordCount: 505,
    text: '<p>There is something about what you refuse to compromise on that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of what you refuse to compromise on that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with what you refuse to compromise on, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate what you refuse to compromise on well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about what you refuse to compromise on in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於What You Refuse to Compromise On，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。What You Refuse to Compromise On中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與What You Refuse to Compromise On有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對What You Refuse to Compromise On的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對What You Refuse to Compromise On得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'non-negotiable', definition: '一個人清楚知道自己不能再退讓的底線或原則', example: 'It took a difficult year before he genuinely appreciated what non-negotiable could do for the way he worked.' },
      { word: 'red line', definition: '一旦踩到就代表嚴重違背自己原則的界線', example: 'He described red line as the thing that made the difference between a good plan and one that actually worked.' },
      { word: 'moral clarity', definition: '對自己真正不能接受什麼，有比較明確的看見', example: 'She had read about moral clarity in theory, but it only made sense once she saw it working in her own life.' },
      { word: 'hidden cost', definition: '當下看不出來、但之後會慢慢浮現的代價', example: 'She finally understood what hidden cost meant when she had to apply it under real pressure at work.' },
      { word: 'self-betrayal', definition: '明知道不合適，卻還是反覆做出違背自己的選擇', example: 'The conversation shifted when she introduced the idea of self-betrayal and everyone in the room went quiet.' }
    ],
  },
  {
    dateKey: '2026-10-11',
    topic: 'Values & Beliefs',
    title: 'Becoming More Thoughtful About What Matters',
    wordCount: 505,
    text: '<p>There is something about becoming more thoughtful about what matters that resists easy description. You can talk around it easily enough — it comes up in passing, gets mentioned in the middle of other things — but when you actually try to say something precise about your own experience of it, the words tend to fall short. This is not a failure of vocabulary. It is a sign that the subject is real enough to be complicated, and complicated things are usually the ones most worth spending time with.</p><p>Something worth noticing about values & beliefs is how often the difficult parts of it are the same parts that ultimately produce the most useful growth. The aspects of becoming more thoughtful about what matters that create friction — the moments where you have to slow down, reconsider, or deal with something you would rather avoid — are often the moments that teach you the most. This does not make the friction enjoyable. But recognizing what it is for can make it more bearable, and occasionally it can make you genuinely grateful for it after the fact.</p><p>Something that becomes clearer with more experience of values & beliefs is the difference between the things you can control and the things you cannot. This distinction sounds obvious, but applying it in practice is considerably harder than stating it. In the middle of a difficult moment with becoming more thoughtful about what matters, it is easy to either over-invest in trying to control things that are genuinely beyond your influence or under-invest in the things that are actually within your reach. Learning to see this more accurately — in the moment, not just in retrospect — is one of the more valuable skills you can develop.</p><p>The practical question — what do you actually do? — is where a lot of thinking about values & beliefs gets vague. It is much easier to discuss the subject in the abstract than to get specific about the choices you make on a Wednesday afternoon when you are tired and the easiest path is not the best one. That gap between the abstract and the specific is where most of the genuine work happens. People who navigate becoming more thoughtful about what matters well tend to have thought through not just what they believe about it in principle but what they will actually do in the kinds of situations they are likely to encounter.</p><p>Whatever you conclude about becoming more thoughtful about what matters in this period of your life, it is worth holding that conclusion lightly. The subject has a way of expanding as you develop more experience with it, and what seemed settled at one stage often becomes more complicated at the next. This is not a problem — it is the normal process of developing genuine understanding rather than just accumulated opinion. The most useful thing you can take from spending time with values & beliefs is not a fixed answer but an improved capacity to keep asking the question more accurately.</p>',
    textZh: '<p>關於Becoming More Thoughtful About What Matters，有一種東西抵抗簡單的描述。你可以很容易地繞著它說——它在談話中隨口提及，在其他事情的中間被提到——但當你真的嘗試精確說出你自己對它的體驗時，語言往往力不從心。這不是詞彙的失敗，而是這個話題真實到足以複雜的跡象，而複雜的事情通常是最值得花時間去處理的。</p><p>關於Values & Beliefs值得注意的一點是，它困難的部分往往是最終產生最有用成長的部分。Becoming More Thoughtful About What Matters中製造摩擦的面向——你必須放慢速度、重新考慮，或處理你寧願避免的事情的時刻——往往是教給你最多的時刻。這不讓摩擦變得令人愉快。但認識到它的用途，可以使它更容易承受，偶爾在事後還能讓你真正對它感激。</p><p>隨著對Values & Beliefs有更多經驗，變得更清晰的一件事是你能控制的事情和你不能控制的事情之間的區別。這個區分聽起來顯而易見，但在實踐中應用它，比陳述它要難得多。在與Becoming More Thoughtful About What Matters有困難的時刻，很容易過度投資於試圖控制真正超出你影響範圍的事情，或對那些實際上在你掌控範圍內的事情投資不足。學會更準確地看到這一點——在當下，而不只是在事後——是你能培養的更有價值的技能之一。</p><p>實際問題——你實際上做什麼？——是很多關於Values & Beliefs的思考變得模糊的地方。在抽象中討論這個話題要容易得多，而不是對你在一個週三下午、疲倦的時候、最容易的路不是最好的路的時候，具體說出你做的選擇。那個抽象與具體之間的差距，是大多數真正工作發生的地方。那些能良好應對Becoming More Thoughtful About What Matters的人，傾向於不只思考了他們原則上相信什麼，還思考了他們在可能遇到的各種情況下實際上會做什麼。</p><p>不管你在這個生命時期對Becoming More Thoughtful About What Matters得出什麼結論，值得輕輕握住那個結論。這個話題有一種隨著你對它發展更多經驗而擴展的方式，在一個階段看起來已定的事情，往往在下一個階段變得更複雜。這不是問題——這是發展真正理解而不只是積累意見的正常過程。你能從花時間在Values & Beliefs上帶走的最有用的東西，不是一個固定的答案，而是以更準確的方式繼續問問題的改進能力。</p>',
    vocabulary: [
      { word: 'value sorting', definition: '在很多事都在拉扯時，重新辨認什麼真正重要的過程', example: 'The conversation shifted when she introduced the idea of value sorting and everyone in the room went quiet.' },
      { word: 'moral attention', definition: '把注意力放在值得認真對待的事情上的能力', example: 'She had read about moral attention in theory, but it only made sense once she saw it working in her own life.' },
      { word: 'borrowed urgency', definition: '被外界節奏和壓力帶著跑、好像什麼都很急的狀態', example: 'She had read about borrowed urgency in theory, but it only made sense once she saw it working in her own life.' },
      { word: 'priority test', definition: '用來分辨事情是真的重要，還是只是很吵很急的判斷方法', example: 'Once she started paying attention to priority test, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'thoughtful filter', definition: '幫助自己過濾資訊和要求、不讓什麼都同樣進來的內在篩選器', example: 'She had read about thoughtful filter in theory, but it only made sense once she saw it working in her own life.' }
    ],
  }
]
