import { SpeakArticle } from './articles-w01'

export const W42_ARTICLES: SpeakArticle[] = [
  {
    dateKey: '2026-10-12',
    topic: 'The Future',
    title: 'Looking Ahead: Hopes, Fears, and the Future',
    wordCount: 505,
    text: '<p>Conversations about looking ahead: hopes, fears, and the future tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of looking ahead: hopes, fears, and the future but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in looking ahead: hopes, fears, and the future is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of looking ahead: hopes, fears, and the future you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of looking ahead: hopes, fears, and the future that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於Looking Ahead: Hopes, Fears, and the Future的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了Looking Ahead: Hopes, Fears, and the Future的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在Looking Ahead: Hopes, Fears, and the Future中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的Looking Ahead: Hopes, Fears, and the Future版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的Looking Ahead: Hopes, Fears, and the Future版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'future thinking', definition: '對未來的思考與預測', example: 'What surprised her most about future thinking was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'worst scenario', definition: '最壞的情況', example: 'His approach to worst scenario changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'genuine planning', definition: '真正的規劃', example: 'She finally understood what genuine planning meant when she had to apply it under real pressure at work.' },
      { word: 'overweight recent experience', definition: '過度依賴近期經驗', example: 'Once she started paying attention to overweight recent experience, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'recency bias', definition: '近因偏誤', example: 'It took a difficult year before he genuinely appreciated what recency bias could do for the way he worked.' }
    ],
  },
  {
    dateKey: '2026-10-13',
    topic: 'The Future',
    title: 'Imagining the Future We Might Live In',
    wordCount: 505,
    text: '<p>Conversations about imagining the future we might live in tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of imagining the future we might live in but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in imagining the future we might live in is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of imagining the future we might live in you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of imagining the future we might live in that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於Imagining the Future We Might Live In的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了Imagining the Future We Might Live In的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在Imagining the Future We Might Live In中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的Imagining the Future We Might Live In版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的Imagining the Future We Might Live In版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'extrapolation', definition: '推演；延伸預測', example: 'What surprised her most about extrapolation was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'desired future', definition: '想要的未來；理想未來', example: 'What surprised her most about desired future was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'compass direction', definition: '指南針方向；大方向', example: 'What surprised her most about compass direction was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'belief about the future', definition: '對未來的信念', example: 'What surprised her most about belief about the future was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'automation', definition: '自動化', example: 'What surprised her most about automation was how rarely people talked about it directly, despite how often it mattered.' }
    ],
  },
  {
    dateKey: '2026-10-14',
    topic: 'The Future',
    title: 'Hope, Fear, and What Comes Next',
    wordCount: 500,
    text: '<p>Conversations about hope, fear, and what comes next tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of hope, fear, and what comes next but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in hope, fear, and what comes next is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of hope, fear, and what comes next you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of hope, fear, and what comes next that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於Hope, Fear, and What Comes Next的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了Hope, Fear, and What Comes Next的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在Hope, Fear, and What Comes Next中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的Hope, Fear, and What Comes Next版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的Hope, Fear, and What Comes Next版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'higher stakes', definition: '更高的風險；更重要的考驗', example: 'After months of ignoring it, he realized that higher stakes was the piece he had been missing all along.' },
      { word: 'let the hope be louder', definition: '讓希望的聲音超越恐懼', example: 'They discovered that let the hope be louder was not a fixed thing but something that shifted depending on context and energy.' },
      { word: 'learning curve', definition: '學習曲線；適應過程', example: 'What surprised her most about learning curve was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'think through consequences', definition: '仔細考慮後果', example: 'They discovered that think through consequences was not a fixed thing but something that shifted depending on context and energy.' },
      { word: 'limiting belief', definition: '限制性信念', example: 'Once she started paying attention to limiting belief, she noticed it coming up in conversations she had thought were about something else entirely.' }
    ],
  },
  {
    dateKey: '2026-10-15',
    topic: 'The Future',
    title: 'Technology, Work, and the Near Future',
    wordCount: 500,
    text: '<p>Conversations about technology, work, and the near future tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of technology, work, and the near future but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in technology, work, and the near future is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of technology, work, and the near future you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of technology, work, and the near future that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於Technology, Work, and the Near Future的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了Technology, Work, and the Near Future的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在Technology, Work, and the Near Future中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的Technology, Work, and the Near Future版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的Technology, Work, and the Near Future版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'feel threatened', definition: '感到被威脅', example: 'She finally understood what feel threatened meant when she had to apply it under real pressure at work.' },
      { word: 'valid reaction', definition: '合理的反應', example: 'What surprised her most about valid reaction was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'skill gap', definition: '技能缺口', example: 'His approach to skill gap changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'historically', definition: '從歷史角度來看', example: 'His approach to historically changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'adaptable skills', definition: '適應性強的技能', example: 'Once she started paying attention to adaptable skills, she noticed it coming up in conversations she had thought were about something else entirely.' }
    ],
  },
  {
    dateKey: '2026-10-16',
    topic: 'The Future',
    title: 'The Kind of Future People Want',
    wordCount: 500,
    text: '<p>Conversations about the kind of future people want tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of the kind of future people want but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in the kind of future people want is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of the kind of future people want you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of the kind of future people want that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於The Kind of Future People Want的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了The Kind of Future People Want的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在The Kind of Future People Want中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的The Kind of Future People Want版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的The Kind of Future People Want版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'relative to', definition: '相對於；取決於', example: 'It took a difficult year before he genuinely appreciated what relative to could do for the way he worked.' },
      { word: 'sense of belonging', definition: '歸屬感', example: 'His approach to sense of belonging changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'shared vision', definition: '共同願景', example: 'They discovered that shared vision was not a fixed thing but something that shifted depending on context and energy.' },
      { word: 'optimize for now', definition: '為當下優化', example: 'It took a difficult year before he genuinely appreciated what optimize for now could do for the way he worked.' },
      { word: 'present bias', definition: '當下偏誤', example: 'His approach to present bias changed completely after spending a week observing how his most effective colleague handled it.' }
    ],
  },
  {
    dateKey: '2026-10-17',
    topic: 'The Future',
    title: 'Planning for a Future You Cannot Fully Predict',
    wordCount: 510,
    text: '<p>Conversations about planning for a future you cannot fully predict tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of planning for a future you cannot fully predict but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in planning for a future you cannot fully predict is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of planning for a future you cannot fully predict you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of planning for a future you cannot fully predict that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於Planning for a Future You Cannot Fully Predict的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了Planning for a Future You Cannot Fully Predict的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在Planning for a Future You Cannot Fully Predict中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的Planning for a Future You Cannot Fully Predict版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的Planning for a Future You Cannot Fully Predict版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'clarify what you value', definition: '釐清你重視的事', example: 'Once she started paying attention to clarify what you value, she noticed it coming up in conversations she had thought were about something else entirely.' },
      { word: 'know your priorities', definition: '清楚自己的優先順序', example: 'He described know your priorities as the thing that made the difference between a good plan and one that actually worked.' },
      { word: 'durable', definition: '持久的；耐用的', example: 'The conversation shifted when she introduced the idea of durable and everyone in the room went quiet.' },
      { word: 'flexible route', definition: '靈活的路徑；替代路線', example: 'His approach to flexible route changed completely after spending a week observing how his most effective colleague handled it.' },
      { word: 'detour', definition: '繞行；替代路線；意外的轉折', example: 'She had read about detour in theory, but it only made sense once she saw it working in her own life.' }
    ],
  },
  {
    dateKey: '2026-10-18',
    topic: 'The Future',
    title: 'How Today\'s Choices Shape Tomorrow',
    wordCount: 495,
    text: '<p>Conversations about how today\'s choices shape tomorrow tend to begin at the surface and stay there. You exchange a few observations, agree on a few generalities, and move on. But the people who get the most out of thinking about the future are usually the ones who push past the easy version — the one where everyone already knows their line — and into something more specific and more honest. That push requires a certain willingness to be uncertain, and uncertainty is something most people find uncomfortable enough to avoid.</p><p>One of the more counterintuitive things about the future is that the people who seem most at ease with it are usually not the ones who have the fewest problems with it. They are the ones who have had more problems with it and have spent more time thinking through those problems. Familiarity in this area does not come from having avoided the difficult version of how today\'s choices shape tomorrow but from having been through it enough times to have a sense of what tends to happen and what tends to help. That kind of familiarity is earned rather than given.</p><p>One thing that consistently comes up in honest conversations about the future is the role of timing. The same insight, delivered at the wrong moment, lands differently than it would if it arrived when you were actually ready for it. The same challenge, faced at a point when you have more resources — more rest, more support, more clarity about what matters — is a different experience than the same challenge faced when you are depleted. Understanding the role of timing in how today\'s choices shape tomorrow is one of the more practical things you can take from thinking about the subject carefully.</p><p>The question of what to prioritize when thinking about the future is one that shifts depending on where you are in your own development with the subject. Early on, the priority is often just getting a clearer picture of what you are actually dealing with — distinguishing between the version of how today\'s choices shape tomorrow you imagined and the version that turns out to be real. Later, the priority tends to shift toward refinement: becoming more precise, more consistent, more able to handle the harder versions of the subject without being thrown off by them.</p><p>The version of how today\'s choices shape tomorrow that proves most durable is not the one built on enthusiasm or ideal conditions but the one built on honest acknowledgment of difficulty. What you build during the harder periods — the habits of thought, the practices that hold up even when motivation is low — is more reliable than what you build when things are going well. This makes the difficult engagement with the future valuable in a way that is not obvious while you are in the middle of it. The difficulty is not separate from the value. It is, in a significant way, the source of it.</p>',
    textZh: '<p>關於How Today\'s Choices Shape Tomorrow的對話往往停留在表面。你交換幾個觀察，在幾個普遍性上達成一致，然後繼續往前走。但那些從思考The Future中獲得最多的人，通常是那些願意突破容易版本的人——那個每個人都已經知道自己台詞的版本——進入更具體、更誠實的地方。這種推進需要一定的願意不確定，而不確定是大多數人都覺得足夠不舒服而想避免的事情。</p><p>關於The Future，一個反覆出現的觀察是，那些似乎最能自在應對它的人，通常不是問題最少的人。他們是那些在它上面遇到過更多問題、並花了更多時間思考那些問題的人。在這個領域的熟悉感，不是來自避免了How Today\'s Choices Shape Tomorrow的困難版本，而是來自經歷過足夠多次，以至於對往往會發生什麼和往往有什麼幫助有了感覺。那種熟悉感是賺來的，而不是給予的。</p><p>在關於The Future的誠實對話中，一個持續出現的事情是時機的作用。同樣的洞見，在錯誤的時刻傳遞，落地方式不同於它在你真正準備好接受時到達的樣子。同樣的挑戰，在你有更多資源的時候面對——更多休息、更多支持、對什麼重要有更多清晰——是一種與在你耗盡時面對同樣挑戰完全不同的體驗。理解時機在How Today\'s Choices Shape Tomorrow中的作用，是你能從仔細思考這個話題中獲得的更實際的事情之一。</p><p>當思考The Future時，優先考慮什麼的問題，是隨著你在自己與這個話題的發展中所處的位置而移位的問題。早期，優先事項通常只是對你實際上在處理什麼獲得更清晰的圖像——區分你想象的How Today\'s Choices Shape Tomorrow版本和結果是真實的版本之間的差異。後來，優先事項傾向於轉向精煉：變得更精確、更一致、更能在不被它們打倒的情況下處理話題的更難版本。</p><p>證明最持久的How Today\'s Choices Shape Tomorrow版本，不是建立在熱情或理想條件上的，而是建立在對困難的誠實承認上的。你在更難時期建立的——即使在動力低落時也能維持的思維習慣、練習——比你在事情順利時建立的更可靠。這使得對The Future的困難接觸，以一種你在其中間時並不明顯的方式有價值。困難不是與價值分離的，它在很大程度上是價值的來源。</p>',
    vocabulary: [
      { word: 'delayed feedback', definition: '延遲的反饋', example: 'After months of ignoring it, he realized that delayed feedback was the piece he had been missing all along.' },
      { word: 'open options', definition: '開啟選項；創造更多可能性', example: 'It took a difficult year before he genuinely appreciated what open options could do for the way he worked.' },
      { word: 'reversible decision', definition: '可逆的決定', example: 'What surprised her most about reversible decision was how rarely people talked about it directly, despite how often it mattered.' },
      { word: 'compound', definition: '複利累積；不斷疊加增長', example: 'It took a difficult year before he genuinely appreciated what compound could do for the way he worked.' },
      { word: 'professional habit', definition: '職業習慣', example: 'What surprised her most about professional habit was how rarely people talked about it directly, despite how often it mattered.' }
    ],
  }
]
