export interface ConversationQuestion {
  weekNumber: number
  theme: string
  day: string
  question: string
  chineseHint: string
  structureTip: string
}

const q = (
  weekNumber: number,
  theme: string,
  day: string,
  question: string,
  chineseHint: string,
  structureTip: string,
): ConversationQuestion => ({
  weekNumber,
  theme,
  day,
  question,
  chineseHint,
  structureTip,
})

export const CONVERSATIONS_W01_W08: ConversationQuestion[] = [
  q(
    1,
    'Fresh Starts & New Beginnings',
    'Monday',
    'Introduce yourself in English: tell me your name, where you live, and what you do for work or study.',
    '把三個基本資訊都說到：你的名字、你住哪個城市或地區、你的工作或學生身份。',
    'Say your name first, then your city or area, then your job title or what you study — one clear sentence each.',
  ),
  q(
    1,
    'Fresh Starts & New Beginnings',
    'Tuesday',
    'What is one small, realistic habit you want to build this month? It does not have to be big.',
    '選一件真的可以每天做的小事，說清楚是什麼、你打算什麼時候做。',
    'Name the habit, say exactly when in the day you plan to do it, and give one reason why you chose something small.',
  ),
  q(
    1,
    'Fresh Starts & New Beginnings',
    'Wednesday',
    'Describe what a normal weekday looks like for you, from when you wake up to when you go to sleep.',
    '按照時間順序說最順：起床時間、白天的主要事情、下班或下課後做什麼、大概幾點睡。',
    'Go in time order — morning, daytime, evening — and include two or three specific things you do in each part.',
  ),
  q(
    1,
    'Fresh Starts & New Beginnings',
    'Thursday',
    'Tell me about where you live. What city or area is it, and what do you like most about it?',
    '先說地點，再選一個你覺得最不錯的地方，可以是食物、交通、環境或附近的方便性。',
    'Name your city or neighborhood, describe one thing you genuinely like about it, and add one thing you wish were different.',
  ),
  q(
    2,
    'Morning Routines',
    'Monday',
    'Walk me through the first hour after you wake up on a normal workday.',
    '按照時間順序講最自然：起床後先做什麼、接著做什麼、哪一段最容易被打亂。',
    'Go in order and include one small detail that makes your morning feel truly yours.',
  ),
  q(
    2,
    'Morning Routines',
    'Tuesday',
    'Are you better when you wake up early, or when you sleep enough even if it is later? Explain with a real example.',
    '先選一邊，不要兩邊都講得很平均，再用自己最近的生活例子支持你的答案。',
    'Choose one side clearly, then prove it with a weekday that you remember well.',
  ),
  q(
    2,
    'Morning Routines',
    'Wednesday',
    'What kind of breakfast helps you feel steady, and what kind usually leads to a bad morning?',
    '可以從食物本身、吃早餐的時間、吃得太快或太趕這些角度來講。',
    'Compare the helpful version with the bad version, and say how each one affects the next few hours.',
  ),
  q(
    2,
    'Morning Routines',
    'Thursday',
    'Have you ever exercised in the morning and regretted it, or been glad you did? Tell that story.',
    '這題適合講一個具體早晨，不用講原則太久，讓人聽得到那天發生了什麼。',
    'Tell it like a short story: what you expected, what actually happened, and how you felt afterward.',
  ),
  q(
    2,
    'Morning Routines',
    'Friday',
    'Which part of your morning routine is easiest to keep, and which part breaks first when life gets busy?',
    '把兩邊放在一起比較會更好答，一個是你穩定做到的，一個是最容易消失的。',
    'Name the stable habit, name the fragile habit, and explain what makes the difference.',
  ),
  q(
    2,
    'Morning Routines',
    'Saturday',
    'What does a good slow morning give you that a rushed morning cannot?',
    '這題可以談情緒、專注力、身體感受，或你和家人相處的方式。',
    'Focus on the effect: describe the pace first, then what that pace changes in you.',
  ),
  q(
    2,
    'Morning Routines',
    'Sunday',
    'Think of a morning that went completely wrong. What happened, and how did the rest of the day feel?',
    '先講那個失控點，例如睡過頭、忘東西、下雨、交通卡住，再說後面整天怎麼被影響。',
    'A clear answer gives the trigger, the chain reaction, and the lesson you took from it.',
  ),

  q(
    3,
    'Commuting',
    'Monday',
    'How do you usually get to work or school? Describe your typical commute.',
    '說你搭什麼交通工具、大概要多久、沿途有什麼，把你的通勤路線講得有畫面一點。',
    'Name your transport, say how long the commute takes, and describe one thing you notice or do along the way.',
  ),
  q(
    3,
    'Commuting',
    'Tuesday',
    'If you walked or biked to work more often, what would be the biggest benefit and the biggest obstacle?',
    '這題很適合一正一反來講：一個你想得到的好處，加上一個現實中的阻礙。',
    'Keep the contrast sharp: one real advantage, one honest barrier, one idea about whether it is worth it.',
  ),
  q(
    3,
    'Commuting',
    'Wednesday',
    'What do you usually do during your commute — listen to music, listen to a podcast, scroll your phone, or something else?',
    '選你最常做的一件事，說為什麼選它，或說你希望在通勤時做但還沒做到的事。',
    'Name one thing you usually do, explain why it suits that time, and say how it affects your mood when you arrive.',
  ),
  q(
    3,
    'Commuting',
    'Thursday',
    'What behavior on public transport makes you uncomfortable, and what do you wish people did instead?',
    '可以選一種最有感的情況來講，像是音量、佔位、排隊或手機外放。',
    'Start with the behavior, then explain why it bothers you, and end with the alternative you prefer.',
  ),
  q(
    3,
    'Commuting',
    'Friday',
    'Would you rather have a shorter commute or a bigger home, even if it means choosing one over the other?',
    '先選一個你偏好的，再用你現在的生活狀態或你覺得重要的事來解釋你的選擇。',
    'State your preference clearly, give one reason connected to your daily life, and say what trade-off you are willing to accept.',
  ),
  q(
    3,
    'Commuting',
    'Saturday',
    'What do you like most about your current commute, and what do you dislike most?',
    '一正一反，各說一件事，可以是交通工具、時間長短、費用、人潮，或沿途的環境。',
    'Name one thing you enjoy and one thing you dislike, then say which one has more impact on how your day starts.',
  ),
  q(
    3,
    'Commuting',
    'Sunday',
    'If you could change one thing about your daily commute, what would it be and why?',
    '選最有感的那一點：通勤時間、費用、舒適度、人潮、路線，說清楚為什麼這個最困擾你。',
    'Name the one thing you would change, explain why it bothers you the most, and say how fixing it would improve your day.',
  ),

  q(
    4,
    'Home & Living Space',
    'Monday',
    'What do you usually do when you get home after work or school? Describe your typical evening.',
    '按照時間順序說：回家後先做什麼、通常幾點吃晚餐、晚上怎麼放鬆、大概幾點睡。',
    'Go in time order: what you do first when you arrive home, when and how you eat dinner, and how you wind down before bed.',
  ),
  q(
    4,
    'Home & Living Space',
    'Tuesday',
    'What are your plans for this weekend? Give me two or three things you are planning to do.',
    '直接說你這週末打算做的事，可以是休息、家事、出去玩、見朋友，說清楚是什麼。',
    'List two or three plans, say roughly when each one will happen, and mention which one you are most looking forward to.',
  ),
  q(
    4,
    'Home & Living Space',
    'Wednesday',
    'What household chores do you do regularly? Which one do you not mind, and which one do you dislike most?',
    '先說你固定做哪些家事，再選一個你還好的、一個你最討厭的，解釋為什麼是它。',
    'Name two or three regular chores, then compare: describe one you can live with and one that you find most draining.',
  ),
  q(
    4,
    'Home & Living Space',
    'Thursday',
    'What kind of relationship do you want with your neighbors: close, polite, or distant? Why?',
    '先選一種，再說是什麼讓你偏好這樣的邊界——可以談個性、過去的經驗，或你現在的生活狀況。',
    'State your preferred distance clearly, then explain what experience or personality shaped that preference.',
  ),
  q(
    4,
    'Home & Living Space',
    'Friday',
    'When you cook at home, what do you enjoy, and what makes you want to give up and order food instead?',
    '把喜歡和放棄的點都講出來，答案會更像真實口說。',
    'Balance both sides: one part of cooking that nourishes you, and one part that drains you.',
  ),
  q(
    4,
    'Home & Living Space',
    'Saturday',
    'What did you do last weekend? Was it restful, busy, or a mix of both?',
    '說你上週末實際做了什麼，不用挑好聽的，說真的就好：出去了嗎、做了什麼家事、休息了多久。',
    'Describe two or three things you did, say whether the weekend felt restful or tiring overall, and name one highlight.',
  ),
  q(
    4,
    'Home & Living Space',
    'Sunday',
    'Is there anything you want to do differently at home next week? Name one small change you would like to make.',
    '可以是整理某個地方、改變某個習慣、嘗試自己煮一頓，選一件具體的事，不用太大。',
    'Name the specific change you want to make, explain why you want to make it, and say what first step you would take.',
  ),

  q(
    5,
    'Traditions & Gatherings',
    'Monday',
    'Think of a gathering you actually enjoyed. What made it feel meaningful instead of tiring?',
    '不要只說很好玩，重點是說出那場標記為什麼有重量、有人味或有記憶點。',
    'Describe the event briefly, then explain which detail gave it emotional meaning.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Tuesday',
    'At the beginning of a new chapter or season, do you usually feel energized, pressured, or mostly unchanged?',
    '先選一個最接近你的反應，再說是什麼讓你有這種感覺。',
    'Pick one emotional direction and support it with one recent example.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Wednesday',
    'What is one gift you still remember clearly, and why did it stay with you?',
    '可以是很貴的，也可以很小；真正重要的是它代表了什麼。',
    'A memorable answer tells us who gave it, what it was, and why it still lives in your mind.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Thursday',
    'At family reunions, what role do you usually play: organizer, listener, peacemaker, entertainer, or something else?',
    '先選角色，再說你是怎麼慢慢變成那個角色的。',
    'Name the role, give one scene that proves it, and say how you feel about having that role.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Friday',
    'What kind of gathering food feels emotionally important to you, not just tasty?',
    '這題可以講味道背後的家庭、地方、特別場合記憶，不需要講很多菜名。',
    'Connect the food to a memory, a person, or a season so it feels alive.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Saturday',
    'Have you ever wanted to keep a tradition, but change the way it is done?',
    '這題很適合談長輩版本和你這一代版本之間的差別。',
    'Explain what you want to keep, what you want to change, and why both matter.',
  ),
  q(
    5,
    'Traditions & Gatherings',
    'Sunday',
    'After a big gathering ends, how do you like to carry a little of that feeling back into normal life?',
    '可以是某個習慣、某種心情、和家人聯絡的方式，或一個你想留下的小儀式。',
    'Keep the answer grounded by naming one feeling and one action that helps it last.',
  ),

  q(
    6,
    'Food & Eating Habits',
    'Monday',
    'When you need comfort, what food do you usually want, and what does it give you besides taste?',
    '這題不只是在講食物，而是在講那個食物帶來的安全感、熟悉感或回憶。',
    'Mention the food first, then move beyond flavor into mood, memory, or routine.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Tuesday',
    'What makes a restaurant experience worth the money for you?',
    '可以從食物、服務、聊天氣氛、方便程度，或「不用自己收拾」這種現實角度來談。',
    'Build your answer around your top two factors, not a long general list.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Wednesday',
    'Tell me about a local street food or small food stall that you would recommend without hesitation.',
    '把對方當成真的要去吃的人，講出品項、味道、場合或你推薦的理由。',
    'Make it vivid: name the food, the setting, and the reason you would send someone there.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Thursday',
    'Which eating habit of yours feels healthy and sustainable, and which one keeps pulling you in the wrong direction?',
    '兩邊一起講會更完整，一個是你做得還不錯的，一個是你反覆卡住的。',
    'Contrast the helpful pattern with the difficult one, then say what each one leads to.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Friday',
    'Is there a family recipe, food memory, or smell from childhood that still feels powerful?',
    '可以選一個最有畫面的回憶，講誰在場、什麼味道、那時候的感覺。',
    'Let the memory do the work: describe the scene before you explain why it matters.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Saturday',
    'When you try food from another culture, what helps you stay curious instead of judgmental?',
    '這題可以談你的心態，也可以談你看過別人怎麼把未知變成拒絕。',
    'Answer with one mindset and one behavior that keeps you open.',
  ),
  q(
    6,
    'Food & Eating Habits',
    'Sunday',
    'Looking ahead, how do you think people in your country will eat differently in the next ten years?',
    '不用講太多宏大趨勢，選兩三個你真的看得到的改變就好。',
    'A believable future answer mentions concrete changes in habit, cost, or convenience.',
  ),

  q(
    7,
    'Weather & Seasons',
    'Monday',
    'If someone asked about the weather where you live this month, what would you warn them about first?',
    '把它當成你在提醒一個第一次來的人，講出最需要準備的那一點。',
    'Speak as if you are helping a visitor: describe the condition, the problem, and the useful advice.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Tuesday',
    'During a rainy season or a long stretch of bad weather, what change in your routine helps the most?',
    '答案可以很生活化，像是提早出門、換鞋、改做室內活動，或調整心情。',
    'Choose one adjustment and explain why it works better than just complaining.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Wednesday',
    'Does weather mostly change your mood, your clothes, your plans, or your energy?',
    '先選影響最大的一項，再補一個最近的例子讓答案更真。',
    'Pick the strongest effect and support it with one ordinary day that shows it clearly.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Thursday',
    'When people feel climate anxiety, what kind of action do you think actually helps?',
    '這題不一定要很大，可以談讓自己不麻木、也不空轉的小行動。',
    'A thoughtful answer separates useful action from pure worry.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Friday',
    'Tell me about a storm, typhoon, or extreme weather day you still remember clearly.',
    '把它講成一個短故事：事情開始時你在哪裡、後來發生了什麼、你記住了什麼。',
    'Use story order here: before, during, after.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Saturday',
    'Which season makes you feel most like yourself, and which season is hardest on you?',
    '兩邊一起講會很有層次，一個是你最舒服的季節，一個是你最難適應的。',
    'Compare the two seasons through body, mood, and daily rhythm.',
  ),
  q(
    7,
    'Weather & Seasons',
    'Sunday',
    'If you could take a trip based only on the best season, where would you go and when?',
    '不要只講地點，講那個季節為什麼剛好，讓答案更有畫面。',
    'Name the place, the season, and what would be different because of that timing.',
  ),

  q(
    8,
    'Shopping & Money',
    'Monday',
    'What does your spending over the last month reveal about what you really care about?',
    '這題不是在檢討自己，而是誠實看最近的錢都流去哪裡。',
    'Talk about patterns, not single purchases, and say what those patterns suggest.',
  ),
  q(
    8,
    'Shopping & Money',
    'Tuesday',
    'When you make a budget, what part is easy, and what part do you avoid?',
    '可以談記帳、分類、控制衝動購物，或不想面對某些數字。',
    'Name one part that feels manageable and one part that creates resistance.',
  ),
  q(
    8,
    'Shopping & Money',
    'Wednesday',
    'What kind of purchase usually triggers regret for you: convenience, boredom, stress, or social pressure?',
    '先選一個最有感的來源，再講一次你真的後悔過的消費。',
    'Choose the main trigger, then bring in a real example so the reason sounds believable.',
  ),
  q(
    8,
    'Shopping & Money',
    'Thursday',
    'Are you comfortable asking for a discount or a better deal? Why or why not?',
    '這題可以談個性，也可以談文化、尷尬感、或你曾經成功或失敗的經驗。',
    'Answer with your instinct first, then explain what experience taught you.',
  ),
  q(
    8,
    'Shopping & Money',
    'Friday',
    'What financial goal feels important to you this year, even if it is still small?',
    '選一個真的跟你生活有關的目標，不一定要很宏大，例如存緊急預備金或減少某種支出。',
    'Say what the goal is, why it matters now, and what first step would make it real.',
  ),
  q(
    8,
    'Shopping & Money',
    'Saturday',
    'When money is involved in friendships or family, what kind of etiquette matters most to you?',
    '可以談請客、分帳、借錢、送禮或還人情，講出你重視的分寸。',
    'Focus on one principle and one situation where that principle gets tested.',
  ),
  q(
    8,
    'Shopping & Money',
    'Sunday',
    'If you suddenly had to cut your spending by twenty percent, what would you change first?',
    '這題很適合講優先順序：你會先砍什麼、保留什麼、為什麼。',
    'A clear answer names the first cut, the protected expense, and the value behind both.',
  ),
]
