import { ConversationQuestion } from './conversations-w01-w08'

export const CONVERSATIONS_W42_W53: ConversationQuestion[] = [
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Monday',
    question: 'Describe a real situation where the theme of "Looking Ahead: Hopes, Fears, and the Future" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Looking Ahead: Hopes, Fears, and the Future」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Tuesday',
    question: 'What makes "Imagining the Future We Might Live In" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Imagining the Future We Might Live In」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Wednesday',
    question: 'What is one habit or mindset that helps you with "Hope, Fear, and What Comes Next"?',
    chineseHint: '面對「Hope, Fear, and What Comes Next」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Thursday',
    question: 'What have you learned about "The Future" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「The Future」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Friday',
    question: 'If a friend asked for advice about "The Kind of Future People Want", what would you say?',
    chineseHint: '如果朋友問你關於「The Kind of Future People Want」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Saturday',
    question: 'How would you like to improve in the area of "Planning for a Future You Cannot Fully Predict"?',
    chineseHint: '在「Planning for a Future You Cannot Fully Predict」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 42,
    theme: 'The Future',
    day: 'Sunday',
    question: 'How does "How Today’s Choices Shape Tomorrow" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「How Today’s Choices Shape Tomorrow」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Monday',
    question: 'What makes "Full Circle: Reflections on the Journey" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Full Circle: Reflections on the Journey」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Tuesday',
    question: 'What is one habit or mindset that helps you with "Looking Back on How Much You’ve Changed"?',
    chineseHint: '面對「Looking Back on How Much You’ve Changed」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Wednesday',
    question: 'What have you learned about "Looking Back & Moving Forward" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Looking Back & Moving Forward」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Thursday',
    question: 'If a friend asked for advice about "The People and Moments That Shaped You", what would you say?',
    chineseHint: '如果朋友問你關於「The People and Moments That Shaped You」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Friday',
    question: 'How would you like to improve in the area of "Regret, Gratitude, and Perspective"?',
    chineseHint: '在「Regret, Gratitude, and Perspective」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Saturday',
    question: 'How does "What You Want to Leave Behind" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「What You Want to Leave Behind」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 43,
    theme: 'Looking Back & Moving Forward',
    day: 'Sunday',
    question: 'Describe a real situation where the theme of "Moving Forward with More Intention" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Moving Forward with More Intention」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Monday',
    question: 'What is one habit or mindset that helps you with "Finding Your Creative Voice"?',
    chineseHint: '面對「Finding Your Creative Voice」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Tuesday',
    question: 'What have you learned about "Creativity & Self-Expression" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Creativity & Self-Expression」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Wednesday',
    question: 'If a friend asked for advice about "Storytelling as a Human Need", what would you say?',
    chineseHint: '如果朋友問你關於「Storytelling as a Human Need」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Thursday',
    question: 'How would you like to improve in the area of "Design Thinking in Daily Life"?',
    chineseHint: '在「Design Thinking in Daily Life」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Friday',
    question: 'How does "Music and Emotional Expression" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Music and Emotional Expression」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Saturday',
    question: 'Describe a real situation where the theme of "The Writer\'s Mind" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Writer\'s Mind」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 44,
    theme: 'Creativity & Self-Expression',
    day: 'Sunday',
    question: 'What makes "Living a Creative Life" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Living a Creative Life」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Monday',
    question: 'What have you learned about "Leadership & Influence" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Leadership & Influence」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Tuesday',
    question: 'If a friend asked for advice about "Influence Without Authority", what would you say?',
    chineseHint: '如果朋友問你關於「Influence Without Authority」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Wednesday',
    question: 'How would you like to improve in the area of "Emotional Intelligence in Leadership"?',
    chineseHint: '在「Emotional Intelligence in Leadership」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Thursday',
    question: 'How does "Building and Leading Teams" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Building and Leading Teams」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Friday',
    question: 'Describe a real situation where the theme of "Decision-Making Under Pressure" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Decision-Making Under Pressure」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Saturday',
    question: 'What makes "Leading Yourself First" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Leading Yourself First」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 45,
    theme: 'Leadership & Influence',
    day: 'Sunday',
    question: 'What is one habit or mindset that helps you with "Leadership in Everyday Life"?',
    chineseHint: '面對「Leadership in Everyday Life」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Monday',
    question: 'If a friend asked for advice about "The Power of Community", what would you say?',
    chineseHint: '如果朋友問你關於「The Power of Community」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Tuesday',
    question: 'How would you like to improve in the area of "The Art of Listening"?',
    chineseHint: '在「The Art of Listening」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Wednesday',
    question: 'How does "Local Heroes and Changemakers" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Local Heroes and Changemakers」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Thursday',
    question: 'Describe a real situation where the theme of "Navigating Differences in Community" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Navigating Differences in Community」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Friday',
    question: 'What makes "Technology for Social Good" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Technology for Social Good」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Saturday',
    question: 'What is one habit or mindset that helps you with "Generations of Service"?',
    chineseHint: '面對「Generations of Service」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 46,
    theme: 'Community & Giving Back',
    day: 'Sunday',
    question: 'What have you learned about "Community & Giving Back" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Community & Giving Back」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Monday',
    question: 'How would you like to improve in the area of "What Is Culture, Anyway?"?',
    chineseHint: '在「What Is Culture, Anyway?」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Tuesday',
    question: 'How does "Navigating Cultural Differences at Work" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Navigating Cultural Differences at Work」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Wednesday',
    question: 'Describe a real situation where the theme of "Food as a Cultural Gateway" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Food as a Cultural Gateway」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Thursday',
    question: 'What makes "Traveling with Curiosity" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Traveling with Curiosity」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Friday',
    question: 'What is one habit or mindset that helps you with "Values Across Cultures"?',
    chineseHint: '面對「Values Across Cultures」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Saturday',
    question: 'What have you learned about "Cross-Cultural Understanding" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Cross-Cultural Understanding」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 47,
    theme: 'Cross-Cultural Understanding',
    day: 'Sunday',
    question: 'If a friend asked for advice about "Building Cultural Bridges", what would you say?',
    chineseHint: '如果朋友問你關於「Building Cultural Bridges」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Monday',
    question: 'How does "Who Are You When You Speak?" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Who Are You When You Speak?」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Tuesday',
    question: 'Describe a real situation where the theme of "Slang, Jargon, and Belonging" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Slang, Jargon, and Belonging」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Wednesday',
    question: 'What makes "Bilingual Lives" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Bilingual Lives」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Thursday',
    question: 'What is one habit or mindset that helps you with "Storytelling and Narrative Identity"?',
    chineseHint: '面對「Storytelling and Narrative Identity」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Friday',
    question: 'What have you learned about "Language & Identity" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Language & Identity」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Saturday',
    question: 'If a friend asked for advice about "Writing and Self-Expression", what would you say?',
    chineseHint: '如果朋友問你關於「Writing and Self-Expression」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 48,
    theme: 'Language & Identity',
    day: 'Sunday',
    question: 'How would you like to improve in the area of "The Gift of Expression"?',
    chineseHint: '在「The Gift of Expression」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Monday',
    question: 'Describe a real situation where the theme of "Why Rest Is Productive" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Why Rest Is Productive」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Tuesday',
    question: 'What makes "The Art of Doing Nothing" difficult or easy for you in daily life?',
    chineseHint: '你覺得「The Art of Doing Nothing」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Wednesday',
    question: 'What is one habit or mindset that helps you with "Sabbath and Sacred Rest"?',
    chineseHint: '面對「Sabbath and Sacred Rest」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Thursday',
    question: 'What have you learned about "Rest & Renewal" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Rest & Renewal」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Friday',
    question: 'If a friend asked for advice about "Physical Renewal and Body Wisdom", what would you say?',
    chineseHint: '如果朋友問你關於「Physical Renewal and Body Wisdom」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Saturday',
    question: 'How would you like to improve in the area of "Slow Living in a Fast World"?',
    chineseHint: '在「Slow Living in a Fast World」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 49,
    theme: 'Rest & Renewal',
    day: 'Sunday',
    question: 'How does "A Week of Rest Reflections" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「A Week of Rest Reflections」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Monday',
    question: 'What makes "The Science of Gratitude" difficult or easy for you in daily life?',
    chineseHint: '你覺得「The Science of Gratitude」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Tuesday',
    question: 'What is one habit or mindset that helps you with "Appreciating People in Your Life"?',
    chineseHint: '面對「Appreciating People in Your Life」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Wednesday',
    question: 'What have you learned about "Gratitude & Appreciation" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Gratitude & Appreciation」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Thursday',
    question: 'If a friend asked for advice about "Gratitude and Perspective", what would you say?',
    chineseHint: '如果朋友問你關於「Gratitude and Perspective」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Friday',
    question: 'How would you like to improve in the area of "Gratitude at Work"?',
    chineseHint: '在「Gratitude at Work」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Saturday',
    question: 'How does "Gratitude Across Cultures" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Gratitude Across Cultures」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 50,
    theme: 'Gratitude & Appreciation',
    day: 'Sunday',
    question: 'Describe a real situation where the theme of "A Week of Thankfulness" mattered to you.',
    chineseHint: '描述一個真實情境，說明「A Week of Thankfulness」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Monday',
    question: 'What is one habit or mindset that helps you with "What Do You Really Want?"?',
    chineseHint: '面對「What Do You Really Want?」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Tuesday',
    question: 'What have you learned about "Goals & Intentions" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Goals & Intentions」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Wednesday',
    question: 'If a friend asked for advice about "Habits, Systems, and Daily Practice", what would you say?',
    chineseHint: '如果朋友問你關於「Habits, Systems, and Daily Practice」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Thursday',
    question: 'How would you like to improve in the area of "Work, Purpose, and Calling"?',
    chineseHint: '在「Work, Purpose, and Calling」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Friday',
    question: 'How does "Resilience and Bouncing Back" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Resilience and Bouncing Back」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Saturday',
    question: 'Describe a real situation where the theme of "The Year Ahead" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Year Ahead」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 51,
    theme: 'Goals & Intentions',
    day: 'Sunday',
    question: 'What makes "Setting Yourself Up for a Great Year" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Setting Yourself Up for a Great Year」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Monday',
    question: 'What have you learned about "Year in Review" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Year in Review」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Tuesday',
    question: 'If a friend asked for advice about "Relationships and Connections", what would you say?',
    chineseHint: '如果朋友問你關於「Relationships and Connections」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Wednesday',
    question: 'How would you like to improve in the area of "Health and Energy in Review"?',
    chineseHint: '在「Health and Energy in Review」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Thursday',
    question: 'How does "Work and Purpose Review" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Work and Purpose Review」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Friday',
    question: 'Describe a real situation where the theme of "Growth and Learning This Year" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Growth and Learning This Year」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Saturday',
    question: 'What makes "Creativity and Joy in Review" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Creativity and Joy in Review」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 52,
    theme: 'Year in Review',
    day: 'Sunday',
    question: 'What is one habit or mindset that helps you with "A Letter to Your Future Self"?',
    chineseHint: '面對「A Letter to Your Future Self」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 53,
    theme: 'New Beginnings',
    day: 'Monday',
    question: 'If a friend asked for advice about "The Threshold", what would you say?',
    chineseHint: '如果朋友問你關於「The Threshold」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 53,
    theme: 'New Beginnings',
    day: 'Tuesday',
    question: 'How would you like to improve in the area of "Letting Go to Move Forward"?',
    chineseHint: '在「Letting Go to Move Forward」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 53,
    theme: 'New Beginnings',
    day: 'Wednesday',
    question: 'How does "Designing the Year Ahead" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Designing the Year Ahead」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 53,
    theme: 'New Beginnings',
    day: 'Thursday',
    question: 'Describe a real situation where the theme of "The Last Day and the First Step" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Last Day and the First Step」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  }
]
