export interface ConversationQuestion {
  weekNumber: number
  theme: string
  day: string
  question: string
  chineseHint: string
  structureTip: string
}

export const CONVERSATIONS_W01_W08: ConversationQuestion[] = [
  {
    weekNumber: 1,
    theme: 'New Year & Fresh Starts',
    day: 'Monday',
    question: 'What makes "The First Day of Everything" difficult or easy for you in daily life?',
    chineseHint: '你覺得「The First Day of Everything」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 1,
    theme: 'New Year & Fresh Starts',
    day: 'Tuesday',
    question: 'What is one habit or mindset that helps you with "Intentions, Not Resolutions"?',
    chineseHint: '面對「Intentions, Not Resolutions」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 1,
    theme: 'New Year & Fresh Starts',
    day: 'Wednesday',
    question: 'What have you learned about "New Year & Fresh Starts" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「New Year & Fresh Starts」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 1,
    theme: 'New Year & Fresh Starts',
    day: 'Thursday',
    question: 'If a friend asked for advice about "Letting Go to Move Forward", what would you say?',
    chineseHint: '如果朋友問你關於「Letting Go to Move Forward」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Monday',
    question: 'What is one habit or mindset that helps you with "The Perfect Morning"?',
    chineseHint: '面對「The Perfect Morning」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Tuesday',
    question: 'What have you learned about "Morning Routines" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Morning Routines」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Wednesday',
    question: 'If a friend asked for advice about "Breakfast Conversations", what would you say?',
    chineseHint: '如果朋友問你關於「Breakfast Conversations」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Thursday',
    question: 'How would you like to improve in the area of "Moving Your Body at Dawn"?',
    chineseHint: '在「Moving Your Body at Dawn」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Friday',
    question: 'How does "Mindful Mornings" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Mindful Mornings」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Saturday',
    question: 'Describe a real situation where the theme of "The Art of the Slow Morning" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Art of the Slow Morning」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 2,
    theme: 'Morning Routines',
    day: 'Sunday',
    question: 'What makes "When Routines Go Wrong" difficult or easy for you in daily life?',
    chineseHint: '你覺得「When Routines Go Wrong」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Monday',
    question: 'What have you learned about "Commuting" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Commuting」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Tuesday',
    question: 'If a friend asked for advice about "Walking and Cycling to Work", what would you say?',
    chineseHint: '如果朋友問你關於「Walking and Cycling to Work」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Wednesday',
    question: 'How would you like to improve in the area of "Remote Work Days"?',
    chineseHint: '在「Remote Work Days」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Thursday',
    question: 'How does "Commuting Etiquette" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Commuting Etiquette」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Friday',
    question: 'Describe a real situation where the theme of "Driving to Work" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Driving to Work」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Saturday',
    question: 'What makes "Long-Distance Commuters" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Long-Distance Commuters」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 3,
    theme: 'Commuting',
    day: 'Sunday',
    question: 'What is one habit or mindset that helps you with "The Future of Getting to Work"?',
    chineseHint: '面對「The Future of Getting to Work」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Monday',
    question: 'If a friend asked for advice about "Where I Live: Describing Your Home", what would you say?',
    chineseHint: '如果朋友問你關於「Where I Live: Describing Your Home」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Tuesday',
    question: 'How would you like to improve in the area of "Renting vs. Buying"?',
    chineseHint: '在「Renting vs. Buying」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Wednesday',
    question: 'How does "Decluttering and Minimalism" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Decluttering and Minimalism」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Thursday',
    question: 'Describe a real situation where the theme of "Neighbors and Community" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Neighbors and Community」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Friday',
    question: 'What makes "Home Cooking and the Kitchen" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Home Cooking and the Kitchen」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Saturday',
    question: 'What is one habit or mindset that helps you with "Interior Design and Personal Style"?',
    chineseHint: '面對「Interior Design and Personal Style」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 4,
    theme: 'Home & Living Space',
    day: 'Sunday',
    question: 'What have you learned about "Home & Living Space" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Home & Living Space」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Monday',
    question: 'How would you like to improve in the area of "The Language of Celebration"?',
    chineseHint: '在「The Language of Celebration」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Tuesday',
    question: 'How does "New Year, New Energy" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「New Year, New Energy」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Wednesday',
    question: 'Describe a real situation where the theme of "Gifts and Giving" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Gifts and Giving」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Thursday',
    question: 'What makes "Family Reunions" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Family Reunions」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Friday',
    question: 'What is one habit or mindset that helps you with "Feasting and Food Culture"?',
    chineseHint: '面對「Feasting and Food Culture」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Saturday',
    question: 'What have you learned about "Celebrations & Festivals" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Celebrations & Festivals」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 5,
    theme: 'Celebrations & Festivals',
    day: 'Sunday',
    question: 'If a friend asked for advice about "Carrying the Festival Spirit Forward", what would you say?',
    chineseHint: '如果朋友問你關於「Carrying the Festival Spirit Forward」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Monday',
    question: 'How does "Let\'s Eat: Food Preferences and Habits" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Let\'s Eat: Food Preferences and Habits」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Tuesday',
    question: 'Describe a real situation where the theme of "Eating Out and Restaurant Culture" mattered to you.',
    chineseHint: '描述一個真實情境，說明「Eating Out and Restaurant Culture」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Wednesday',
    question: 'What makes "Street Food and Local Eats" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Street Food and Local Eats」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Thursday',
    question: 'What is one habit or mindset that helps you with "Healthy Eating and Diets"?',
    chineseHint: '面對「Healthy Eating and Diets」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Friday',
    question: 'What have you learned about "Food & Eating Habits" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Food & Eating Habits」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Saturday',
    question: 'If a friend asked for advice about "International Cuisine and Fusion", what would you say?',
    chineseHint: '如果朋友問你關於「International Cuisine and Fusion」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 6,
    theme: 'Food & Eating Habits',
    day: 'Sunday',
    question: 'How would you like to improve in the area of "Food Trends and the Future of Eating"?',
    chineseHint: '在「Food Trends and the Future of Eating」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Monday',
    question: 'Describe a real situation where the theme of "The Weather Today: Talking About Climate" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Weather Today: Talking About Climate」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Tuesday',
    question: 'What makes "Surviving the Rainy Season" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Surviving the Rainy Season」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Wednesday',
    question: 'What is one habit or mindset that helps you with "How Weather Shapes Culture"?',
    chineseHint: '面對「How Weather Shapes Culture」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Thursday',
    question: 'What have you learned about "Weather & Seasons" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Weather & Seasons」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Friday',
    question: 'If a friend asked for advice about "Storm Stories and Weather Memories", what would you say?',
    chineseHint: '如果朋友問你關於「Storm Stories and Weather Memories」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Saturday',
    question: 'How would you like to improve in the area of "Weather and Romance"?',
    chineseHint: '在「Weather and Romance」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 7,
    theme: 'Weather & Seasons',
    day: 'Sunday',
    question: 'How does "Dream Destinations by Season" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Dream Destinations by Season」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Monday',
    question: 'What makes "Spending Habits: How We Buy Things" difficult or easy for you in daily life?',
    chineseHint: '你覺得「Spending Habits: How We Buy Things」在日常生活中對你來說困難或容易的地方是什麼？',
    structureTip: 'Use: The difficult part for me is... / What makes it easier is... / I usually struggle when...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Tuesday',
    question: 'What is one habit or mindset that helps you with "Budgeting and Saving Money"?',
    chineseHint: '面對「Budgeting and Saving Money」時，有哪一個習慣或心態對你最有幫助？',
    structureTip: 'Use: One thing that helps me is... / I try to... / This works because...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Wednesday',
    question: 'What have you learned about "Shopping & Money" from your own experience?',
    chineseHint: '根據你自己的經驗，你對「Shopping & Money」有什麼新的理解？',
    structureTip: 'Use: I used to think... / Now I realize... / Experience has taught me that...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Thursday',
    question: 'If a friend asked for advice about "Negotiating and Getting a Good Deal", what would you say?',
    chineseHint: '如果朋友問你關於「Negotiating and Getting a Good Deal」的建議，你會怎麼回答？',
    structureTip: 'Use: I would probably say... / My advice would be... / It helps to...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Friday',
    question: 'How would you like to improve in the area of "Financial Goals and the Future"?',
    chineseHint: '在「Financial Goals and the Future」這個面向上，你希望自己接下來怎麼進步？',
    structureTip: 'Use: I want to get better at... / My next step is... / I hope to...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Saturday',
    question: 'How does "Gifting, Tipping, and Money Etiquette" show up in your own life right now?',
    chineseHint: '結合自己的經驗，說說「Gifting, Tipping, and Money Etiquette」目前如何出現在你的生活裡。',
    structureTip: 'Use: In my life right now... / I notice this most when... / A recent example is...',
  },
  {
    weekNumber: 8,
    theme: 'Shopping & Money',
    day: 'Sunday',
    question: 'Describe a real situation where the theme of "The Future of Money" mattered to you.',
    chineseHint: '描述一個真實情境，說明「The Future of Money」這個主題為什麼對你重要。',
    structureTip: 'Use: One situation that comes to mind is... / What happened was... / It mattered because...',
  }
]
