import { ConversationQuestion } from './conversations-w01-w08'

export const CONVERSATIONS_W33_W41: ConversationQuestion[] = [
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Monday',
    question: 'Use the phrase "fresh air" in a short story from your real life. What happened?',
    chineseHint: '把今天學到的說法「新鮮空氣」放進你自己的小故事裡，重點是自然，不用講得很長。',
    structureTip: 'Try: One time, I had to... / That was a moment of... / Since then,...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Tuesday',
    question: 'If you only had thirty seconds, how would you explain why "Why Nature Changes the Way We Feel" matters in daily life?',
    chineseHint: '想像你只有很短的時間，要用簡單英文把這件事講清楚，重點放在日常例子。',
    structureTip: 'Try: This matters because... / You can see it when... / A simple example is...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Wednesday',
    question: 'Where do you draw the line when it comes to "Urban Nature and Small Outdoor Rituals"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Thursday',
    question: 'Tell a short personal story that includes both "protect the place" and "fresh air".',
    chineseHint: '試著把「保護這個地方」和「新鮮空氣」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Friday',
    question: 'What usually tells you that it is time to change something about "Children, Screens, and Nature Deprivation"?',
    chineseHint: '可以說一個你會注意到的訊號，像是情緒、結果，或生活裡某個反覆出現的小細節。',
    structureTip: 'Try: I know it is time to change when... / One sign is... / After that, I usually...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Saturday',
    question: 'In "Travel, Tourism, and Protecting Fragile Places", which feels harder for you: "protect the place" or "fresh air"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 33,
    theme: 'Nature & Outdoors',
    day: 'Sunday',
    question: 'What has experience taught you about "Living Closer to the Living World" that you did not understand before?',
    chineseHint: '可以先說你以前怎麼想，再說後來因為經驗改變了什麼看法。',
    structureTip: 'Try: I used to think... / But over time I realized... / Now I see that...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Monday',
    question: 'If you only had thirty seconds, how would you explain why "Moving Your Body: Sports, Exercise, and Staying Active" matters in daily life?',
    chineseHint: '想像你只有很短的時間，要用簡單英文把這件事講清楚，重點放在日常例子。',
    structureTip: 'Try: This matters because... / You can see it when... / A simple example is...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Tuesday',
    question: 'Where do you draw the line when it comes to "Why People Exercise for Different Reasons"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Wednesday',
    question: 'Tell a short personal story that includes both "find what works" and "work out".',
    chineseHint: '試著把「找到適合自己的方式」和「運動鍛鍊」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Thursday',
    question: 'What usually tells you that it is time to change something about "Sportsmanship, Competition, and Character"?',
    chineseHint: '可以說一個你會注意到的訊號，像是情緒、結果，或生活裡某個反覆出現的小細節。',
    structureTip: 'Try: I know it is time to change when... / One sign is... / After that, I usually...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Friday',
    question: 'In "Social Media, Body Image, and Fitness Pressure", which feels harder for you: "body image pressure" or "work out"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Saturday',
    question: 'What has experience taught you about "Aging, Recovery, and Exercising for the Long Term" that you did not understand before?',
    chineseHint: '可以先說你以前怎麼想，再說後來因為經驗改變了什麼看法。',
    structureTip: 'Try: I used to think... / But over time I realized... / Now I see that...',
  },
  {
    weekNumber: 34,
    theme: 'Sports & Fitness',
    day: 'Sunday',
    question: 'What is one small step that would help you improve in "A Better Relationship With Your Body" this week?',
    chineseHint: '不要想太大，先說一個這週真的做得到的小步驟，再補原因。',
    structureTip: 'Try: One small step I can take is... / It is realistic because... / I hope it will...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Monday',
    question: 'Where do you draw the line when it comes to "Always On: Technology in Our Daily Lives"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Tuesday',
    question: 'Tell a short personal story that includes both "constant notifications" and "focus time".',
    chineseHint: '試著把「一直跳出的通知」和「專注時間」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Wednesday',
    question: 'What usually tells you that it is time to change something about "Convenience and the Hidden Costs of Tech"?',
    chineseHint: '可以說一個你會注意到的訊號，像是情緒、結果，或生活裡某個反覆出現的小細節。',
    structureTip: 'Try: I know it is time to change when... / One sign is... / After that, I usually...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Thursday',
    question: 'In "Smart Homes and Digital Habits", which feels harder for you: "smart device" or "digital clutter"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Friday',
    question: 'What has experience taught you about "When Technology Feels Overwhelming" that you did not understand before?',
    chineseHint: '可以先說你以前怎麼想，再說後來因為經驗改變了什麼看法。',
    structureTip: 'Try: I used to think... / But over time I realized... / Now I see that...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Saturday',
    question: 'What is one small step that would help you improve in "Choosing What Technology Is Worth Keeping" this week?',
    chineseHint: '不要想太大，先說一個這週真的做得到的小步驟，再補原因。',
    structureTip: 'Try: One small step I can take is... / It is realistic because... / I hope it will...',
  },
  {
    weekNumber: 35,
    theme: 'Technology & Everyday Life',
    day: 'Sunday',
    question: 'What would progress look like for you in "Building a Healthier Relationship with Devices" over the next month?',
    chineseHint: '先說你覺得什麼樣的變化算進步，再說你會怎麼看出來。',
    structureTip: 'Try: For me, progress would look like... / I would notice it when... / That would matter because...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Monday',
    question: 'What would progress look like for you in "Intelligent Machines: Living With AI" over the next month?',
    chineseHint: '先說你覺得什麼樣的變化算進步，再說你會怎麼看出來。',
    structureTip: 'Try: For me, progress would look like... / I would notice it when... / That would matter because...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Tuesday',
    question: 'When does "What AI Is Good At and What It Is Not" feel energizing, and when does it feel draining for you?',
    chineseHint: '這題可以從兩面來說：什麼時候你會覺得有力量，什麼時候又會覺得很累。',
    structureTip: 'Try: It feels energizing when... / It feels draining when... / The difference is...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Wednesday',
    question: 'What is the most common challenge you face with "How AI Changes Everyday Work", and how do you usually handle it?',
    chineseHint: '先講最常碰到的難點，再說你平常怎麼應對，不一定要是完美做法。',
    structureTip: 'Try: The most common challenge for me is... / Usually, I handle it by... / What still feels hard is...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Thursday',
    question: 'How would you explain "Trust, Accuracy, and Human Judgment" to someone who has never really thought about it before?',
    chineseHint: '把對方想成完全沒想過這件事的人，用簡單、清楚的方式慢慢帶他進來。',
    structureTip: 'Try: I would start by saying... / A simple way to explain it is... / In everyday life,...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Friday',
    question: 'A friend wants help with "Creative Work in the Age of AI". What practical advice would you give first?',
    chineseHint: '把自己想成真的在給朋友建議，先說第一個最實用的做法，再解釋為什麼。',
    structureTip: 'Try: The first thing I would suggest is... / It helps because... / I would tell them to...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Saturday',
    question: 'Describe a situation where you had to balance "bias in the system" and "automate a task". What choice did you make?',
    chineseHint: '先說兩件事情拉扯的情境，再說你最後怎麼選，以及那個選擇帶來什麼結果。',
    structureTip: 'Try: I had to choose between... and... / I ended up... / Looking back,...',
  },
  {
    weekNumber: 36,
    theme: 'Artificial Intelligence',
    day: 'Sunday',
    question: 'What do people often misunderstand about "Living Alongside Smarter Machines"? What would you say instead?',
    chineseHint: '可以先說常見的誤解，再用自己的話補上一個比較貼近真實的看法。',
    structureTip: 'Try: People often assume that... / But I think... / A better way to see it is...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Monday',
    question: 'In "Mind and Body: Taking Care of Your Health", which feels harder for you: "mental wellbeing" or "chronic stress"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Tuesday',
    question: 'What has experience taught you about "What Mental Wellbeing Really Means" that you did not understand before?',
    chineseHint: '可以先說你以前怎麼想，再說後來因為經驗改變了什麼看法。',
    structureTip: 'Try: I used to think... / But over time I realized... / Now I see that...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Wednesday',
    question: 'What is one small step that would help you improve in "Stress, Anxiety, and Modern Life" this week?',
    chineseHint: '不要想太大，先說一個這週真的做得到的小步驟，再補原因。',
    structureTip: 'Try: One small step I can take is... / It is realistic because... / I hope it will...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Thursday',
    question: 'What would progress look like for you in "Small Habits That Protect Your Mind" over the next month?',
    chineseHint: '先說你覺得什麼樣的變化算進步，再說你會怎麼看出來。',
    structureTip: 'Try: For me, progress would look like... / I would notice it when... / That would matter because...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Friday',
    question: 'When does "Talking More Honestly About Struggle" feel energizing, and when does it feel draining for you?',
    chineseHint: '這題可以從兩面來說：什麼時候你會覺得有力量，什麼時候又會覺得很累。',
    structureTip: 'Try: It feels energizing when... / It feels draining when... / The difference is...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Saturday',
    question: 'What is the most common challenge you face with "Rest, Therapy, and Support Systems", and how do you usually handle it?',
    chineseHint: '先講最常碰到的難點，再說你平常怎麼應對，不一定要是完美做法。',
    structureTip: 'Try: The most common challenge for me is... / Usually, I handle it by... / What still feels hard is...',
  },
  {
    weekNumber: 37,
    theme: 'Health & Mental Wellbeing',
    day: 'Sunday',
    question: 'How would you explain "Building a More Sustainable Inner Life" to someone who has never really thought about it before?',
    chineseHint: '把對方想成完全沒想過這件事的人，用簡單、清楚的方式慢慢帶他進來。',
    structureTip: 'Try: I would start by saying... / A simple way to explain it is... / In everyday life,...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Monday',
    question: 'How does "long-term thinking" show up in your routine right now? Is it helping or causing problems?',
    chineseHint: '想一想「長期思考」現在怎麼出現在你的生活裡，再說它帶來幫助還是壓力。',
    structureTip: 'Try: Right now, this shows up when... / It helps me by... / The hard part is...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Tuesday',
    question: 'Use the phrase "climate issue" in a short story from your real life. What happened?',
    chineseHint: '把今天學到的說法「氣候議題」放進你自己的小故事裡，重點是自然，不用講得很長。',
    structureTip: 'Try: One time, I had to... / That was a moment of... / Since then,...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Wednesday',
    question: 'If you only had thirty seconds, how would you explain why "Daily Choices and Their Real Impact" matters in daily life?',
    chineseHint: '想像你只有很短的時間，要用簡單英文把這件事講清楚，重點放在日常例子。',
    structureTip: 'Try: This matters because... / You can see it when... / A simple example is...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Thursday',
    question: 'Where do you draw the line when it comes to "Convenience, Consumption, and Waste"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Friday',
    question: 'Tell a short personal story that includes both "climate issue" and "reduce waste".',
    chineseHint: '試著把「氣候議題」和「減少浪費」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Saturday',
    question: 'What usually tells you that it is time to change something about "Cities, Nature, and Sustainable Design"?',
    chineseHint: '可以說一個你會注意到的訊號，像是情緒、結果，或生活裡某個反覆出現的小細節。',
    structureTip: 'Try: I know it is time to change when... / One sign is... / After that, I usually...',
  },
  {
    weekNumber: 38,
    theme: 'Environment & Sustainability',
    day: 'Sunday',
    question: 'In "What a Sustainable Future Could Look Like", which feels harder for you: "climate issue" or "reduce waste"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Monday',
    question: 'What would you tell your younger self about "Talking About Money: Goals, Habits, and Mindset" now?',
    chineseHint: '把自己想成在對以前的自己說話，內容可以是提醒、安慰，或一個更成熟的理解。',
    structureTip: 'Try: I would tell my younger self... / I did not understand then that... / What I know now is...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Tuesday',
    question: 'Think of a recent time when "money mindset" became important in your life. What was happening, and what did you do?',
    chineseHint: '先交代最近的一個真實情境，再說事情為什麼跟「金錢心態」有關，最後補一句你怎麼做。',
    structureTip: 'Try: A recent time this came up was... / It became important because... / So I decided to...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Wednesday',
    question: 'How does "personal priority" show up in your routine right now? Is it helping or causing problems?',
    chineseHint: '想一想「個人優先順序」現在怎麼出現在你的生活裡，再說它帶來幫助還是壓力。',
    structureTip: 'Try: Right now, this shows up when... / It helps me by... / The hard part is...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Thursday',
    question: 'Use the phrase "talk about money" in a short story from your real life. What happened?',
    chineseHint: '把今天學到的說法「談錢」放進你自己的小故事裡，重點是自然，不用講得很長。',
    structureTip: 'Try: One time, I had to... / That was a moment of... / Since then,...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Friday',
    question: 'If you only had thirty seconds, how would you explain why "Financial Goals and Emotional Pressure" matters in daily life?',
    chineseHint: '想像你只有很短的時間，要用簡單英文把這件事講清楚，重點放在日常例子。',
    structureTip: 'Try: This matters because... / You can see it when... / A simple example is...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Saturday',
    question: 'Where do you draw the line when it comes to "Lifestyle, Status, and the Cost of Image"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 39,
    theme: 'Money & Financial Goals',
    day: 'Sunday',
    question: 'Tell a short personal story that includes both "money mindset" and "talk about money".',
    chineseHint: '試著把「金錢心態」和「談錢」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Monday',
    question: 'Where do you draw the line when it comes to "Life in Motion: Navigating Change and New Chapters"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Tuesday',
    question: 'Tell a short personal story that includes both "life transition" and "start over".',
    chineseHint: '試著把「人生轉換期」和「重新開始」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Wednesday',
    question: 'What usually tells you that it is time to change something about "Life Transitions and Identity Shifts"?',
    chineseHint: '可以說一個你會注意到的訊號，像是情緒、結果，或生活裡某個反覆出現的小細節。',
    structureTip: 'Try: I know it is time to change when... / One sign is... / After that, I usually...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Thursday',
    question: 'In "Starting Over in Midstream", which feels harder for you: "start over" or "in-between stage"? Explain with one short example.',
    chineseHint: '可以先選出對你比較難的一個點，再補一個短例子；如果願意，也可以順帶比較另一個點。',
    structureTip: 'Try: The harder one for me is... / For example,... / The easier side is...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Friday',
    question: 'What has experience taught you about "How to Adapt Without Losing Yourself" that you did not understand before?',
    chineseHint: '可以先說你以前怎麼想，再說後來因為經驗改變了什麼看法。',
    structureTip: 'Try: I used to think... / But over time I realized... / Now I see that...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Saturday',
    question: 'What is one small step that would help you improve in "Letting Go of What No Longer Fits" this week?',
    chineseHint: '不要想太大，先說一個這週真的做得到的小步驟，再補原因。',
    structureTip: 'Try: One small step I can take is... / It is realistic because... / I hope it will...',
  },
  {
    weekNumber: 40,
    theme: 'Change & Transitions',
    day: 'Sunday',
    question: 'What would progress look like for you in "Trusting Yourself Through Uncertainty" over the next month?',
    chineseHint: '先說你覺得什麼樣的變化算進步，再說你會怎麼看出來。',
    structureTip: 'Try: For me, progress would look like... / I would notice it when... / That would matter because...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Monday',
    question: 'What would you tell your younger self about "What We Stand For: Values, Principles, and Beliefs" now?',
    chineseHint: '把自己想成在對以前的自己說話，內容可以是提醒、安慰，或一個更成熟的理解。',
    structureTip: 'Try: I would tell my younger self... / I did not understand then that... / What I know now is...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Tuesday',
    question: 'Think of a recent time when "core value" became important in your life. What was happening, and what did you do?',
    chineseHint: '先交代最近的一個真實情境，再說事情為什麼跟「核心價值」有關，最後補一句你怎麼做。',
    structureTip: 'Try: A recent time this came up was... / It became important because... / So I decided to...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Wednesday',
    question: 'How does "change your mind" show up in your routine right now? Is it helping or causing problems?',
    chineseHint: '想一想「改變想法」現在怎麼出現在你的生活裡，再說它帶來幫助還是壓力。',
    structureTip: 'Try: Right now, this shows up when... / It helps me by... / The hard part is...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Thursday',
    question: 'Use the phrase "core value" in a short story from your real life. What happened?',
    chineseHint: '把今天學到的說法「核心價值」放進你自己的小故事裡，重點是自然，不用講得很長。',
    structureTip: 'Try: One time, I had to... / That was a moment of... / Since then,...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Friday',
    question: 'If you only had thirty seconds, how would you explain why "Disagreeing with People You Respect" matters in daily life?',
    chineseHint: '想像你只有很短的時間，要用簡單英文把這件事講清楚，重點放在日常例子。',
    structureTip: 'Try: This matters because... / You can see it when... / A simple example is...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Saturday',
    question: 'Where do you draw the line when it comes to "What You Refuse to Compromise On"?',
    chineseHint: '這題可以談原則或界線，說說你通常會在哪裡停下來、拒絕，或特別注意。',
    structureTip: 'Try: I am usually okay with... / But I draw the line when... / That matters to me because...',
  },
  {
    weekNumber: 41,
    theme: 'Values & Beliefs',
    day: 'Sunday',
    question: 'Tell a short personal story that includes both "thoughtful conviction" and "core value".',
    chineseHint: '試著把「經過思考的信念」和「核心價值」一起放進同一個例子裡，讓答案更像真實口說。',
    structureTip: 'Try: One situation that fits both ideas was... / First,... / Then...',
  }
]
