export interface ConversationQuestion {
  weekNumber: number
  theme: string
  day: string
  question: string
  chineseHint: string
  structureTip: string
}

const q = (
  weekNumber: number,
  theme: string,
  day: string,
  question: string,
  chineseHint: string,
  structureTip: string,
): ConversationQuestion => ({
  weekNumber,
  theme,
  day,
  question,
  chineseHint,
  structureTip,
})

export const CONVERSATIONS_W09_W16: ConversationQuestion[] = [
  q(
    9,
    'Health & Body',
    'Monday',
    'What does taking care of yourself actually look like on a normal weekday, not an ideal one?',
    '不要回答成完美版本，講你現在真的做得到的照顧自己方式。',
    'Use everyday detail here: name one habit, one limit, and one thing you still neglect.',
  ),
  q(
    9,
    'Health & Body',
    'Tuesday',
    'How can you tell when lack of sleep is starting to affect your work or mood?',
    '可以講身體訊號、情緒反應，或你在工作上會出現的錯誤。',
    'A clear answer names the signs first, then shows what those signs lead to.',
  ),
  q(
    9,
    'Health & Body',
    'Wednesday',
    'In a busy work period, what helps you protect your mental health before things get too bad?',
    '重點不是講大道理，而是講你會提早做的預防動作。',
    'Talk about prevention, not recovery: what do you notice early, and what do you do next?',
  ),
  q(
    9,
    'Health & Body',
    'Thursday',
    'What does eating well mean to you when you are busy and tired?',
    '這題適合談現實版本的健康，不用講理想餐盤，講你撐得住的方法就好。',
    'Define eating well in practical terms, then explain what makes that realistic for you.',
  ),
  q(
    9,
    'Health & Body',
    'Friday',
    'When you start to get sick, what is your usual pattern: rest early, ignore it, or keep working?',
    '先誠實說你的反應，再補一句這個習慣帶來的結果。',
    'Start with your default pattern and finish with what it usually costs you.',
  ),
  q(
    9,
    'Health & Body',
    'Saturday',
    'Which kind of movement feels realistic for your current life?',
    '可以談散步、健身、伸展、騎車或任何你真的可能維持的活動。',
    'The best answer connects one form of movement to your actual schedule and energy.',
  ),
  q(
    9,
    'Health & Body',
    'Sunday',
    'If you could build one healthier habit and keep it for a year, what would you choose?',
    '選一個你真的相信自己能守住的習慣，比選很厲害的更重要。',
    'Name the habit, say why it matters, and explain why this one has a chance of lasting.',
  ),

  q(
    10,
    'Daily Schedules',
    'Monday',
    'Talk me through a recent weekday from morning to night. Where did your time really go?',
    '照時間順序講會最好答，也比較能看出時間到底花在哪裡。',
    'Move through the day in order and pause on the part that consumed more time than expected.',
  ),
  q(
    10,
    'Daily Schedules',
    'Tuesday',
    'At what time of day do you do your best thinking, and how do you know?',
    '不要只說早上或晚上，講一個你明顯感受到自己最清楚的時段。',
    'Give the time, the kind of thinking it helps, and one sign that tells you you are in that zone.',
  ),
  q(
    10,
    'Daily Schedules',
    'Wednesday',
    'What part of your workday needs better structure right now?',
    '可以是開工前、午餐後、會議之間，或某段你總是被打斷的時間。',
    'Be specific about the weak part of the day, then explain what better structure would change.',
  ),
  q(
    10,
    'Daily Schedules',
    'Thursday',
    'After work, how do you usually shift from task mode to personal time?',
    '這題很適合講一個小儀式，例如散步、洗澡、吃飯、通勤或關掉通知。',
    'Describe the transition, not just the activity, and explain why it helps your brain switch.',
  ),
  q(
    10,
    'Daily Schedules',
    'Friday',
    'What makes a weekend feel restoring for you rather than just full?',
    '不要只列行程，講哪種安排讓你真的有恢復感。',
    'A natural answer compares a full weekend with a restoring one and shows the difference.',
  ),
  q(
    10,
    'Daily Schedules',
    'Saturday',
    'Is there any part of your life where doing less would actually make things better?',
    '可以談社交、工作、資訊量、行程安排或自我要求。',
    'Name the area, explain why more is not helping, and say what less would create.',
  ),
  q(
    10,
    'Daily Schedules',
    'Sunday',
    'What invisible responsibility takes more of your time than other people realize?',
    '這題很適合講那些別人看不到但你一直在處理的事。',
    'Show the hidden work clearly: what it is, why people miss it, and how it affects your day.',
  ),

  q(
    11,
    'Friendship',
    'Monday',
    'What makes you trust someone enough to call them a real friend?',
    '不要只說人很好，講出你判斷友情的標準會更有內容。',
    'Build your answer around two or three signals that make trust feel earned.',
  ),
  q(
    11,
    'Friendship',
    'Tuesday',
    'Why is it harder to make new friends as an adult than it was before?',
    '你可以從時間、工作、戒心、生活圈固定，或價值觀差異來講。',
    'Explain the difficulty through real adult life conditions, not only personality.',
  ),
  q(
    11,
    'Friendship',
    'Wednesday',
    'How do you keep a long-distance friendship alive when everyday life gets crowded?',
    '如果你沒有這樣的朋友，也可以講你認為有效的方法。',
    'A useful answer mentions one habit that keeps connection alive and one reason it still fails sometimes.',
  ),
  q(
    11,
    'Friendship',
    'Thursday',
    'When you want to stay in touch with someone, what do you actually do?',
    '不要講理想中的友情，講你真的會傳訊息、約見面，還是分享小事。',
    'Speak concretely: what is your real pattern, and what does it communicate to the other person?',
  ),
  q(
    11,
    'Friendship',
    'Friday',
    'Tell me about a close friend who brings out a better side of you.',
    '先講這個朋友是怎樣的人，再講他怎麼影響你。',
    'Start with the person, then describe the version of yourself that appears around them.',
  ),
  q(
    11,
    'Friendship',
    'Saturday',
    'What kind of honesty do you want in a close friendship, and what kind feels too much?',
    '這題可以談界線，也可以談說真話的方法與時機。',
    'Give one example of honesty that helps and one that crosses the line for you.',
  ),
  q(
    11,
    'Friendship',
    'Sunday',
    'Have you ever become good friends with someone very different from you? What made it work?',
    '差異可以是個性、背景、年齡、工作或生活方式。',
    'Describe the difference first, then explain what was strong enough to bridge it.',
  ),

  q(
    12,
    'Family',
    'Monday',
    'When people ask about your family, what is the best way to describe the atmosphere at home?',
    '不要只介紹成員，這題重點是家裡的感覺，例如安靜、熱鬧、緊密、客氣。',
    'Lead with the atmosphere, then support it with one or two family habits or scenes.',
  ),
  q(
    12,
    'Family',
    'Tuesday',
    'What usually makes family gatherings easy, and what makes them tiring?',
    '把兩邊都講出來，答案會更成熟也更真實。',
    'Compare the enjoyable part with the draining part and show why both can exist together.',
  ),
  q(
    12,
    'Family',
    'Wednesday',
    'If you have siblings or cousin-like relationships, how have those shaped you?',
    '可以談競爭、照顧、玩伴感，或你學會了怎麼相處。',
    'Choose one relationship and explain the influence through a pattern, not just a label.',
  ),
  q(
    12,
    'Family',
    'Thursday',
    'Is there a family role you naturally fall into even when you do not choose it?',
    '例如負責安排的人、安靜傾聽的人、出面處理事情的人，都可以。',
    'Name the role, say when it appears, and explain whether you welcome it or resist it.',
  ),
  q(
    12,
    'Family',
    'Friday',
    'When something important needs to be said in your family, who says it well?',
    '這題可以講溝通能力，也可以講家裡誰最有分量、誰最會處理情緒。',
    'Focus on one person and describe what makes their way of speaking effective.',
  ),
  q(
    12,
    'Family',
    'Saturday',
    'What is difficult about caring for aging parents or older relatives in your culture?',
    '可以談時間、責任分配、情感壓力，或傳統期待。',
    'Answer at two levels: the practical difficulty and the emotional difficulty.',
  ),
  q(
    12,
    'Family',
    'Sunday',
    'Who feels like family to you even without a blood relationship?',
    '這題很適合講一個你很信任的人，以及他為什麼有家的感覺。',
    'Introduce the person, then explain what makes the bond feel family-like rather than casual.',
  ),

  q(
    13,
    'Colleagues & Teamwork',
    'Monday',
    'What makes it easy for you to work well with one colleague, but hard with another?',
    '不要回答成個性好不好，講合作中的具體差別會更強。',
    'Compare two working dynamics and point to the behavior that changes everything.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Tuesday',
    'When you receive feedback, what kind helps you improve and what kind makes you shut down?',
    '可以談語氣、清楚程度、時機，或對方有沒有真的理解你的工作。',
    'Split the answer into helpful feedback and unhelpful feedback, then show why each lands differently.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Wednesday',
    'How do you handle someone at work who is not openly rude but still creates tension?',
    '這題很生活化，你可以談保持距離、講清楚界線，或先看對工作有沒有影響。',
    'Start with the kind of behavior you mean, then explain your response step by step.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Thursday',
    'When a team project goes well, what kind of shared responsibility usually exists behind it?',
    '這題不是要稱讚團隊，而是講順利背後有哪些真的做對的事。',
    'A strong answer names the hidden habits that make teamwork feel smooth.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Friday',
    'On remote teams, what helps people feel connected instead of isolated?',
    '可以談會議方式、回應速度、聊天空間，或主管帶人的方式。',
    'Talk about connection as something people build on purpose, not something automatic.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Saturday',
    'What kind of meeting makes you think, "That was worth my time"?',
    '想一場你真的覺得有用的會議，講它和普通會議差在哪裡。',
    'Describe the meeting through outcomes, not vague praise.',
  ),
  q(
    13,
    'Colleagues & Teamwork',
    'Sunday',
    'What professional skill are you trying to grow this year, and why now?',
    '技能可以是溝通、領導、簡報、判斷力或專業能力，重點是說為什麼現在特別重要。',
    'State the skill, the reason this is the right season, and how you plan to practice it.',
  ),

  q(
    14,
    'Social Situations',
    'Monday',
    'When you walk into a social event where you know almost no one, what is your first move?',
    '這題可以很真實，講你會先找熟人、先觀察、先拿飲料，或直接開口。',
    'Answer through behavior, then explain what that behavior helps you manage.',
  ),
  q(
    14,
    'Social Situations',
    'Tuesday',
    'What helps you feel included in a group, and what quickly makes you feel like an outsider?',
    '兩邊一起講會更完整，也比較像真實社交感受。',
    'Name the welcoming signal and the excluding signal, then say why they hit you that way.',
  ),
  q(
    14,
    'Social Situations',
    'Wednesday',
    'Do you see small talk as useful, fake, or necessary? Explain with an example.',
    '先選你的立場，再用一個具體社交場景支持它。',
    'Choose your view clearly and let one real conversation show why you think that way.',
  ),
  q(
    14,
    'Social Situations',
    'Thursday',
    'What does reading the room mean to you in real life?',
    '這題可以談你怎麼看氣氛、語氣、表情，或什麼時候該收、什麼時候該講。',
    'Define the skill through an example instead of through a dictionary-like explanation.',
  ),
  q(
    14,
    'Social Situations',
    'Friday',
    'Tell me about an awkward social moment that you handled better than expected.',
    '把它講成小故事最自然：當時發生什麼、你怎麼反應、後來怎麼收住。',
    'Use story shape here and end with what you learned about yourself.',
  ),
  q(
    14,
    'Social Situations',
    'Saturday',
    'When invitations are uneven in a friend group, how do you usually interpret it?',
    '這題可以談不安全感，也可以談你會怎麼理性地看待這件事。',
    'Show both your first emotional reaction and your calmer second thought.',
  ),
  q(
    14,
    'Social Situations',
    'Sunday',
    'What kind of boundary helps you enjoy social situations without getting drained?',
    '可以談時間長度、聊天深度、喝酒、回訊息速度或活動頻率。',
    'Name one boundary and explain how it protects your energy without cutting people off.',
  ),

  q(
    15,
    'Personality & Character',
    'Monday',
    'When people meet you for the first time, what do they usually get right and wrong about you?',
    '先說他們看對的地方，再說最容易誤判的部分。',
    'A balanced answer shows the accurate first impression and the hidden layer behind it.',
  ),
  q(
    15,
    'Personality & Character',
    'Tuesday',
    'Do first impressions tend to be fair in your experience?',
    '你可以同意也可以反對，但最好用一個人際經驗來證明。',
    'Take a position, then test it against one experience that still stands out.',
  ),
  q(
    15,
    'Personality & Character',
    'Wednesday',
    'Which part of your personality becomes stronger at work, and which part shows up more with friends?',
    '這題很適合比較兩個版本的自己，不用講成矛盾，講成情境差異就好。',
    'Contrast your work self and your friend self through behavior, not just adjectives.',
  ),
  q(
    15,
    'Personality & Character',
    'Thursday',
    'What trait do you admire most in other people because you know how rare it is?',
    '可以選穩定、誠實、溫柔、判斷力等，重點是說你為什麼特別珍惜它。',
    'Name the trait, explain why it feels rare, and describe how it changes a relationship.',
  ),
  q(
    15,
    'Personality & Character',
    'Friday',
    'What habit or flaw are you trying to grow out of without becoming fake?',
    '這題不是自我批判，而是談一個你想修正、但又不想失去真實感的地方。',
    'Describe the flaw honestly, then explain the better version you are aiming for.',
  ),
  q(
    15,
    'Personality & Character',
    'Saturday',
    'How does your personality affect the way you handle closeness or conflict?',
    '可以談你是先講、先退、先觀察，還是先想很多。',
    'Tie personality to one relationship pattern so the answer feels grounded.',
  ),
  q(
    15,
    'Personality & Character',
    'Sunday',
    'In what area of life do you feel most like your real self?',
    '可以是工作、朋友、獨處、學習或創作，選一個你最有感的場域。',
    'Name the setting and explain what becomes easier there: your voice, your pace, or your choices.',
  ),

  q(
    16,
    'Communication Styles',
    'Monday',
    'In your culture or workplace, when is direct communication helpful, and when does it fail?',
    '這題適合講界線、效率、關係感，或不同場合需要不同說法。',
    'Answer in two parts: where directness works, and where it creates friction.',
  ),
  q(
    16,
    'Communication Styles',
    'Tuesday',
    'Think of a time when an indirect hint was misunderstood. What happened?',
    '你可以講自己沒聽懂，也可以講別人沒聽懂你的意思。',
    'Tell the original hint, the misunderstanding, and what became clear afterward.',
  ),
  q(
    16,
    'Communication Styles',
    'Wednesday',
    'What tells you that someone is listening carefully, not just waiting to reply?',
    '可以談眼神、追問方式、回應內容，或對方有沒有抓到真正重點。',
    'Give two or three signs that make you feel genuinely heard.',
  ),
  q(
    16,
    'Communication Styles',
    'Thursday',
    'How do you disagree respectfully when you actually care a lot about the topic?',
    '這題可以講語氣、字眼、順序，或你會先承認什麼再提出不同意見。',
    'Show your method: how do you protect the relationship without hiding your real view?',
  ),
  q(
    16,
    'Communication Styles',
    'Friday',
    'Which causes more misunderstandings for you: text, voice notes, or face-to-face talk?',
    '先選一種最容易出問題的，再說它為什麼特別危險。',
    'Choose one format and explain what gets lost there that matters to you.',
  ),
  q(
    16,
    'Communication Styles',
    'Saturday',
    'What kind of question usually leads to a better conversation?',
    '不是問句型而已，而是問什麼樣的提問真的能把人打開。',
    'Give one example of a good question and explain what it invites the other person to do.',
  ),
  q(
    16,
    'Communication Styles',
    'Sunday',
    'When you are under pressure, what happens to the way you speak?',
    '可以談講太快、講太少、太直接、太模糊，或腦中一片空白。',
    'Describe the pressure effect first, then say what helps you recover clarity.',
  ),
]
