import { Episode } from '../../app/src/data/episode-sample'

export const EPISODE_10: Episode = {
  weekNumber: 10,
  theme: 'Family',
  title: 'Family Life: Talking About the People We Grew Up With',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — Describing Your Family',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Mira, how would you describe your family in a few words? Like if a stranger asked.", zh: 'Mira，如果用幾個字描述你的家人，你會怎麼說？比如說陌生人問你的話。' },
        { speaker: 'a', speakerName: 'Mira', en: "Hmm. Loud, opinionated, and deeply caring. We argue over everything but nobody holds grudges for long.", zh: '嗯。吵鬧、很有自己的意見、還有深沉的關愛。我們什麼都吵，但沒有人記仇太久。', vocab: [{ word: 'opinionated', def: '固執己見的' }, { word: 'hold a grudge', def: '記仇' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That sounds like a classic big family dynamic. Are you close with everyone, or are some relationships more complicated?", zh: '聽起來像是典型大家庭的動態。你和大家都親近嗎，還是有些關係比較複雜？' },
        { speaker: 'a', speakerName: 'Mira', en: "There's definitely variation. My sister and I are very close — she's one of my best friends. My relationship with my parents has evolved a lot as I've become an adult. More equal now than when I was younger.", zh: '確實各有不同。我和姊姊非常親近——她是我最好的朋友之一。我和父母的關係隨著我成年後改變了很多。現在比我年輕時更平等了。', vocab: [{ word: 'evolved', def: '演變、改變' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That shift from parent-child to something more like peers is interesting. Did it happen gradually or was there a moment where things changed?", zh: '從親子關係轉向更像同輩的那個轉變很有趣。是漸進式發生的，還是有某個讓事情改變的時刻？', vocab: [{ word: 'peers', def: '同輩' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Gradually, I think. But moving out accelerated it. Once I was financially independent and living on my own terms, the dynamic shifted. They started asking for my opinion instead of just giving me theirs.", zh: '我覺得是漸進的。但搬出去加速了它。一旦我經濟獨立、按自己的方式生活，動態就改變了。他們開始詢問我的意見，而不只是給我他們的。', vocab: [{ word: 'accelerated', def: '加速了' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Independence really does change the relationship. I noticed the same thing — my parents became more interesting to me when I stopped needing them to provide everything.", zh: '獨立真的改變了關係。我注意到同樣的事——當我不再需要他們提供一切，我的父母對我來說變得更有趣了。' },
        { speaker: 'a', speakerName: 'Mira', en: "You start seeing them as people, not just roles. Realizing your parents had whole lives before you existed is actually quite fascinating.", zh: '你開始把他們視為人，而不只是角色。意識到你的父母在你存在之前有完整的生活，這其實相當迷人。' },
      ],
    },
    {
      title: 'Part 2 — Family Traditions',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Does your family have any traditions that are really important to you?", zh: '你們家有任何對你來說非常重要的傳統嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "Sunday dinner is the big one. No matter how busy everyone is, we try to have a proper meal together at least a couple of times a month. It's where the real conversations happen.", zh: '週日晚餐是最重要的。不管大家多忙，我們每個月至少試著好好吃幾次飯。真正的對話就在那裡發生。', vocab: [{ word: 'proper', def: '正式的、完整的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "There's something about sharing food that lowers people's defenses. Conversations that wouldn't happen anywhere else seem to happen at the dinner table.", zh: '共享食物有某種降低人防禦心的力量。在其他地方不會發生的對話，似乎在餐桌上都會發生。' },
        { speaker: 'a', speakerName: 'Mira', en: "Completely. And the rituals around food carry so much meaning — who makes what dish, the jokes that come up every year, the things never said aloud but understood by everyone.", zh: '完全同意。圍繞食物的儀式承載著很多意義——誰做什麼菜、每年都會出現的笑話、那些從未大聲說出但大家都懂的事。', vocab: [{ word: 'rituals', def: '儀式、慣例' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Do you have any holiday traditions that feel uniquely yours as a family?", zh: '你們家有任何感覺是獨特屬於你們的節假日傳統嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "We always watch a particular old movie together on New Year's Eve — it's so cheesy but nobody would dare skip it. The ritual itself matters more than the movie at this point.", zh: '我們除夕夜總是一起看某部老電影——俗氣得很，但沒有人敢跳過它。儀式本身現在比那部電影更重要了。', vocab: [{ word: 'cheesy', def: '俗氣的、老套的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Those shared rituals are what give families their identity. They're the stories you tell about each other — 'that's just what we do.'", zh: '那些共同的儀式賦予了家庭身分。它們是你們彼此講述的故事——「我們就是這樣做的。」' },
        { speaker: 'a', speakerName: 'Mira', en: "And the ones you'd feel a real loss without, even if you can't fully explain why. Traditions don't need to make sense — they just need to be yours.", zh: '還有那些如果沒有你會真的感到失落的，即使你無法完全解釋原因。傳統不需要有道理——它們只需要是你的。' },
      ],
    },
    {
      title: 'Part 3 — Navigating Family Differences',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Families can also be a source of real tension, especially when people have very different views. How do you handle that?", zh: '家庭也可能是真正緊張關係的來源，尤其是當人們有非常不同的觀點時。你怎麼應對？' },
        { speaker: 'a', speakerName: 'Mira', en: "With effort and some strategic topic-avoidance, honestly. There are a few subjects I've learned not to raise at family gatherings. Not because I'm giving up — I just pick my battles.", zh: '靠努力和一些策略性的話題迴避，說真的。有幾個話題我已經學到就是不在家庭聚會上提起。不是因為我放棄了——我只是選擇我的戰場。', vocab: [{ word: 'pick your battles', def: '選擇你的戰場、有所取捨' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's wise. Though it can also feel like you're constantly performing a slightly filtered version of yourself.", zh: '那很明智。雖然有時也感覺像是你在不斷表演一個略經過濾的自己版本。' },
        { speaker: 'a', speakerName: 'Mira', en: "It is a kind of filtering. But most close relationships involve some version of that — you're choosing what serves the relationship. That's not inauthenticity, it's social intelligence.", zh: '確實是一種過濾。但大多數親密關係都包含某種版本的這個——你在選擇什麼對關係有幫助。那不是不真誠，只是社交智慧。' },
        { speaker: 'b', speakerName: 'Jamie', en: "The generation gap can be so stark sometimes. Values that seemed obvious to our parents' generation feel completely different to ours.", zh: '代溝有時候真的很明顯。對我們父母那一代來說顯而易見的價值觀，對我們來說感覺完全不同。', vocab: [{ word: 'generation gap', def: '代溝' }, { word: 'stark', def: '明顯的、鮮明的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes, and that can be really hard. The tricky part is maintaining respect for where they're coming from, even when you fundamentally disagree. They usually mean well — they just see the world differently.", zh: '是的，那可能真的很難。棘手的部分是保持對他們出發點的尊重，即使你從根本上不同意。他們通常是好意的——只是看世界的方式不同。' },
        { speaker: 'b', speakerName: 'Jamie', en: "And sometimes they surprise you. My dad said something last month that completely changed how I saw a problem I was dealing with.", zh: '有時他們會讓你驚訝。我爸上個月說了一件事，完全改變了我對一個問題的看法。' },
        { speaker: 'a', speakerName: 'Mira', en: "That's the thing about family — they've seen enough of life to have perspectives you just can't have at our age yet. If you listen past the delivery, there's often wisdom in there.", zh: '這就是家人的事——他們見過足夠多的生活，有一些我們這個年紀還無法擁有的觀點。如果你忽略表達方式去傾聽，裡面通常有智慧。' },
      ],
    },
    {
      title: 'Part 4 — Family and Identity',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "How much do you think family shapes who you are? Do we grow into ourselves despite our families, or because of them?", zh: '你覺得家庭在多大程度上塑造了你這個人？我們是儘管有家庭才成長為自己，還是因為家庭而成長？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Both, I think — and the line isn't always clear. Some of my best qualities I got directly from my parents. Some of the things I've had to work hardest to change also came from home.", zh: '我覺得兩者都有——界限並不總是清晰。我一些最好的品質直接來自我的父母。我最努力改變的一些事情也來自家庭。', vocab: [{ word: 'qualities', def: '特質、品質' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Awareness is the key — recognizing which patterns you want to carry forward and which ones you want to consciously break.", zh: '覺察是關鍵——認識到哪些模式你想繼續，哪些你想有意識地打破。', vocab: [{ word: 'consciously', def: '有意識地' }, { word: 'patterns', def: '模式' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "My parents worked incredibly hard, and I inherited a strong work ethic from them. But I also absorbed some anxiety about security that I've had to unlearn.", zh: '我父母工作非常努力，我從他們身上繼承了強烈的工作倫理。但我也吸收了一些關於安全感的焦慮，那是我需要去除的。', vocab: [{ word: 'work ethic', def: '工作倫理' }, { word: 'unlearn', def: '去除習慣' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Same behavior — hard work — but coming from passion or from fear. Knowing the difference matters enormously.", zh: '同樣的行為——努力工作——但來自熱情或恐懼。知道差異非常重要。' },
        { speaker: 'b', speakerName: 'Jamie', en: "Family gives us our first language for emotions — what expressing affection looks like, how to handle grief, how to deal with conflict. Those templates are really deep.", zh: '家庭給了我們情感的第一語言——愛意是什麼樣子、如何處理悲傷、如何應對衝突。那些模板根深蒂固。', vocab: [{ word: 'affection', def: '愛意、情感' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And you carry them into every relationship afterward. Understanding your family isn't just nostalgia — it's useful for understanding yourself right now.", zh: '你把它們帶進你之後所有的關係中。理解你的家庭不只是懷舊——它對現在理解自己很有用。', vocab: [{ word: 'nostalgia', def: '懷舊' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I'd never thought about it that way but it's so true. The family is like the original operating system you run on.", zh: '我從來沒有這樣想過，但確實如此。家庭就像你運行的原始作業系統。' },
      ],
    },
    {
      title: 'Part 5 — What Family Really Means',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Is family just the people you're born into, or does it expand beyond that?", zh: '家人只是你出生進入的那些人，還是它可以超越那個範圍？' },
        { speaker: 'a', speakerName: 'Mira', en: "Definitely expands. Some of my chosen family — close friends, a couple of mentors — feel more like family than some relatives I share DNA with. Family is about consistent presence and care, not blood.", zh: '絕對會擴展。我的一些「選擇的家人」——親密的朋友、幾位導師——感覺比一些和我有血緣關係的親戚更像家人。家人是關於持續的存在和關懷，不是血緣。', vocab: [{ word: 'chosen family', def: '選擇的家人' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The concept of chosen family is powerful. Especially for people whose biological families are complicated or absent.", zh: '「選擇的家人」這個概念很有力量。尤其是對那些原生家庭複雜或缺席的人。', vocab: [{ word: 'biological', def: '血緣的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Even people with close biological families build chosen families too — the friends your parents call by their first names, who show up at every milestone.", zh: '即使是有緊密血緣家庭的人也會建立選擇的家人——你父母直接叫名字的那些朋友、每個重要時刻都出現的人。', vocab: [{ word: 'milestone', def: '重要時刻、里程碑' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "What's the most important thing you've learned from your family?", zh: '你從家人身上學到的最重要的事是什麼？' },
        { speaker: 'a', speakerName: 'Mira', en: "That love isn't just a feeling — it's a practice. Showing up, staying, doing the boring and difficult parts. My family isn't perfect, but they've taught me that you stay even when it's hard.", zh: '愛不只是一種感覺——它是一種實踐。出現、留下來、做枯燥和困難的部分。我的家人不完美，但他們教會了我即使很難也要留下來。' },
        { speaker: 'b', speakerName: 'Jamie', en: "Commitment as love, not just emotion. That's a really grounding thing to carry with you.", zh: '承諾是一種愛，不只是情感。那是一件很有根基的事情，讓你帶著走。', vocab: [{ word: 'grounding', def: '有根基的、穩固的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And maybe that's something we can apply to all our relationships — not just family. Choosing to show up, over and over again.", zh: '也許那是我們可以應用到所有關係中的事——不只是家人。選擇一次又一次地出現。' },
      ],
    },
  ],
  keyPhrases: [
    { en: 'hold a grudge', zh: '記仇', example: "He apologized sincerely, so I decided not to hold a grudge." },
    { en: 'pick your battles', zh: '選擇你的戰場', example: "You can't argue about everything — you have to pick your battles." },
    { en: 'generation gap', zh: '代溝', example: "The generation gap between us shows most clearly in our views on work." },
    { en: 'chosen family', zh: '選擇的家人', example: "My college friends became my chosen family — I can't imagine life without them." },
    { en: 'work ethic', zh: '工作倫理', example: "She has an impressive work ethic — she always gives a hundred percent." },
    { en: 'unlearn', zh: '去除習慣', example: "Some things you were taught growing up you'll need to unlearn as an adult." },
    { en: 'nostalgia', zh: '懷舊', example: "Looking through old photos filled me with nostalgia for simpler times." },
    { en: 'grounding', zh: '有根基的', example: "Having strong family values gives me a grounding sense of stability." },
    { en: 'showing up', zh: '出現、在場', example: "Love is mostly about showing up — being there when it counts." },
    { en: 'consciously', zh: '有意識地', example: "I consciously chose to respond differently than my parents would have." },
  ],
}
