import { Episode } from '../../app/src/data/episode-sample'

export const EPISODE_11: Episode = {
  weekNumber: 11,
  theme: 'Colleagues & Teamwork',
  title: 'Working Together: Office Relationships',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — The People You Work With',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Mira, how important do you think workplace relationships are — like, beyond just being polite?", zh: 'Mira，你覺得職場關係有多重要——不只是表面上的禮貌那種？' },
        { speaker: 'a', speakerName: 'Mira', en: "Enormously important. You spend more waking hours with colleagues than with most people in your personal life. The quality of those relationships affects everything — your mood, your performance, how much you dread Mondays.", zh: '非常重要。你醒著的時候和同事相處的時間，比生活中大多數人都多。那些關係的品質影響一切——你的心情、你的表現、你有多討厭星期一。', vocab: [{ word: 'dread', def: '非常害怕、厭惡' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's so true. I've had jobs where the work itself was fine but the team was toxic, and it made everything miserable.", zh: '太真實了。我有過工作本身還好，但團隊有毒的情況，那讓一切都很痛苦。', vocab: [{ word: 'toxic', def: '有毒的、充滿負能量的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And the reverse — I've stayed in jobs longer than I should have purely because I loved the people I worked with. They become a kind of second family whether you plan for it or not.", zh: '反過來也是——我純粹因為喜歡一起工作的人，在某份工作待得比應該的更久。不管你有沒有計劃，他們會變成一種第二家庭。' },
        { speaker: 'b', speakerName: 'Jamie', en: "How do you go about building those relationships intentionally? Like, what actually works beyond the usual office small talk?", zh: '你怎麼有意識地建立那些關係？就是，除了平常的辦公室閒聊，什麼真正有效？' },
        { speaker: 'a', speakerName: 'Mira', en: "I think the quickest way is to show genuine interest in what someone is working on. Not in a networking way — just real curiosity. People light up when someone actually cares about what they do.", zh: '我覺得最快的方式是對某人正在做的事表現出真正的興趣。不是用那種建立人脈的方式——只是真正的好奇心。當有人真的關心他們做什麼時，人們就會發亮。', vocab: [{ word: 'genuine', def: '真誠的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Curiosity as a social tool. And it probably works because it's hard to fake for very long.", zh: '好奇心作為社交工具。而且它可能有效是因為假裝很難持久。' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. People sense inauthenticity quickly. But when it's real, the connection happens naturally.", zh: '正是。人們很快就能感覺到不真誠。但當它是真實的，連結就自然發生了。', vocab: [{ word: 'inauthenticity', def: '不真誠' }] },
      ],
    },
    {
      title: 'Part 2 — Difficult Colleagues',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What about difficult colleagues? Almost everyone has at least one person at work who they find really challenging.", zh: '那難相處的同事呢？幾乎每個人工作中都有至少一個他們覺得真的很有挑戰性的人。' },
        { speaker: 'a', speakerName: 'Mira', en: "I've had a few. I think the key is separating the behavior from the person — they might be acting in a way that's frustrating, but there's usually a reason behind it that has nothing to do with you.", zh: '我遇過幾個。我覺得關鍵是把行為和人分開——他們可能以一種令你沮喪的方式行事，但通常背後有一個與你無關的原因。', vocab: [{ word: 'separating', def: '分開、區分' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's easier said than done when someone is being passive-aggressive or throwing you under the bus in meetings.", zh: '當有人消極攻擊或在會議上把你推出去背鍋時，說起來容易做起來難。', vocab: [{ word: 'passive-aggressive', def: '消極攻擊的' }, { word: 'throw under the bus', def: '出賣、讓人背鍋' }] },
        { speaker: 'a', speakerName: 'Mira', en: "It is. And in those cases I think you have to address it directly — privately, not in a group setting. Most people behave badly because they feel threatened or unheard, and a direct conversation can often defuse things.", zh: '確實。在那些情況下，我覺得你必須直接處理它——私下，不是在群體場合。大多數人行為不佳是因為他們感到受威脅或沒有被聽見，直接的談話往往可以化解事情。', vocab: [{ word: 'defuse', def: '化解、緩和' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That takes confidence though. A lot of people would rather just avoid the person.", zh: '那需要自信。很多人寧願就是迴避那個人。' },
        { speaker: 'a', speakerName: 'Mira', en: "Avoidance works short-term but compounds the problem. The tension just grows quietly in the background. I learned that the hard way with a colleague a few years ago.", zh: '迴避短期有效，但會讓問題複合。緊張只是在背景中悄悄增長。我幾年前和一個同事吃了虧才學到這個。', vocab: [{ word: 'compounds', def: '使複合、使惡化' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So you eventually had the conversation?", zh: '所以你最終有了那個對話？' },
        { speaker: 'a', speakerName: 'Mira', en: "I did, and it was uncomfortable but it cleared the air. We actually ended up working quite well together after that. Sometimes friction just means you haven't communicated well yet.", zh: '我有，那很不舒服，但它清除了誤會。我們之後其實相處得很好。有時候摩擦只是意味著你們還沒有充分溝通。', vocab: [{ word: 'friction', def: '摩擦' }] },
      ],
    },
    {
      title: 'Part 3 — Teamwork and Collaboration',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What makes a team actually work well together? Not just get along, but really produce good results?", zh: '什麼讓一個團隊真正合作得好？不只是相處融洽，而是真正產出好結果？' },
        { speaker: 'a', speakerName: 'Mira', en: "Clarity and trust, I think. Everyone needs to know what they're responsible for, and they need to trust that others are doing their part. When those two things are missing, everything falls apart.", zh: '我覺得是清晰和信任。每個人都需要知道自己負責什麼，並且需要相信其他人在盡自己的責任。當這兩件事缺失時，一切都會崩潰。', vocab: [{ word: 'clarity', def: '清晰、明確性' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I'd add communication. The teams I've been on that worked best were ones where people felt safe to say what they were thinking — including problems.", zh: '我會補充溝通。我參與過效果最好的團隊，是那些人們覺得可以安全說出自己想法的——包括問題。' },
        { speaker: 'a', speakerName: 'Mira', en: "Psychological safety. That's the term researchers use — when people aren't afraid of being judged or punished for speaking up, teams innovate and solve problems so much better.", zh: '心理安全感。那是研究人員使用的術語——當人們不害怕因為發聲而被評判或懲罰時，團隊的創新和解決問題的能力好得多。', vocab: [{ word: 'psychological safety', def: '心理安全感' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The flip side is when people don't feel safe to disagree. You get groupthink — everyone nodding along even when the plan has obvious problems.", zh: '另一面是當人們不覺得可以安全地不同意時。你就會得到群體思維——即使計劃有明顯問題，每個人都點頭附和。', vocab: [{ word: 'groupthink', def: '群體思維' }] },
        { speaker: 'a', speakerName: 'Mira', en: "That's dangerous. The best thing a team member can do is be the person willing to say 'I think there's a problem here' when everyone else is nodding.", zh: '那很危險。一個團隊成員能做的最好的事，就是在其他所有人都點頭時，願意說「我覺得這裡有問題」。' },
        { speaker: 'b', speakerName: 'Jamie', en: "That requires trust in the team and some personal courage. Not everyone's willing to stick their neck out.", zh: '那需要對團隊的信任和一些個人勇氣。不是每個人都願意冒險。', vocab: [{ word: 'stick your neck out', def: '冒險說出意見' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And it depends on whether leadership creates that environment. A good manager rewards the person who raises the concern, instead of making them regret it.", zh: '而且取決於領導者是否創造那種環境。一個好的管理者會獎勵提出擔憂的人，而不是讓他們後悔。' },
      ],
    },
    {
      title: 'Part 4 — Office Social Dynamics',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What's your take on socializing with coworkers outside of work? Like, team dinners or after-work drinks?", zh: '你對在工作以外和同事社交有什麼看法？比如說團隊聚餐或下班後喝酒？' },
        { speaker: 'a', speakerName: 'Mira', en: "I think it's valuable but shouldn't be mandatory. The best team bonding happens when people genuinely want to be there, not when they're attending out of obligation.", zh: '我覺得很有價值，但不應該是強制的。最好的團隊凝聚發生在人們真正想在那裡的時候，而不是出於義務參加。', vocab: [{ word: 'mandatory', def: '強制的' }, { word: 'obligation', def: '義務' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I've noticed that the best work friendships often develop in the spaces between tasks — the spontaneous coffee runs, the random hallway conversations.", zh: '我注意到最好的工作友誼往往在任務之間的空間裡發展——自發的去拿咖啡、隨機的走廊對話。', vocab: [{ word: 'spontaneous', def: '自發的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "You can't really manufacture those moments. They happen when there's time and ease. Which is one reason I think fully remote work has its limits — those accidental interactions are really valuable.", zh: '你無法真的製造那些時刻。它們在有時間和輕鬆的時候發生。這也是我認為完全遠端工作有其局限的原因之一——那些偶然的互動真的很有價值。' },
        { speaker: 'b', speakerName: 'Jamie', en: "How about office politics? That's an unavoidable part of most workplaces.", zh: '那辦公室政治呢？那是大多數工作場所不可避免的一部分。', vocab: [{ word: 'office politics', def: '辦公室政治' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I try to stay out of the gossip side of it. But understanding the informal power structures — who actually influences decisions, who people go to when things are stuck — that's not politics, that's just knowing how things work.", zh: '我盡量遠離八卦的那一面。但理解非正式的權力結構——誰真正影響決策、事情卡住時人們去找誰——那不是政治，那只是了解事情如何運作。', vocab: [{ word: 'gossip', def: '八卦' }, { word: 'informal', def: '非正式的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's a mature way to put it. Political awareness without playing games.", zh: '那是一個成熟的說法。政治意識而不玩手段。' },
        { speaker: 'a', speakerName: 'Mira', en: "Right. You don't have to participate in the politics to understand them. And understanding them protects you.", zh: '正是。你不必參與政治，但要理解它們。而理解它們保護你。' },
      ],
    },
    {
      title: 'Part 5 — Being a Good Colleague',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "If you had to sum up what makes someone a genuinely good colleague, what would you say?", zh: '如果你必須總結是什麼讓一個人成為真正的好同事，你會怎麼說？' },
        { speaker: 'a', speakerName: 'Mira', en: "Reliability. Do what you say you're going to do, on time. That sounds basic but it's actually rare, and it builds more trust than almost anything else.", zh: '可靠性。做你說要做的事，準時。聽起來很基本，但實際上很罕見，而且它建立的信任幾乎超過其他任何事情。', vocab: [{ word: 'reliability', def: '可靠性' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "What else?", zh: '還有什麼？' },
        { speaker: 'a', speakerName: 'Mira', en: "Being generous with information and credit. Some people hoard knowledge as a form of job security, and it makes the whole team slower. The best colleagues share what they know freely.", zh: '對資訊和功勞大方。有些人把知識當作工作保障而囤積，那讓整個團隊變慢。最好的同事會自由分享他們所知道的。', vocab: [{ word: 'hoard', def: '囤積' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And giving credit is huge. There's nothing more demoralizing than doing good work and having someone else take credit for it.", zh: '而給予功勞是很重要的。沒有什麼比做了好工作卻被別人搶功更讓人洩氣的了。', vocab: [{ word: 'demoralizing', def: '令人洩氣的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And I'd add — being a good colleague means asking 'how can I help?' before you need anything yourself. Relationships are deposits and withdrawals. Make more deposits than withdrawals.", zh: '我還要補充——成為好同事意味著在你需要任何東西之前先問「我能幫什麼忙？」關係就是存款和提款。存款要多於提款。', vocab: [{ word: 'deposits', def: '存款（比喻付出）' }, { word: 'withdrawals', def: '提款（比喻索取）' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I like that framing. Relationships as a balance sheet.", zh: '我喜歡這個比喻。關係就像資產負債表。' },
        { speaker: 'a', speakerName: 'Mira', en: "And if you maintain that balance over time, people want to work with you — which honestly makes every job a lot better.", zh: '如果你長期維持那種平衡，人們就想和你一起工作——這說真的讓每份工作都好很多。' },
      ],
    },
  ],
  keyPhrases: [
    { en: 'toxic (environment)', zh: '有毒的（環境）', example: "A toxic team can make even a great job feel unbearable." },
    { en: 'throw under the bus', zh: '讓人背鍋', example: "Don't throw your colleagues under the bus just to look good in front of management." },
    { en: 'defuse', zh: '化解、緩和', example: "A calm, direct conversation can often defuse a tense work situation." },
    { en: 'psychological safety', zh: '心理安全感', example: "Psychological safety allows teams to take risks and share ideas openly." },
    { en: 'groupthink', zh: '群體思維', example: "Groupthink is dangerous — teams need someone willing to challenge the consensus." },
    { en: 'stick your neck out', zh: '冒險發聲', example: "He stuck his neck out and pointed out the flaw in the plan before it was too late." },
    { en: 'office politics', zh: '辦公室政治', example: "Understanding office politics doesn't mean you have to participate in them." },
    { en: 'hoard', zh: '囤積', example: "Don't hoard information — sharing knowledge helps the whole team." },
    { en: 'demoralizing', zh: '令人洩氣的', example: "It's demoralizing when your contributions aren't acknowledged." },
    { en: 'deposits and withdrawals', zh: '存款與提款（付出與索取）', example: "Think of relationships as a balance of deposits and withdrawals." },
  ],
}
