import { Episode } from '../types';

export const WEEK_50: Episode[] = [
  {
    weekNumber: 50,
    dayOfWeek: 1,
    date: '2026-12-07',
    theme: 'Gratitude & Appreciation',
    title: 'The Science of Gratitude',
    phase: 'p6',
    parts: [
      {
                title: 'What Is Gratitude?',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude — it seems simple, but it's actually quite profound when you look closely.", zh: "感恩——聽起來簡單，但仔細看時其實相當深刻。", vocab: [{ word: "gratitude", def: "感恩；感謝" }] },
          { speaker: 'b', speakerName: 'James', en: "It's more than just saying thank you. It's a way of orienting toward the world.", zh: "它不只是說謝謝，它是一種朝向世界的定向方式。", vocab: [{ word: "orienting", def: "定向；朝向" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Psychologist Robert Emmons calls it 'recognizing the goodness in one's life.'", zh: "心理學家羅伯特·埃蒙斯稱之為「認識生命中的善」。", vocab: [{ word: "goodness", def: "善；美好的事物" }] },
          { speaker: 'b', speakerName: 'James', en: "And acknowledging that some of that goodness comes from outside yourself.", zh: "並且承認那種善的一些來自於你自身之外。", vocab: [{ word: "acknowledging", def: "承認；認可" }] },
          { speaker: 'a', speakerName: 'Maya', en: "That's an important piece — gratitude implies a source, a giver, not just a feeling.", zh: "那是重要的一點——感恩暗示著一個來源、一個給予者，而不只是一種感覺。", vocab: [{ word: "implies", def: "暗示；意味著" }] },
          { speaker: 'b', speakerName: 'James', en: "Which is why it creates connection — it orients you toward others and the world.", zh: "這就是為什麼它創造連結——它使你朝向他人和世界定向。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Unlike happiness, which can be passive, gratitude requires active noticing.", zh: "不像幸福，幸福可以是被動的，感恩需要積極地注意。", vocab: [{ word: "passive", def: "被動的；消極的" }] },
          { speaker: 'b', speakerName: 'James', en: "You have to choose to see and name what's good. That act itself is transformative.", zh: "你必須選擇看到並命名美好的事物，那個行為本身就是轉化性的。", vocab: [] },
        ],
      },
      {
                title: 'The Research Behind Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "The research on gratitude is genuinely impressive. It's one of the most studied positive psychology interventions.", zh: "關於感恩的研究真的令人印象深刻，它是研究最多的積極心理學介入之一。", vocab: [{ word: "intervention", def: "介入；干預" }] },
          { speaker: 'b', speakerName: 'James', en: "Regular gratitude practice increases life satisfaction, reduces depression, and improves sleep.", zh: "定期的感恩實踐增加生活滿意度、減少抑鬱並改善睡眠。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Martin Seligman's three good things exercise — writing down three positive things each day — is simple and powerful.", zh: "馬丁·塞利格曼的三件好事練習——每天寫下三件積極的事情——簡單而有力量。", vocab: [{ word: "three good things exercise", def: "三件好事練習" }] },
          { speaker: 'b', speakerName: 'James', en: "It trains the brain to scan for positives rather than threats — rewiring attention.", zh: "它訓練大腦掃描積極面而不是威脅——重新連接注意力。", vocab: [{ word: "rewiring", def: "重新連接；重塑神經迴路" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The brain has negativity bias — it notices bad things more readily than good ones.", zh: "大腦有負面偏見——它比好事更容易注意到壞事。", vocab: [{ word: "negativity bias", def: "負面偏見" }] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude practice actively counteracts that bias by intentionally noticing the good.", zh: "感恩實踐通過有意識地注意美好事物，積極地對抗那種偏見。", vocab: [{ word: "counteracts", def: "對抗；抵消" }] },
          { speaker: 'a', speakerName: 'Maya', en: "And it's cumulative — the more you practice, the more natural it becomes.", zh: "而且它是累積的——你練習得越多，它就越自然。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Like any skill, gratitude gets stronger with use.", zh: "像任何技能一樣，感恩隨著使用而增強。", vocab: [] },
        ],
      },
      {
                title: 'Gratitude Letters',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "One of the most powerful gratitude exercises is writing a gratitude letter.", zh: "最有力量的感恩練習之一是寫感恩信。", vocab: [{ word: "gratitude letter", def: "感恩信" }] },
          { speaker: 'b', speakerName: 'James', en: "Writing to someone who made a difference in your life and telling them specifically how.", zh: "寫信給對你生命有影響的人，並具體告訴他們如何影響你。", vocab: [{ word: "specifically", def: "具體地；明確地" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The research shows both the writer and the recipient benefit enormously.", zh: "研究顯示，寫信者和收信者都大量受益。", vocab: [{ word: "recipient", def: "收信者；接受者" }] },
          { speaker: 'b', speakerName: 'James', en: "And reading it in person — delivering it face-to-face — amplifies the effect dramatically.", zh: "親自朗讀它——面對面地傳遞——極大地放大了效果。", vocab: [{ word: "amplifies", def: "放大；增強" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Have you ever written one?", zh: "你有寫過嗎？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Yes — to a mentor who never knew how much she changed my life. She cried. I cried.", zh: "有——寫給一位從不知道她改變了我多少生命的導師，她哭了，我也哭了。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "It's one of those experiences that stays with you forever.", zh: "那是那種永遠留在你心中的體驗之一。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The investment of time and vulnerability returns profound connection.", zh: "時間和脆弱的投資換來了深刻的連結。", vocab: [{ word: "investment", def: "投資；付出" }] },
        ],
      },
      {
                title: 'Gratitude in Difficult Times',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Here's a harder question — can you be grateful even during painful times?", zh: "這是一個更難的問題——即使在痛苦的時期，你能感恩嗎？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That's where gratitude gets deep. It's not about pretending everything is fine.", zh: "那是感恩變得深刻的地方，不是關於假裝一切都好。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Toxic positivity — forcing gratitude when you're genuinely suffering — is harmful.", zh: "毒性積極性——在真正受苦時強迫感恩——是有害的。", vocab: [{ word: "toxic positivity", def: "毒性積極性" }] },
          { speaker: 'b', speakerName: 'James', en: "But authentic gratitude can coexist with difficulty. Even in hard times, something remains.", zh: "但真正的感恩可以與困難共存，即使在艱難時期，某些東西仍然存在。", vocab: [{ word: "coexist", def: "共存；並存" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Viktor Frankl found meaning and gratitude even in extreme suffering.", zh: "維克多·法蘭可即使在極度痛苦中也找到了意義和感恩。", vocab: [{ word: "extreme suffering", def: "極度痛苦" }] },
          { speaker: 'b', speakerName: 'James', en: "Finding tiny moments of goodness — a kind word, a beam of light — that's not denial. It's strength.", zh: "找到微小的善意時刻——一句善意的話、一道光束——那不是否認，而是力量。", vocab: [{ word: "denial", def: "否認；拒絕承認" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude in hard times doesn't erase the hardship — it contextualizes it.", zh: "艱難時期的感恩不會消除艱辛——它將其置於情境中。", vocab: [{ word: "contextualizes", def: "置於情境；賦予背景" }] },
          { speaker: 'b', speakerName: 'James', en: "It says: this is hard, and there is still something here worth noticing.", zh: "它說：這很難，而且這裡仍然有值得注意的東西。", vocab: [] },
        ],
      },
      {
                title: 'Starting a Gratitude Practice',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "How would you recommend someone start a gratitude practice if they've never tried?", zh: "如果有人從未嘗試過，你會怎麼建議他們開始感恩實踐？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Start incredibly small. One thing, each morning. Doesn't have to be poetic.", zh: "從非常小的地方開始，每天早晨一件事，不必很詩意。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Just naming it — I'm grateful for this coffee, for the quiet, for my health today.", zh: "只是命名它——我感恩這杯咖啡，感恩這份安靜，感恩今天的健康。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Specificity matters — vague gratitude is less powerful than specific.", zh: "具體性很重要——模糊的感恩不如具體的有力量。", vocab: [{ word: "specificity", def: "具體性；特殊性" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Not just 'I'm grateful for my family' — but 'I'm grateful my sister called this morning.'", zh: "不只是「我感恩我的家人」——而是「我感恩我姐姐今天早上打來電話」。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The specific details anchor the feeling. They make it real and visceral.", zh: "具體的細節讓感覺落地，使它真實而直接。", vocab: [{ word: "anchor", def: "固定；使落地" }] },
          { speaker: 'a', speakerName: 'Maya', en: "I'm going to commit to the three good things exercise every evening this week.", zh: "我打算承諾這週每天晚上做三件好事練習。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And I'll write that gratitude letter I've been putting off for too long.", zh: "我要寫那封我拖延太久的感恩信。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "negativity bias", zh: "負面偏見" },
      { en: "three good things exercise", zh: "三件好事練習" },
      { en: "gratitude letter", zh: "感恩信" },
      { en: "toxic positivity", zh: "毒性積極性" },
      { en: "rewiring attention", zh: "重新連接注意力" },
      { en: "specificity", zh: "具體性；特殊性" },
      { en: "coexist", zh: "共存；並存" },
      { en: "intervention", zh: "介入；干預" },
      { en: "denial", zh: "否認；拒絕承認" },
      { en: "contextualizes", zh: "置於情境；賦予背景" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 2,
    date: '2026-12-08',
    theme: 'Gratitude & Appreciation',
    title: 'Appreciating People in Your Life',
    phase: 'p6',
    parts: [
      {
                title: 'The Appreciation Gap',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "There's research showing we consistently underestimate how much people appreciate being told they matter.", zh: "有研究表明，我們一直低估了人們被告知他們很重要時的感激程度。", vocab: [{ word: "underestimate", def: "低估" }] },
          { speaker: 'b', speakerName: 'James', en: "The appreciation gap — we feel appreciation but rarely express it.", zh: "感激差距——我們感到感激但很少表達它。", vocab: [{ word: "appreciation gap", def: "感激差距" }] },
          { speaker: 'a', speakerName: 'Maya', en: "We assume the other person knows, or we feel awkward saying it.", zh: "我們假設對方知道，或者我們覺得說出來很尷尬。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "But people don't know unless you tell them. Mind-reading doesn't work.", zh: "但人們除非你告訴他們，否則不知道，讀心術是行不通的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "And the awkwardness we fear is almost always less bad than we imagine.", zh: "而我們擔心的尷尬幾乎總是沒有我們想像的那麼糟糕。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "I've never once regretted telling someone I appreciated them. Not once.", zh: "我從來沒有後悔告訴某人我感激他們，一次都沒有。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "The regret almost always runs the other direction — wishing you'd said it when you had the chance.", zh: "後悔幾乎總是朝另一個方向運行——希望你在有機會時說了它。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Say it now. People leave, circumstances change. Don't wait for perfect moment.", zh: "現在說，人們離開，情況改變，不要等待完美的時刻。", vocab: [] },
        ],
      },
      {
                title: 'Expressing Appreciation Meaningfully',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "There's a difference between a casual 'thanks' and genuine, deep appreciation.", zh: "隨口說的「謝謝」和真誠、深刻的感激之間有差別。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gary Chapman's five love languages — words of affirmation, acts of service, gifts, quality time, touch.", zh: "蓋瑞·查普曼的五種愛的語言——肯定的話語、服務行為、禮物、優質時間、觸摸。", vocab: [{ word: "five love languages", def: "五種愛的語言" }] },
          { speaker: 'a', speakerName: 'Maya', en: "People receive appreciation differently. Knowing someone's language matters.", zh: "人們接受感激的方式不同，了解某人的語言很重要。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Telling a words person 'thank you' is great. Doing an act of service for them is even better.", zh: "對語言型的人說「謝謝」很好，為他們做一個服務行為更好。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Specific appreciation — naming what you valued and why — lands much deeper.", zh: "具體的感激——命名你珍視的東西及原因——能更深入地觸動人心。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Not just 'you're great' — but 'when you did X in that meeting, it made me feel Y.'", zh: "不只是「你很棒」——而是「當你在那次會議中做了X，它讓我感到Y」。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "The specificity makes it real. It shows you really paid attention.", zh: "具體性使它真實，它顯示你真的注意了。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Being seen — truly noticed — might be the deepest form of appreciation we can offer.", zh: "被看見——真正被注意到——可能是我們能提供的最深刻的感激形式。", vocab: [{ word: "truly noticed", def: "真正被注意到" }] },
        ],
      },
      {
                title: 'Appreciating the Everyday',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "We often appreciate people most after we lose them or they're no longer there.", zh: "我們常常在失去他們或他們不在了之後才最感激他們。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The familiarity problem — we stop noticing people when they're constant in our lives.", zh: "熟悉問題——當人們在我們生命中持續存在時，我們停止注意他們。", vocab: [{ word: "familiarity", def: "熟悉；習以為常" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The partner who always makes coffee. The colleague who clears up after meetings.", zh: "總是泡咖啡的伴侶，在會議後清理的同事。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "These invisible contributions keep our lives running. They deserve appreciation.", zh: "這些看不見的貢獻維持著我們的生活，它們值得感激。", vocab: [{ word: "invisible contributions", def: "看不見的貢獻" }] },
          { speaker: 'a', speakerName: 'Maya', en: "A thought experiment: if this person were suddenly gone, what would I miss?", zh: "一個思想實驗：如果這個人突然不在了，我會想念什麼？", vocab: [{ word: "thought experiment", def: "思想實驗" }] },
          { speaker: 'b', speakerName: 'James', en: "That exercise — imagining absence — powerfully restores appreciation for presence.", zh: "那個練習——想像缺席——有力地恢復了對存在的感激。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "George Bailey in It's a Wonderful Life — seeing life as if he'd never existed.", zh: "《生活多美好》中的喬治·貝利——看到生命就好像他從未存在過。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "A story that works precisely because it shows what's already there but unseen.", zh: "一個之所以有效的故事，正是因為它展示了已經存在但未被看見的東西。", vocab: [] },
        ],
      },
      {
                title: 'Self-Appreciation',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "We talk about appreciating others — but what about appreciating yourself?", zh: "我們談論感激他人——但感激自己呢？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That's harder. We're often much harsher critics of ourselves than of others.", zh: "那更難，我們通常對自己比對他人更嚴苛。", vocab: [{ word: "harsher", def: "更嚴苛的；更嚴厲的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Self-compassion researcher Kristin Neff says we should treat ourselves as we'd treat a good friend.", zh: "自我同情研究者克里斯汀·奈夫說，我們應該像對待好朋友一樣對待自己。", vocab: [{ word: "self-compassion", def: "自我同情" }] },
          { speaker: 'b', speakerName: 'James', en: "When a friend fails, you don't berate them endlessly. You offer perspective and kindness.", zh: "當朋友失敗時，你不會無休止地責罵他們，你給予視角和善意。", vocab: [{ word: "berate", def: "責罵；嚴厲批評" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Appreciating your own efforts, your own progress, your own unique qualities.", zh: "感激你自己的努力、你自己的進步、你自己獨特的品質。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Not in a narcissistic way — but in a genuinely respectful recognition of your humanity.", zh: "不是以自戀的方式——而是以真誠尊重地認可你的人性。", vocab: [{ word: "narcissistic", def: "自戀的；自我中心的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "You've made it through difficult things. You've grown. You've shown up.", zh: "你熬過了困難的事情，你成長了，你出現了。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Those things are worth appreciating — even if no one else notices.", zh: "那些事情值得感激——即使沒有人注意到。", vocab: [] },
        ],
      },
      {
                title: 'The Ripple Effect of Appreciation',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Appreciation creates ripples — when someone feels valued, they pass it on.", zh: "感激創造漣漪——當某人感到被重視時，他們會傳遞出去。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Research shows appreciated employees are more productive, creative, and loyal.", zh: "研究顯示，被感激的員工更有生產力、創造力和忠誠度。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Appreciation is free and infinite — yet so many environments are starved of it.", zh: "感激是免費且無限的——然而如此多的環境都缺乏它。", vocab: [{ word: "starved of", def: "缺乏；極度渴望" }] },
          { speaker: 'b', speakerName: 'James', en: "Managers who make people feel genuinely appreciated create fundamentally different cultures.", zh: "讓人們真正感到被感激的管理者創造了根本不同的文化。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "And families, and friendships, and communities too.", zh: "家庭、友誼和社群也是如此。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Starting a gratitude practice isn't just good for you — it changes the environments around you.", zh: "開始感恩實踐不只對你有益——它改變了你周圍的環境。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "As you notice more good, you express more good, and good multiplies.", zh: "當你注意到更多的好，你表達更多的好，好事就會倍增。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That's a pretty wonderful cycle to set in motion.", zh: "那是一個相當美好的循環，值得啟動。", vocab: [{ word: "set in motion", def: "啟動；使開始運轉" }] },
        ],
      },
    ],
    keyPhrases: [
      { en: "appreciation gap", zh: "感激差距" },
      { en: "five love languages", zh: "五種愛的語言" },
      { en: "thought experiment", zh: "思想實驗" },
      { en: "self-compassion", zh: "自我同情" },
      { en: "invisible contributions", zh: "看不見的貢獻" },
      { en: "familiarity problem", zh: "熟悉問題（習以為常而忽視）" },
      { en: "set in motion", zh: "啟動；使開始運轉" },
      { en: "narcissistic", zh: "自戀的；自我中心的" },
      { en: "starved of", zh: "缺乏；極度渴望" },
      { en: "truly noticed", zh: "真正被注意到" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 3,
    date: '2026-12-09',
    theme: 'Gratitude & Appreciation',
    title: 'Finding Beauty in Ordinary Life',
    phase: 'p6',
    parts: [
      {
                title: 'The Art of Noticing',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "There's an art to noticing beauty in the ordinary — it doesn't happen automatically.", zh: "在平凡中注意美麗是一種藝術——它不會自動發生。", vocab: [{ word: "noticing", def: "注意；覺察" }] },
          { speaker: 'b', speakerName: 'James', en: "We habituate to our lives. The extraordinary becomes invisible through repetition.", zh: "我們習慣了自己的生活，非凡的東西通過重複而變得不可見。", vocab: [{ word: "habituate", def: "習慣化；養成習慣" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The first time you saw your city's skyline — remember that wonder? It fades.", zh: "你第一次看到你城市的天際線——記得那種驚奇嗎？它會消退。", vocab: [{ word: "wonder", def: "驚奇；奇蹟" }] },
          { speaker: 'b', speakerName: 'James', en: "Habituation is helpful — we can't be amazed by everything all the time. But we lose something.", zh: "習慣化是有用的——我們無法始終對每件事都感到驚嘆，但我們失去了一些東西。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Mindfulness practices — paying attention on purpose — help restore fresh perception.", zh: "正念實踐——有目的地注意——幫助恢復新鮮的感知。", vocab: [{ word: "fresh perception", def: "新鮮的感知；新眼光" }] },
          { speaker: 'b', speakerName: 'James', en: "Beginner's mind — approaching familiar things with the curiosity of someone seeing them first.", zh: "初學者的心態——以第一次看到它們的人的好奇心接近熟悉的事物。", vocab: [{ word: "beginner's mind", def: "初學者的心態" }] },
          { speaker: 'a', speakerName: 'Maya', en: "I sometimes try to walk home from work as if I've never seen the street before.", zh: "我有時嘗試像從未見過那條街一樣走路回家。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And what do you notice?", zh: "你注意到了什麼？", vocab: [] },
        ],
      },
      {
                title: 'Seeing the Sacred in the Ordinary',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Everything. The way light falls, the trees I'd never noticed, interesting doorways.", zh: "一切，光線落下的方式、我從未注意到的樹木、有趣的門廊。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That's the insight of so many contemplative traditions — the sacred is in the ordinary.", zh: "那是許多沉思傳統的洞察——神聖存在於平凡之中。", vocab: [{ word: "contemplative", def: "沉思的；冥想的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The Japanese aesthetic of wabi-sabi — beauty in the imperfect, impermanent, and incomplete.", zh: "日本的侘寂美學——在不完美、無常和不完整中的美。", vocab: [{ word: "impermanent", def: "無常的；短暫的" }] },
          { speaker: 'b', speakerName: 'James', en: "A cracked bowl repaired with gold — kintsugi — becomes more beautiful for having been broken.", zh: "用黃金修復的破碗——金繼——因為曾經破碎而變得更美麗。", vocab: [{ word: "kintsugi", def: "金繼（日本修復藝術，以金粉修補裂縫）" }] },
          { speaker: 'a', speakerName: 'Maya', en: "That philosophy changes how you see scars, failures, imperfections — in objects and in people.", zh: "那種哲學改變了你如何看待疤痕、失敗、不完美——在物品和人中。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude for the flawed and impermanent — for what is, not what we wish it were.", zh: "對有缺陷和無常的感激——對現狀，而不是我們希望它是什麼。", vocab: [{ word: "flawed", def: "有缺陷的；不完美的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "That acceptance itself is a profound act of appreciation.", zh: "那種接受本身就是一種深刻的感激行為。", vocab: [{ word: "acceptance", def: "接受；接納" }] },
          { speaker: 'b', speakerName: 'James', en: "Loving things as they are rather than as you wish they would be.", zh: "愛事物本來的樣子，而不是你希望它們成為的樣子。", vocab: [] },
        ],
      },
      {
                title: 'Sensory Appreciation',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Our senses are incredible gifts. We rarely use them fully.", zh: "我們的感官是不可思議的禮物，我們很少完全使用它們。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Actually tasting food, really hearing music, feeling the texture of things under your hands.", zh: "真正地品嚐食物，真正地聆聽音樂，感受手下事物的紋理。", vocab: [{ word: "texture", def: "紋理；質感" }] },
          { speaker: 'a', speakerName: 'Maya', en: "We often consume experiences rather than inhabit them.", zh: "我們通常消費體驗而不是居住在體驗中。", vocab: [{ word: "inhabit", def: "居住於；真正體驗" }] },
          { speaker: 'b', speakerName: 'James', en: "Tasting without distraction — no screen, no conversation — is a revelation.", zh: "不分心地品嚐——沒有螢幕，沒有對話——是一種啟示。", vocab: [{ word: "revelation", def: "啟示；揭示" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The food you eat every day suddenly becomes new when you actually pay attention.", zh: "當你真正注意時，你每天吃的食物突然變得新鮮起來。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Sound bathing — really listening to music without doing anything else — is similar.", zh: "聲音浴——不做任何其他事情，真正地聆聽音樂——是類似的。", vocab: [{ word: "sound bathing", def: "聲音浴；沉浸式聆聽" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Or just listening to ambient sound — rain, birds, city noise — without labeling it.", zh: "或者只是聆聽環境聲音——雨聲、鳥鳴、城市噪音——不給它貼標籤。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Sensory appreciation is a form of gratitude for being alive, for having a body.", zh: "感官感激是對活著的感謝，對擁有身體的感謝。", vocab: [] },
        ],
      },
      {
                title: 'Gratitude for Nature',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Nature offers endless beauty to appreciate — if we stop and look.", zh: "大自然提供了無盡的美麗可以感激——如果我們停下來看。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "A sunset, the pattern of bark on a tree, the sound of wind in leaves.", zh: "日落、樹皮上的紋理、樹葉中風的聲音。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "These experiences are free and available to everyone. Nature is the great democratizer of beauty.", zh: "這些體驗是免費的，每個人都可以獲得，大自然是美麗的偉大民主化者。", vocab: [{ word: "democratizer", def: "民主化者；使人人可及的力量" }] },
          { speaker: 'b', speakerName: 'James', en: "Research confirms that time in nature generates the same feelings as spiritual experiences.", zh: "研究證實，在大自然中度過時間會產生與靈性體驗相同的感覺。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Awe — that feeling of something vast and beautiful beyond your full comprehension.", zh: "敬畏——那種超出你完整理解的廣大而美麗事物的感覺。", vocab: [{ word: "awe", def: "敬畏；驚嘆" }] },
          { speaker: 'b', speakerName: 'James', en: "Awe research shows it increases prosocial behavior and reduces self-focus.", zh: "敬畏研究表明它增加了親社會行為並減少了自我關注。", vocab: [{ word: "prosocial behavior", def: "親社會行為" }] },
          { speaker: 'a', speakerName: 'Maya', en: "When you feel small in the face of something vast, your problems shrink too.", zh: "當你在某個廣大的事物面前感到渺小時，你的問題也縮小了。", vocab: [{ word: "shrink", def: "縮小；收縮" }] },
          { speaker: 'b', speakerName: 'James', en: "That's why mountains, oceans, and starry skies have comforted humans throughout history.", zh: "這就是為什麼山脈、海洋和星空在整個歷史上讓人類感到安慰。", vocab: [] },
        ],
      },
      {
                title: 'Cultivating Appreciation Daily',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "How do you build the habit of noticing and appreciating what's already there?", zh: "你如何建立注意和感激已有事物的習慣？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Anchor it to something you already do. Morning coffee, your commute, getting dressed.", zh: "把它固定在你已經做的事情上，早晨咖啡、通勤、穿衣服。", vocab: [{ word: "anchor it to", def: "把它固定在；與……連結" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Use that moment to notice one thing you're grateful for. It takes thirty seconds.", zh: "利用那個時刻注意一件你感激的事，只需三十秒。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Habit stacking — attaching a new behavior to an existing one — is powerful for practice.", zh: "習慣堆疊——將新行為附加到現有習慣上——對實踐很有力量。", vocab: [{ word: "habit stacking", def: "習慣堆疊" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Photography can also train appreciation — looking for things worth capturing.", zh: "攝影也可以訓練感激——尋找值得捕捉的東西。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Even just looking for light, composition, and beauty — it retrains your attention.", zh: "即使只是尋找光線、構圖和美麗——它重新訓練了你的注意力。", vocab: [{ word: "composition", def: "構圖；構成" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The world doesn't have to change for your experience of it to become richer.", zh: "世界不必改變，你對它的體驗就可以變得更豐富。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The change is in the quality of attention you bring. And that's always available to you.", zh: "改變在於你帶來的注意力質量，那始終對你是可用的。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "beginner's mind", zh: "初學者的心態" },
      { en: "wabi-sabi", zh: "侘寂（日本不完美之美）" },
      { en: "kintsugi", zh: "金繼（用黃金修補裂縫的藝術）" },
      { en: "awe", zh: "敬畏；驚嘆" },
      { en: "habit stacking", zh: "習慣堆疊" },
      { en: "fresh perception", zh: "新鮮的感知；新眼光" },
      { en: "habituation", zh: "習慣化；養成習慣" },
      { en: "impermanent", zh: "無常的；短暫的" },
      { en: "prosocial behavior", zh: "親社會行為" },
      { en: "sensory appreciation", zh: "感官感激" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 4,
    date: '2026-12-10',
    theme: 'Gratitude & Appreciation',
    title: 'Gratitude and Perspective',
    phase: 'p6',
    parts: [
      {
                title: 'Perspective as a Choice',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Perspective is maybe the most powerful mental tool we have.", zh: "視角也許是我們擁有的最有力的心理工具。", vocab: [{ word: "perspective", def: "視角；觀點" }] },
          { speaker: 'b', speakerName: 'James', en: "The same situation can be experienced as a disaster or a blessing depending on the frame.", zh: "同一個情況可以根據框架被體驗為災難或祝福。", vocab: [{ word: "frame", def: "框架；框架效應" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Stoic philosophy taught this — you can't always control events, but you can control your response.", zh: "斯多葛哲學教導了這一點——你無法始終控制事件，但你可以控制你的反應。", vocab: [{ word: "Stoic philosophy", def: "斯多葛哲學" }] },
          { speaker: 'b', speakerName: 'James', en: "Marcus Aurelius wrote entire books on finding gratitude and equanimity within difficult circumstances.", zh: "馬可·奧里略寫了整本書，關於在艱難情況下找到感激和平靜。", vocab: [{ word: "equanimity", def: "平靜；沉著" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The discipline of perspective isn't about denying difficulty — it's about not being defined by it.", zh: "視角的訓練不是關於否認困難——而是關於不被它定義。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Asking 'what can I learn here?' or 'what does this make possible?' — those reframe everything.", zh: "問「我在這裡能學到什麼？」或「這使什麼成為可能？」——那些重新框架了一切。", vocab: [{ word: "reframe", def: "重新框架；重新詮釋" }] },
          { speaker: 'a', speakerName: 'Maya', en: "It takes practice. Gratitude and perspective together become a kind of resilience.", zh: "這需要練習，感激和視角一起成為一種韌性。", vocab: [{ word: "resilience", def: "韌性；復原力" }] },
          { speaker: 'b', speakerName: 'James', en: "Not Pollyanna positivity — but genuine, grounded strength.", zh: "不是波麗安娜式的積極性——而是真實、有根基的力量。", vocab: [{ word: "Pollyanna", def: "波麗安娜（過度樂觀的比喻）" }] },
        ],
      },
      {
                title: 'Comparative Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Have you heard of the concept of 'downward comparison'?", zh: "你聽說過「向下比較」的概念嗎？", vocab: [{ word: "downward comparison", def: "向下比較" }] },
          { speaker: 'b', speakerName: 'James', en: "Comparing yourself to those worse off — it can generate gratitude, though it feels uncomfortable.", zh: "將自己與處境更差的人比較——它可以產生感激，雖然感覺不舒服。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "We naturally compare upward — with those who have more. It breeds envy and dissatisfaction.", zh: "我們自然地向上比較——與擁有更多的人比較，這滋生了嫉妒和不滿。", vocab: [{ word: "envy", def: "嫉妒；羨慕" }] },
          { speaker: 'b', speakerName: 'James', en: "Consciously noticing what you have that others lack shifts that default.", zh: "有意識地注意你所擁有而他人缺乏的東西改變了那個默認模式。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Clean water, safety, health, education — billions lack things we take for granted.", zh: "清潔的水、安全、健康、教育——數十億人缺乏我們視為理所當然的東西。", vocab: [{ word: "take for granted", def: "視為理所當然" }] },
          { speaker: 'b', speakerName: 'James', en: "Not to feel guilty — but to feel genuinely appreciative of what fortune has provided.", zh: "不是為了感到內疚——而是為了真正感激命運所提供的東西。", vocab: [{ word: "appreciative", def: "感激的；欣賞的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "There's a thin line between gratitude and guilt here. How do you walk it?", zh: "這裡感激和內疚之間有一條細線，你如何走過它？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude motivates generosity. Guilt leads to paralysis. Choose gratitude.", zh: "感激激勵慷慨，內疚導致癱瘓，選擇感激。", vocab: [{ word: "paralysis", def: "癱瘓；無法行動" }] },
        ],
      },
      {
                title: 'Gratitude After Failure',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Can you be genuinely grateful for failures and setbacks? Not just in retrospect?", zh: "你能真正感激失敗和挫折嗎？不只是在事後？", vocab: [{ word: "setbacks", def: "挫折；退步" }] },
          { speaker: 'b', speakerName: 'James', en: "That's a very advanced practice. Most of us only get there in hindsight.", zh: "那是非常高級的實踐，我們大多數人只有事後才能到達那裡。", vocab: [{ word: "hindsight", def: "事後之明；後見之明" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Post-traumatic growth — real growth that comes from genuinely hard experiences.", zh: "創傷後成長——來自真正艱難體驗的真實成長。", vocab: [{ word: "post-traumatic growth", def: "創傷後成長" }] },
          { speaker: 'b', speakerName: 'James', en: "Most people who've been through significant hardship report it deepened them somehow.", zh: "大多數經歷過重大艱辛的人表示，它以某種方式加深了他們。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That doesn't mean seeking out suffering — or glorifying it.", zh: "那不意味著尋求痛苦——或美化它。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "But finding that what broke you also built you — and being genuinely grateful for that.", zh: "但發現打垮你的東西也建造了你——並對此真正感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The Japanese concept of mono no aware — the bittersweet appreciation of transience.", zh: "日本的物哀概念——對無常的苦樂參半的感激。", vocab: [{ word: "mono no aware", def: "物哀（日語，對無常的苦樂參半感知）" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Beauty that is poignant precisely because it doesn't last.", zh: "正因為它不持久而令人心痛的美麗。", vocab: [{ word: "poignant", def: "令人心痛的；深深感人的" }] },
        ],
      },
      {
                title: 'Global Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "There's a global dimension to gratitude too — appreciating the world as it is.", zh: "感激也有全球維度——感激世界本來的樣子。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Despite real problems — poverty, conflict, environmental damage — there is so much beauty and progress.", zh: "儘管有真實的問題——貧困、衝突、環境破壞——仍有如此多的美麗和進步。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Steven Pinker's work on long-term progress — violence, poverty, and disease are historically at lows.", zh: "史蒂芬·平克關於長期進步的研究——暴力、貧困和疾病在歷史上處於低點。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The news focuses on what's going wrong. The aggregate trend is often positive.", zh: "新聞關注正在出錯的事情，總體趨勢往往是積極的。", vocab: [{ word: "aggregate", def: "總體的；聚集的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Cultivating gratitude for the world means seeing both the problems and the progress.", zh: "培養對世界的感激意味著看到問題和進步兩者。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And appreciating the countless people who work to make things better every day.", zh: "並感激每天為讓事情變得更好而努力工作的無數人。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "The doctors, teachers, engineers, activists — builders of human civilization.", zh: "醫生、教師、工程師、活動人士——人類文明的建造者。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "We inherited so much from those before us. Living with gratitude means honoring that debt.", zh: "我們從前人那裡繼承了太多，帶著感激生活意味著尊重那份債務。", vocab: [{ word: "honoring that debt", def: "尊重那份債務；感恩繼承" }] },
        ],
      },
      {
                title: 'Reorienting Through Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude as a practice ultimately reorients your entire relationship with life.", zh: "作為實踐的感激最終重新定向了你與生命的整個關係。", vocab: [{ word: "reorients", def: "重新定向；重新定位" }] },
          { speaker: 'b', speakerName: 'James', en: "It moves you from scarcity thinking to abundance — from 'what's missing' to 'what's here.'", zh: "它把你從匱乏思維移向豐盛——從「缺少什麼」到「這裡有什麼」。", vocab: [{ word: "scarcity thinking", def: "匱乏思維" }] },
          { speaker: 'a', speakerName: 'Maya', en: "From rights to gifts — from feeling owed things to feeling given things.", zh: "從權利到禮物——從感覺被虧欠到感覺被給予。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That shift is radical. It transforms entitlement into appreciation.", zh: "那種轉變是根本性的，它將理所當然轉化為感激。", vocab: [{ word: "entitlement", def: "理所當然；特權心態" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Not that we shouldn't work toward better circumstances — but grounding in gratitude makes that work joyful.", zh: "不是說我們不應該努力爭取更好的情況——但根植於感激使那種努力充滿喜悅。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "You can work for change from a place of hope rather than resentment.", zh: "你可以從希望而不是怨恨的地方為改變而努力。", vocab: [{ word: "resentment", def: "怨恨；憤恨" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude and action together — accepting what is, while working for what could be.", zh: "感激和行動在一起——接受現狀，同時為可能的未來而努力。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That might be the most mature and powerful orientation toward life.", zh: "那可能是對生命最成熟和最有力量的定向方式。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "Stoic philosophy", zh: "斯多葛哲學" },
      { en: "equanimity", zh: "平靜；沉著" },
      { en: "post-traumatic growth", zh: "創傷後成長" },
      { en: "mono no aware", zh: "物哀（對無常的苦樂參半感知）" },
      { en: "scarcity thinking", zh: "匱乏思維" },
      { en: "entitlement", zh: "理所當然；特權心態" },
      { en: "downward comparison", zh: "向下比較" },
      { en: "reframe", zh: "重新框架；重新詮釋" },
      { en: "poignant", zh: "令人心痛的；深深感人的" },
      { en: "equanimity", zh: "平靜；沉著" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 5,
    date: '2026-12-11',
    theme: 'Gratitude & Appreciation',
    title: 'Gratitude at Work',
    phase: 'p6',
    parts: [
      {
                title: 'Why Workplace Gratitude Matters',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "We spend so many hours at work. What does gratitude look like in that context?", zh: "我們在工作上花了這麼多小時，在那個情境中感激是什麼樣的？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Workplace gratitude is deeply linked to employee engagement and retention.", zh: "職場感激與員工敬業度和留任率深深相關。", vocab: [{ word: "employee engagement", def: "員工敬業度" }] },
          { speaker: 'a', speakerName: 'Maya', en: "One of the top reasons people leave jobs is feeling unappreciated.", zh: "人們離職的首要原因之一是感到不被欣賞。", vocab: [{ word: "unappreciated", def: "不被欣賞的；未被感激的" }] },
          { speaker: 'b', speakerName: 'James', en: "Yet expressing appreciation costs nothing and takes almost no time.", zh: "然而表達感激不花任何成本，幾乎不花任何時間。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "A simple sincere 'thank you for your effort on that' changes how people feel.", zh: "一個簡單真誠的「謝謝你為此付出的努力」改變了人們的感受。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "But it has to be genuine — people can tell the difference between a real thank-you and a hollow one.", zh: "但它必須是真誠的——人們能分辨真正的謝謝和空洞的謝謝之間的區別。", vocab: [{ word: "hollow", def: "空洞的；不真誠的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Specific appreciation — naming what they did and why it mattered — is the gold standard.", zh: "具體的感激——命名他們做了什麼以及為什麼重要——是黃金標準。", vocab: [{ word: "gold standard", def: "黃金標準；最高標準" }] },
          { speaker: 'b', speakerName: 'James', en: "It shows you actually paid attention. That the work was seen, not just received.", zh: "它表明你真的注意了，工作被看見了，而不只是被接收了。", vocab: [] },
        ],
      },
      {
                title: 'Appreciating Colleagues',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "What are some practical ways to express gratitude to colleagues?", zh: "有哪些實際方式向同事表達感激？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "A handwritten note still carries weight in a digital world — it signals real effort.", zh: "在數位世界中，親手寫的便條仍然有分量——它表示了真正的努力。", vocab: [{ word: "handwritten note", def: "親手寫的便條" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Mentioning someone's contribution in a team meeting, in front of others.", zh: "在團隊會議上，在他人面前提及某人的貢獻。", vocab: [{ word: "contribution", def: "貢獻；付出" }] },
          { speaker: 'b', speakerName: 'James', en: "Public recognition activates a kind of pride that private appreciation doesn't quite reach.", zh: "公開認可激發了一種私下感激無法完全觸及的自豪感。", vocab: [{ word: "public recognition", def: "公開認可" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Helping someone out when they're overwhelmed — that's gratitude in action.", zh: "當某人不知所措時幫助他們——那是行動中的感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Returning favors, remembering what someone mentioned, asking follow-up questions — all signs of appreciation.", zh: "回報幫助、記住某人提到的事、提出後續問題——都是感激的表示。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Being genuinely interested in someone's work and wellbeing is its own form of appreciation.", zh: "真正對某人的工作和幸福感興趣本身就是一種感激形式。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "People can tell when you see them as a whole person versus just a function.", zh: "人們能分辨你何時把他們視為完整的人，而不只是一個功能。", vocab: [] },
        ],
      },
      {
                title: 'Grateful Leadership',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Leaders who express gratitude create very different cultures than those who don't.", zh: "表達感激的領導者創造了與那些不這樣做的人截然不同的文化。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude flowing downward — from leader to team — normalizes appreciation across the organization.", zh: "感激向下流動——從領導者到團隊——使整個組織的感激常態化。", vocab: [{ word: "normalizes", def: "使常態化；使正常化" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The best managers I've had made me feel like my work genuinely mattered.", zh: "我遇過最好的管理者讓我感覺自己的工作真的很重要。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Not just cogs in a machine — contributors to something meaningful.", zh: "不只是機器中的齒輪——而是有意義事物的貢獻者。", vocab: [{ word: "cogs", def: "齒輪；小人物" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Adam Grant's research shows givers — those who generously appreciate and help — often rise to the top.", zh: "亞當·格蘭特的研究顯示，給予者——那些慷慨地感激和幫助的人——往往升到頂端。", vocab: [{ word: "givers", def: "給予者" }] },
          { speaker: 'b', speakerName: 'James', en: "Because gratitude is magnetic — people want to be around those who make them feel good.", zh: "因為感激是有磁性的——人們想要在讓他們感覺良好的人周圍。", vocab: [{ word: "magnetic", def: "有磁性的；有吸引力的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "And in high-trust cultures, people bring their best work because they feel safe and valued.", zh: "在高信任的文化中，人們帶來他們最好的工作，因為他們感到安全和被重視。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude is the foundation of psychological safety — knowing your efforts will be seen.", zh: "感激是心理安全的基礎——知道你的努力將被看見。", vocab: [] },
        ],
      },
      {
                title: 'Finding Meaning in Work Through Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "What if your work doesn't feel meaningful? Can gratitude help?", zh: "如果你的工作感覺沒有意義呢？感激能幫忙嗎？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Amy Wrzesniewski's job crafting research — you can reshape even mundane jobs toward meaning.", zh: "艾米·弗雷斯尼威斯基的工作重塑研究——你可以將即使是平凡的工作重新塑造向意義。", vocab: [{ word: "job crafting", def: "工作重塑" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Hospital cleaners who saw themselves as part of the healing team — not just cleaners — had better outcomes.", zh: "將自己視為治癒團隊的一部分——而不只是清潔工——的醫院清潔工有更好的結果。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The perspective shift came from focusing on the impact of their work rather than the task.", zh: "視角轉變來自專注於他們工作的影響而不是任務。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude for the chance to contribute — in any role — reframes even repetitive work.", zh: "對有機會貢獻的感激——在任何角色中——重新框架了即使是重複性的工作。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Not every job is glamorous, but most touch lives in some way.", zh: "不是每份工作都很迷人，但大多數以某種方式觸及生命。", vocab: [{ word: "glamorous", def: "迷人的；令人嚮往的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Finding and naming that connection — 'I make this possible' — is a form of gratitude.", zh: "找到並命名那種連結——「我使這成為可能」——是一種感激形式。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Meaning doesn't always find you. Sometimes you have to find it through gratitude.", zh: "意義不總是會找到你，有時你必須通過感激來找到它。", vocab: [] },
        ],
      },
      {
                title: 'The Grateful Professional',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "I want to commit to expressing more gratitude at work this week.", zh: "我想承諾這週在工作中表達更多的感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "What specifically?", zh: "具體是什麼？", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Thank the colleague who always catches my mistakes before they become problems.", zh: "感謝那位總是在我的錯誤成為問題之前發現它們的同事。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "That's the perfect example — invisible contributions, deeply deserving of recognition.", zh: "那是完美的例子——看不見的貢獻，深深值得被認可。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "And I want to write a message to my manager saying specifically what I appreciate about her leadership.", zh: "我還想寫一封訊息給我的管理者，具體說明我欣賞她的領導力的哪些方面。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Upward gratitude — expressing appreciation to those above you — is underused and deeply impactful.", zh: "向上感激——對你的上級表達感激——被低度使用卻有深刻影響力。", vocab: [{ word: "upward gratitude", def: "向上感激" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Most managers don't get enough appreciation either. They're human too.", zh: "大多數管理者也沒有得到足夠的感激，他們也是人。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Everyone wants to feel their efforts are seen. Gratitude is how we tell them they are.", zh: "每個人都想感覺他們的努力被看見，感激是我們告訴他們已被看見的方式。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "employee engagement", zh: "員工敬業度" },
      { en: "job crafting", zh: "工作重塑" },
      { en: "public recognition", zh: "公開認可" },
      { en: "upward gratitude", zh: "向上感激（對上司的感謝）" },
      { en: "gold standard", zh: "黃金標準；最高標準" },
      { en: "psychological safety", zh: "心理安全" },
      { en: "givers", zh: "給予者" },
      { en: "invisible contributions", zh: "看不見的貢獻" },
      { en: "grateful leadership", zh: "感激型領導力" },
      { en: "hollow thanks", zh: "空洞的感謝" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 6,
    date: '2026-12-12',
    theme: 'Gratitude & Appreciation',
    title: 'Gratitude Across Cultures',
    phase: 'p6',
    parts: [
      {
                title: 'How Gratitude Is Expressed Differently',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude is universal, but how it's expressed varies enormously across cultures.", zh: "感激是普遍的，但它的表達方式在不同文化間差異極大。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "In some cultures, excessive verbal thanks can feel uncomfortable or even insulting.", zh: "在某些文化中，過多的口頭感謝可能感覺不舒服甚至是侮辱性的。", vocab: [{ word: "excessive", def: "過多的；過分的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "In Japan, gift-giving and actions express gratitude better than words often do.", zh: "在日本，送禮和行動通常比言語更能表達感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The elaborate gift-wrapping culture in Japan is itself a form of expressed care and gratitude.", zh: "日本精緻的禮品包裝文化本身就是一種表達關懷和感激的形式。", vocab: [{ word: "elaborate", def: "精緻的；精心製作的" }] },
          { speaker: 'a', speakerName: 'Maya', en: "In some Middle Eastern cultures, hospitality is gratitude — offering the best of what you have.", zh: "在某些中東文化中，款待就是感激——提供你所有的最好的東西。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The meal that's cooked with love and care — that's the thank-you, not words.", zh: "用愛和關懷烹製的一頓飯——那才是感謝，而不是言語。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Learning how to receive gratitude graciously also differs — some cultures deflect, some accept openly.", zh: "學習如何優雅地接受感激也有所不同——有些文化推辭，有些開放地接受。", vocab: [{ word: "deflect", def: "偏轉；推辭" }] },
          { speaker: 'b', speakerName: 'James', en: "Understanding these differences avoids misreading gratitude — or its absence.", zh: "了解這些差異避免了對感激——或其缺失的誤讀。", vocab: [] },
        ],
      },
      {
                title: 'Gratitude in East Asian Cultures',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Confucian cultures place gratitude in a relational, hierarchical context.", zh: "儒家文化將感激放置在關係性、等級性的情境中。", vocab: [{ word: "hierarchical", def: "等級的；有層次的" }] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude toward parents and elders carries enormous moral weight — filial piety.", zh: "對父母和長者的感激承載著巨大的道德重量——孝道。", vocab: [{ word: "filial piety", def: "孝道；孝順" }] },
          { speaker: 'a', speakerName: 'Maya', en: "The concept of grace or debt — gan en — in Chinese cultures is profound.", zh: "中文文化中的恩情或恩惠概念——感恩——是深刻的。", vocab: [{ word: "gan en", def: "感恩（中文）" }] },
          { speaker: 'b', speakerName: 'James', en: "You don't just feel grateful — you carry a responsibility to repay the kindness received.", zh: "你不只是感到感激——你承擔著回報所受恩惠的責任。", vocab: [{ word: "repay", def: "回報；償還" }] },
          { speaker: 'a', speakerName: 'Maya', en: "That's a beautiful framework — gratitude as relational continuity, not just a feeling.", zh: "那是個美好的框架——感激作為關係的延續，而不只是一種感覺。", vocab: [{ word: "relational continuity", def: "關係的延續" }] },
          { speaker: 'b', speakerName: 'James', en: "It binds community together — the debts of kindness create a web of mutual care.", zh: "它將社群連結在一起——恩情之債創造了一個相互關懷的網絡。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "In Taiwan especially, I see this in how strongly people take care of their networks.", zh: "在台灣尤其如此，我在人們如何強力照顧他們的人際關係中看到這一點。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Reciprocity — giving and receiving in an ongoing way — as the foundation of community.", zh: "互惠——持續地給予和接受——作為社群的基礎。", vocab: [{ word: "reciprocity", def: "互惠；相互性" }] },
        ],
      },
      {
                title: 'Gratitude Practices Around the World',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Different cultures have formalized gratitude practices worth learning from.", zh: "不同的文化有值得學習的正式化感激實踐。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The Hawaiian practice of Ho'oponopono — reconciliation through gratitude and forgiveness.", zh: "夏威夷的 Ho'oponopono 實踐——通過感激和寬恕的和解。", vocab: [{ word: "Ho'oponopono", def: "（夏威夷語）一種和解實踐" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Ubuntu in African cultures — I am because we are — gratitude for the community that shapes you.", zh: "非洲文化中的 Ubuntu——我的存在因為我們——對塑造你的社群的感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Indigenous traditions often include gratitude ceremonies for the land and its gifts.", zh: "原住民傳統通常包括對土地及其恩賜的感恩儀式。", vocab: [{ word: "gratitude ceremonies", def: "感恩儀式" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Giving thanks before meals is nearly universal — pausing to acknowledge the source of nourishment.", zh: "飯前感恩幾乎是普世的——暫停以承認滋養的來源。", vocab: [{ word: "nourishment", def: "滋養；營養" }] },
          { speaker: 'b', speakerName: 'James', en: "Those moments of pause carry so much meaning — the food didn't just appear.", zh: "那些停頓的時刻承載著如此多的意義——食物不是憑空出現的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Someone grew it, someone transported it, someone cooked it. Gratitude honors all of that.", zh: "有人種植了它，有人運輸了它，有人烹飪了它，感激尊重了所有這些。", vocab: [{ word: "honors", def: "尊重；致敬" }] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude has always been humanity's way of acknowledging our interdependence.", zh: "感激一直是人類承認我們相互依存的方式。", vocab: [] },
        ],
      },
      {
                title: 'Teaching Children Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "How do different cultures teach children gratitude?", zh: "不同的文化如何教孩子感激？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The forced thank-you — making children say it even when they don't feel it — is debated.", zh: "被迫的感謝——讓孩子說它即使他們沒有感覺——是有爭議的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Modeling is more powerful — children learn gratitude by watching grateful adults.", zh: "示範更有力量——孩子通過觀察感恩的成年人來學習感激。", vocab: [{ word: "modeling", def: "示範；以身作則" }] },
          { speaker: 'b', speakerName: 'James', en: "When parents genuinely express thanks — to each other, to service workers, to the world — kids absorb that.", zh: "當父母真誠地表達感謝——對彼此、對服務工作者、對世界——孩子吸收了那些。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude journals for children — what went well today? — build the habit early.", zh: "孩子的感恩日記——今天什麼事情進行順利？——早期建立這個習慣。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Framing stories — hearing about what others lack — builds perspective and appreciation.", zh: "框架故事——聽到他人缺乏什麼——建立視角和感激。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Not in a guilt-inducing way — but in a genuinely consciousness-expanding way.", zh: "不是以引發罪惡感的方式——而是以真正擴展意識的方式。", vocab: [{ word: "consciousness-expanding", def: "擴展意識的；啟蒙的" }] },
          { speaker: 'b', speakerName: 'James', en: "A child who grows up with gratitude becomes an adult who sees abundance rather than scarcity.", zh: "帶著感激成長的孩子成為一個看見豐盛而非匱乏的成年人。", vocab: [] },
        ],
      },
      {
                title: 'A Global Gratitude',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "I find it beautiful that gratitude is so universal yet so particular to each culture.", zh: "我覺得感激如此普世卻又如此特屬於每種文化，這很美麗。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "It speaks to something fundamental about human nature — we all need to acknowledge the good.", zh: "它說明了人性中某種根本的東西——我們都需要承認美好的事物。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "And we all have our unique ways of expressing it — which are themselves worth appreciating.", zh: "我們都有表達它的獨特方式——這些方式本身也值得欣賞。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Learning to give and receive gratitude cross-culturally is a beautiful act of understanding.", zh: "學習跨文化地給予和接受感激是一種美麗的理解行為。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Wherever you are, whatever form it takes — expressing gratitude makes the world more human.", zh: "無論你在哪裡，無論採取什麼形式——表達感激使世界更人性化。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And receiving it graciously — really taking in appreciation — is equally important.", zh: "優雅地接受它——真正吸收感激——同樣重要。", vocab: [{ word: "graciously", def: "優雅地；大方地" }] },
          { speaker: 'a', speakerName: 'Maya', en: "We often deflect compliments. Learning to say 'thank you' and mean it — that's a practice too.", zh: "我們常常偏轉讚美，學習說「謝謝」並真心意味著它——那也是一種實踐。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Receiving well honors the giver. It completes the circle of appreciation.", zh: "好好接受尊重了給予者，它完成了感激的循環。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "filial piety", zh: "孝道；孝順" },
      { en: "reciprocity", zh: "互惠；相互性" },
      { en: "Ho'oponopono", zh: "（夏威夷語）一種和解實踐" },
      { en: "relational continuity", zh: "關係的延續" },
      { en: "gratitude ceremonies", zh: "感恩儀式" },
      { en: "modeling", zh: "示範；以身作則" },
      { en: "deflect compliments", zh: "偏轉讚美；謙虛地推辭" },
      { en: "interdependence", zh: "相互依存" },
      { en: "excessive thanks", zh: "過多的感謝" },
      { en: "honoring", zh: "尊重；致敬" },
    ],
  },
  {
    weekNumber: 50,
    dayOfWeek: 7,
    date: '2026-12-13',
    theme: 'Gratitude & Appreciation',
    title: 'A Week of Thankfulness',
    phase: 'p6',
    parts: [
      {
                title: 'Week in Review',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Gratitude and appreciation — I feel genuinely lighter after this week.", zh: "感激和欣賞——這週之後我真的感覺輕鬆多了。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Focusing on what's good rather than what's missing — it's a discipline, but a rewarding one.", zh: "專注於美好的事物而不是缺少的東西——這是一種訓練，但是有回報的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "What was your biggest takeaway from this week?", zh: "這週你最大的收穫是什麼？", vocab: [{ word: "takeaway", def: "收穫；要點" }] },
          { speaker: 'b', speakerName: 'James', en: "That specific gratitude lands so much deeper than general gratitude.", zh: "具體的感激比一般感激要深入得多。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "For me — appreciating the ordinary. I've been more present this week.", zh: "對我來說——感激平凡，這週我更在當下了。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And I wrote that gratitude letter. I finally sent it.", zh: "我寫了那封感謝信，我終於寄出去了。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "You did?! What happened?", zh: "你做到了？！發生了什麼？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "She wrote back crying. Said it was the nicest thing anyone had ever written to her.", zh: "她哭著回覆了，說那是有人寫給她最美好的事情。", vocab: [] },
        ],
      },
      {
                title: 'The Gratitude We Gave',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Tell me more. When did you send it?", zh: "告訴我更多，你什麼時候寄出去的？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Wednesday. I spent about twenty minutes writing it — three paragraphs, very specific.", zh: "週三，我花了大約二十分鐘寫它——三段，非常具體。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "What made it hard to write?", zh: "是什麼讓它難以寫？", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Vulnerability. Saying these things felt very exposed — like showing too much of yourself.", zh: "脆弱，說這些事情感覺很暴露——就像展示了太多的自己。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "But you did it anyway.", zh: "但你還是做了。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "I thought about what we discussed — saying it now, not waiting for the perfect moment.", zh: "我想到了我們討論的——現在說，而不是等待完美的時機。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "That's the whole thing. The discomfort of expressing appreciation is nothing compared to the regret of silence.", zh: "那就是全部，表達感激的不適與沉默的後悔相比根本算不上什麼。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Now I want to write more of them. I have a list forming.", zh: "現在我想寫更多，我在整理一份清單。", vocab: [] },
        ],
      },
      {
                title: 'Gratitude as a Way of Life',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "I've been thinking this week that gratitude isn't a practice — it's a whole orientation.", zh: "這週我一直在想，感激不是一種實踐——它是一種整體的定向方式。", vocab: [{ word: "orientation", def: "定向；方向" }] },
          { speaker: 'b', speakerName: 'James', en: "A way of moving through the world. Noticing, appreciating, expressing, receiving.", zh: "一種在世界中前行的方式，注意、感激、表達、接受。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "It doesn't require anything extraordinary — just an ongoing quality of attention.", zh: "它不需要任何非凡的事物——只是一種持續的注意力質量。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The grateful person and the ungrateful person can have the same life — and experience it totally differently.", zh: "感恩的人和不感恩的人可以擁有相同的生活——卻完全不同地體驗它。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "That's profound. The contents of life matter, but our relationship to them might matter more.", zh: "那很深刻，生命的內容很重要，但我們與它們的關係可能更重要。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude is free. It costs nothing but attention and willingness.", zh: "感激是免費的，除了注意力和意願之外什麼都不需要。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "And yet we spend so little time practicing it — while spending a lot of time complaining.", zh: "然而我們花這麼少的時間練習它——同時花很多時間抱怨。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "The ratio can change. We can choose where to put our attention.", zh: "比例可以改變，我們可以選擇把注意力放在哪裡。", vocab: [] },
        ],
      },
      {
                title: 'Carrying It Forward',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "Next week is about goals and intentions — a great follow-up to gratitude.", zh: "下週是關於目標和意圖——感激的絕佳後續。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Because goals set from a place of gratitude are different from goals set from a place of lack.", zh: "因為從感激的地方設定的目標與從匱乏的地方設定的目標是不同的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "When you appreciate what you have, you're adding to abundance rather than trying to fill a hole.", zh: "當你感激你所有的時，你在增加豐盛，而不是試圖填補空洞。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "Gratitude grounds your ambition — makes it driven by love rather than fear or insecurity.", zh: "感激使你的雄心有根基——使它由愛而不是恐懼或不安全感驅動。", vocab: [{ word: "insecurity", def: "不安全感" }] },
          { speaker: 'a', speakerName: 'Maya', en: "Working toward something while appreciating where you are now — that's healthy striving.", zh: "在感激你現在所在的地方的同時努力追求某些東西——那是健康的追求。", vocab: [{ word: "striving", def: "努力追求；奮鬥" }] },
          { speaker: 'b', speakerName: 'James', en: "I want to carry this week's gratitude practice into the final weeks of the year.", zh: "我想把這週的感恩實踐帶入年末最後幾週。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "End the year with fullness — looking back at what was good, not what was missing.", zh: "以充實結束這年——回顧什麼是美好的，而不是缺少的。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "December is the perfect time for that. The year is coming full circle.", zh: "十二月是最完美的時機，這年正在完整地畫一個圓。", vocab: [{ word: "coming full circle", def: "畫完一個圓；回到起點" }] },
        ],
      },
      {
                title: 'Thank You',
        lines: [
          { speaker: 'a', speakerName: 'Maya', en: "I also want to take a moment to express real gratitude for this learning journey.", zh: "我也想花一點時間對這段學習旅程表達真正的感激。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "To everyone listening — you've committed to something challenging and worthwhile.", zh: "致每一位在聽的人——你承諾了一件有挑戰性且值得的事情。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Learning a language is a long game. Every episode, every minute is building toward something real.", zh: "學習語言是長期的，每一集、每一分鐘都在建造真實的東西。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "You are growing — even on the days it doesn't feel like it. Trust the process.", zh: "你在成長——即使在感覺不像的日子裡，相信這個過程。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "Thank you for being curious. For showing up. For caring about your own growth.", zh: "謝謝你保持好奇心，謝謝你出現，謝謝你關心自己的成長。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "And we're grateful to be part of your journey — these conversations mean something.", zh: "我們很感激能成為你旅程的一部分——這些對話是有意義的。", vocab: [] },
          { speaker: 'a', speakerName: 'Maya', en: "See you next week — for goals, intentions, and looking forward with hope.", zh: "下週見——關於目標、意圖，以及帶著希望向前看。", vocab: [] },
          { speaker: 'b', speakerName: 'James', en: "With gratitude for the week we've had, and excitement for what's ahead.", zh: "帶著對這週的感激，以及對前方的期待。", vocab: [] },
        ],
      },
    ],
    keyPhrases: [
      { en: "coming full circle", zh: "畫完一個圓；回到起點" },
      { en: "healthy striving", zh: "健康的追求；有根基的奮鬥" },
      { en: "gratitude as orientation", zh: "感激作為一種定向方式" },
      { en: "abundance mindset", zh: "豐盛心態" },
      { en: "insecurity", zh: "不安全感" },
      { en: "takeaway", zh: "收穫；要點" },
      { en: "orientation", zh: "定向；方向" },
      { en: "vulnerability", zh: "脆弱；暴露感" },
      { en: "present", zh: "活在當下" },
      { en: "long game", zh: "長期戰略；長期努力" },
    ],
  },
];
