import { Episode } from '../../app/src/data/episode-sample'

export const WEEK_41: Episode[] = [
  {
    weekNumber: 41,
    dayOfWeek: 1,
    date: '2026-10-05',
    theme: 'Values & Beliefs',
    title: 'What We Stand For: Values, Principles, and Beliefs',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Values Quietly Organize a Life',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think values are often invisible until something forces you to choose between them.', zh: '我覺得價值觀常常在平常時看不見，直到某件事逼你在它們之間做選擇時，它才突然浮出來。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. People may not name their values clearly, but those values still shape how they spend time, money, energy, and loyalty.', zh: '對。很多人未必說得出自己的價值觀，但那些價值觀還是會默默決定他把時間、金錢、精力和忠誠放在哪裡。', vocab: [{ word: 'invisible until tested', def: '平常不明顯，但一到選擇時就會突然變清楚' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is why a person can feel deeply uncomfortable even when an option looks successful from the outside.', zh: '這也是為什麼，一個選項明明外表看起來很成功，某個人卻還是會感到很不舒服。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. External success does not calm internal conflict when a decision violates something central.', zh: '沒錯。如果一個決定碰撞到很核心的東西，外在成功並不會平息內在衝突。', vocab: [{ word: 'internal conflict', def: '心裡同時被不同方向拉扯，無法真正安穩的狀態' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So values are not abstract decoration. They are part of what makes a life feel coherent or fractured.', zh: '所以價值觀不是抽象裝飾，它其實會決定一個人的人生感覺起來是整體的，還是破碎的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'And maybe that is why clarifying them matters more than people think.', zh: '而這也許就是為什麼，釐清價值觀這件事比很多人想像得更重要。' },
        ],
      },
      {
        title: 'Part 2 — Principles and Beliefs Are Lived, Not Only Named',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I also think many people confuse stated values with lived values.', zh: '我也覺得，很多人會把「嘴上說的價值」和「真正活出來的價值」搞混。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. It is easy to say you value honesty, kindness, freedom, or family, but daily patterns reveal what is actually being prioritized.', zh: '對。說自己重視誠實、善良、自由或家人都不難，但日常模式才會揭露：到底什麼真的被排在前面。', vocab: [{ word: 'lived values', def: '不是口頭認同，而是實際在生活中反覆做出來的價值' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That can be humbling, because behavior is often a more accurate mirror than self-description.', zh: '這有時會很讓人謙卑，因為行為常常比自我描述更像一面鏡子。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And that mirror is not always there to shame us. It can also help us become more honest.', zh: '而那面鏡子也不一定是在羞辱人，它其實也可能是在幫人變得更誠實。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Noticing the gap between belief and action is often the beginning of real growth.', zh: '沒錯。看見信念和行動之間的距離，很多時候正是成長真正開始的地方。', vocab: [{ word: 'more accurate mirror', def: '比自己想像得更誠實地反映出真實狀態的東西' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So values work is not only about defining ideals. It is also about narrowing the distance between ideals and habits.', zh: '所以價值觀的工作，不只是定義理想，也包括縮短理想和習慣之間的距離。' },
        ],
      },
      {
        title: 'Part 3 — Values Become Visible Under Pressure',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think people learn what they really value when pressure enters the room.', zh: '我覺得一個人真正重視什麼，往往是壓力進場之後才會看得最清楚。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Easy circumstances do not test much. Pressure reveals what people protect, what they sacrifice, and what they justify.', zh: '對。太輕鬆的情境測不出什麼，壓力才會揭露：一個人保護什麼、犧牲什麼，又會合理化什麼。', vocab: [{ word: 'under pressure', def: '在成本變高、情緒變緊、情況變難的時候' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is why integrity is rarely dramatic at first. It often looks like a quiet refusal to betray something important.', zh: '這也是為什麼，誠信一開始很少看起來很戲劇化，它常常只是安靜地拒絕背叛某個重要的東西。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. It may cost opportunity, approval, ease, or money, but it preserves self-respect.', zh: '沒錯。它可能會花掉機會、認同、輕鬆感，甚至金錢，但它保住了自尊。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And self-respect may be one of the hidden rewards of living by principle.', zh: '而自尊，也許就是按原則生活最隱藏但最重要的回報之一。', vocab: [{ word: 'self-respect', def: '知道自己沒有背叛內在標準所帶來的安穩感' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Because shortcuts can look efficient in the moment, but they often leave a longer echo afterward.', zh: '因為捷徑在當下看起來很有效率，但它們常常會在後面留下更長的回音。' },
        ],
      },
      {
        title: 'Part 4 — We Need More Than Slogans',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'What worries me is that people sometimes use values language in a shallow way, almost like branding.', zh: '我會擔心的一點是，現在有些人用價值觀語言的方式很淺，幾乎像在做品牌包裝。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. Words like authenticity, courage, justice, or compassion can sound powerful while remaining completely unexamined.', zh: '對。像 authentic、勇氣、公義或同理這些字，聽起來都很有力量，但其實也可能完全沒有被深究。', vocab: [{ word: 'branding', def: '把某種說法包裝成好聽形象，而不一定真的有內容' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That is why values need context, cost, and practice. Otherwise they stay as slogans.', zh: '這也是為什麼，價值觀一定要放回脈絡、成本和實踐裡，不然它就只會停留在口號。' },
          { speaker: 'a', speakerName: 'Jade', en: 'A belief becomes real when it changes what you are willing to do or not do.', zh: '一個信念真正變真，是當它開始改變你願意做什麼，以及你不願意做什麼。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. If nothing concrete changes, then the belief may be ornamental more than operational.', zh: '沒錯。如果沒有任何具體改變，那個信念可能比較像裝飾，而不是實際運作的原則。', vocab: [{ word: 'ornamental', def: '好看、好聽，但對真實生活沒有真正影響' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So the question is not only What do I believe? but also What does this belief do inside my life?', zh: '所以問題不只是「我相信什麼」，也包括「這個信念在我的生活裡到底有做什麼？」' },
        ],
      },
      {
        title: 'Part 5 — A Life Has a Moral Shape',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Maybe every life develops a moral shape over time, whether a person thinks consciously about it or not.', zh: '也許每個人的人生，久了都會長出某種道德形狀，不管他有沒有很有意識地去想。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think that is true. Repeated choices carve character, and character eventually becomes destiny in slow motion.', zh: '我覺得那是真的。反覆的選擇會刻出性格，而性格最後常常就會變成慢動作發生的命運。', vocab: [{ word: 'moral shape', def: '一個人長期活出來的價值方向和品格輪廓' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That sounds serious, but it is also hopeful, because it means values can be practiced into reality.', zh: '這聽起來很嚴肅，但也很有希望，因為它表示：價值觀是可以被練到現實裡的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. A person does not need perfect certainty to start living more truthfully.', zh: '沒錯。一個人不需要先有完美確定感，才開始活得更真。' },
          { speaker: 'a', speakerName: 'Jade', en: 'They may only need the courage to ask what they stand for, and then keep answering through action.', zh: '他需要的，也許只是問自己到底站在什麼上面，然後用行動不斷回答那個問題。', vocab: [{ word: 'stand for', def: '一個人真正願意捍衛、堅持、代表的是什麼' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And that may be the beginning of a more integrated life.', zh: '而那也許就是一種更整合人生的開始。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'lived values', zh: '活出來的價值觀', example: 'Lived values matter more than stated values.' },
      { en: 'under pressure', zh: '在壓力下', example: 'Values become visible under pressure.' },
      { en: 'self-respect', zh: '自尊', example: 'Integrity often preserves self-respect.' },
      { en: 'ornamental', zh: '裝飾性的', example: 'Some beliefs are ornamental until they shape behavior.' },
      { en: 'moral shape', zh: '道德形狀', example: 'A life slowly develops a moral shape.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 2,
    date: '2026-10-06',
    theme: 'Values & Beliefs',
    title: 'Where Our Values Come From',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — We Absorb Values Early',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think many of our values are absorbed long before we are capable of consciously choosing them.', zh: '我覺得很多價值觀，都是在我們還沒能力有意識選擇之前，就先被吸收進來了。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Family, religion, school, class background, culture, and community all leave a deep imprint.', zh: '對。家庭、宗教、學校、階級背景、文化和社群，都會留下很深的印記。', vocab: [{ word: 'absorbed early', def: '在很早期就默默進入一個人的內在，而不是後來理性選來的' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That can be helpful, of course. Children need some framework before they can evaluate it.', zh: '這當然也有幫助。孩子在還不會判斷之前，本來就需要某種框架。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. The problem is not having inherited values. The problem is never examining them.', zh: '沒錯。問題不是你有繼承來的價值，而是你一輩子都沒看過它們。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That is such an important distinction, because no one starts from a blank slate.', zh: '這個區分真的很重要，因為沒有人是一張白紙開始的。', vocab: [{ word: 'imprint', def: '某種影響深深留在一個人身上的痕跡' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And realizing that can make people less naive about why they react the way they do.', zh: '而一旦意識到這點，人也比較不會對自己那些反應感到天真或毫無理解。' },
        ],
      },
      {
        title: 'Part 2 — Family Teaches More Than It Says',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'Families often teach values not only through what they say, but through what they reward, fear, avoid, and repeat.', zh: '家庭教價值觀，很多時候不只是靠嘴巴說，而是靠它獎勵什麼、害怕什麼、逃避什麼，以及重複什麼。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. A family may say kindness matters, but if achievement is what always gets attention, a child learns something more complicated.', zh: '對。一個家庭可能嘴上說善良重要，但如果真正一直被注意、被獎勵的是成就，那孩子學到的東西就會更複雜。', vocab: [{ word: 'what gets attention', def: '一個系統真正看重、會回應與獎勵的東西' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Children are excellent observers of emotional reality, even when they cannot explain it.', zh: '孩子對情緒現實的觀察其實非常敏銳，就算他說不清楚。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So some values are taught explicitly, while others are simply soaked up from atmosphere.', zh: '所以有些價值觀是被明講的，但另一些其實只是從氛圍裡被泡進去的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'That is why adult reflection can feel surprising. You begin to notice values you were never formally taught but still deeply carry.', zh: '這也是為什麼成人反思有時會很讓人驚訝，因為你會開始注意到：有些價值觀從來沒人正式教你，但你卻一直深深帶著。', vocab: [{ word: 'soaked up', def: '不是刻意學，而是在環境裡慢慢吸收進來' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And noticing them can be the beginning of real freedom.', zh: '而看見那些東西，本身就可能是真正自由的開始。' },
        ],
      },
      {
        title: 'Part 3 — Culture Shapes What Feels Normal',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Culture also shapes values by telling people what is normal, admirable, shameful, or expected.', zh: '文化也會透過告訴人什麼是正常、值得欽佩、可恥或被期待的，來塑造價值觀。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Some cultures emphasize duty, others emphasize self-expression, others emphasize achievement, harmony, or independence.', zh: '對。有些文化強調責任，有些強調自我表達，也有些強調成就、和諧，或獨立。', vocab: [{ word: 'what feels normal', def: '一個社會讓你覺得理所當然、不太會質疑的那套標準' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is why two people can be equally sincere and still prioritize very different things.', zh: '這也是為什麼，兩個都很真誠的人，仍然可能把完全不同的東西擺在前面。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Values are not formed in a vacuum. They grow inside social worlds.', zh: '沒錯。價值觀不是在真空裡形成的，它們是在社會世界裡長出來的。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And that should make people both more reflective about themselves and less simplistic about others.', zh: '而這一點也應該讓人對自己更願意反思，對別人也少一點過度簡化。', vocab: [{ word: 'vacuum', def: '完全不受外界影響、孤立存在的狀態' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Because what feels obvious to you may partly be the result of where you were formed.', zh: '因為你覺得很理所當然的東西，很大一部分也許只是你被塑造成這樣。' },
        ],
      },
      {
        title: 'Part 4 — Reflection Helps Separate Inheritance from Choice',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think a big part of adulthood is learning how to separate inheritance from genuine conviction.', zh: '我覺得成年的一個大任務，就是學會怎麼把「繼承來的」和「自己真正相信的」分開。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. Not to reject everything from the past, but to ask what still feels true after honest examination.', zh: '對。不是把過去所有東西都推翻，而是問：在誠實檢查之後，哪些東西現在對我仍然是真的？', vocab: [{ word: 'inheritance from choice', def: '分辨哪些是承襲來的，哪些是自己後來真的選擇的' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That process can be painful, because it may involve disappointing people, questioning authority, or seeing your own contradictions.', zh: '那個過程可能很痛，因為它常常會牽涉到讓別人失望、質疑權威，或看見自己的矛盾。' },
          { speaker: 'a', speakerName: 'Jade', en: 'But without that work, people may spend years living out values that are not really theirs.', zh: '但如果沒有做那個工，一個人很可能會花很多年活在其實不屬於自己的價值系統裡。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Reflection is not rebellion for its own sake. It is a search for ownership.', zh: '沒錯。反思不是為了反叛而反叛，而是在尋找一種真正屬於自己的 ownership。', vocab: [{ word: 'ownership', def: '不是被動繼承，而是真正認領這些價值是自己的' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And ownership may be what transforms values from inheritance into conviction.', zh: '而那種認領感，也許就是把繼承變成信念的關鍵。' },
        ],
      },
      {
        title: 'Part 5 — We Can Become More Deliberate',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'What I find hopeful is that values may begin passively, but they do not have to stay that way.', zh: '我覺得很有希望的一點是：價值觀也許一開始是被動形成的，但它們不必永遠停在那裡。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I agree. People can become more deliberate about what they keep, what they question, and what they choose to grow into.', zh: '我同意。人可以越來越有意識地決定：哪些要留下、哪些要質疑，以及自己想長成什麼價值方向。', vocab: [{ word: 'deliberate', def: '不是隨波逐流，而是帶著選擇與思考去形成自己' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That does not erase where you came from, but it does change how where you came from lives inside you.', zh: '那不會抹掉你的來處，但會改變你的來處是怎麼活在你裡面的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. The past may shape you, but it does not have to decide everything forever.', zh: '沒錯。過去會塑造你，但它不必永遠決定一切。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And maybe that is what it means to become more thoughtful about values: not pretending you invented yourself, but taking responsibility for who you are becoming.', zh: '而也許這就是對價值觀變得更有思考的意思：不是假裝自己完全發明了自己，而是願意對自己正在變成誰負責。', vocab: [{ word: 'taking responsibility', def: '不再只是接受，而是主動承擔自己要成為什麼樣的人' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That is a demanding task, but also a deeply human one.', zh: '那是一個很不容易的任務，但也非常有人味。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'absorbed early', zh: '很早就吸收進來', example: 'Many values are absorbed early in life.' },
      { en: 'what gets attention', zh: '真正被注意的東西', example: 'Children learn from what gets attention.' },
      { en: 'what feels normal', zh: '覺得很正常的東西', example: 'Culture shapes what feels normal.' },
      { en: 'ownership', zh: '真正認領感', example: 'Reflection creates ownership of your values.' },
      { en: 'deliberate', zh: '有意識的', example: 'Adults can become more deliberate about values.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 3,
    date: '2026-10-07',
    theme: 'Values & Beliefs',
    title: 'When Beliefs Start to Change',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Changing Beliefs Can Feel Disloyal',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think changing a belief can feel more emotional than people expect.', zh: '我覺得改變一個信念，常常會比人想像得更情緒化。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Beliefs are often tied to identity, community, family loyalty, and a sense of who we have been.', zh: '對。信念常常和身份感、群體歸屬、家庭忠誠，還有「我一直是怎樣的人」這種感覺綁在一起。', vocab: [{ word: 'beliefs start to change', def: '原本相信的東西開始動搖、鬆開或重新形成' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That means changing your mind is not always a simple intellectual update.', zh: '這也表示，改變想法不一定只是理智上的更新而已。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. It can feel like betrayal, even when the change is sincere and honest.', zh: '沒錯。它甚至可能讓人覺得像背叛，即使那個改變其實很真、很誠實。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Especially if the old belief connected you to people you love or to a world that once felt certain.', zh: '尤其當那個舊信念曾經把你連到你愛的人，或連到某個曾讓你覺得很確定的世界。', vocab: [{ word: 'betrayal', def: '好像自己正在背叛某個曾經承載你的人或系統的感覺' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'So belief change often carries grief as well as freedom.', zh: '所以信念改變裡，常常同時帶著悲傷和自由。' },
        ],
      },
      {
        title: 'Part 2 — Doubt Is Not Always Weakness',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I wish doubt were seen less as weakness and more as a serious part of thinking.', zh: '我很希望大家不要再那麼把懷疑看成軟弱，而是把它看成思考裡很重要的一部分。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. Doubt can be destructive, but it can also be a sign that someone is refusing to live by slogans.', zh: '對。懷疑當然可能有破壞性，但它也可能表示：一個人不願意再只靠口號活著。', vocab: [{ word: 'doubt', def: '原本確定的東西開始出現問題感與不確定' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. If a belief cannot survive sincere questioning, then maybe it was more fragile than people wanted to admit.', zh: '沒錯。如果一個信念撐不過真誠提問，那它也許比大家願意承認的還脆弱。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That does not mean every old belief should be abandoned, only that honest beliefs should be able to meet scrutiny.', zh: '這不是說每個舊信念都該丟掉，而是說：誠實的信念，應該有能力面對檢視。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'And sometimes scrutiny deepens a belief instead of destroying it.', zh: '而且有時檢視不會摧毀信念，反而會讓信念更深。', vocab: [{ word: 'scrutiny', def: '不只是懷疑，而是認真、仔細地檢查一個觀念' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So doubt may be part of the path toward stronger conviction, not only away from it.', zh: '所以懷疑也可能是通往更深信念的路，而不只是離開信念的路。' },
        ],
      },
      {
        title: 'Part 3 — New Experience Can Rearrange Old Assumptions',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'A lot of beliefs begin changing when life gives people experiences their old assumptions cannot easily explain.', zh: '很多信念開始改變，是因為人生給了一些經驗，而舊假設已經很難把那些經驗解釋進去。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Meeting different people, suffering, traveling, falling in love, losing certainty, or seeing injustice directly can all rearrange the inside of someone.', zh: '對。遇見不同的人、受苦、旅行、愛上一個人、失去確定感，或親眼看見不公，都可能重排一個人的內在。', vocab: [{ word: 'old assumptions', def: '以前理所當然相信、幾乎不太懷疑的基本想法' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is why belief change is often more embodied than academic.', zh: '這也是為什麼，信念改變很多時候比起學術上的轉變，更像是整個人被重新移動。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. It is not only that new arguments appear. It is that reality itself starts pressing against old categories.', zh: '沒錯。不只是有新的論點出現，而是現實本身開始擠壓舊的分類方式。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And when reality keeps doing that, people eventually have to decide whether they will adjust the belief or deny the experience.', zh: '而當現實一直這樣推，你最後就得決定：是要調整信念，還是要否認經驗。', vocab: [{ word: 'reality presses back', def: '現實不斷給出你原本那套說法裝不下的事實與經驗' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That may be one of the deepest crossroads in adult life.', zh: '而那也許就是成年人生裡最深的一種岔路之一。' },
        ],
      },
      {
        title: 'Part 4 — Belief Change Can Be Lonely',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'One of the hardest parts is that changing beliefs can be lonely.', zh: '最難的一部分之一，是信念改變的路通常很孤單。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. If your beliefs are shared by your family or community, changing them can feel like stepping outside the circle.', zh: '對。如果你的信念本來和家庭或群體綁在一起，那改變它就會像是走出圈子。', vocab: [{ word: 'outside the circle', def: '不再完全屬於原本那個熟悉的群體與秩序' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And even if nobody rejects you directly, the fear of disappointing people can be intense.', zh: '而且就算沒有人直接排斥你，那種「會不會讓人失望」的害怕也可能很強。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That is why people sometimes stay silent for a long time while the inside is already shifting.', zh: '這也是為什麼，有些人會沉默很久，雖然他的裡面其實早就在移動了。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Belief transitions are often lived privately long before they are spoken publicly.', zh: '沒錯。信念過渡很多時候都先在私底下活很久，之後才會被公開說出來。', vocab: [{ word: 'spoken publicly', def: '不是只在心裡想，而是真正對外承認與表達' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And that privacy deserves compassion, not suspicion.', zh: '而那種私底下的掙扎，值得的是同理，不是懷疑。' },
        ],
      },
      {
        title: 'Part 5 — Change Can Lead to More Honest Conviction',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'What gives me hope is that belief change does not always lead to emptiness. Sometimes it leads to greater honesty.', zh: '讓我有希望的一點是，信念改變不一定會通往空洞，有時它反而會通往更大的誠實。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think so too. A belief that survives questioning often becomes humbler, deeper, and less performative.', zh: '我也這樣覺得。一個撐過提問的信念，往往會變得更謙卑、更深，也比較不表演。', vocab: [{ word: 'greater honesty', def: '不再只是照著既有說法，而是真正面對自己所相信的' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And a belief that changes may also become more compassionate, because it knows what uncertainty feels like.', zh: '而一個改變過的信念，也可能會變得更有同理，因為它知道不確定長什麼樣。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. People who have wrestled honestly with belief often speak differently from those who only inherited certainty.', zh: '沒錯。那些真正和信念誠實搏鬥過的人，說話方式往往和只繼承確定感的人不太一樣。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So maybe belief change is not always the loss of truth. Sometimes it is the stripping away of borrowed certainty.', zh: '所以也許信念改變不一定是失去真理，有時反而是在剝掉那些借來的確定感。', vocab: [{ word: 'borrowed certainty', def: '不是自己真正走出來的，而是從別人那裡直接接收的確定感' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And what remains after that may be more fragile, but also more real.', zh: '而留下來的東西也許比較脆，但也更真。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'doubt', zh: '懷疑', example: 'Doubt can be part of honest thinking.' },
      { en: 'scrutiny', zh: '檢視', example: 'Deep beliefs should be able to face scrutiny.' },
      { en: 'old assumptions', zh: '舊假設', example: 'New experience can challenge old assumptions.' },
      { en: 'outside the circle', zh: '走出圈子', example: 'Changing beliefs can feel like standing outside the circle.' },
      { en: 'borrowed certainty', zh: '借來的確定感', example: 'People sometimes live on borrowed certainty.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 4,
    date: '2026-10-08',
    theme: 'Values & Beliefs',
    title: 'Living According to What You Believe',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Belief Becomes Real in Action',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think belief becomes most real when it starts shaping behavior instead of remaining only an idea.', zh: '我覺得信念真正變得真，是它開始影響行為，而不再只是停留在想法裡。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. A belief may sound noble in conversation, but its depth is revealed by what it costs in practice.', zh: '對。一個信念在對話裡聽起來可以很高尚，但它有多深，通常是被它在現實中要花多少成本揭露出來的。', vocab: [{ word: 'in practice', def: '不是在理論裡，而是在真實生活中實際發生時' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is where convenience starts to compete with conviction.', zh: '而也就是在那裡，方便開始和信念互相競爭。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. It is easy to value honesty until honesty threatens comfort, reputation, or advantage.', zh: '沒錯。誠實在不影響舒服、名聲或利益之前，總是很容易被說自己很重視。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So living by belief is not mostly about self-expression. It is often about sacrifice and consistency.', zh: '所以按信念而活，不太只是自我表達，它更多時候其實和犧牲與一致性有關。', vocab: [{ word: 'conviction', def: '不是口號式相信，而是深到足以改變行動的信念' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And consistency may be more powerful than intensity in the long run.', zh: '而且長期來看，一致性常常比強烈感更有力量。' },
        ],
      },
      {
        title: 'Part 2 — Small Actions Carry Moral Weight',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think people sometimes overlook how much moral weight exists in ordinary actions.', zh: '我覺得很多人會忽略：普通行動裡其實也有很大的道德重量。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. How you speak to service workers, how you keep promises, how you use power, and how you respond when nobody is impressed all matter.', zh: '對。你怎麼對服務人員說話、怎麼守承諾、怎麼使用權力，還有在沒人會稱讚你時你怎麼回應，這些都很重要。', vocab: [{ word: 'ordinary actions', def: '看起來平凡，但其實會揭露品格的日常行為' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Those things do not usually appear in mission statements, but they reveal character much more clearly.', zh: '那些東西通常不會出現在任何漂亮宣言裡，但它們往往更清楚地揭露一個人的品格。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That is humbling because it means values are not tested only in dramatic moral crises.', zh: '這很讓人謙卑，因為它代表價值觀不是只有在戲劇性的道德危機裡才會被考驗。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Most of the time they are tested in traffic, in deadlines, in fatigue, and in conversations no one will remember.', zh: '沒錯。大多數時候，它們是在塞車裡、在期限裡、在疲憊裡，還有那些沒人會記得的對話裡被考驗。', vocab: [{ word: 'moral weight', def: '一個小行動其實也帶著真正的道德意義和分量' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And maybe that is what makes daily life morally serious, even when it looks ordinary.', zh: '而也許這就是為什麼，日常生活看起來普通，卻仍然有很嚴肅的道德性。' },
        ],
      },
      {
        title: 'Part 3 — Alignment Requires Repetition',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think people imagine alignment as a feeling, but it may be more like a practice.', zh: '我覺得很多人把一致感想成某種感覺，但它其實更像一種練習。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. A life aligned with belief is usually built by repetition, not by one grand declaration.', zh: '對。和信念一致的人生，通常是靠反覆建立的，不是靠一次盛大宣告。', vocab: [{ word: 'alignment', def: '選擇、行動和內在價值比較對得上的狀態' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That means people should expect some effort, because habits often lag behind conviction.', zh: '這也表示，人應該預期會有一些辛苦，因為習慣常常會落後於信念。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. You may believe something sincerely before you fully know how to live it well.', zh: '沒錯。你可能先真心相信某件事，但還不知道要怎麼把它活得很好。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That gap should not lead to cynicism. It should lead to practice.', zh: '而那個落差不該把人帶向犬儒，反而該把人帶向練習。', vocab: [{ word: 'lag behind', def: '雖然信念已經改變了，但習慣和行為還沒有跟上' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Because a value becomes stronger when it is rehearsed in real life again and again.', zh: '因為一個價值觀，就是在現實裡一再被排練之後，才會真正變強。' },
        ],
      },
      {
        title: 'Part 4 — Hypocrisy, Failure, and Repair',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'Of course, living by belief does not mean doing it perfectly.', zh: '當然，按信念而活也不代表會做得完美。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. People fail their values all the time, and that does not automatically make the values fake.', zh: '對。人常常會辜負自己的價值觀，但那不會自動讓那些價值觀變假。', vocab: [{ word: 'fail your values', def: '明明相信某件事，卻沒有照那樣去做' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'The important question is what happens next. Do you justify, ignore, or repair?', zh: '真正重要的問題是接下來怎麼辦。你是合理化、忽略，還是修補？' },
          { speaker: 'a', speakerName: 'Jade', en: 'Repair seems like a crucial moral skill that people do not talk about enough.', zh: '我覺得修補這件事，是一個大家談得不夠多、但非常關鍵的道德能力。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Integrity is not only never failing. It is also returning honestly after failure.', zh: '沒錯。誠信不只是永遠不犯錯，它也包括在犯錯後誠實地回來。', vocab: [{ word: 'repair', def: '承認失誤後，盡量補回來並重新對齊自己的價值' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That makes moral life feel more demanding, but also more compassionate.', zh: '這讓道德生活聽起來更嚴格，但也更有同理。' },
        ],
      },
      {
        title: 'Part 5 — Belief Should Change the Shape of a Life',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Maybe the best test of belief is whether it changes the shape of a life over time.', zh: '也許信念最好的測試，就是它會不會隨著時間改變一個人生的形狀。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think so. A genuine belief should influence priorities, boundaries, responses, and the kind of person someone is slowly becoming.', zh: '我也這樣覺得。真正的信念，應該會影響優先順序、界線、回應方式，還有一個人慢慢正在成為什麼樣的人。', vocab: [{ word: 'shape of a life', def: '一個人的人生最終長成的樣子與方向' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That does not require moral perfection, but it probably does require seriousness.', zh: '這不需要道德完美，但大概的確需要一種認真。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. If belief never leaves a mark on action, then maybe it is admiration more than conviction.', zh: '沒錯。如果一個信念從來沒在行動上留下痕跡，那它也許比較像欣賞，而不是信念。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So to live according to what you believe may mean letting belief become costly enough to matter.', zh: '所以要活出自己的信念，也許就意味著：讓信念變得有足夠成本，因此也才有足夠重量。', vocab: [{ word: 'admiration more than conviction', def: '你欣賞某個價值，但還沒有真正把它活成自己的原則' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And that is when belief stops being theory and starts becoming character.', zh: '而也就是在那裡，信念才會從理論，開始變成性格。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'in practice', zh: '在實際生活中', example: 'Beliefs are tested in practice.' },
      { en: 'ordinary actions', zh: '日常行動', example: 'Ordinary actions often reveal moral character.' },
      { en: 'alignment', zh: '一致感', example: 'Alignment takes practice, not just intention.' },
      { en: 'repair', zh: '修補', example: 'After failure, repair matters more than excuses.' },
      { en: 'shape of a life', zh: '人生的形狀', example: 'Real belief changes the shape of a life.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 5,
    date: '2026-10-09',
    theme: 'Values & Beliefs',
    title: 'Disagreeing with People You Respect',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Respect Does Not Remove Difference',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think one of the most difficult forms of disagreement is disagreement with people you genuinely respect.', zh: '我覺得最難的一種分歧，就是你和那些你真心尊敬的人意見不同。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. It is easier to dismiss people you do not respect. Respect makes difference emotionally more complicated.', zh: '對。你不尊敬的人比較容易直接 dismiss，但尊敬會讓差異在情緒上變得更複雜。', vocab: [{ word: 'genuinely respect', def: '不是表面客氣，而是真心覺得對方有某些值得敬重的地方' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'Because now the disagreement is not only about ideas. It is also about trust, closeness, and how much you want to remain connected.', zh: '因為這時候，分歧不只是在談觀點，也是在談信任、親近感，還有你多希望彼此還能保持連結。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. A person may feel torn between honesty and belonging.', zh: '沒錯。人很容易在誠實和歸屬之間被拉扯。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That tension is real, especially when the respected person helped shape you in some way.', zh: '那種張力是真的，尤其當那個被你尊敬的人，在某種程度上也塑造過你。', vocab: [{ word: 'belonging', def: '還能被接納、留在關係裡、不被排除的感覺' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And that is why disagreement can feel like a threat to the relationship, not just to agreement.', zh: '而這也就是為什麼，分歧會讓人感覺像是在威脅關係本身，而不只是威脅共識。' },
        ],
      },
      {
        title: 'Part 2 — Curiosity Protects Respect',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think curiosity is one of the few things that can protect respect during disagreement.', zh: '我覺得好奇心，是在分歧裡少數還能保護尊重的東西之一。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. If curiosity leaves, people usually start moving toward caricature and defense.', zh: '對。如果好奇心一離開，對話通常很快就會往扁平化和防衛走。', vocab: [{ word: 'curiosity', def: '不是急著判斷，而是真的想理解對方為什麼這樣想' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And caricature is dangerous because it lets you feel morally clean without understanding anything difficult.', zh: '而 caricature 很危險，因為它讓你可以在完全沒理解難的部分前，就先覺得自己很道德正確。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So asking What do you see that I do not? may be more powerful than trying to win too quickly.', zh: '所以與其急著贏，不如問一句「你看到了什麼是我沒看到的？」也許更有力量。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Curiosity does not guarantee agreement, but it often prevents contempt.', zh: '沒錯。好奇心不保證會有共識，但它常常能防止蔑視。', vocab: [{ word: 'prevent contempt', def: '避免把對方看低、看扁，甚至失去基本尊重' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And in many relationships, preventing contempt may matter more than forcing resolution.', zh: '而在很多關係裡，避免蔑視也許比硬逼出結論還重要。' },
        ],
      },
      {
        title: 'Part 3 — Respect Does Not Mean Agreement',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'At the same time, respect should not require pretending differences do not matter.', zh: '但同時，尊重也不該變成假裝差異不重要。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I agree. Some disagreements are minor, but others touch justice, harm, or moral boundaries very deeply.', zh: '我同意。有些分歧很小，但有些真的會深深碰到正義、傷害，或道德界線。', vocab: [{ word: 'moral boundaries', def: '一個人心中認為不能輕易越過的原則界線' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And in those cases, minimizing the issue can become another form of dishonesty.', zh: '而在那些情況下，把事情說小，反而會變成另一種不誠實。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. You can treat someone with dignity while still saying, This difference is serious to me.', zh: '沒錯。你完全可以一邊維持對人的尊嚴感，一邊很清楚地說：這個差異對我來說很嚴重。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That is hard because many people confuse peacekeeping with love.', zh: '這很難，因為很多人會把維持表面和平誤認成愛。', vocab: [{ word: 'peacekeeping', def: '把衝突壓下去，不讓表面起波瀾的做法' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'But sometimes love requires clarity, not just comfort.', zh: '但有時愛真正需要的是清楚，而不只是舒服。' },
        ],
      },
      {
        title: 'Part 4 — Boundaries May Be Part of Respect',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I also think boundaries are sometimes part of respectful disagreement.', zh: '我也覺得，有時候界線本身就是尊重分歧的一部分。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Meaning not every disagreement has to be processed endlessly?', zh: '你的意思是，不是每一種分歧都要無止盡地談下去？', vocab: [{ word: 'boundaries', def: '知道一段關係裡哪些對話可以進行、哪些地方需要停下來' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Some conversations become harmful or repetitive, and knowing when to pause is not always avoidance.', zh: '沒錯。有些對話會變得有害或只是重複，知道什麼時候先停下來，不一定就是逃避。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That is important because some people think real respect means unlimited availability for debate.', zh: '這很重要，因為有些人會以為真正的尊重，代表你必須無限供應自己來辯論。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'But human dignity includes the right not to keep reopening what is becoming damaging.', zh: '但人的尊嚴裡，也包括不必一直重開那些正在造成傷害的事情。', vocab: [{ word: 'unlimited availability', def: '好像自己必須隨時準備好被問、被辯、被挑戰到底' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So boundaries may actually keep respect alive where endless argument would destroy it.', zh: '所以有時界線反而是讓尊重活下來的條件，不然無止盡爭論只會把它毀掉。' },
        ],
      },
      {
        title: 'Part 5 — Mature Disagreement Keeps Humanity Intact',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Maybe mature disagreement means holding on to two truths at once: this difference matters, and this person is still human to me.', zh: '也許成熟的分歧，就是同時握住兩個事實：這個差異真的重要，而且這個人對我來說仍然是人。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think that is beautifully said. The challenge is not only intellectual honesty, but moral imagination.', zh: '我覺得這句話說得很漂亮。這裡的挑戰不只是智識上的誠實，也包括道德想像力。', vocab: [{ word: 'moral imagination', def: '即使有分歧，也仍能把對方看成完整的人，而不是標籤' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And moral imagination may be what keeps disagreement from collapsing into dehumanization.', zh: '而道德想像力，也許就是阻止分歧墜入去人性化的關鍵。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. You may still need distance, boundaries, or hard conversations, but you do not have to lose your humanity in the process.', zh: '沒錯。你也許還是需要距離、界線，或艱難對話，但你不必在過程中把自己的人性丟掉。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That sounds like a demanding kind of respect.', zh: '這聽起來是一種要求很高的尊重。', vocab: [{ word: 'dehumanization', def: '不再把對方當成完整的人，而只剩敵意或標籤' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes, but maybe the most necessary kind in a divided world.', zh: '對，但也許正是這個分裂世界裡最必要的一種。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'genuinely respect', zh: '真心尊敬', example: 'It is hardest to disagree with people you genuinely respect.' },
      { en: 'curiosity', zh: '好奇心', example: 'Curiosity can protect respect in disagreement.' },
      { en: 'moral boundaries', zh: '道德界線', example: 'Some disagreements involve moral boundaries.' },
      { en: 'unlimited availability', zh: '無限供應自己', example: 'Respect does not require unlimited availability for argument.' },
      { en: 'dehumanization', zh: '去人性化', example: 'Good disagreement resists dehumanization.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 6,
    date: '2026-10-10',
    theme: 'Values & Beliefs',
    title: 'What You Refuse to Compromise On',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Every Life Has Pressure Points',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think everyone eventually faces moments when they have to decide what they will not trade away.', zh: '我覺得每個人最後都一定會遇到那些時刻：你得決定自己有哪些東西是不拿來交換的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. Life keeps presenting pressure points where convenience, belonging, money, or fear test the firmness of your values.', zh: '對。人生會不斷出現壓力點，讓方便、歸屬、金錢或恐懼，來測試你的價值觀到底有多穩。', vocab: [{ word: 'pressure points', def: '某些情境會特別強烈地逼你表態、做選擇的關鍵時刻' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That is when compromise stops being a neutral word and starts becoming a moral question.', zh: '而也就是在那裡，妥協這個字不再只是中性操作，而會開始變成道德問題。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Some compromises are wise and necessary, but others cost too much of the self.', zh: '沒錯。有些妥協是成熟而必要的，但有些妥協會花掉太多自己的核心。' },
          { speaker: 'a', speakerName: 'Jade', en: 'The hard part is knowing the difference.', zh: '而最難的部分，就是怎麼分辨那兩者。', vocab: [{ word: 'cost too much of the self', def: '雖然外表看似划算，但其實會傷到一個人很核心的部分' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And that difference is often only visible when something valuable is on the line.', zh: '而那個差別，也常常只有在你真的有重要東西擺上檯面時，才看得出來。' },
        ],
      },
      {
        title: 'Part 2 — Non-Negotiables Need Clarity',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think people need more clarity about their non-negotiables before they are tested.', zh: '我覺得人在被考驗之前，真的需要先更清楚自己的 non-negotiables 是什麼。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. Otherwise they may improvise under pressure and end up betraying themselves without meaning to.', zh: '對。不然他很可能在壓力下臨場亂決定，最後在沒打算的情況下就背叛了自己。', vocab: [{ word: 'non-negotiables', def: '那些你認為不能輕易拿來交換、妥協或放掉的原則' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That is why reflection matters in calm seasons. You prepare your future self by thinking ahead.', zh: '這也是為什麼，在平靜時期做反思很重要。你是在替未來的自己做準備。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And maybe not everything has to be absolute, but some things should be named clearly enough that you recognize them when they are threatened.', zh: '也許不是每件事都要是絕對的，但至少有些東西應該被命名得夠清楚，這樣它們被威脅時你才認得出來。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Clarity does not guarantee courage, but it gives courage something to stand on.', zh: '沒錯。清楚感不保證你一定勇敢，但它至少會給勇氣一個站得住的地方。', vocab: [{ word: 'stand on', def: '在困難時刻能依靠的一塊比較穩的內在地面' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And without that ground, people are much easier to move by fear or pressure.', zh: '而沒有那塊地時，人真的很容易就被恐懼或壓力推走。' },
        ],
      },
      {
        title: 'Part 3 — Cost Reveals Seriousness',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think a value only becomes fully serious when keeping it actually costs you something.', zh: '我覺得一個價值觀，通常要到你真的為了守住它付出代價時，才會真正變得嚴肅。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. If a principle never asks anything of you, it may be preference more than conviction.', zh: '對。如果一個原則從來沒向你要求過任何東西，那它可能比較像偏好，而不是信念。', vocab: [{ word: 'cost', def: '你為了守住某件事，真的必須付出的代價或失去' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That does not mean suffering is the goal, only that cost reveals what is real.', zh: '這不是說受苦本身是目標，而是說：代價會把真實性照出來。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. It may cost approval, ease, money, speed, or a certain image of yourself.', zh: '沒錯。那個代價可能是他人的認同、輕鬆感、金錢、速度，或你原本很喜歡的自我形象。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And that is why non-compromise can feel both painful and clarifying at the same time.', zh: '這也是為什麼，不妥協常常會同時又痛、又很清楚。', vocab: [{ word: 'preference more than conviction', def: '喜歡某個原則的樣子，但還沒有真的把它當成自己活著的標準' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Because once cost enters, the person finally sees what matters more.', zh: '因為一旦代價真的進來，人就會比較清楚看見：到底什麼比較重要。' },
        ],
      },
      {
        title: 'Part 4 — Not Every Flexibility Is Betrayal',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'At the same time, not every flexibility should be treated as betrayal.', zh: '但同時，也不是每一種彈性都該被當成背叛。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Right. If people are too rigid, they may confuse ego with principle.', zh: '對。如果一個人太僵，很容易把 ego 誤認成原則。', vocab: [{ word: 'rigid', def: '太僵硬，不願意分辨情境，只想死守某種樣子' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Wisdom probably means knowing which things can bend and which things should not.', zh: '成熟大概就是知道：哪些東西可以彎，哪些東西不該彎。' },
          { speaker: 'a', speakerName: 'Jade', en: 'That discernment keeps conviction from becoming performative stubbornness.', zh: '而那種分辨力，也會讓信念不至於變成一種表演式的固執。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Strong principles and humble flexibility are not enemies. They need each other.', zh: '沒錯。堅定原則和謙卑彈性其實不是敵人，它們反而需要彼此。', vocab: [{ word: 'performative stubbornness', def: '看起來很有原則，其實只是為了面子而死不退讓' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So the real question is not Am I compromising? but What exactly am I compromising, and should I?', zh: '所以真正的問題不是「我是不是在妥協」，而是「我到底在妥協什麼？而且這值得嗎？」' },
        ],
      },
      {
        title: 'Part 5 — What You Protect Becomes You',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Maybe what you refuse to compromise on slowly becomes part of who you are.', zh: '也許那些你拒絕拿來妥協的東西，久了就會慢慢變成你的一部分。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think so. What you protect repeatedly shapes your character just as much as what you pursue.', zh: '我也這樣覺得。你反覆保護什麼，和你追求什麼一樣，都會塑造你的性格。', vocab: [{ word: 'what you protect', def: '你真正願意去守住、不輕易放掉的那些東西' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That makes moral life feel less like theory and more like formation.', zh: '這也讓道德生活聽起來比較不像理論，而比較像成形的過程。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Every serious refusal leaves a mark on the person who makes it.', zh: '沒錯。每一次認真的拒絕，都會在做出那個拒絕的人身上留下痕跡。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So perhaps non-compromise is not mainly about proving moral strength. It is about becoming trustworthy to yourself.', zh: '所以也許不妥協的重點，不是證明自己多有道德，而是讓自己對自己變得可信。', vocab: [{ word: 'trustworthy to yourself', def: '你知道自己在關鍵時刻不會輕易拋下真正重要的東西' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And that kind of trust may be one of the deepest rewards of principle.', zh: '而那種自我信任，也許就是原則感最深的一種回報。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'pressure points', zh: '壓力點', example: 'Life reveals values through pressure points.' },
      { en: 'non-negotiables', zh: '不能輕易交換的原則', example: 'Clear non-negotiables help under pressure.' },
      { en: 'cost', zh: '代價', example: 'Principles become real when they involve cost.' },
      { en: 'performative stubbornness', zh: '表演式固執', example: 'Good values are not the same as performative stubbornness.' },
      { en: 'trustworthy to yourself', zh: '對自己可信', example: 'Integrity makes you trustworthy to yourself.' },
    ],
  },
  {
    weekNumber: 41,
    dayOfWeek: 7,
    date: '2026-10-11',
    theme: 'Values & Beliefs',
    title: 'Becoming More Thoughtful About What Matters',
    phase: 'p5',
    parts: [
      {
        title: 'Part 1 — Thoughtfulness Takes Time',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I think becoming thoughtful about values is a long process, not a one-time realization.', zh: '我覺得，對價值觀變得有思考，是一個很長的過程，不是一次頓悟就完成的。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Yes. People often want quick clarity, but values usually deepen through reflection, failure, conflict, and repeated choices.', zh: '對。人很想要快速清楚，但價值觀通常是透過反思、失敗、衝突和反覆選擇才慢慢變深。', vocab: [{ word: 'thoughtful', def: '不是只接受現成答案，而是有反思地看待自己相信什麼' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That can feel slow, but maybe slowness is part of what makes the process honest.', zh: '這會讓人覺得很慢，但也許正是這種慢，讓整個過程變得比較誠實。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Deep values are often formed through lived tension, not just through clever ideas.', zh: '沒錯。深的價值觀，很多時候是透過活過張力才形成的，不只是靠聰明想法。' },
          { speaker: 'a', speakerName: 'Jade', en: 'So if someone still feels unfinished in what they believe, that may simply mean they are still growing.', zh: '所以如果一個人還覺得自己的信念很未完成，那也許只是代表他還在長。', vocab: [{ word: 'lived tension', def: '在真實人生裡被衝突、選擇和後果拉扯的經驗' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And growth is usually a better sign than rigid certainty anyway.', zh: '而且說到底，成長通常本來就比僵硬的確定感更健康。' },
        ],
      },
      {
        title: 'Part 2 — Reflection Needs Honesty',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think reflection only becomes useful when it is honest enough to notice contradiction.', zh: '我覺得反思只有在夠誠實、能看見矛盾時，才會真的有用。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. Otherwise it becomes self-flattering storytelling.', zh: '對。不然它很容易變成一種讓自己聽起來很好看的故事。', vocab: [{ word: 'contradiction', def: '自己說相信的，和自己實際活出的，彼此對不起來的地方' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'And noticing contradiction is uncomfortable, because it often reveals where desire and principle are not aligned.', zh: '而看見矛盾會很不舒服，因為它常常會揭露：你的欲望和原則其實沒有對齊。' },
          { speaker: 'a', speakerName: 'Jade', en: 'But without seeing that gap, a person cannot really grow more integrated.', zh: '但如果不先看見那個落差，一個人就很難真正長成比較整合的樣子。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Honest reflection is not there to crush you. It is there to reunite you with yourself.', zh: '沒錯。誠實反思不是拿來壓垮你的，它是拿來把你重新帶回自己身邊的。', vocab: [{ word: 'self-flattering storytelling', def: '把自己講得很好看，但其實沒有真正面對真相的敘事' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'And that is why honest reflection often feels painful before it feels freeing.', zh: '而這也就是為什麼，誠實反思通常會先痛，然後才開始有自由感。' },
        ],
      },
      {
        title: 'Part 3 — Wisdom Is Not Only Knowing, but Ordering',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'I also think being thoughtful about values means learning how to order them, not just list them.', zh: '我也覺得，對價值觀有思考，不只是把它們列出來，而是學會怎麼排序。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Definitely. Almost nobody can honor every value equally in every moment.', zh: '真的。幾乎沒有人能在每一個時刻，把所有價值觀都平均地顧到。', vocab: [{ word: 'order them', def: '知道當不同價值彼此衝突時，自己會把哪個放前面' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That means wisdom includes deciding what matters most when values collide.', zh: '這也表示，智慧裡面包含了：當價值互撞時，知道什麼應該排在前面。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Freedom and loyalty, honesty and kindness, ambition and peace, justice and mercy can all come into tension.', zh: '沒錯。自由和忠誠、誠實和善良、野心和平靜、公義和憐憫，都可能彼此拉扯。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And a thoughtful person does not panic when tension appears. They learn to interpret it.', zh: '而一個有思考的人，不會一看到張力就慌，他會試著去讀懂那個張力在說什麼。', vocab: [{ word: 'values collide', def: '兩個都重要的價值，在某個情境裡不能同時被完整滿足' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That may be one of the deepest forms of moral adulthood.', zh: '而那也許就是道德成熟最深的一種形式之一。' },
        ],
      },
      {
        title: 'Part 4 — Thoughtfulness Should Make Us More Humane',
        lines: [
          { speaker: 'b', speakerName: 'Ryan', en: 'I think the goal of becoming thoughtful about values is not becoming morally superior, but becoming more humane.', zh: '我覺得，對價值觀變得有思考的目標，不是變得道德優越，而是變得更有人味。' },
          { speaker: 'a', speakerName: 'Jade', en: 'Yes. If reflection only makes someone harsher, more performative, or less compassionate, something has gone wrong.', zh: '對。如果反思最後只把人變得更苛刻、更表演，或更沒有同理，那中間一定哪裡出錯了。', vocab: [{ word: 'more humane', def: '更有同理、更完整，也更能承受人性的複雜' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. Good moral reflection should deepen humility because it shows how difficult good living actually is.', zh: '沒錯。好的道德反思，反而應該會讓人更謙卑，因為它會讓你看到：好好活其實真的很不容易。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And humility may be what keeps conviction from hardening into arrogance.', zh: '而謙卑，也許就是防止信念硬化成傲慢的東西。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'That matters so much in a world where people often confuse certainty with wisdom.', zh: '這在現在這個世界裡真的很重要，因為很多人會把確定感誤認成智慧。', vocab: [{ word: 'hardening into arrogance', def: '原本有力量的信念，最後變得驕傲、僵硬、看不起別人' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'So perhaps becoming thoughtful means becoming both clearer and kinder at the same time.', zh: '所以也許所謂變得有思考，就是同時變得更清楚，也更溫柔。' },
        ],
      },
      {
        title: 'Part 5 — What Matters Deserves Attention',
        lines: [
          { speaker: 'a', speakerName: 'Jade', en: 'Maybe one of the simplest truths is that what matters most deserves repeated attention.', zh: '也許最簡單的一個真理就是：真正重要的事，值得被一再放回注意力裡。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'I think so. Values fade into slogans when they are not revisited, and they deepen when they are returned to honestly.', zh: '我也這樣覺得。價值觀如果不被重新回看，很容易變成口號；但如果被誠實地反覆回來看，它就會變深。', vocab: [{ word: 'repeated attention', def: '不是偶爾想到，而是長期反覆把重要問題帶回心裡看' }] },
          { speaker: 'a', speakerName: 'Jade', en: 'That sounds less like arriving and more like continuing.', zh: '這聽起來比較不像抵達，反而比較像持續。' },
          { speaker: 'b', speakerName: 'Ryan', en: 'Exactly. A thoughtful life is probably not a finished set of answers, but an ongoing practice of returning to what matters.', zh: '沒錯。一個有思考的人生，大概不是一套已完成的答案，而是不斷回到真正重要之事的練習。' },
          { speaker: 'a', speakerName: 'Jade', en: 'And maybe that practice is what keeps values alive instead of merely inherited.', zh: '而也許正是那種練習，才讓價值觀活著，而不只是被繼承著。', vocab: [{ word: 'ongoing practice', def: '不是一次做完，而是會一直回來做的長期練習' }] },
          { speaker: 'b', speakerName: 'Ryan', en: 'That sounds like a very good way to live.', zh: '這聽起來就是一種很好的活法。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'thoughtful', zh: '有思考的', example: 'A thoughtful life takes time to build.' },
      { en: 'contradiction', zh: '矛盾', example: 'Reflection often begins with contradiction.' },
      { en: 'order them', zh: '把價值排序', example: 'Wisdom means learning how to order them.' },
      { en: 'more humane', zh: '更有人味', example: 'Deep reflection should make people more humane.' },
      { en: 'ongoing practice', zh: '持續練習', example: 'Values become clearer through ongoing practice.' },
    ],
  },
]
