import { Episode } from '../types'

const line = (speaker, en, zh, vocab) => ({
  speaker,
  speakerName: speaker === 'a' ? 'Mira' : 'Jamie',
  en,
  zh,
  ...(vocab ? { vocab: [vocab] } : {}),
})

const a = (en, zh, word, def) => line('a', en, zh, word ? { word, def } : undefined)
const b = (en, zh, word, def) => line('b', en, zh, word ? { word, def } : undefined)
const part = (title, lines) => ({ title, lines })
const kp = (en, zh, example) => ({ en, zh, example })

export const WEEK_46: Episode[] = [
  {
    weekNumber: 46,
    dayOfWeek: 1,
    date: '2026-11-09',
    theme: 'Community & Giving Back',
    title: 'The Power of Community',
    phase: 'p6',
    parts: [
      part('Part 1 — Why People Need More Than Individual Strength', [
        b('People talk a lot about independence, but community seems to matter just as much.', '大家很常談獨立，可是社群似乎一樣重要。'),
        a('It does, because most people get through hard seasons through shared support, not private strength alone.', '真的很重要，因為大多數人撐過艱難時期，靠的不是純粹個人意志，而是共享的支持。', 'shared support', '不是一個人硬撐，而是彼此支撐的支持網'),
        b('So community is not a sentimental extra.', '所以社群不是一種感性的加分題。'),
        a('Not at all. A strong community gives people practical backup, emotional belonging, and a sense that they do not have to solve life alone.', '完全不是。好的社群會提供實際後援、情感上的歸屬，以及一種「不用獨自解決人生」的感覺。', 'emotional belonging', '在一個群體裡感覺自己真的被接住、被接納'),
        b('That already sounds powerful.', '光這樣聽起來就很有力量。'),
        a('It is powerful because it changes how much fear a person has to carry by themselves.', '它之所以有力量，是因為它改變了一個人得獨自扛多少恐懼。', 'fear load', '一個人需要自己扛住的心理壓力重量'),
        b('So the power of community is partly about reducing isolation.', '所以社群的力量，有一部分其實是在降低孤立感。'),
        a('Yes, and once isolation drops, people often become more generous, more stable, and more able to help others too.', '對。而當孤立感下降，人常常也會變得更慷慨、更穩，甚至更有能力去幫別人。', 'social steadiness', '因為有人接住，所以人變得比較穩定的狀態'),
      ]),
      part('Part 2 — What Healthy Communities Actually Do', [
        b('What do healthy communities do that weak communities do not?', '健康的社群，和脆弱的社群相比，真正多做了什麼？'),
        a('They make help visible and normal. In a healthy community, asking for help is not treated like a personal failure.', '它們會讓求助變得可見，也變得正常。在健康的社群裡，求助不會被當成個人失敗。', 'normalize help', '讓求助與互助變成自然、不丟臉的事'),
        b('That alone would change how many people behave.', '光這一點，就會讓很多人的行為不一樣。'),
        a('It really does. Healthy groups also spread the burden. One person may start the work, but the work does not stay on one back forever.', '真的會。而且健康的群體也會分散負擔。也許一個人先開始，但那個重量不會永遠只壓在同一個人身上。', 'spread the burden', '把責任和辛苦分散，不讓單一人一直扛'),
        b('So sustainability is part of care too.', '所以可持續性，本來就是照顧的一部分。'),
        a('Exactly. Burned-out helping is still burnout. Good communities protect the helpers as well as the people being helped.', '沒錯。燒乾自己的幫忙，終究還是 burnout。好的社群會同時保護幫忙的人和被幫助的人。', 'protect the helpers', '照顧付出的人，不讓照顧只變成耗損'),
        b('That feels wiser than the idea of endless sacrifice.', '這比無止盡犧牲的想像，聰明太多了。'),
        a('It is wiser, and in the long run it is kinder too.', '它確實更聰明，而且長期來看也更溫柔。'),
      ]),
      part('Part 3 — English for Talking About Community', [
        b('How can I describe community in natural English?', '如果我要用自然英文談 community，可以怎麼說？'),
        a('A useful sentence is: "I realized I was not carrying the whole thing alone anymore." That captures relief and connection at the same time.', '一句很好用的是：「I realized I was not carrying the whole thing alone anymore.」這句同時抓到了鬆一口氣和連結感。', 'carry it alone', '一個人獨自扛住所有事情'),
        b('That line feels very human.', '這句很有人味。'),
        a('Another one is: "Our community is small, but people show up when it counts." That sounds simple and believable.', '另一句也很好：「Our community is small, but people show up when it counts.」這句簡單，而且很可信。', 'show up when it counts', '在真正重要的時候出現並付出'),
        b('I like that because it sounds real, not idealized.', '我喜歡這句，因為它聽起來很真，不是理想化。'),
        a('If you want something more reflective, say, "Community changed from a nice idea into a survival skill for me." That works when support became personally meaningful.', '如果你想講得更有反思感，可以說：「Community changed from a nice idea into a survival skill for me.」這很適合描述支持突然變得很切身。', 'survival skill', '不是抽象美德，而是真的讓人撐得下去的能力'),
        b('That sentence has weight.', '這句真的有重量。'),
        a('It should. For many people, community only becomes visible after a hard season makes it necessary.', '本來就該有重量。對很多人來說，社群是在困難時期逼近之後，才真正變得看得見。'),
      ]),
      part('Part 4 — A Community Moment People Recognize', [
        b('What is an ordinary example of community in action?', '有沒有一個很普通、但大家都認得出來的 community 例子？'),
        a('Imagine a family member gets sick and neighbors begin doing practical things before anyone has to make a dramatic request.', '想像家裡有人生病了，而鄰居在還沒有人發出戲劇性求助前，就開始做一些實際的事。'),
        b('What kind of practical things?', '像什麼樣的實際事情？'),
        a('Meals, rides, child pickup, small check-ins, and updates that keep one tired person from having to explain the same story all day.', '像是送餐、接送、幫忙接小孩、小小的關心訊息，還有代為更新近況，讓那個已經很累的人不用整天重複說同一個故事。', 'practical care', '看得見、做得到、能減輕負擔的照顧'),
        b('That is the kind of help that changes the day itself.', '那種幫忙是真的會直接改變一天的樣子。'),
        a('Exactly. Community care often looks ordinary from the outside, but from the inside it can feel life-saving.', '沒錯。從外面看，社群照顧常常很普通；但從裡面的人來看，它可能像救命一樣。', 'community care', '由一群人共同提供、能實際接住人的照顧'),
        b('So what matters is not grand language. It is usable help.', '所以真正重要的不是很大的語言，而是可用的幫忙。'),
        a('Yes. People remember the help that made the next hour possible.', '對。人會記得的是那種讓「下一個小時變得可過」的幫忙。'),
      ]),
      part('Part 5 — Why Giving Back Matters', [
        b('Why does giving back matter so much once someone has received help?', '一個人一旦真的被幫過，為什麼 give back 會變得那麼重要？'),
        a('Because receiving care changes your sense of debt and connection. You start wanting the circle to continue, not stop with you.', '因為被照顧會改變你對連結和責任的感覺。你會開始想讓那個循環繼續，而不是停在自己身上。'),
        b('So gratitude becomes action.', '所以 gratitude 最後會變成行動。'),
        a('Often, yes. Giving back is one way people turn private relief into shared meaning.', '很多時候確實如此。回饋社群，是把私人層面的鬆一口氣，變成公共層面的意義的一種方式。'),
        b('That makes service sound much less abstract.', '這樣一講，服務社群就沒那麼抽象了。'),
        a('Good service usually is not abstract. It begins when someone remembers exactly what kind of help once mattered to them.', '好的服務本來就不抽象。它往往開始於一個人還記得，哪一種幫忙曾經真實地對自己有用。'),
        b('That is a beautiful place to begin from.', '那是一個很美的起點。'),
        a('It is, because it keeps care specific, humble, and close to real life.', '對，因為它會讓照顧維持在具體、謙卑，而且貼近真實生活的地方。'),
      ]),
    ],
    keyPhrases: [
      kp('shared support', '不是一個人硬撐，而是彼此支撐的支持網', 'Shared support changed the whole situation for them.'),
      kp('emotional belonging', '在一個群體裡感覺自己真的被接住、被接納', 'Emotional belonging matters as much as practical help.'),
      kp('fear load', '一個人需要自己扛住的心理壓力重量', 'Community reduces the fear load people carry alone.'),
      kp('normalize help', '讓求助與互助變成自然、不丟臉的事', 'A strong community knows how to normalize help.'),
      kp('spread the burden', '把責任和辛苦分散，不讓單一人一直扛', 'They spread the burden before anyone burned out.'),
      kp('protect the helpers', '照顧付出的人，不讓照顧只變成耗損', 'Good systems protect the helpers too.'),
      kp('show up when it counts', '在真正重要的時候出現並付出', 'Real friends show up when it counts.'),
      kp('community care', '由一群人共同提供、能實際接住人的照顧', 'Community care made the hardest week survivable.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 2,
    date: '2026-11-10',
    theme: 'Community & Giving Back',
    title: 'The Art of Listening',
    phase: 'p6',
    parts: [
      part('Part 1 — Listening Is More Than Waiting Quietly', [
        b('Why do people call listening an art?', '為什麼大家會把傾聽叫做一種藝術？'),
        a('Because real listening is active. You are not just staying silent; you are making room for another person to become clearer.', '因為真正的傾聽是主動的。你不是只是在安靜而已；你是在替另一個人騰出空間，讓他變得更清楚。', 'make room', '讓對方有空間把自己說完整'),
        b('So silence alone is not enough.', '所以光安靜還不夠。'),
        a('Not at all. Some silence feels warm, curious, and steady. Other silence feels absent, impatient, or judgmental.', '完全不夠。有些沉默讓人覺得溫暖、好奇、穩定；有些沉默卻讓人覺得你根本不在、很不耐煩，或正在評價他。', 'listening stance', '你在聽人時整體呈現出的態度與存在感'),
        b('That is a huge difference.', '那個差別真的很大。'),
        a('It is. People often know within seconds whether your attention is truly with them.', '真的很大。很多人幾秒內就能感覺到，你的注意力到底是不是真的在他身上。', 'true attention', '不是表面在聽，而是真的把注意力放在對方身上'),
        b('So listening begins in presence, not in advice.', '所以傾聽是從 presence 開始，不是從 advice 開始。'),
        a('Exactly. Advice too early can feel like being replaced before you were understood.', '沒錯。建議來得太早，會讓人覺得自己還沒被理解，就已經被跳過了。', 'premature advice', '對方還沒被理解之前就太快給出的建議'),
      ]),
      part('Part 2 — What Good Listening Gives People', [
        b('What does good listening actually give someone?', '好的傾聽，真正會給一個人什麼？'),
        a('Often it gives shape. People arrive with a tangle, and being listened to helps them hear their own thinking more clearly.', '很多時候它給的是形狀。人來的時候腦子是一團亂，而被好好聽，會幫他比較清楚地聽見自己的思路。', 'give shape', '幫一件混亂的事慢慢變得有輪廓'),
        b('So the listener is not solving the problem, but helping the problem become speakable.', '所以聽的人不是直接解決問題，而是在幫問題變得可以說得出來。'),
        a('Yes, and that can be deeply relieving. Many people calm down once the inside of their head starts sounding less chaotic outside of it.', '對，而那會讓人非常鬆。很多人是等到自己腦中的混亂，終於在外面聽起來沒那麼亂，人才開始 calm down。', 'speakable problem', '從一團感受變成可以被說清楚的問題'),
        b('That is such a compassionate way to describe it.', '這個描述很有同理。'),
        a('Listening is compassionate when it says, without saying it directly, "You do not have to untangle this alone."', '傾聽之所以有同理，是因為它會在不明講的情況下，傳遞出一句話：「你不用一個人把這一切理開。」', 'shared untangling', '不是自己一個人硬整理，而是有人陪你一起理開'),
        b('So listening can feel like partnership.', '所以傾聽也會讓人感覺像一種同行。'),
        a('Exactly, and that is why it matters so much in friendships, teams, and families alike.', '沒錯。也正因如此，它在友情、團隊和家庭裡都那麼重要。'),
      ]),
      part('Part 3 — English That Sounds Like Real Listening', [
        b('What English sounds like real listening instead of fake listening?', '有哪些英文，聽起來像真的在聽，而不是假的在聽？'),
        a('A very useful line is: "I want to make sure I am understanding this the way you mean it." That shows care and humility.', '一句很好用的是：「I want to make sure I am understanding this the way you mean it.」這句同時有關心和謙卑。', 'check understanding', '確認自己有沒有照對方的意思理解'),
        b('That sounds much better than jumping straight to a solution.', '這句真的比直接跳去解法好多了。'),
        a('Another one is: "Say more about that part." It invites detail without taking over the conversation.', '另一句也很自然：「Say more about that part.」它會邀請細節，但不會搶走對話。', 'invite detail', '鼓勵對方把真正重要的細節說出來'),
        b('I like how small and usable that is.', '我喜歡它很小，但很能用。'),
        a('If someone is emotional, try: "That sounds heavier than people might realize." It can help them feel seen without sounding dramatic.', '如果對方情緒比較重，可以試：「That sounds heavier than people might realize.」這句能讓人覺得被看見，但不會太戲劇化。', 'reflect the weight', '把事情的重量反映回去，讓對方知道你有感受到'),
        b('That would be good when someone is downplaying what happened.', '這句很適合那種一直在淡化自己經歷的人。'),
        a('Exactly. Good listening often sounds simple because it is focused on the other person, not on your own performance.', '沒錯。好的傾聽聽起來往往很簡單，因為它的焦點在對方，不是在自己的表現。'),
      ]),
      part('Part 4 — When Listening Goes Wrong', [
        b('What usually ruins listening?', '什麼最容易把傾聽搞壞？'),
        a('Interrupting with yourself too soon. People often hear one sentence and immediately start searching for their own version of the story.', '太早把自己插進去。很多人一聽到一句話，就立刻開始搜尋自己相似的故事。', 'self-insertion', '對方還沒說完，就把焦點移回自己身上'),
        b('That feels common and a little embarrassing.', '這真的很常見，而且有點尷尬。'),
        a('It is common because the brain wants connection, but rushed connection can still feel like being erased.', '它很常見，因為大腦本來就想建立連結；但太趕的連結，還是會讓人感覺自己被抹掉。', 'rushed connection', '急著建立連結，反而讓對方沒被真正聽見'),
        b('So good listening waits longer than the ego wants to wait.', '所以好的傾聽，會比 ego 想等的時間再多等一點。'),
        a('Yes. Another common problem is listening only for facts and missing the emotional center of the story.', '對。另一個常見問題是：只聽事實，卻漏掉整個故事真正的情緒核心。', 'emotional center', '一段故事裡真正重要的情緒重心'),
        b('That would make the response sound technically correct but emotionally off.', '那樣回應就會變成事實上沒錯，但情緒上完全不對。'),
        a('Exactly. Listening well means hearing not only what happened, but what it cost the person inside it.', '沒錯。聽得好，代表你不只聽見發生了什麼，也聽見那件事讓那個人付出了什麼。'),
      ]),
      part('Part 5 — Listening as a Form of Care', [
        b('Why does being listened to feel so powerful?', '為什麼被好好聽見，會讓人覺得那麼有力量？'),
        a('Because it tells you that your inner life is not too inconvenient to stay with.', '因為它會讓你知道：你的內在世界，並沒有麻煩到別人待不下去。'),
        b('That is a beautiful way to put it.', '這個說法很美。'),
        a('It matters because many people have learned to edit themselves before they speak. Good listening gives them permission to be less edited.', '它很重要，因為很多人早就學會在開口前先刪改自己。好的傾聽會給他們一點 permission，讓他們不用那麼修。'),
        b('So listening can slowly rebuild honesty.', '所以傾聽其實會慢慢把誠實修回來。'),
        a('Yes, and that is why listening is not passive at all. It actively changes what becomes possible between people.', '對。也正因如此，傾聽一點都不被動。它會主動改變人和人之間有哪些東西變得可能。'),
        b('That makes me want to practice it more seriously.', '這會讓我想更認真地練這件事。'),
        a('That is a very good instinct. Listening well is one of the most practical forms of care we have.', '這個直覺很好。好好傾聽，是我們手上最實用的照顧形式之一。'),
      ]),
    ],
    keyPhrases: [
      kp('make room', '讓對方有空間把自己說完整', 'She made room for him to explain the hard part.'),
      kp('listening stance', '你在聽人時整體呈現出的態度與存在感', 'Your listening stance shapes the whole conversation.'),
      kp('premature advice', '對方還沒被理解之前就太快給出的建議', 'Premature advice made her shut down.'),
      kp('speakable problem', '從一團感受變成可以被說清楚的問題', 'The problem became speakable once he slowed down.'),
      kp('shared untangling', '不是自己一個人硬整理，而是有人陪你一起理開', 'The conversation felt like shared untangling.'),
      kp('invite detail', '鼓勵對方把真正重要的細節說出來', 'A good listener knows how to invite detail.'),
      kp('self-insertion', '對方還沒說完，就把焦點移回自己身上', 'Self-insertion often ruins empathy.'),
      kp('emotional center', '一段故事裡真正重要的情緒重心', 'She heard the emotional center, not only the facts.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 3,
    date: '2026-11-11',
    theme: 'Community & Giving Back',
    title: 'Local Heroes and Changemakers',
    phase: 'p6',
    parts: [
      part('Part 1 — Heroism That Looks Ordinary', [
        b('When people hear "local hero," they often imagine someone dramatic.', '大家一聽到 local hero，常常就會想到很戲劇化的人。'),
        a('But many local heroes look ordinary. They are often the people who keep showing up long after the attention is gone.', '但很多在地英雄其實看起來很普通。他們常常是那些在注意力都退場之後，還持續出現的人。', 'steady service', '不是一次很亮眼，而是長期穩定地付出'),
        b('So what makes them stand out is consistency.', '所以讓他們真正突出的是一致性。'),
        a('Exactly. Local change usually grows through repetition, trust, and patient effort, not one perfect moment.', '沒錯。在地改變通常是靠重複、信任和耐心的努力長出來的，不是靠某一個完美瞬間。', 'patient effort', '不急著看見成果，但持續投入的努力'),
        b('That sounds less cinematic and more real.', '這樣聽起來比較不電影，但更真。'),
        a('It is more real. The people who matter most in a community are often the ones who become dependable before they become visible.', '它本來就更真。對社群最重要的人，常常是在變得可見之前，就已經先變得可靠。', 'dependable presence', '長期出現，讓人知道你值得依靠'),
        b('So local heroes often earn trust quietly.', '所以在地英雄常常是安靜地把信任賺起來。'),
        a('Yes, and that quiet trust can move a neighborhood more than a loud campaign can.', '對，而那種安靜的信任，有時候比一場很大聲的宣傳更能推動一個地方。'),
      ]),
      part('Part 2 — The Kind of Change That Lasts', [
        b('What kind of change do changemakers usually aim for?', 'Changemaker 通常在追求的是哪一種改變？'),
        a('The lasting kind. Not only the change that gets noticed, but the change that keeps helping after the spotlight moves on.', '是能留下來的那種。不是只有被看見的改變，而是 spotlight 移走之後，還繼續有幫助的改變。', 'lasting change', '就算注意力散去，效果仍會留下的改變'),
        b('So they are designing for durability, not applause.', '所以他們設計的是耐久度，不是掌聲。'),
        a('Exactly. A good changemaker often cares about systems, relationships, and habits, not only one visible event.', '沒錯。好的 changemaker 通常在乎的是系統、關係和習慣，不只是某個看得見的活動。', 'system mindset', '會去看整體結構，而不是只看單一事件'),
        b('That already sounds like harder work.', '光這樣聽起來就比較難。'),
        a('It is harder, because system work is slower and often less glamorous. But it protects the future instead of decorating the present.', '它真的比較難，因為系統層的工作更慢，也通常比較不 glamorous。但它保護的是未來，不是只裝飾現在。', 'future-protecting work', '雖然慢，但能讓未來真的變好的工作'),
        b('That is such a strong phrase.', '這個說法很有力。'),
        a('Many meaningful people do exactly that kind of work, even if very few cameras notice.', '很多有意義的人做的正是這種工作，就算很少有鏡頭真的看見。'),
      ]),
      part('Part 3 — English for Describing Changemakers', [
        b('How would you describe a changemaker in English naturally?', '如果要用自然英文形容 changemaker，可以怎麼說？'),
        a('You can say, "She is the kind of person who keeps a good idea alive long enough for other people to join it." That sounds human and specific.', '你可以說：「She is the kind of person who keeps a good idea alive long enough for other people to join it.」這句有人味，也很具體。', 'keep an idea alive', '把一個好想法撐久，撐到它能被更多人接上'),
        b('I like that because it includes time and patience.', '我喜歡這句，因為它把時間和耐心都放進去了。'),
        a('Another one is: "He turned concern into organized action." That works well when someone moved from caring to doing.', '另一句也很好：「He turned concern into organized action.」這句很適合描述一個人把在乎變成行動。', 'organized action', '不是零散熱情，而是有安排、有方向的行動'),
        b('That sounds strong without sounding exaggerated.', '這句很有力，但不會太誇張。'),
        a('If you want something more reflective, say, "People trusted her because she kept doing small useful things." That points to credibility, not charisma.', '如果你想講得更反思一點，可以說：「People trusted her because she kept doing small useful things.」這句抓的是可信度，不是 charisma。', 'small useful things', '看起來不大，但真的對人有幫助的小事'),
        b('That line feels very true to local work.', '這句很符合在地工作的現實。'),
        a('Exactly. Local impact often grows through ordinary usefulness.', '沒錯。在地影響力，很多時候就是從普通但有用開始長大的。'),
      ]),
      part('Part 4 — A Person Everyone Remembers', [
        b('Can you give me a concrete picture of a local hero?', '你可以給我一個很具體的 local hero 畫面嗎？'),
        a('Think of the person at a community center who knows which teenager needs encouragement, which parent needs information, and which volunteer needs a break.', '想像社區中心裡那個人，他知道哪個青少年需要鼓勵、哪個家長需要資訊、哪個志工已經該休息了。'),
        b('So they hold a map of people, not only a list of tasks.', '所以他手上拿的是一張人的地圖，不只是工作清單。'),
        a('Exactly. They carry local knowledge that is practical and relational at the same time.', '沒錯。他們身上帶著一種在地知識，既實際，也非常關係導向。', 'local knowledge', '對一個地方、那裡的人與真實需要的熟悉感'),
        b('That kind of knowledge probably cannot be downloaded from a report.', '那種知識大概不是看一份 report 就能下載的。'),
        a('No. It comes from being present long enough to notice patterns and earn trust.', '不能。它來自你待得夠久，久到你能看見模式，也把信任賺起來。', 'earned trust', '不是一開始就有，而是靠長期在場慢慢建立的信任'),
        b('So changemakers are often very good observers.', '所以 changemaker 很多時候也都是很好的觀察者。'),
        a('Yes. Good observation is one of the least glamorous and most important community skills.', '對。觀察力是社群工作裡最不 glamorous、卻又最重要的能力之一。'),
      ]),
      part('Part 5 — Becoming Useful Where You Live', [
        b('If someone wants to become more useful in their own community, where should they start?', '如果有人想在自己住的地方變得更有用，該從哪裡開始？'),
        a('Start by noticing what people are already trying to do before inventing something new. Service begins better when it starts with listening.', '先去看大家已經在努力做什麼，再決定要不要發明新的東西。服務從傾聽開始，通常會比較好。'),
        b('So the first move is not self-expression. It is observation and respect.', '所以第一步不是自我發揮，而是觀察和尊重。'),
        a('Exactly. Ask what is missing, what is duplicated, and where one extra pair of hands could really matter.', '沒錯。去問：現在缺的是什麼、重複的是什麼，以及多一雙手在哪裡真的會有差。'),
        b('That makes helping sound smarter and more humble.', '這樣一來，幫忙聽起來就更聰明，也更謙卑。'),
        a('That is usually the right tone. Real changemakers are often less interested in being impressive than in being useful.', '那通常就是對的 tone。真正的 changemaker，常常對「讓自己很厲害」沒那麼有興趣，反而更在意自己是不是有用。'),
        b('That is a value system I really respect.', '這是一套我很尊敬的價值系統。'),
        a('It is a good one, because it keeps service close to real people and real needs.', '它確實很好，因為它會讓服務一直貼著真實的人和真實的需要。'),
      ]),
    ],
    keyPhrases: [
      kp('steady service', '不是一次很亮眼，而是長期穩定地付出', 'Steady service mattered more than one big event.'),
      kp('patient effort', '不急著看見成果，但持續投入的努力', 'Patient effort changed the neighborhood over time.'),
      kp('dependable presence', '長期出現，讓人知道你值得依靠', 'Her dependable presence made people trust the program.'),
      kp('lasting change', '就算注意力散去，效果仍會留下的改變', 'They were aiming for lasting change, not quick praise.'),
      kp('system mindset', '會去看整體結構，而不是只看單一事件', 'A system mindset helped them solve the real problem.'),
      kp('organized action', '不是零散熱情，而是有安排、有方向的行動', 'He turned concern into organized action.'),
      kp('local knowledge', '對一個地方、那裡的人與真實需要的熟悉感', 'Local knowledge guided every decision they made.'),
      kp('earned trust', '不是一開始就有，而是靠長期在場慢慢建立的信任', 'Their project worked because they had earned trust first.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 4,
    date: '2026-11-12',
    theme: 'Community & Giving Back',
    title: 'Navigating Differences in Community',
    phase: 'p6',
    parts: [
      part('Part 1 — Living Together Without Thinking the Same', [
        b('Communities sound nice until people disagree.', '社群聽起來都很好，直到大家開始不同意。'),
        a('Exactly, and that is why disagreement is not a side issue. It is part of whether a community can stay real and stay intact.', '沒錯，所以意見不同不是旁枝小事。它本來就是社群能不能保持真實、又保持完整的一部分。', 'stay intact', '即使有摩擦，群體仍然沒有碎掉'),
        b('So the goal is not perfect agreement.', '所以目標不是所有人都完全同意。'),
        a('Not at all. The goal is to build enough trust and process that disagreement does not automatically become damage.', '完全不是。目標是建立足夠的信任和流程，讓不同意不會自動變成傷害。', 'fair process', '讓不同立場的人都覺得程序合理的討論方式'),
        b('That sounds hard in real life.', '這在現實裡聽起來很難。'),
        a('It is hard, especially when people care deeply. But care is not the problem. The problem is when care becomes contempt.', '它本來就難，尤其是當大家都很在乎的時候。但在乎本身不是問題；問題是當在乎變成輕蔑。', 'care without contempt', '很在乎，但不因不同意就看不起對方'),
        b('That line says a lot.', '這句真的講很多。'),
        a('Many community conflicts get worse the moment one side stops believing the other side is acting in good faith.', '很多社群衝突變糟的瞬間，就是其中一方開始不相信另一方有基本善意的時候。', 'good-faith assumption', '先假設對方至少不是故意惡意而來'),
      ]),
      part('Part 2 — What Helps When Tension Rises', [
        b('What helps most when community tension rises?', '當社群裡的張力升高時，最有幫助的是什麼？'),
        a('Clear boundaries and a clear process. People do better when they know what is allowed, what is not, and how the conversation will move.', '清楚的界線和清楚的流程。當人知道什麼可以、什麼不行、以及對話會怎麼走，他通常會表現得比較好。', 'clear boundary', '先說清楚討論的界線和底線'),
        b('So structure is calming.', '所以結構本身就有安定效果。'),
        a('Very much. Without structure, fear and projection rush in to fill the space.', '非常有。沒有結構時，恐懼和投射就會很快衝進來把空白填滿。', 'contain the conversation', '用結構把對話控制在可處理的範圍內'),
        b('And what about tone?', '那語氣呢？'),
        a('Tone matters because it signals whether the goal is understanding or victory. A winning tone often creates a losing community.', '語氣很重要，因為它會洩露你的目標到底是理解，還是勝利。贏面子用的語氣，常常會創造一個輸掉的社群。', 'victory tone', '把對話講成輸贏競賽的語氣'),
        b('That is painfully true on the internet too.', '這在網路上也真的準到痛。'),
        a('Yes. The more public the disagreement, the more intentional people need to be about preserving dignity on all sides.', '對。越公開的不同意，越需要人有意識地保住每一邊的尊嚴。', 'preserve dignity', '在衝突中仍保留彼此基本尊嚴'),
      ]),
      part('Part 3 — English for Respectful Disagreement', [
        b('What English is helpful when you disagree inside a community?', '如果你在社群裡要表達不同意，有哪些英文比較好用？'),
        a('A strong one is: "I see the concern differently, but I do think the concern is real." That lowers defensiveness immediately.', '一句很好用的是：「I see the concern differently, but I do think the concern is real.」這句會立刻降低防衛。', 'validate without agreeing', '承認對方在意的東西是真實的，但不等於同意全部結論'),
        b('That sounds respectful and still honest.', '這句聽起來很尊重，但也很誠實。'),
        a('Another useful line is: "Can we separate what we value from the method we prefer?" That helps when people share goals but not tactics.', '另一句也很好：「Can we separate what we value from the method we prefer?」這很適合用在價值相近、方法不同的情況。', 'separate value from method', '把共同價值和彼此偏好的做法拆開來談'),
        b('I wish more people used that sentence.', '我真希望更多人會用這句。'),
        a('If emotions are already high, try: "I want to keep this constructive, so I am going to slow down here." That helps protect the room.', '如果情緒已經起來了，可以試試：「I want to keep this constructive, so I am going to slow down here.」這句很能保住房間。', 'keep it constructive', '把對話拉回有建設性的方向'),
        b('That gives you a brake without sounding passive.', '這句像踩了煞車，但又不會顯得消極。'),
        a('Exactly. Respectful disagreement needs language that keeps both truth and relationship in view.', '沒錯。帶著尊重的不同意，需要一種同時把真相和關係都放在眼前的語言。'),
      ]),
      part('Part 4 — A Neighborhood Conflict', [
        b('Can you give me a concrete community disagreement?', '你可以給我一個具體的社群衝突例子嗎？'),
        a('Imagine a neighborhood meeting about turning an empty lot into a small garden. Some people love the idea. Others are worried about noise, parking, and maintenance.', '想像一場里民會議，大家在討論要不要把一塊空地改成小花園。有些人很喜歡，有些人卻擔心噪音、停車和後續維護。'),
        b('That sounds like exactly the kind of issue that can get personal fast.', '這就是那種很容易一下子變得很 personal 的議題。'),
        a('Exactly. A helpful leader might say, "It sounds like we all care about the neighborhood, but we are protecting different parts of it." That reframes the room.', '沒錯。這時一個有幫助的帶領者可以說：「It sounds like we all care about the neighborhood, but we are protecting different parts of it.」這句會重新框住整個房間。', 'shared concern', '彼此雖然不同意，但其實都在乎同一個整體'),
        b('Because now nobody has to be the villain.', '因為這樣一來，就不用有人被演成壞人。'),
        a('Right. Once people feel less attacked, they can start bargaining over details instead of identities.', '對。當人不再覺得自己被攻擊時，大家就有可能開始談細節，而不是開始捍衛身份。', 'detail-level problem solving', '把衝突從身份對打，拉回到具體細節的處理'),
        b('That shift alone could save a lot of communities.', '光是這個轉換，就可以救很多社群。'),
        a('It can, because many conflicts do not explode from the issue itself. They explode from the meaning people attach to the issue.', '確實可以。因為很多衝突不是從議題本身爆炸，而是從人賦予那個議題的意義爆炸。'),
      ]),
      part('Part 5 — Staying in the Community After Disagreement', [
        b('What matters after a disagreement is over?', '一場不同意結束之後，什麼最重要？'),
        a('Whether people can still remain in relationship. Community dies when every conflict becomes a permanent split.', '是彼此還能不能留在關係裡。當每一次衝突都變成永久決裂，社群就會死掉。'),
        b('So repair matters as much as the debate itself.', '所以修復和辯論本身一樣重要。'),
        a('Absolutely. People need ways to come back after tension, not only ways to argue during it.', '完全是。人需要的是在張力之後能回來的方式，不只是張力當下爭論的方式。'),
        b('That sounds like a deeper definition of community.', '這聽起來像一個更深的 community 定義。'),
        a('It is. Real community is not the absence of conflict. It is the presence of enough care, structure, and repair that conflict does not end everything.', '它本來就是。真正的社群，不是沒有衝突，而是有足夠的照顧、結構和修復，讓衝突不會變成一切的終點。'),
        b('That is a version of community I can really believe in.', '這才是我真的相信得下去的社群版本。'),
        a('Good. It is also the version that lasts longer than idealism alone.', '很好。而且這個版本，也比單靠理想主義更撐得久。'),
      ]),
    ],
    keyPhrases: [
      kp('stay intact', '即使有摩擦，群體仍然沒有碎掉', 'A healthy community can disagree and still stay intact.'),
      kp('fair process', '讓不同立場的人都覺得程序合理的討論方式', 'Fair process helped people stay engaged.'),
      kp('care without contempt', '很在乎，但不因不同意就看不起對方', 'Care without contempt is hard but necessary.'),
      kp('good-faith assumption', '先假設對方至少不是故意惡意而來', 'A good-faith assumption made the conversation possible.'),
      kp('contain the conversation', '用結構把對話控制在可處理的範圍內', 'The moderator knew how to contain the conversation.'),
      kp('preserve dignity', '在衝突中仍保留彼此基本尊嚴', 'Good leaders preserve dignity even in conflict.'),
      kp('shared concern', '彼此雖然不同意，但其實都在乎同一個整體', 'They finally recognized the shared concern underneath the argument.'),
      kp('detail-level problem solving', '把衝突從身份對打，拉回到具體細節的處理', 'Detail-level problem solving helped the group move forward.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 5,
    date: '2026-11-13',
    theme: 'Community & Giving Back',
    title: 'Technology for Social Good',
    phase: 'p6',
    parts: [
      part('Part 1 — What Social Good Technology Is Really For', [
        b('People say technology can help society, but that phrase can sound vague.', '大家常說科技可以幫助社會，但那句話有時候很空。'),
        a('It gets less vague when you ask a simple question: whose daily burden becomes lighter because of this tool?', '當你問一個很簡單的問題時，它就不空了：到底是誰的日常負擔，因為這個工具變輕了？', 'lighter burden', '因為工具設計得好，讓人的辛苦真的變少'),
        b('So the test is practical relief.', '所以測試標準是實際的減壓。'),
        a('Exactly. Social-good technology is not impressive because it is advanced. It is impressive because it becomes useful where people are already struggling.', '沒錯。為社會有益的科技，不是因為很先進才厲害，而是因為它在大家本來就很辛苦的地方變得有用。', 'practical usefulness', '工具不是炫技，而是真的能用'),
        b('That sounds much more grounded than innovation language.', '這樣聽起來比那種 innovation 語言落地多了。'),
        a('It should. Communities need fewer shiny promises and more tools that solve repeated, local problems.', '本來就該比較落地。社群真正需要的，是少一點亮晶晶的承諾，多一點能解決重複、在地問題的工具。', 'local problem solving', '針對地方上的真實小問題做出實際解法'),
        b('So technology helps most when it respects context.', '所以科技最有幫助的時候，是它尊重情境。'),
        a('Yes. A good tool fits the real life of the people using it, not only the imagination of the people building it.', '對。好工具會去貼使用者的真實生活，而不是只貼設計者的想像。', 'human fit', '工具和人的真實使用情境是貼合的'),
      ]),
      part('Part 2 — Where Good Intentions Go Wrong', [
        b('What usually goes wrong when people build technology for social good?', '大家在做 social good technology 時，最常出錯的是哪裡？'),
        a('They solve the problem they can see from far away, not the problem people actually have from close up.', '他們解決的是遠看得到的問題，而不是近看之後人真正正在面對的問題。', 'distance error', '站太遠看問題，導致解法偏掉'),
        b('So intention is not enough.', '所以只有好意根本不夠。'),
        a('Not even close. You also need listening, local partnership, and the humility to discover that your first idea may be wrong.', '差得遠了。你還需要傾聽、在地合作，以及接受自己第一個想法可能是錯的謙卑。', 'local partnership', '不是外面的人單做，而是和在地的人一起做'),
        b('That sounds slower but healthier.', '這聽起來比較慢，但也比較健康。'),
        a('It is healthier because tools fail when they ignore access, language, trust, or habit. People do not adopt what does not fit their world.', '它確實比較健康，因為工具如果忽略了使用門檻、語言、信任或習慣，就會失敗。東西不貼世界，人就不會真的用。', 'adoption barrier', '讓一個工具無法真正被使用起來的障礙'),
        b('So usefulness includes being usable in context.', '所以所謂有用，也包含它在真實情境裡用得起來。'),
        a('Exactly. Good social design respects friction instead of pretending friction is a user flaw.', '沒錯。好的社會設計會尊重摩擦，而不是把摩擦全怪到使用者頭上。', 'respect friction', '承認真實使用上會遇到的阻力，而不是假裝不存在'),
      ]),
      part('Part 3 — English for Talking About Tech and Community', [
        b('What English is useful for talking about this topic?', '如果要談這個主題，有哪些英文比較好用？'),
        a('A strong sentence is: "The tool only mattered once it reduced a real burden for real people." It keeps the focus where it belongs.', '一句很好用的是：「The tool only mattered once it reduced a real burden for real people.」這會把焦點放回該放的地方。', 'reduce a burden', '讓某個真實負擔被減輕'),
        b('That already sounds more honest than product hype.', '這句已經比很多產品宣傳誠實多了。'),
        a('Another one is: "We built this with the community, not only for the community." That signals partnership instead of savior thinking.', '另一句也很好：「We built this with the community, not only for the community.」這句會傳達 partnership，而不是救世主心態。', 'build with, not only for', '和社群一起做，不只是替社群做'),
        b('That distinction matters a lot.', '那個區別真的很重要。'),
        a('If you want something more critical, say: "A good idea failed because the access problem was bigger than the software problem." That works when context was underestimated.', '如果你想講得更批判一點，可以說：「A good idea failed because the access problem was bigger than the software problem.」這很適合用來描述情境被低估。', 'access problem', '真正卡住人的不是軟體，而是使用門檻或資源差距'),
        b('That line is useful in many projects, not only community projects.', '這句在很多專案裡都好用，不只是社群專案。'),
        a('Exactly. Technology becomes wiser when it stops confusing possibility with reality.', '沒錯。當科技不再把「做得到」和「現實裡用得起來」混為一談時，它就會更聰明。'),
      ]),
      part('Part 4 — A Simple Example That Matters', [
        b('Can you give me a simple example of technology helping a community?', '你可以給我一個簡單但有感的例子嗎？'),
        a('Imagine a neighborhood group that keeps missing important updates because older residents do not use the main app everyone else uses.', '想像一個社區群體一直漏掉重要通知，因為年長住戶根本不用大家常用的那個 app。'),
        b('That feels like a very normal problem.', '這真的很像一個超正常的問題。'),
        a('A useful response might be a simple bilingual SMS system, not a more complicated platform. Sometimes the best tech choice is the least flashy one.', '一個有用的回應可能是很簡單的雙語簡訊系統，而不是更複雜的平台。有時候最好的科技選擇，反而是最不花俏的那個。', 'least flashy solution', '不是最炫，但最貼近需求的解法'),
        b('So good design is often humble.', '所以好的設計很多時候是謙卑的。'),
        a('Yes. It asks what people can already reach, understand, and trust, then builds from there.', '對。它會先問：人們目前碰得到、看得懂、信得過的是什麼，然後再從那裡開始蓋。', 'build from what exists', '先從現有可行的條件出發，而不是強迫大家跳很遠'),
        b('That sounds much more respectful to the community.', '這樣真的對社群尊重多了。'),
        a('And respect is often the difference between adoption and abandonment.', '而尊重，常常就是「被採用」和「被放棄」之間的差別。'),
      ]),
      part('Part 5 — Technology That Deserves Trust', [
        b('What makes a piece of technology deserve trust?', '什麼樣的科技，才算真的值得被信任？'),
        a('It should make life more navigable without making people feel extracted, confused, or talked down to.', '它應該讓生活變得更可走，而不是讓人覺得自己被利用、被搞混，或被居高臨下地對待。'),
        b('So dignity is part of design too.', '所以尊嚴也是設計的一部分。'),
        a('Absolutely. Especially in community settings, the best tools protect dignity while increasing access and clarity.', '完全是。尤其在社群場景裡，最好的工具會一邊保護尊嚴，一邊增加可近性和清楚度。'),
        b('That feels like a better definition of progress.', '這感覺像一個更好的 progress 定義。'),
        a('It is a better definition, because progress should not only make systems more efficient. It should make people feel more reachable inside those systems too.', '它確實更好，因為 progress 不應該只讓系統變得更有效率；它也應該讓人覺得自己在系統裡比較碰得到路。'),
        b('That is the kind of technology I want more of.', '這就是我想看到更多的那種科技。'),
        a('Then keep asking the human question first. It usually leads to better tools than the technical question alone.', '那就把人的問題放在最前面。它通常會帶你做出比單純技術問題更好的工具。'),
      ]),
    ],
    keyPhrases: [
      kp('lighter burden', '因為工具設計得好，讓人的辛苦真的變少', 'The app mattered because it created a lighter burden.'),
      kp('practical usefulness', '工具不是炫技，而是真的能用', 'Practical usefulness mattered more than novelty.'),
      kp('human fit', '工具和人的真實使用情境是貼合的', 'The project worked because the design had human fit.'),
      kp('local partnership', '不是外面的人單做，而是和在地的人一起做', 'Local partnership changed the whole design process.'),
      kp('adoption barrier', '讓一個工具無法真正被使用起來的障礙', 'They finally identified the real adoption barrier.'),
      kp('build with, not only for', '和社群一起做，不只是替社群做', 'Their best principle was to build with, not only for.'),
      kp('access problem', '真正卡住人的不是軟體，而是使用門檻或資源差距', 'The access problem was bigger than the technical one.'),
      kp('least flashy solution', '不是最炫，但最貼近需求的解法', 'The least flashy solution turned out to be the best one.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 6,
    date: '2026-11-14',
    theme: 'Community & Giving Back',
    title: 'Generations of Service',
    phase: 'p6',
    parts: [
      part('Part 1 — Service That Gets Passed Down', [
        b('Do you think service can be passed down across generations?', '你覺得服務他人的習慣，會一代一代傳下去嗎？'),
        a('Definitely. Many people first learn service not as a principle, but as something they watched an older person quietly do again and again.', '一定會。很多人第一次學會服務，不是靠道理，而是一直看著某個長輩安靜地做同一件事。', 'passed-down care', '一代代傳下來的照顧方式與服務習慣'),
        b('So values are often learned through observation.', '所以價值很多時候是靠看見，不是靠被教導。'),
        a('Exactly. A child may not remember the speech, but they remember who delivered meals, who checked on neighbors, and who made room at the table.', '沒錯。小孩也許不記得那些大道理，但會記得誰送飯、誰去關心鄰居、誰在餐桌邊多留了一個位置。', 'observed value', '不是聽來的，而是看著大人怎麼做而學到的價值'),
        b('That makes service feel very embodied.', '這樣一來，服務就變得很有身體感。'),
        a('It is embodied. We often inherit care through gestures, routines, and tone long before we inherit it through language.', '它本來就很有身體感。很多時候，我們繼承的是動作、日常習慣和語氣，語言反而比較慢。', 'care routine', '會反覆出現、變成習慣的照顧行動'),
        b('So service becomes part of family culture.', '所以服務最後會變成家庭文化的一部分。'),
        a('Yes, and when that happens, people start seeing care as normal rather than exceptional.', '對。而當那件事發生時，人就會把照顧別人看成正常，不是特別偉大才做的事。', 'normal care', '把照顧別人視為日常，不是只有特殊時刻才出現'),
      ]),
      part('Part 2 — What Different Generations Bring', [
        b('What do different generations bring to service work?', '不同世代在服務裡，各自會帶來什麼？'),
        a('Older generations often bring patience, long memory, and knowledge of how the community has changed over time.', '比較年長的一代，常常會帶來耐心、長期記憶，以及對社區變化脈絡的理解。', 'long memory', '記得一個地方過去怎麼走到現在的能力'),
        b('And younger generations?', '那比較年輕的一代呢？'),
        a('Younger people often bring speed, new tools, and a willingness to question habits that no longer work.', '年輕一代常常帶來速度、新工具，以及願意去挑戰那些已經失效的舊習慣。', 'fresh energy', '比較新的動能、速度與改變意願'),
        b('So the best service work probably needs both.', '所以最好的服務工作，可能其實兩邊都需要。'),
        a('Exactly. Wisdom without energy can stall. Energy without wisdom can repeat old mistakes. Together, they can make something much stronger.', '沒錯。只有智慧沒有動能，事情會停住；只有動能沒有智慧，又很容易重犯舊錯。兩者放在一起，才會變得更強。', 'intergenerational strength', '不同世代合作時產生的互補力量'),
        b('That is a very hopeful picture.', '這是一個很有希望的畫面。'),
        a('It is hopeful because it reminds people that service does not have to belong to one age group or one style.', '它之所以讓人有希望，是因為它提醒了大家：服務不必屬於某一個年齡層，也不必只長成某一種樣子。'),
      ]),
      part('Part 3 — English for Talking About Generational Service', [
        b('What English is useful for this topic?', '談這個主題時，有哪些英文比較好用？'),
        a('You can say, "I learned service by watching how the older people around me treated everyday responsibilities." That sounds natural and personal.', '你可以說：「I learned service by watching how the older people around me treated everyday responsibilities.」這句很自然，也很個人。', 'learn by watching', '不是被講道理，而是透過觀察學會'),
        b('That feels warmer than just saying "They taught me."', '這句比單純說「They taught me」更有溫度。'),
        a('Another useful line is: "Different generations carry different strengths, and good communities know how to combine them." That works well when you want a broader point.', '另一句也很好：「Different generations carry different strengths, and good communities know how to combine them.」如果你想講更大的觀察，這句很好用。', 'combine strengths', '把不同人的優勢放在一起使用'),
        b('That would sound good in a speech or conversation.', '這句不管在演講還是對話裡都很好用。'),
        a('If you want something more emotional, say, "I did not realize I was inheriting a way of caring until I caught myself doing the same thing."', '如果你想講得更有情感，可以說：「I did not realize I was inheriting a way of caring until I caught myself doing the same thing.」', 'inherit a way of caring', '在不知不覺中接下了某種照顧人的方式'),
        b('That line really lands.', '這句真的很有感。'),
        a('It lands because many people have lived that exact realization.', '它之所以有感，是因為很多人真的活過那種瞬間。'),
      ]),
      part('Part 4 — A Family Example', [
        b('Can you give me a family example of service passing down?', '你可以給我一個家庭裡服務傳承的例子嗎？'),
        a('Sure. Imagine a grandmother who always makes one extra portion of food because "someone may need it later." The family grows up watching that.', '可以。想像一個奶奶總是多煮一份飯，因為她會說「晚一點可能有人需要」。全家就是在看著這件事長大的。'),
        b('That is such a simple but powerful image.', '這個畫面很簡單，但很有力量。'),
        a('Years later, one grandchild starts doing the same thing for a stressed roommate or a friend after surgery. That is how care travels.', '幾年後，其中一個孫子開始對很累的室友，或剛開完刀的朋友做一樣的事。照顧就是這樣在移動。', 'care travels', '一種照顧方式從一個人移到另一個人身上'),
        b('So the lesson was stored in the body, not only in the memory.', '所以那個 lesson 是存進身體裡了，不只是存進記憶裡。'),
        a('Exactly. Repeated acts become muscle memory for kindness.', '沒錯。重複的動作，最後會變成善意的肌肉記憶。', 'kindness muscle memory', '因為長期做而變得很自然的善意行動'),
        b('That makes service feel less like a program and more like a lineage.', '這樣一來，服務就不像一個 program，比較像一條傳承。'),
        a('That is a beautiful way to say it.', '你這個說法很美。'),
      ]),
      part('Part 5 — What We Choose to Pass On', [
        b('So what matters most if we want to pass service on well?', '如果我們想把服務的精神好好傳下去，最重要的是什麼？'),
        a('Living it in small repeatable ways. Big speeches fade fast. Small repeated actions quietly teach people what matters.', '是在小而可重複的地方把它活出來。大的演講很快就會散，小而持續的行動才會安靜地教人什麼重要。'),
        b('So the message has to be visible in behavior.', '所以那個訊息得先在行為裡看得見。'),
        a('Yes, and it helps to explain the meaning too. People inherit values more deeply when they know not only what to do, but why it matters.', '對，而且把意義說出來也有幫助。當人不只知道怎麼做，也知道為什麼重要時，價值會傳得更深。'),
        b('That makes the transmission more conscious.', '這樣那個傳承就會更有意識。'),
        a('Exactly. We do not control everything the next generation keeps, but we can offer them patterns worth inheriting.', '沒錯。我們不能控制下一代會留下什麼，但我們可以提供一些值得被繼承的模式。'),
        b('That is a hopeful responsibility.', '那是一種很有希望的責任。'),
        a('It is, and communities get stronger whenever people take that responsibility seriously.', '它確實是。而每當有人認真看待這份責任，社群就會變得更強。'),
      ]),
    ],
    keyPhrases: [
      kp('passed-down care', '一代代傳下來的照顧方式與服務習慣', 'Passed-down care shaped how he treated other people.'),
      kp('observed value', '不是聽來的，而是看著大人怎麼做而學到的價值', 'That value was observed long before it was explained.'),
      kp('care routine', '會反覆出現、變成習慣的照顧行動', 'A care routine can shape a whole family culture.'),
      kp('long memory', '記得一個地方過去怎麼走到現在的能力', 'Her long memory helped the younger volunteers avoid old mistakes.'),
      kp('fresh energy', '比較新的動能、速度與改變意願', 'Fresh energy helped the project grow.'),
      kp('intergenerational strength', '不同世代合作時產生的互補力量', 'The program succeeded because of intergenerational strength.'),
      kp('inherit a way of caring', '在不知不覺中接下了某種照顧人的方式', 'She inherited a way of caring from her aunt.'),
      kp('kindness muscle memory', '因為長期做而變得很自然的善意行動', 'Kindness muscle memory showed up in the smallest gestures.'),
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 7,
    date: '2026-11-15',
    theme: 'Community & Giving Back',
    title: 'This Week\'s Reflections',
    phase: 'p6',
    parts: [
      part('Part 1 — Looking Back on What Community Really Means', [
        b('After a week like this, what idea stays with you most?', '像這樣一週走下來，最留在你心裡的是哪個想法？'),
        a('That community is not only a group of people. It is a pattern of how people keep life possible for one another.', '我最留下來的是：社群不只是一群人，它其實是一種模式，一種彼此讓生活還能繼續下去的方式。', 'keep life possible', '彼此支撐，讓日子繼續過得下去'),
        b('That sounds bigger than friendship.', '這聽起來比 friendship 還更大。'),
        a('It is bigger, because community includes systems, habits, memory, and practical care. It is built into ordinary life.', '它確實更大，因為 community 包含系統、習慣、記憶，以及實際照顧。它是被蓋進普通生活裡的。', 'ordinary infrastructure of care', '存在於日常裡、支撐人生活的照顧網'),
        b('So you notice it most when it works or when it breaks.', '所以你最容易注意到它，通常是在它運作得很好，或整個壞掉的時候。'),
        a('Exactly. Good community often feels invisible because it quietly prevents collapse.', '沒錯。好的社群常常很隱形，因為它安靜地防止崩塌。', 'prevent collapse', '用很多小支撐避免事情整個垮掉'),
        b('That is such a strong image.', '這個畫面真的很強。'),
        a('It is the image I trust most when I think about what giving back really means.', '這也是我在想 give back 真正是什麼時，最相信的一個畫面。'),
      ]),
      part('Part 2 — Receiving Help Can Change a Person Too', [
        b('We often focus on giving help, but what about receiving it?', '我們很常講幫助別人，可是被幫助本身呢？'),
        a('Receiving help can change a person deeply, especially if they are used to surviving alone.', '被幫助會很深地改變一個人，尤其是那些已經習慣一個人撐的人。', 'receive help well', '能夠接受幫忙，而不是把所有支持都推開'),
        b('Why is it so hard for many people?', '為什麼對很多人來說，那麼難？'),
        a('Because help can trigger shame, debt, or fear of becoming a burden. Community becomes healing when it makes help feel human, not humiliating.', '因為被幫忙會勾起羞愧、虧欠感，或害怕自己成為負擔。當社群能讓幫忙感覺像人和人之間，而不是羞辱，事情就會變得有療癒性。', 'help without humiliation', '讓幫助發生時，不讓人覺得自己被看低'),
        b('That sounds like a very important skill for communities.', '這聽起來像社群很重要的一項能力。'),
        a('It is. Good communities know how to offer support in ways that preserve dignity and choice.', '確實是。好的社群知道怎麼提供支持，同時保住一個人的尊嚴和選擇權。', 'preserve choice', '在提供幫助時，仍保留對方的自主感'),
        b('So help should not feel like being trapped.', '所以幫助不應該讓人感覺自己被困住。'),
        a('Exactly. The best support says, "You are still fully a person here, even while you need something."', '沒錯。最好的支持會傳遞一句話：「就算你現在需要幫忙，你在這裡仍然完整是一個人。」'),
      ]),
      part('Part 3 — English for Reflecting on the Week', [
        b('What English can I use if I want to reflect on this topic personally?', '如果我想很個人地反思這個主題，可以用哪些英文？'),
        a('Try: "This week reminded me that support is often made of small practical acts, not grand gestures." It sounds thoughtful and clear.', '你可以試試：「This week reminded me that support is often made of small practical acts, not grand gestures.」這句很清楚，也很有反思感。', 'small practical acts', '不是誇張的大動作，而是日常真的有幫助的小事'),
        b('That line feels easy to use right away.', '這句感覺我現在就能拿來用。'),
        a('Another one is: "I used to think community was a nice idea. Now I think it is a survival structure." That works if your view has changed.', '另一句也很好：「I used to think community was a nice idea. Now I think it is a survival structure.」如果你的看法真的改變了，這句很適合。', 'survival structure', '不是抽象概念，而是讓人活得下去的支撐結構'),
        b('That sentence sounds strong in a good way.', '這句的力道很好。'),
        a('And if you want to keep it simple, say: "What helped me most was not advice. It was knowing I was not alone." That often lands.', '如果你想更簡單一點，也可以說：「What helped me most was not advice. It was knowing I was not alone.」這句通常很能打到人。', 'not alone in it', '知道自己不是一個人面對這件事'),
        b('Yes, that one definitely lands.', '對，這句真的很有感。'),
        a('Because many people are not starving for solutions first. They are starving for shared reality.', '因為很多人最缺的，不是解法，而是有人和自己一起承認現實。'),
      ]),
      part('Part 4 — What Giving Back Can Look Like Now', [
        b('After a week like this, what does giving back look like in a realistic way?', '像這樣一週走下來，現實裡的 give back 可以長什麼樣？'),
        a('It may look smaller than people expect. Checking in consistently, sharing useful information, volunteering one hour well, or making one process easier for others.', '它可能比很多人想像的小。像是穩定地關心、分享有用資訊、把一個小時的志工時間做好，或讓別人的某個流程稍微更容易。', 'realistic contribution', '不誇大自己，但真實有幫助的付出'),
        b('So contribution does not have to be dramatic to count.', '所以 contribution 不必很戲劇化，才算數。'),
        a('Not at all. Communities often improve through accumulation, not spectacle.', '完全不用。社群很多時候是靠累積變好，不是靠表演。', 'quiet accumulation', '很多小的付出慢慢累積成真正的改變'),
        b('That makes participation feel more possible.', '這樣一來，參與就感覺比較做得到。'),
        a('Good. People are more likely to help when helping feels sustainable and real.', '很好。當幫忙聽起來可持續、也很真實時，人反而更可能真的出手。', 'sustainable help', '一個人做得久、做得下去的幫忙方式'),
        b('So the goal is not to be impressive. It is to be reliable.', '所以重點不是讓自己很厲害，而是讓自己很可靠。'),
        a('Exactly. Reliable people are part of what makes any community feel safe.', '沒錯。可靠的人，本來就是任何社群安全感的一部分。'),
      ]),
      part('Part 5 — A Future Built Together', [
        b('What kind of future does a strong community create?', '強的社群，會創造出什麼樣的未來？'),
        a('A future where fewer people fall through alone, and more people know that asking, offering, and receiving are all part of being human.', '是一個比較少人會獨自掉下去、而更多人知道求助、給予和接受，本來都是人性一部分的未來。'),
        b('That sounds both practical and hopeful.', '這聽起來既實際，又有希望。'),
        a('It is hopeful because community does not ask us to become perfect. It only asks us to become more available to one another.', '它之所以有希望，是因為 community 不要求我們變得完美；它只是邀請我們對彼此更在場一點。'),
        b('That feels like a way of living, not just a topic.', '這聽起來像一種生活方式，不只是課題。'),
        a('Exactly. The best topics in an English app should connect back to life, and this one very clearly does.', '沒錯。英語 app 最好的主題，本來就應該能接回生活，而這個主題就是非常清楚地能。'),
        b('I can feel that after this week.', '經過這一週，我真的感覺得到。'),
        a('Good. That means the language is no longer floating above life. It is starting to live inside it.', '很好。那代表語言不再飄在生活上面，而是開始住進生活裡了。'),
      ]),
    ],
    keyPhrases: [
      kp('keep life possible', '彼此支撐，讓日子繼續過得下去', 'Communities keep life possible in quiet ways.'),
      kp('ordinary infrastructure of care', '存在於日常裡、支撐人生活的照顧網', 'A city needs an ordinary infrastructure of care.'),
      kp('receive help well', '能夠接受幫忙，而不是把所有支持都推開', 'Learning to receive help well took time for him.'),
      kp('help without humiliation', '讓幫助發生時，不讓人覺得自己被看低', 'Good communities offer help without humiliation.'),
      kp('small practical acts', '不是誇張的大動作，而是日常真的有幫助的小事', 'Small practical acts often mean the most.'),
      kp('survival structure', '不是抽象概念，而是讓人活得下去的支撐結構', 'For many people, community became a survival structure.'),
      kp('quiet accumulation', '很多小的付出慢慢累積成真正的改變', 'Social change often grows through quiet accumulation.'),
      kp('sustainable help', '一個人做得久、做得下去的幫忙方式', 'Sustainable help matters more than heroic burnout.'),
    ],
  },
]
