import { Episode } from '../../app/src/data/episode-sample'

export const WEEK_20: Episode[] = [
  {
    weekNumber: 20,
    dayOfWeek: 1,
    date: '2026-05-11',
    theme: 'Meetings & Discussions',
    title: "Let's Meet: Navigating Work Meetings",
    phase: 'p3',
    parts: [
      {
        title: 'Why Meetings Matter',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: "Meetings are one of those things everyone complains about, but they're hard to live without.", zh: '會議是那種每個人都會抱怨，但又很難完全沒有的東西。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. Too many bad meetings and people start to wonder if anything is getting done.', zh: '沒錯。糟糕的會議一多，大家就會開始懷疑工作到底有沒有真的在推進。' },
          { speaker: 'a', speakerName: 'Sara', en: 'What makes a meeting worth having, in your view?', zh: '在你看來，什麼樣的會議才算值得開？', vocab: [{ word: 'worth having', def: '值得花時間召開的' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'It needs a clear purpose. Are we making a decision, sharing updates, or brainstorming?', zh: '它一定要有清楚目的。是要做決定、同步資訊，還是腦力激盪？', vocab: [{ word: 'brainstorming', def: '腦力激盪' }] },
          { speaker: 'a', speakerName: 'Sara', en: "If you don't know why you're meeting, you probably don't need to meet.", zh: '如果你根本說不清楚為什麼要開會，那很可能就不需要開。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That rule would save a lot of people a lot of time.', zh: '如果大家真的照這個原則走，應該能救回很多時間。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Still, some topics do need real-time conversation.', zh: '不過有些議題，還是得靠即時對話來處理。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Sensitive issues, tradeoffs, and team dynamics are hard to solve through email alone.', zh: '像敏感議題、取捨判斷，還有團隊互動這些，通常很難只靠 email 解決。', vocab: [{ word: 'team dynamics', def: '團隊互動方式與氣氛' }] },
        ],
      },
      {
        title: 'Before the Meeting',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Good meetings actually start before the meeting begins.', zh: '好的會議，其實在會議開始之前就已經開始了。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. Preparation changes the quality of the whole room.', zh: '對。準備程度，會直接改變整個會議室的品質。' },
          { speaker: 'a', speakerName: 'Sara', en: 'An agenda helps a lot because people know what kind of thinking is needed.', zh: '議程很重要，因為它會讓大家知道自己要帶著什麼樣的思考進來。', vocab: [{ word: 'agenda', def: '議程' }] },
          { speaker: 'b', speakerName: 'Alex', en: "I also think materials should be sent early if people are expected to react thoughtfully.", zh: '如果真的期待大家有品質地回應，那資料也應該提前發。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Surprise documents usually lead to shallow discussion.', zh: '沒錯。會上才第一次看到文件，通常只會帶來很淺的討論。', vocab: [{ word: 'shallow discussion', def: '沒有足夠思考深度的討論' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And it also helps to know your role before you walk in.', zh: '而且進會議前先知道自己的角色，也非常重要。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Are you there to decide, to advise, or just to listen and learn?', zh: '你是要做決定、給建議，還是單純聽和吸收？' },
          { speaker: 'b', speakerName: 'Alex', en: 'That one detail can change how confidently someone participates.', zh: '這個小細節，往往就會決定一個人參與時有多穩。' },
        ],
      },
      {
        title: 'Speaking Up in Meetings',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'A lot of people know what they think, but still struggle to speak up in a meeting.', zh: '很多人其實心裡有想法，但到了會議裡還是很難開口。', vocab: [{ word: 'speak up', def: '在群體中開口表達' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Especially in larger groups. It is easy to feel that your comment will slow things down.', zh: '尤其在大團體裡，很容易覺得自己一開口就會拖慢節奏。' },
          { speaker: 'a', speakerName: 'Sara', en: 'But when everyone waits, only the fastest or loudest voices shape the conversation.', zh: '可是如果每個人都這樣等，最後對話就只會被最快或最大聲的人主導。' },
          { speaker: 'b', speakerName: 'Alex', en: `"Can I add one point?" is a very useful sentence for entering politely.`, zh: '像「Can I add one point?」這種話，就是很實用的禮貌切入句。', vocab: [{ word: 'add one point', def: '補充一個觀點' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'I also like writing down one sentence before speaking, especially in English.', zh: '我也很喜歡先把一句核心意思寫下來，尤其用英文開會時特別有幫助。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That lowers the mental pressure. You are not inventing your thought at the same time you are saying it.', zh: '那會降低腦內壓力，因為你不是一邊想、一邊硬講出來。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Prepared clarity often sounds more confident than spontaneous complexity.', zh: '沒錯。事先整理過的清楚感，常常比臨場講得很複雜更有自信。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And confidence in meetings is often just good preparation in disguise.', zh: '很多時候，會議裡的自信，其實只是準備得好而已。' },
        ],
      },
      {
        title: 'Running a Meeting Well',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Running a meeting well is a separate skill from just having a lot to say.', zh: '把會議帶得好，是一種獨立能力，不等於你只是很有東西可講。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Definitely. A good meeting lead watches time, energy, and clarity at the same time.', zh: '真的。好的主持人，會同時看時間、氣氛，還有整體清楚度。', vocab: [{ word: 'meeting lead', def: '主持或帶領會議的人' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Starting on time matters more than people think.', zh: '準時開始，比很多人想的還重要。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes, because it signals that people’s time is being respected.', zh: '對，因為那會傳遞出一個訊息：大家的時間是被尊重的。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And when the discussion wanders, someone has to bring it back without sounding controlling.', zh: '而且當討論開始飄走時，也需要有人把它拉回來，但又不能聽起來像在硬壓。' },
          { speaker: 'b', speakerName: 'Alex', en: `"Let's come back to the decision we need to make" is a helpful phrase.`, zh: '像「我們先回到今天要做的決定」這種句子就很好用。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That keeps the meeting focused while staying respectful.', zh: '那會讓會議保持聚焦，同時又不失禮。', vocab: [{ word: 'stay focused', def: '維持聚焦' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And if the meeting ends without action items, it usually was not specific enough.', zh: '而如果會議結束時沒有明確行動項目，通常就表示討論還不夠具體。', vocab: [{ word: 'action items', def: '會後的明確行動事項' }] },
        ],
      },
      {
        title: 'Virtual Meetings',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Online meetings changed a lot about how teams communicate.', zh: '線上會議真的改變了團隊溝通的很多細節。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. They are efficient in some ways, but they also remove a lot of natural human cues.', zh: '對。它們在某些方面很有效率，但也拿掉了很多自然的人際訊號。', vocab: [{ word: 'cues', def: '訊號、線索' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'It is harder to read energy, timing, and hesitation on a screen.', zh: '在螢幕上要讀懂氣氛、節奏，還有一個人的猶豫，本來就更難。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is why small habits matter so much online. Muting, pausing, and naming who should speak next all help.', zh: '所以在線上，小習慣反而特別重要。像是靜音、停頓，還有清楚點名下一位發言者，都很有幫助。' },
          { speaker: 'a', speakerName: 'Sara', en: 'I also think summaries matter more in virtual meetings because attention slips faster.', zh: '我也覺得，線上會議裡的總結更重要，因為大家注意力比較容易滑掉。', vocab: [{ word: 'attention slips', def: '注意力滑走、分散' }] },
          { speaker: 'b', speakerName: 'Alex', en: `"So far, here's what we've agreed on" is a very stabilizing sentence.`, zh: '像「到目前為止，我們已經同意的是這些」這種句子，就會很穩。' },
          { speaker: 'a', speakerName: 'Sara', en: 'It gives the group a shared map again.', zh: '那會讓整個群體重新拿回同一張地圖。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And in any meeting, shared clarity is half the work.', zh: '而在任何會議裡，共享的清楚感，本來就完成了一半的工作。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'worth having', zh: '值得召開的', example: 'A meeting is worth having only if the purpose is clear.' },
      { en: 'agenda', zh: '議程', example: 'Please read the agenda before the meeting starts.' },
      { en: 'speak up', zh: '開口表達', example: 'I know it is hard, but try to speak up early in the meeting.' },
      { en: 'action items', zh: '行動事項', example: 'Good meetings end with clear action items.' },
      { en: 'team dynamics', zh: '團隊互動狀態', example: 'Some team dynamics are easier to discuss live than by email.' },
      { en: 'shallow discussion', zh: '沒有深度的討論', example: 'Without preparation, meetings often lead to shallow discussion.' },
      { en: 'meeting lead', zh: '會議主持人', example: 'A skilled meeting lead protects both time and clarity.' },
      { en: 'stay focused', zh: '維持聚焦', example: 'Someone has to help the group stay focused.' },
      { en: 'attention slips', zh: '注意力開始滑走', example: 'In online meetings, attention slips faster than people realize.' },
      { en: 'shared clarity', zh: '共享的清楚感', example: 'Shared clarity is one of the most valuable outcomes of a meeting.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 2,
    date: '2026-05-12',
    theme: 'Meetings & Discussions',
    title: 'Preparing for Meetings That Matter',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Preparation Changes Everything',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Some meetings fail before they even begin.', zh: '有些會議，其實在開始之前就已經注定要失敗了。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Usually because nobody knows why they are there or what kind of input is needed.', zh: '通常就是因為沒有人真的知道自己為什麼在那裡，或需要帶著什麼樣的意見進來。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why preparation matters so much. It is not just admin work.', zh: '所以事前準備真的很重要，它不只是行政工作而已。', vocab: [{ word: 'admin work', def: '行政性、看似瑣碎的準備工作' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Right. Preparation shapes the quality of the thinking that happens in the room.', zh: '對。準備的程度，會直接影響會議裡能出現多好的思考。' },
          { speaker: 'a', speakerName: 'Sara', en: 'A clear agenda is the first sign that someone respects everyone’s time.', zh: '一份清楚的議程，往往就是「有人在尊重大家時間」的第一個訊號。', vocab: [{ word: 'respect everyone’s time', def: '重視每個人的時間成本' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And it lowers stress too, because people walk in knowing what they are walking into.', zh: '而且它也會降低壓力，因為大家進去之前就知道自己要面對什麼。' },
        ],
      },
      {
        title: 'Part 2 — What to Review Beforehand',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'When you prepare for an important meeting, what do you review first?', zh: '如果你要準備一場重要會議，你通常最先看什麼？' },
          { speaker: 'a', speakerName: 'Sara', en: 'I start with the purpose, then the documents, then the decision points.', zh: '我通常先看目的，再看文件，最後抓出哪些點是要做決定的。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That order makes sense. If you start with the documents but not the purpose, you can get lost in detail.', zh: '這個順序很合理。如果先埋進文件、卻沒先抓目的，很容易在細節裡迷路。', vocab: [{ word: 'decision points', def: '需要做決定的關鍵點' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. I also like to mark what is still unclear before the meeting starts.', zh: '沒錯。而且我也會先標出自己還不清楚的地方。' },
          { speaker: 'b', speakerName: 'Alex', en: 'So you walk in with questions, not just information.', zh: '所以你進會議時，帶進去的不只是資訊，也包括問題。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. That makes participation much more active.', zh: '對。這樣參與起來就會主動很多。' },
        ],
      },
      {
        title: 'Part 3 — Preparing to Speak',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'A lot of people prepare by reading, but not by preparing how they will speak.', zh: '很多人準備會議時只會讀資料，卻不會準備自己要怎麼講。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is true. Then they understand the issue, but still freeze when it is their turn.', zh: '真的。所以他們明明懂內容，輪到自己講時卻還是會卡住。', vocab: [{ word: 'freeze', def: '在壓力下突然卡住' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'I usually write one or two key sentences before the meeting if I know I need to contribute.', zh: '如果我知道自己會需要發言，我通常會先寫一兩句關鍵句。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is smart. It gives you a stable starting point.', zh: '這很聰明。這樣你在現場就會有一個穩定的起點。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Especially in English, a prepared opening sentence can calm the whole body down.', zh: '尤其用英文時，先準備好開頭那一句，真的會讓整個人安定很多。', vocab: [{ word: 'opening sentence', def: '準備好的開頭句' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And once you get started well, the rest usually comes more easily.', zh: '而且一旦起頭起得穩，後面通常就會順很多。' },
        ],
      },
      {
        title: 'Part 4 — Knowing Your Goal',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'Do you think people should enter a meeting with a personal goal too?', zh: '你覺得一個人進會議前，也應該替自己設定一個個人目標嗎？' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes, even a small one. It could be to ask one useful question or to clarify one major risk.', zh: '我覺得要，就算只是很小的目標也可以。像是問出一個有用問題，或釐清一個主要風險。', vocab: [{ word: 'clarify a risk', def: '把風險說清楚' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'That makes the meeting feel less passive.', zh: '這會讓會議比較不像只是被動地坐在那裡。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Without an internal goal, it is easy to drift.', zh: '沒錯。沒有內在目標時，人很容易就漂走。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And it probably helps quieter people participate more intentionally too.', zh: '而且這應該也會幫助比較安靜的人更有意識地參與。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Definitely. Intention often gives people more courage than confidence does.', zh: '一定會。有時候，比起自信，真正給人勇氣的是明確的意圖。' },
        ],
      },
      {
        title: 'Part 5 — Meetings Go Better When People Arrive Ready',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'So in the end, good preparation is not really about being impressive. It is about being useful.', zh: '說到底，好的準備其實不是為了讓自己看起來很厲害，而是為了讓自己真的有用。' },
          { speaker: 'b', speakerName: 'Alex', en: 'I like that. Prepared people make meetings lighter for everyone else too.', zh: '我喜歡這個說法。準備好的人，也會讓整個會議對其他人來說輕鬆很多。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. They ask better questions, make clearer points, and waste less group energy.', zh: '對。他們會問出更好的問題、講出更清楚的觀點，也更少浪費團體能量。', vocab: [{ word: 'group energy', def: '整體團隊可用的注意力與精力' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'That makes preparation sound less like homework and more like respect.', zh: '這樣一說，準備就比較不像作業，反而更像一種尊重。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Good meetings are rarely accidental.', zh: '正是。好的會議很少是碰巧發生的。' },
          { speaker: 'b', speakerName: 'Alex', en: 'They usually come from people arriving ready.', zh: '它們通常來自一群有備而來的人。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'have a clear agenda', zh: '有清楚議程', example: 'Every important meeting should have a clear agenda.' },
      { en: 'decision points', zh: '決策點', example: 'I highlight the decision points before the meeting starts.' },
      { en: 'prepare how you will speak', zh: '準備自己要怎麼講', example: 'Do not only read the slides. Prepare how you will speak.' },
      { en: 'opening sentence', zh: '開頭關鍵句', example: 'A prepared opening sentence can reduce anxiety in English meetings.' },
      { en: 'personal goal', zh: '個人目標', example: 'I go into meetings with one personal goal in mind.' },
      { en: 'clarify a risk', zh: '釐清風險', example: 'My goal in the meeting was to clarify a risk.' },
      { en: 'arrive ready', zh: '有備而來', example: 'Discussions go better when everyone arrives ready.' },
      { en: 'group energy', zh: '團體能量', example: 'Clear thinking helps protect group energy.' },
      { en: 'less like homework, more like respect', zh: '不像作業，更像尊重', example: 'Preparation is less like homework and more like respect.' },
      { en: 'not accidental', zh: '不是碰巧發生的', example: 'Strong meetings are usually not accidental.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 3,
    date: '2026-05-13',
    theme: 'Meetings & Discussions',
    title: 'Speaking Up Without Sounding Aggressive',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Why Speaking Up Feels Hard',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'A lot of professionals are caught between two fears in meetings.', zh: '很多職場人其實都卡在兩種害怕之間。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Being too quiet on one side and sounding too aggressive on the other?', zh: '一邊怕自己太安靜，一邊又怕一開口就顯得太強勢？' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. And that tension makes people hesitate even when they have something useful to say.', zh: '沒錯。這種拉扯，常常會讓人就算有好內容也不敢講。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Especially in English, where tone can be harder to judge in real time.', zh: '尤其用英文時更明顯，因為你很難在當下精準判斷自己的語氣。', vocab: [{ word: 'in real time', def: '在當下、即時地' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why useful sentence patterns matter so much.', zh: '所以固定好用的句型，才會那麼重要。' },
          { speaker: 'b', speakerName: 'Alex', en: 'They give you a way to be clear without sounding sharp.', zh: '它們會給你一條路，讓你既清楚，又不會太刺。', vocab: [{ word: 'sharp', def: '語氣尖銳、容易讓人防衛的' }] },
        ],
      },
      {
        title: 'Part 2 — Polite Entry Points',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'What are your favorite ways to enter a discussion politely?', zh: '你最常用、也最喜歡的禮貌切入句是哪些？' },
          { speaker: 'a', speakerName: 'Sara', en: `"Can I add something here?" and "I'd like to build on that point" are both useful.`, zh: '像是「Can I add something here?」和「I\'d like to build on that point」都很好用。' },
          { speaker: 'b', speakerName: 'Alex', en: 'I like those because they sound cooperative, not competitive.', zh: '我喜歡這類句子，因為它們聽起來是在合作，不是在搶。', vocab: [{ word: 'cooperative', def: '合作性的' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. The goal is not just to get airtime. It is to join the discussion in a useful way.', zh: '對。目標不只是拿到發言時間，而是用有用的方式進入討論。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And if you disagree, the opening matters even more.', zh: '而且如果你是要表達不同意，開頭就更重要了。' },
          { speaker: 'a', speakerName: 'Sara', en: `"I see it a little differently" is softer than "I don't agree."`, zh: '像「I see it a little differently」通常就比直接說「I don\'t agree」柔和很多。', vocab: [{ word: 'softer', def: '比較柔和、比較不刺激' }] },
        ],
      },
      {
        title: 'Part 3 — Clear but Not Harsh',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Do you think people sometimes become vague because they are trying too hard to sound polite?', zh: '你覺得有些人會不會因為太想禮貌，結果講得太模糊？' },
          { speaker: 'b', speakerName: 'Alex', en: 'Definitely. Then no one can tell what they actually mean.', zh: '會。結果就是沒有人知道他真正想表達什麼。' },
          { speaker: 'a', speakerName: 'Sara', en: 'So the answer is not to become harsher. It is to become clearer.', zh: '所以答案不是變得更兇，而是變得更清楚。', vocab: [{ word: 'become clearer', def: '更明確地表達' }] },
          { speaker: 'b', speakerName: 'Alex', en: `"My concern is..." works well because it introduces a point without sounding personal.`, zh: '像「My concern is...」就很好，因為它把重點帶出來，但不會太針對人。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And "I think we may be overlooking..." is useful when you want to raise a risk.', zh: '而像「I think we may be overlooking...」則很適合在你想提醒風險時使用。', vocab: [{ word: 'raise a risk', def: '提出一個風險點' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Those phrases give structure to disagreement.', zh: '這類句子，等於是替不同意本身加上了結構。' },
        ],
      },
      {
        title: 'Part 4 — Timing and Brevity',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'Timing also matters. Even a good point can land badly if it comes in the wrong moment.', zh: '時機也很重要。再好的觀點，如果進場時間不對，也可能效果很差。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is true. Interrupting carelessly can make people feel dismissed.', zh: '真的。太隨意地打斷，會讓人感覺自己被打掉。', vocab: [{ word: 'dismissed', def: '感覺被忽略、被打斷掉' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And long speeches are often less effective than short, focused comments.', zh: '而且長篇大論通常也不如短而集中的發言有效。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. In meetings, brevity is often a kindness.', zh: '對。在會議裡，簡潔本身常常就是一種體貼。', vocab: [{ word: 'brevity', def: '簡潔、簡短有力' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'One clear sentence can change the direction of a meeting.', zh: '有時一句很清楚的話，就足以改變整場會議的方向。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Which means you do not need to dominate the room to have influence.', zh: '這也代表，你不需要主導全場，才算有影響力。' },
        ],
      },
      {
        title: 'Part 5 — A Stronger Presence',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'So maybe a strong meeting presence is not loudness. It is precision.', zh: '所以，一個人在會議裡有存在感，也許不是靠大聲，而是靠精準。' },
          { speaker: 'b', speakerName: 'Alex', en: 'I think that is true. Precision earns trust faster than volume does.', zh: '我覺得是這樣。精準，比音量更快贏得信任。', vocab: [{ word: 'precision', def: '精準度' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'And once people trust your judgment, you do not need to push as hard.', zh: '而當別人開始信任你的判斷時，你就不需要那麼用力推。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is encouraging for quieter professionals.', zh: '這對比較安靜的職場人來說，其實很鼓舞。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. You can be thoughtful, calm, and still be very effective in a room.', zh: '對。你可以很沈穩、很有思考，同時在會議裡非常有效。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That sounds like a much healthier goal than trying to sound powerful all the time.', zh: '這聽起來也比一直想把自己講得很有氣勢，健康多了。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'speak up without sounding sharp', zh: '開口但不顯得尖銳', example: 'It takes practice to speak up without sounding sharp.' },
      { en: 'build on that point', zh: '延續那個觀點', example: 'I would like to build on that point for a moment.' },
      { en: 'see it differently', zh: '有不同看法', example: 'I see it differently, but I understand your concern.' },
      { en: 'my concern is', zh: '我的顧慮是', example: 'My concern is that the timeline may be too optimistic.' },
      { en: 'raise a risk', zh: '提出風險', example: 'I want to raise a risk before we commit to this plan.' },
      { en: 'brevity is a kindness', zh: '簡潔是一種體貼', example: 'In large meetings, brevity is a kindness.' },
      { en: 'one clear sentence', zh: '一句清楚的話', example: 'Sometimes one clear sentence is enough.' },
      { en: 'meeting presence', zh: '會議裡的存在感', example: 'A strong meeting presence does not require a loud personality.' },
      { en: 'precision earns trust', zh: '精準會贏得信任', example: 'Precision earns trust faster than volume.' },
      { en: 'thoughtful and calm', zh: '有思考且沈穩', example: 'She is thoughtful and calm, but very effective in meetings.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 4,
    date: '2026-05-14',
    theme: 'Meetings & Discussions',
    title: 'How to Disagree Productively in Discussions',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Disagreement Is Normal',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'A productive discussion usually includes at least some disagreement.', zh: '一場有價值的討論，通常多少都會有一些不同意。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. If everyone agrees immediately, either the issue is simple or people are holding back.', zh: '對。如果大家立刻全同意，那不是問題太簡單，就是有人其實沒說。' },
          { speaker: 'a', speakerName: 'Sara', en: 'The challenge is helping disagreement improve the discussion instead of damaging it.', zh: '真正的挑戰，是讓不同意能幫助討論變好，而不是把它弄壞。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That often depends on whether people stay focused on the idea or slip into judging the person.', zh: '這常常取決於大家是不是還在討論觀點，還是已經滑到在判斷人。', vocab: [{ word: 'focus on the idea', def: '把注意力放在觀點本身' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Once it becomes personal, the room gets tighter immediately.', zh: '沒錯。一旦變成人身上的事，整個會議室就會立刻變緊。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Which is why language matters so much in disagreement.', zh: '所以語言怎麼用，在不同意的時候特別重要。' },
        ],
      },
      {
        title: 'Part 2 — Useful Ways to Disagree',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'What phrases help you disagree without escalating the room?', zh: '你覺得哪些句子最能幫助人不同意，但又不會讓會議升溫？' },
          { speaker: 'a', speakerName: 'Sara', en: `"I have a different read on this" is one I use a lot.`, zh: '我很常用的一句是「I have a different read on this」。' },
          { speaker: 'b', speakerName: 'Alex', en: 'I like that because it sounds like perspective, not attack.', zh: '我喜歡那句，因為它聽起來是在提供不同視角，而不是攻擊。', vocab: [{ word: 'different read', def: '不同的理解或判讀' }] },
          { speaker: 'a', speakerName: 'Sara', en: `"I am not fully convinced yet" is useful too, especially when the discussion is moving too fast.`, zh: '像「I am not fully convinced yet」也很好，特別適合在討論跑太快的時候。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And "What problem are we solving with this approach?" helps bring the discussion back to purpose.', zh: '而「What problem are we solving with this approach?」則很能把大家拉回目的。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Good disagreement adds clarity, not just friction.', zh: '正是。好的不同意，帶來的是清楚，而不只是摩擦。', vocab: [{ word: 'friction', def: '摩擦、阻力感' }] },
        ],
      },
      {
        title: 'Part 3 — Staying Calm Under Tension',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'It is much harder to disagree well when the room already feels tense.', zh: '當現場氣氛已經很緊時，要把不同意說好，其實更難。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Definitely. Once people feel threatened, they start defending positions instead of examining them.', zh: '當然。一旦人感到有威脅，就會開始防守自己的立場，而不是檢查自己的立場。', vocab: [{ word: 'defend positions', def: '防守自己的立場' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why tone matters as much as wording.', zh: '所以語氣和用字一樣重要。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Sometimes speaking more slowly is enough to lower the emotional temperature.', zh: '有時你只要講慢一點，就已經能把情緒溫度降下來。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And if needed, naming the tension can help too.', zh: '如果有需要，直接點出那個緊張感，有時也會有幫助。' },
          { speaker: 'b', speakerName: 'Alex', en: `"I think we may be talking past each other" is gentler than "You misunderstood me."`, zh: '像「I think we may be talking past each other」就會比「你誤解我了」柔和很多。', vocab: [{ word: 'talking past each other', def: '彼此在講，但沒有真正對上彼此意思' }] },
        ],
      },
      {
        title: 'Part 4 — Finding the Next Step',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'Not every disagreement gets resolved in one meeting, though.', zh: '不過也不是每個不同意，都能在一次會議裡解決。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is true. Sometimes the best outcome is just a clearer next step.', zh: '這是真的。有時最好的結果，只是把下一步釐清而已。', vocab: [{ word: 'next step', def: '接下來明確可做的下一步' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Like agreeing to gather more data, run a small test, or revisit the issue later.', zh: '像是先補資料、先做小型測試，或約好之後再回來討論。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Progress is not always agreement. Sometimes progress is better definition.', zh: '沒錯。進展不一定代表共識，有時候進展只是定義得更清楚。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That makes disagreement feel less threatening and more workable.', zh: '這樣一來，不同意就不會那麼可怕，反而變得比較可操作。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. A good discussion can leave people thinking, not just deciding.', zh: '對。一場好的討論，不只會留下決定，也會留下更成熟的思考。' },
        ],
      },
      {
        title: 'Part 5 — Productive Tension',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'I think mature teams learn how to tolerate some tension without panicking.', zh: '我覺得成熟的團隊，會學著承受一些張力，而不是一有張力就慌。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. Productive tension often means people care enough to think carefully.', zh: '對。有建設性的張力，常常代表大家其實很在乎，也願意認真想。', vocab: [{ word: 'productive tension', def: '有建設性的張力' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'The goal is not a perfectly smooth meeting. It is a useful one.', zh: '目標不是把會議弄得毫無波瀾，而是讓它真的有用。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is a much healthier standard.', zh: '這個標準其實健康得多。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Because useful discussions can survive difference.', zh: '因為真的有價值的討論，本來就承受得住差異。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And sometimes difference is exactly what makes the discussion worth having.', zh: '而且有時候，正是差異本身，讓一場討論變得值得。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'focus on the idea', zh: '聚焦在觀點上', example: 'Try to focus on the idea, not the person presenting it.' },
      { en: 'a different read', zh: '不同的判讀', example: 'I have a different read on the customer feedback.' },
      { en: 'not fully convinced yet', zh: '還沒有完全被說服', example: 'I am not fully convinced yet, and I want to understand more.' },
      { en: 'solve with this approach', zh: '這個做法要解決什麼問題', example: 'What problem are we solving with this approach?' },
      { en: 'talking past each other', zh: '彼此沒有真正對上話', example: 'I think we may be talking past each other.' },
      { en: 'clearer next step', zh: '更清楚的下一步', example: 'We may not agree yet, but we do have a clearer next step.' },
      { en: 'productive tension', zh: '有建設性的張力', example: 'A strong team knows how to hold productive tension.' },
      { en: 'useful, not perfectly smooth', zh: '有用，不必完全平順', example: 'A good meeting does not have to be perfectly smooth. It just has to be useful.' },
      { en: 'survive difference', zh: '承受得住差異', example: 'Healthy discussions can survive difference.' },
      { en: 'worth having', zh: '值得進行', example: 'Sometimes disagreement is what makes a discussion worth having.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 5,
    date: '2026-05-15',
    theme: 'Meetings & Discussions',
    title: 'Keeping a Meeting on Track',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Meetings Drift Easily',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Meetings drift so easily, especially when the topic is broad.', zh: '會議真的很容易飄掉，尤其當議題本身很大的時候。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. One interesting side topic appears, and suddenly twenty minutes are gone.', zh: '對。只要出現一個有趣的旁支話題，二十分鐘可能就這樣不見了。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why facilitation matters, even in casual internal meetings.', zh: '所以帶會議的能力很重要，就算只是內部比較輕鬆的會議也是一樣。', vocab: [{ word: 'facilitation', def: '帶領討論、維持節奏與方向' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'A group can have smart people and still have an unproductive conversation.', zh: '一群很聰明的人，也一樣可能開出一場沒效率的會。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Intelligence does not replace structure.', zh: '沒錯。聰明，不能取代結構。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And structure is often what protects the group from its own habits.', zh: '而結構，常常就是保護群體不被自己習慣帶走的東西。' },
        ],
      },
      {
        title: 'Part 2 — Bringing the Group Back',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'What is a good way to bring a meeting back without sounding impatient?', zh: '如果要把會議拉回來，怎麼講才不會聽起來很不耐煩？' },
          { speaker: 'a', speakerName: 'Sara', en: `"This is helpful, and I want to connect it back to our main question" works well.`, zh: '像是「這個討論有幫助，但我想把它拉回我們原本的主要問題」就很好用。' },
          { speaker: 'b', speakerName: 'Alex', en: 'I like that because it acknowledges the side topic before redirecting.', zh: '我喜歡這句，因為它先承認旁支話題不是沒價值，再轉回主軸。', vocab: [{ word: 'redirect', def: '重新導回正題' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. People resist less when they feel heard.', zh: '沒錯。當人覺得自己有被聽見時，就比較不會抗拒。' },
          { speaker: 'b', speakerName: 'Alex', en: 'And sometimes it helps to restate the goal out loud.', zh: '而且有時候，把目標重新說一遍也很有幫助。' },
          { speaker: 'a', speakerName: 'Sara', en: `"By the end of this meeting, we need to choose A or B" gives everyone a target.`, zh: '像是「這場會議結束前，我們需要在 A 和 B 之間做出選擇」，就會讓大家重新看到目標。' },
        ],
      },
      {
        title: 'Part 3 — Parking Lot and Follow-Up',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Do you use a parking lot in meetings?', zh: '你開會時會用 parking lot 這個方法嗎？' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes, especially when people raise good points that are real but not urgent.', zh: '會，特別是當有人提出很好的點，但那個點現在不是最急的時候。', vocab: [{ word: 'parking lot', def: '暫放待處理議題的區域' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'I like it because it shows respect without losing focus.', zh: '我喜歡它，因為它讓人感受到被尊重，同時又不失去聚焦。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. "Let us park that and come back if we have time" is a very useful sentence.', zh: '對。像是「我們先把這題停在這裡，如果時間夠再回來」就非常實用。' },
          { speaker: 'a', speakerName: 'Sara', en: 'The important part is that the parking lot should not become a graveyard.', zh: '但重點是，parking lot 不能最後變成議題墳場。', vocab: [{ word: 'graveyard', def: '比喻被丟著不再處理的地方' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Right. If you capture it, you also need a way to follow up later.', zh: '對。如果你把議題收進來，就也要有後續處理的方式。' },
        ],
      },
      {
        title: 'Part 4 — Time Is Part of the Discussion',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'People often treat time as separate from the content, but it is really part of the content.', zh: '很多人會把時間當成內容以外的事，但其實時間本身就是內容的一部分。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is a great point. If you spend forty minutes on background, you have changed the decision process.', zh: '這句很重要。你如果花四十分鐘講背景，其實就已經改變了整個決策流程。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. Time allocation reveals what the group really values.', zh: '沒錯。時間怎麼分配，往往最能看出一個團隊真正重視什麼。', vocab: [{ word: 'time allocation', def: '時間分配方式' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why someone has to watch the clock without apologizing for it.', zh: '所以一定要有人盯時間，而且不需要因此感到抱歉。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Because protecting time is also protecting the quality of the outcome.', zh: '因為保護時間，同時也是在保護結果品質。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And in a healthy team, that should be seen as support, not control.', zh: '而在健康團隊裡，這應該被看作支持，而不是控制。' },
        ],
      },
      {
        title: 'Part 5 — Ending With Clarity',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'I think the end of a meeting is often the most underestimated part.', zh: '我覺得會議結尾，常常是最被低估的一段。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. People run out of time and then leave without a shared understanding.', zh: '對。很多時候大家時間到了就散了，但其實根本沒有共同理解。' },
          { speaker: 'a', speakerName: 'Sara', en: 'A short recap can prevent so much confusion later.', zh: '一個簡短總結，真的可以避免後面很多混亂。', vocab: [{ word: 'recap', def: '簡短回顧總結' }] },
          { speaker: 'b', speakerName: 'Alex', en: `"So to recap, here is what we decided, and here is who owns what" is ideal.`, zh: '像是「最後整理一下，我們做了哪些決定、誰負責哪些事」這種收尾就很理想。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That makes the meeting actionable instead of just memorable.', zh: '那會讓會議變成可執行的，而不只是「大家覺得今天有聊很多」。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. A good meeting should leave people clear, not just tired.', zh: '沒錯。好的會議，應該讓人留下的是清楚感，不只是疲憊。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'bring it back', zh: '把話題拉回來', example: 'Someone needs to bring it back to the main topic.' },
      { en: 'redirect respectfully', zh: '有禮貌地導回來', example: 'A good facilitator can redirect respectfully.' },
      { en: 'parking lot', zh: '暫存議題區', example: 'Let us put that in the parking lot for later.' },
      { en: 'not a graveyard', zh: '不是議題墳場', example: 'A parking lot should not become a graveyard for good ideas.' },
      { en: 'time allocation', zh: '時間分配', example: 'Time allocation shapes the quality of a meeting.' },
      { en: 'watch the clock', zh: '盯時間', example: 'Someone has to watch the clock during decision meetings.' },
      { en: 'protect the outcome', zh: '保護結果品質', example: 'Managing time helps protect the outcome.' },
      { en: 'short recap', zh: '簡短總結', example: 'A short recap at the end saves everyone time later.' },
      { en: 'who owns what', zh: '誰負責什麼', example: 'Before we end, let us confirm who owns what.' },
      { en: 'clear, not just tired', zh: '留下清楚感，不只是疲憊', example: 'A strong meeting leaves people clear, not just tired.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 6,
    date: '2026-05-16',
    theme: 'Meetings & Discussions',
    title: 'Better Participation in Virtual Meetings',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Presence Is Different Online',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Being present in a virtual meeting is not the same as being present in a room.', zh: '在線上會議裡的「在場」，和真的坐在一個房間裡的在場感，其實不一樣。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Definitely. Online, people can disappear without technically leaving.', zh: '真的。在線上，人其實可以在不離開會議的情況下消失。', vocab: [{ word: 'be present', def: '真正投入在當下' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why visible engagement matters more in remote settings.', zh: '所以在遠端情境下，看得見的參與感反而更重要。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Even simple things help, like nodding, using reactions, or turning your camera on when appropriate.', zh: '有時很簡單的事就有幫助，像是點頭、用 reaction，或在合適的時候開鏡頭。' },
          { speaker: 'a', speakerName: 'Sara', en: 'I think the keyword is appropriate. One rule does not fit every meeting.', zh: '我覺得關鍵字是「合適」。不是每種會議都適合同一套規則。', vocab: [{ word: 'appropriate', def: '合適的、視情況而定的' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. Good virtual etiquette is contextual, not rigid.', zh: '對。好的線上禮儀是看情境的，不是僵硬的一刀切。' },
        ],
      },
      {
        title: 'Part 2 — Helping People Enter the Conversation',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'I think it is harder to jump into a conversation online than in person.', zh: '我覺得在線上插入對話，其實比在現場更難。' },
          { speaker: 'a', speakerName: 'Sara', en: 'I agree. The timing feels less natural because of delays, muting, and the lack of body cues.', zh: '我同意。因為有延遲、靜音，加上沒有身體線索，節奏本來就不自然。', vocab: [{ word: 'body cues', def: '肢體線索' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'That is why some people use the chat or hand-raise function instead of interrupting.', zh: '所以有些人會用聊天室或舉手功能，而不是直接打斷。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And good hosts actively create openings too.', zh: '而好的主持人，也會主動替大家創造開口的空間。' },
          { speaker: 'b', speakerName: 'Alex', en: `"Let's hear from someone who hasn't spoken yet" can change the whole balance.`, zh: '像是「我們來聽聽剛才還沒發言的人」，就很可能改變整場平衡。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. Inclusion in virtual meetings needs to be more intentional.', zh: '對。線上會議裡的參與公平，通常需要更有意識地被設計出來。', vocab: [{ word: 'inclusion', def: '讓不同人都有機會參與' }] },
        ],
      },
      {
        title: 'Part 3 — Audio, Video, and Courtesy',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'A lot of online meeting problems are not strategic. They are technical or behavioral.', zh: '很多線上會議的問題，其實不是策略問題，而是技術或行為細節。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Open microphones, bad lighting, multitasking, and people speaking over each other?', zh: '像是麥克風沒關、光線很差、一邊多工，或大家互相搶話？' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. These things seem small, but they shape the whole experience.', zh: '對。這些事情看起來小，但它們其實會塑造整場會議的感受。', vocab: [{ word: 'multitasking', def: '同時做很多事' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'A little basic courtesy goes a long way online.', zh: '在線上，基本禮貌其實會產生很大的效果。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Muting when you are not speaking is one example. So is avoiding loud typing into the microphone.', zh: '像是不發言時把自己靜音，或不要把很大的打字聲直接送進麥克風。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is not just etiquette. It is also a way of protecting everyone else’s focus.', zh: '那不只是禮儀，也是在保護其他人的專注力。', vocab: [{ word: 'protect focus', def: '保護專注度' }] },
        ],
      },
      {
        title: 'Part 4 — Summaries Matter More Online',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'I notice that online meetings need more verbal summaries than in-person ones.', zh: '我發現線上會議比起實體會議，更需要口頭上的整理和總結。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes, because shared understanding drifts more easily when everyone is in a different environment.', zh: '對，因為當每個人都在不同環境裡時，共同理解比較容易鬆掉。', vocab: [{ word: 'shared understanding', def: '大家對目前狀況有共同理解' }] },
          { speaker: 'b', speakerName: 'Alex', en: `"Just to summarize where we are..." is one of the most useful online phrases.`, zh: '像「Just to summarize where we are...」就是線上會議裡很有用的一句。' },
          { speaker: 'a', speakerName: 'Sara', en: 'It helps re-synchronize the group.', zh: '它會幫助整個群體重新同步。', vocab: [{ word: 're-synchronize', def: '重新回到同一節奏與理解' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And it gives people a chance to correct misunderstandings before the meeting ends.', zh: '而且這也會讓人有機會在會議結束前修正誤解。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. In remote work, summary is part of leadership.', zh: '正是。在遠端工作裡，總結能力本來就是領導力的一部分。' },
        ],
      },
      {
        title: 'Part 5 — Good Online Meetings Feel Designed',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'The best virtual meetings I have been in never felt accidental.', zh: '我參加過最好的線上會議，從來沒有一場是靠運氣的。' },
          { speaker: 'b', speakerName: 'Alex', en: 'They probably felt smooth because someone had designed the flow carefully.', zh: '它們之所以順，往往是因為有人很仔細地設計了整體流程。', vocab: [{ word: 'flow', def: '流程與節奏' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. Good remote meetings need structure, technical awareness, and human awareness at the same time.', zh: '對。好的遠端會議，要同時顧到結構、技術，還有人與人之間的感受。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That sounds like a lot, but it is worth it when teams depend on online communication every day.', zh: '聽起來很多，但如果團隊每天都得靠線上溝通，這些其實很值得。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Digital meetings may be ordinary now, but they still deserve craft.', zh: '沒錯。數位會議雖然現在很日常，但它仍然值得被好好設計。', vocab: [{ word: 'craft', def: '有技巧地做、講究做法' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And when they are done well, they can feel efficient without feeling cold.', zh: '而當它們被做得夠好時，就能同時有效率，又不會冷冰冰。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'be present', zh: '真正有在場感', example: 'It is possible to join a call without really being present.' },
      { en: 'appropriate for the setting', zh: '符合情境', example: 'Camera use should be appropriate for the setting.' },
      { en: 'create openings', zh: '創造開口空間', example: 'A skilled host creates openings for quieter people.' },
      { en: 'inclusion needs intention', zh: '參與公平需要刻意設計', example: 'Online inclusion needs more intention than people realize.' },
      { en: 'protect focus', zh: '保護專注力', example: 'Muting when not speaking helps protect focus.' },
      { en: 'shared understanding', zh: '共同理解', example: 'Summaries help restore shared understanding.' },
      { en: 're-synchronize the group', zh: '重新同步整個群體', example: 'A short recap can re-synchronize the group.' },
      { en: 'part of leadership', zh: '領導力的一部分', example: 'In remote work, summarizing well is part of leadership.' },
      { en: 'designed flow', zh: '被設計過的流程', example: 'The best online meetings have a designed flow.' },
      { en: 'efficient without feeling cold', zh: '有效率但不冷', example: 'A strong virtual meeting feels efficient without feeling cold.' },
    ],
  },

  {
    weekNumber: 20,
    dayOfWeek: 7,
    date: '2026-05-17',
    theme: 'Meetings & Discussions',
    title: 'What Makes a Discussion Actually Useful',
    phase: 'p3',
    parts: [
      {
        title: 'Part 1 — Talking Is Not the Same as Progress',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'People often leave a discussion feeling busy, but not necessarily clear.', zh: '很多人離開一場討論時，只覺得很忙，但不一定真的更清楚。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. A lot of talking can create the feeling of progress without producing actual movement.', zh: '對。很多說話會製造出「好像有進展」的感覺，但其實沒有真的往前。', vocab: [{ word: 'actual movement', def: '真正的推進' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'So what makes a discussion genuinely useful?', zh: '所以到底什麼才會讓一場討論真的有用？' },
          { speaker: 'b', speakerName: 'Alex', en: 'Usually three things: clarity, participation, and a meaningful outcome.', zh: '我覺得通常是三件事：清楚感、參與度，還有真的有意義的結果。' },
          { speaker: 'a', speakerName: 'Sara', en: 'That sounds simple, but most weak discussions are missing at least one of those.', zh: '聽起來很簡單，但大多數沒效果的討論，至少都會缺其中一項。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. If people do not know what the point is, the discussion starts leaking energy immediately.', zh: '沒錯。如果大家不知道這場討論到底要幹嘛，它就會立刻開始漏能量。', vocab: [{ word: 'leaking energy', def: '持續消耗能量卻沒有累積成果' }] },
        ],
      },
      {
        title: 'Part 2 — Clarity of Purpose',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'I think the first question in any discussion should be, "What are we trying to leave with?"', zh: '我覺得任何討論一開始，都應該先問一句：「我們希望最後帶走的是什麼？」' },
          { speaker: 'a', speakerName: 'Sara', en: 'That is a strong question because it frames the ending at the beginning.', zh: '這個問題很強，因為它在一開始就先把結尾框起來。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Exactly. Are we trying to understand, decide, generate options, or simply align?', zh: '對。這場討論到底是要理解、做決定、發想選項，還是只是同步認知？', vocab: [{ word: 'align', def: '同步想法、取得一致理解' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Those are very different goals, and they require different kinds of discussion.', zh: '這些目標都很不一樣，所需要的討論方式當然也不同。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Without that clarity, people often start solving the wrong problem.', zh: '如果沒有這層清楚感，人很容易就開始解錯問題。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And then even good ideas can go to the wrong place.', zh: '然後即使是好想法，也可能被丟到錯的地方去。' },
        ],
      },
      {
        title: 'Part 3 — Better Participation',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'Useful discussions also depend on who is able to participate.', zh: '有用的討論，也很取決於誰有機會真的參與進來。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Yes. If only two people carry the whole conversation, the group loses perspective.', zh: '對。如果整場都只有兩個人在扛討論，團體視角就會變窄。', vocab: [{ word: 'lose perspective', def: '失去更完整的視角' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'That is why strong facilitation is not about control. It is about distribution.', zh: '所以好的帶領不是控制，而是分配。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Distributing airtime, questions, and attention more fairly.', zh: '是把發言空間、問題，還有注意力分配得更公平。', vocab: [{ word: 'airtime', def: '發言時間' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Good discussions do not just surface ideas. They surface more than one kind of mind.', zh: '沒錯。好的討論，不只是把想法挖出來，而是把不只一種思考方式都帶到檯面上。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That is what makes a group smarter than the individuals in it.', zh: '而這正是讓團體比個人更聰明的地方。' },
        ],
      },
      {
        title: 'Part 4 — A Useful Ending',
        lines: [
          { speaker: 'b', speakerName: 'Alex', en: 'The ending matters too. A discussion without a clean ending often feels unfinished.', zh: '結尾也很重要。沒有乾淨收尾的討論，通常都會讓人覺得卡著。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Yes. Even if there is no final decision, people still need to know what happened.', zh: '對。就算最後沒有定案，大家也還是需要知道：剛才到底發生了什麼。' },
          { speaker: 'b', speakerName: 'Alex', en: 'A good ending might be a summary, a decision, an open question, or a next step.', zh: '好的結尾可能是總結、決定、待回答的問題，或明確的下一步。', vocab: [{ word: 'clean ending', def: '讓人清楚知道討論停在哪裡的收尾' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Closure does not always mean certainty.', zh: '沒錯。收束感，不一定代表事情已經完全確定。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Sometimes closure just means everyone knows where the uncertainty is now.', zh: '有時候，所謂收束，只是大家都知道不確定現在在哪裡。' },
          { speaker: 'a', speakerName: 'Sara', en: 'And that is already much more useful than confusion.', zh: '而這，就已經比一片混亂有用很多了。' },
        ],
      },
      {
        title: 'Part 5 — Useful Discussions Build Good Teams',
        lines: [
          { speaker: 'a', speakerName: 'Sara', en: 'In the long run, the quality of a team often shows up in the quality of its discussions.', zh: '長期來看，一個團隊的品質，常常就會反映在它討論的品質上。' },
          { speaker: 'b', speakerName: 'Alex', en: 'That makes sense. Discussions reveal whether people know how to think together, not just work next to each other.', zh: '這很有道理。討論會揭露一件事：大家是會一起思考，還是只是坐在一起工作。', vocab: [{ word: 'think together', def: '共同思考，而不只是各做各的' }] },
          { speaker: 'a', speakerName: 'Sara', en: 'And teams that learn how to discuss well usually make better decisions over time.', zh: '而會討論的團隊，通常也會在時間中做出更好的決策。' },
          { speaker: 'b', speakerName: 'Alex', en: 'Because they are better at using disagreement, difference, and uncertainty productively.', zh: '因為他們更懂得把不同意、差異，還有不確定，轉成有生產力的東西。' },
          { speaker: 'a', speakerName: 'Sara', en: 'Exactly. Good discussions are not just events. They are a team skill.', zh: '正是。好的討論不只是某一次事件，而是一種團隊能力。', vocab: [{ word: 'team skill', def: '屬於整個團隊的能力' }] },
          { speaker: 'b', speakerName: 'Alex', en: 'And like any skill, they improve when people practice them intentionally.', zh: '而且就像其他能力一樣，只要大家有意識地練，它就會變好。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'actual movement', zh: '真正的推進', example: 'A discussion can feel active without creating actual movement.' },
      { en: 'clarity of purpose', zh: '目的清楚', example: 'The first requirement for a good discussion is clarity of purpose.' },
      { en: 'leave with', zh: '最後要帶走什麼', example: 'What are we trying to leave with by the end of this discussion?' },
      { en: 'lose perspective', zh: '失去完整視角', example: 'When only a few people speak, the group can lose perspective.' },
      { en: 'distribute airtime', zh: '分配發言時間', example: 'A strong facilitator knows how to distribute airtime fairly.' },
      { en: 'clean ending', zh: '乾淨的收尾', example: 'Every useful discussion needs a clean ending.' },
      { en: 'closure without certainty', zh: '有收束感但未必有定案', example: 'A meeting can end with closure without certainty.' },
      { en: 'think together', zh: '一起思考', example: 'The best teams know how to think together.' },
      { en: 'team skill', zh: '團隊能力', example: 'Running good discussions is a team skill, not just an individual talent.' },
      { en: 'practice intentionally', zh: '有意識地練習', example: 'Teams improve when they practice discussions intentionally.' },
    ],
  },
]
