import { Episode } from '../../app/src/data/episode-sample'

export const WEEK_15: Episode[] = [
  {
  weekNumber: 15,
  dayOfWeek: 1,
  date: '2026-04-06',
  theme: 'Personality & Character',
  title: 'Who Are You: Talking About Personality Types',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — How Well Do You Know Yourself?',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Mira, how well do you think you actually know yourself? Like, your real personality versus the one you present to others?", zh: 'Mira，你覺得你有多了解你自己？就是，你真實的個性和你向他人展示的那個？' },
        { speaker: 'a', speakerName: 'Mira', en: "I think I know myself reasonably well now, but it took a long time. In my twenties I had a very fixed idea of who I was, and a lot of it turned out to be who I thought I was supposed to be.", zh: '我覺得我現在對自己了解得相當好，但花了很長時間。在我二十多歲的時候，我對自己是誰有一個非常固定的想法，其中很多原來是我認為自己應該是的樣子。', vocab: [{ word: 'fixed idea', def: '固定的想法' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That gap between who we are and who we think we should be is interesting. Where does that pressure come from?", zh: '我們是誰和我們認為我們應該是誰之間的差距很有趣。那種壓力從哪裡來？' },
        { speaker: 'a', speakerName: 'Mira', en: "Family, culture, the people around us. We absorb expectations early and often confuse them with our own preferences. It takes years of living independently to sort out which is which.", zh: '家庭、文化、我們周圍的人。我們很早就吸收了期望，常常把它們和自己的偏好混淆。需要多年的獨立生活才能分清哪個是哪個。', vocab: [{ word: 'absorb', def: '吸收' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Do you use any frameworks for thinking about personality? Like Myers-Briggs or Enneagram?", zh: '你有使用任何框架來思考個性嗎？比如MBTI或九型人格？', vocab: [{ word: 'frameworks', def: '框架' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I've tried most of them. I take them with a grain of salt — they're useful for starting conversations about tendencies, but I'm skeptical of anyone who treats them as definitive.", zh: '我大多數都試過了。我不會完全依賴它們——對於開始關於傾向的對話很有用，但我對任何將它們視為決定性的人持懷疑態度。', vocab: [{ word: 'grain of salt', def: '保留一點懷疑' }, { word: 'skeptical', def: '懷疑的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The danger of over-identifying with a type, right? 'I can't help being this way, it's just my personality.'", zh: '過度認同某個類型的危險，對吧？「我沒辦法，這只是我的個性。」' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Personality frameworks can become either a helpful lens or a convenient excuse. The difference is whether you use them to grow or to justify staying the same.", zh: '正是。個性框架可以成為有用的視角，也可以成為方便的藉口。差別在於你用它們來成長，還是用來為保持原樣辯護。' },
      ],
    },
    {
      title: 'Part 2 — Strengths and Weaknesses',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What would you say your main personality strengths are? The things that genuinely help you?", zh: '你會說你主要的個性優點是什麼？真正幫助你的那些？' },
        { speaker: 'a', speakerName: 'Mira', en: "I'm a good listener — people feel heard when they talk to me, and I notice things they don't say as much as what they do. I'm also fairly calm under pressure, which helps in difficult situations.", zh: '我是個好的傾聽者——人們和我說話時感到被聆聽，我注意到他們沒說的和他們說的一樣多。我在壓力下也相當冷靜，這在困難情況下很有幫助。' },
        { speaker: 'b', speakerName: 'Jamie', en: "Those are genuinely useful traits. What about weaknesses — things you've had to actively work on?", zh: '那些是真正有用的特質。那弱點呢——你不得不積極努力的事情？' },
        { speaker: 'a', speakerName: 'Mira', en: "I can be overly self-critical. I hold myself to high standards and sometimes that tips into perfectionism, which is its own kind of obstacle. I've learned to recognize when good enough is genuinely enough.", zh: '我可能過於自我批評。我對自己要求很高，有時那會變成完美主義，那本身就是一種障礙。我學會了認識什麼時候「夠好」真的就夠了。', vocab: [{ word: 'perfectionism', def: '完美主義' }, { word: 'obstacle', def: '障礙' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Perfectionism is a sneaky one — it masquerades as ambition.", zh: '完美主義是個狡猾的——它偽裝成雄心壯志。', vocab: [{ word: 'masquerade as', def: '偽裝成' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. And it can be paralyzing. I've had periods where I've not started things because I couldn't guarantee they'd be done well. Which is obviously counterproductive.", zh: '正是。而且它可以令人癱瘓。我有過一些時期因為無法保證事情會做得好而沒有開始。那顯然是適得其反的。', vocab: [{ word: 'paralyzing', def: '令人癱瘓的' }, { word: 'counterproductive', def: '適得其反的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I struggle with impatience. I want things to move quickly and I can get frustrated when they don't. It's useful as a driver but not great for relationships.", zh: '我在耐心方面有挑戰。我希望事情快速推進，當它們沒有時我會變得沮喪。作為推動力很有用，但對關係不太好。', vocab: [{ word: 'impatience', def: '不耐煩' }] },
        { speaker: 'a', speakerName: 'Mira', en: "That's an honest self-assessment. And recognizing that your strengths have shadow sides is the beginning of managing them better.", zh: '那是誠實的自我評估。而認識到你的優點有陰暗面，是更好地管理它們的開始。', vocab: [{ word: 'shadow sides', def: '陰暗面' }] },
      ],
    },
    {
      title: 'Part 3 — How Others See Us',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do you think the way others see you matches how you see yourself?", zh: '你覺得別人看你的方式和你看自己的方式一致嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "Not entirely. I think I come across as more confident than I actually feel on the inside. Which is useful sometimes, but it also means people don't always offer me support when I actually need it.", zh: '不完全是。我覺得我表現出的自信比我內心實際感受的更多。有時很有用，但也意味著人們並不總是在我實際需要時給予我支持。' },
        { speaker: 'b', speakerName: 'Jamie', en: "That's the paradox of competence — the more capable you appear, the less likely people are to check in on you.", zh: '那是能力的悖論——你看起來越有能力，人們越不可能關心你。', vocab: [{ word: 'paradox', def: '悖論' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Which is why vulnerability matters. Occasionally letting the mask slip — showing that you're uncertain or struggling — actually invites more authentic connection.", zh: '這就是為什麼脆弱很重要。偶爾讓面具滑落——展示你不確定或在掙扎——實際上邀請了更真實的連結。', vocab: [{ word: 'vulnerability', def: '脆弱、易受傷害性' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Have you ever received feedback about your personality that really surprised you?", zh: '你有沒有收到過真的讓你驚訝的關於你個性的反饋？' },
        { speaker: 'a', speakerName: 'Mira', en: "Yes — someone told me once that I could seem intimidating to people who didn't know me. I was shocked. I think of myself as warm and approachable. But I can be reserved with new people, and apparently that reads as distant.", zh: '有——有人曾告訴我，我對不認識我的人來說可能看起來讓人畏懼。我很震驚。我認為自己溫暖且平易近人。但我對新人可能比較保守，顯然那被解讀為疏遠。', vocab: [{ word: 'intimidating', def: '讓人畏懼的' }, { word: 'reserved', def: '保守的、內斂的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That kind of feedback is valuable, even if it stings. It's a reminder that our internal experience and our external presentation don't always match.", zh: '那種反饋是有價值的，即使它刺痛了。它提醒我們，我們的內部體驗和外部呈現並不總是一致的。', vocab: [{ word: 'stings', def: '刺痛' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And it's not always possible to know how we're coming across. That's why feedback from people who know us well is such a gift, even when it's uncomfortable.", zh: '而且我們不總是能知道自己給人什麼印象。這就是為什麼了解我們的人的反饋是一種禮物，即使它讓人不舒服。' },
      ],
    },
    {
      title: 'Part 4 — Can Personality Change?',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do you think personality fundamentally changes over a lifetime? Or are people basically the same at their core?", zh: '你認為個性在一生中會根本改變嗎？還是人們在核心上基本相同？' },
        { speaker: 'a', speakerName: 'Mira', en: "I think the core tendencies stay fairly stable — I'll always be somewhat introverted and detail-oriented. But a lot changes in how those tendencies are expressed and managed.", zh: '我覺得核心傾向保持相當穩定——我永遠會有些內向且注重細節。但那些傾向如何表達和管理改變了很多。', vocab: [{ word: 'tendencies', def: '傾向' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Experience shapes behavior even if the underlying traits persist. Someone anxious at twenty might be calm at forty — not because anxiety disappeared, but because they learned to manage it.", zh: '即使底層特質持續存在，經驗也會塑造行為。一個二十歲時焦慮的人四十歲時可能很平靜——不是因為焦慮消失了，而是因為他們學會了管理它。', vocab: [{ word: 'underlying', def: '底層的' }, { word: 'persist', def: '持續存在' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Research suggests that the Big Five personality traits do shift slowly over a lifetime — people tend to become more agreeable and conscientious with age. So change is real, just slow.", zh: '研究表明，五大人格特質確實在一生中緩慢變化——人們隨著年齡往往變得更隨和和認真負責。所以改變是真實的，只是很慢。', vocab: [{ word: 'conscientious', def: '認真負責的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's reassuring in a way. It means we're not stuck with our worst traits.", zh: '那以某種方式令人安慰。意思是我們不會被我們最糟糕的特質困住。', vocab: [{ word: 'reassuring', def: '令人安慰的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And that intention matters. People who actively work on themselves — therapy, honest self-reflection, seeking feedback — tend to change more than those who just let life happen to them.", zh: '而且意圖很重要。那些積極致力於自我提升的人——治療、誠實的自我反思、尋求反饋——比那些只是讓生活隨波逐流的人更容易改變。' },
        { speaker: 'b', speakerName: 'Jamie', en: "So personality isn't destiny — it's a starting point.", zh: '所以個性不是命運——它是一個起點。' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. The raw material shapes you, but you still get to do something with it.", zh: '正是。原料塑造你，但你仍然可以對它做些事情。' },
      ],
    },
    {
      title: 'Part 5 — Character vs. Personality',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Is there a difference between personality and character? I feel like people use those words interchangeably but they might mean different things.", zh: '個性和品格有區別嗎？我感覺人們可以互換使用這兩個詞，但它們可能意味著不同的事情。', vocab: [{ word: 'interchangeably', def: '可互換地' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I think there is. Personality is how you tend to behave — your patterns, preferences, default responses. Character is about what you do when it's hard — how you act when no one is watching, how you treat people who can't help you.", zh: '我覺得有。個性是你傾向於如何行為——你的模式、偏好、預設反應。品格是關於你在困難時做什麼——當沒有人看的時候你怎麼行動，你如何對待無法幫助你的人。', vocab: [{ word: 'default responses', def: '預設反應' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Character as the part that requires choice, not just tendency.", zh: '品格作為需要選擇的部分，而不只是傾向。' },
        { speaker: 'a', speakerName: 'Mira', en: "Yes. You might be naturally impatient — that's personality. But you can still choose to be kind and fair, even when you're frustrated. That choice over time becomes character.", zh: '是的。你天生可能不耐煩——那是個性。但你仍然可以選擇善良和公正，即使你很沮喪。那種選擇隨著時間成為品格。' },
        { speaker: 'b', speakerName: 'Jamie', en: "I like that framing. It puts agency back in the picture — you're not just the sum of your tendencies.", zh: '我喜歡那個框架。它把主體性放回了畫面——你不只是你傾向的總和。', vocab: [{ word: 'agency', def: '主體性、自主能力' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And I think this is why character is something people find admirable — it represents conscious choices made repeatedly over time.", zh: '我覺得這就是為什麼品格是人們覺得值得欽佩的東西——它代表了隨著時間反覆做出的有意識的選擇。', vocab: [{ word: 'admirable', def: '值得欽佩的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "It's built, not born. That's both a challenge and a reassurance.", zh: '它是建立的，不是天生的。那既是一個挑戰，也是一種安慰。' },
        { speaker: 'a', speakerName: 'Mira', en: "Perfectly put. We come with raw material, but we're also the architects of who we become.", zh: '說得很好。我們帶著原料而來，但我們也是我們成為誰的建築師。', vocab: [{ word: 'architects', def: '建築師、設計者' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'take with a grain of salt', zh: '保留一點懷疑', example: "Take online personality tests with a grain of salt — they're a starting point, not a verdict." },
    { en: 'shadow side', zh: '陰暗面', example: "Every strength has a shadow side — determination can become stubbornness." },
    { en: 'paradox of competence', zh: '能力的悖論', example: "The paradox of competence is that people stop offering help when you seem to have everything under control." },
    { en: 'mask slip', zh: '面具滑落、露出真面目', example: "Letting the mask slip occasionally builds deeper trust with people." },
    { en: 'counterproductive', zh: '適得其反的', example: "Working long hours without rest is often counterproductive." },
    { en: 'reassuring', zh: '令人安慰的', example: "It's reassuring to know that character can be developed over time." },
    { en: 'conscientious', zh: '認真負責的', example: "She is one of the most conscientious people I've worked with — always thorough and reliable." },
    { en: 'default responses', zh: '預設反應', example: "Stress reveals your default responses — how you behave when you're not thinking carefully." },
    { en: 'agency', zh: '主體性、自主能力', example: "Having a sense of agency means believing that your choices matter." },
    { en: 'architects of who we become', zh: '我們成為誰的建築師', example: "We are the architects of who we become — our choices shape us daily." },
  ],
  },

  // Day 2
  {
  weekNumber: 15,
  dayOfWeek: 2,
  date: '2026-04-07',
  theme: 'Personality & Character',
  title: 'First Impressions and Personality Signals',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — The Fast Judgments We Make',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "Jamie, do you trust your first impressions of people?", zh: 'Jamie，你相信自己對人的第一印象嗎？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Only a little. First impressions tell me something real, but usually not the whole truth.", zh: '只會相信一點點。第一印象會告訴我一些真實的東西，但通常不是全部的真相。', vocab: [{ word: 'the whole truth', def: '完整真相' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I agree. They can be emotionally accurate before they're factually accurate.", zh: '我同意。它們常常在情緒上很準，但在事實上還不夠準。', vocab: [{ word: 'factually accurate', def: '在事實上準確的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Exactly. Someone may seem cold when they're actually shy, or confident when they're simply socially practiced.", zh: '正是。有些人看起來冷，其實只是害羞；有些人看起來很有自信，其實只是很會社交。', vocab: [{ word: 'socially practiced', def: '社交上很熟練的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "We underestimate how much context shapes those first few minutes.", zh: '我們低估了情境對前幾分鐘印象的影響。', vocab: [{ word: 'underestimate', def: '低估' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And then we build stories too quickly. One moment becomes a whole personality.", zh: '然後我們太快開始編故事。一個瞬間就被我們當成整個人格。', vocab: [{ word: 'build stories', def: '自行腦補情節' }] },
      ],
    },
    {
      title: 'Part 2 — The Signals We Send',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What do you think people notice first, before they even understand your words?", zh: '你覺得在人們真的聽懂你說什麼之前，他們先注意到的是什麼？' },
        { speaker: 'a', speakerName: 'Mira', en: "Posture, eye contact, pace of speech, whether you seem tense or relaxed.", zh: '姿勢、眼神接觸、說話速度，還有你看起來緊繃還是放鬆。', vocab: [{ word: 'posture', def: '姿勢' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "It's strange how much meaning people can attach to signals that aren't always intentional.", zh: '很奇怪，人們會替那些不一定是刻意發出的訊號加上很多意思。', vocab: [{ word: 'attach meaning', def: '賦予意義' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes. A reserved person can be read as distant, and a nervous person can be read as overly cheerful.", zh: '對。內斂的人可能被讀成疏離，而緊張的人可能被讀成過度熱情。', vocab: [{ word: 'reserved', def: '內斂的' }, { word: 'distant', def: '有距離感的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So style gets noticed first, but character takes longer.", zh: '所以人最先注意到的是風格，但品格需要更久。', vocab: [{ word: 'character', def: '品格' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Anybody can have a polished first ten minutes. Consistency is what tells the deeper story.", zh: '正是。任何人都可能有一個很圓滑的前十分鐘。真正說明更深層故事的是一致性。', vocab: [{ word: 'polished', def: '圓滑成熟的' }, { word: 'consistency', def: '一致性' }] },
      ],
    },
    {
      title: 'Part 3 — Misreading Other People',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "Have you ever been completely wrong about someone at first?", zh: '你有沒有曾經對某個人一開始完全看錯？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Many times. Some of the kindest people I've known first seemed intimidating because they were quiet and serious.", zh: '很多次。我認識的一些最善良的人，一開始反而很讓人有壓力，因為他們安靜又嚴肅。', vocab: [{ word: 'intimidating', def: '讓人有壓力、畏懼的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I've had the opposite too. Charming at first, but unreliable over time.", zh: '我也遇過相反的。一開始很有魅力，但久了發現其實不可靠。', vocab: [{ word: 'charming', def: '有魅力的' }, { word: 'unreliable', def: '不可靠的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's why charisma can be misleading. It can feel like depth when it's really just fluency.", zh: '這就是為什麼魅力可能會誤導人。它會讓人以為那是深度，但有時其實只是流暢。', vocab: [{ word: 'misleading', def: '誤導人的' }, { word: 'fluency', def: '流暢度' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And silence can be misleading too. We project a lot onto quiet people.", zh: '而沉默本身也可能誤導人。我們很容易把很多東西投射到安靜的人身上。', vocab: [{ word: 'project onto', def: '投射到…身上' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Which says as much about the observer as the person being observed.", zh: '而那其實和觀察者本身有關，和被觀察的人一樣多。', vocab: [{ word: 'observer', def: '觀察者' }] },
      ],
    },
    {
      title: 'Part 4 — Managing the Impression You Make',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do you think it's worth trying to manage the impression you give people?", zh: '你覺得刻意管理自己給別人的印象值得嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "To a degree, yes. Not by pretending, but by noticing whether your signals match your intentions.", zh: '某種程度上值得。不是靠假裝，而是留意你發出的訊號是否符合你的本意。', vocab: [{ word: 'to a degree', def: '某種程度上' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So it's more like adjusting presentation than inventing a fake self.", zh: '所以比較像調整呈現方式，而不是發明一個假的自己。', vocab: [{ word: 'presentation', def: '呈現方式' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. If you know you tend to seem distant, you can bring a little more warmth into your voice or your face.", zh: '正是。如果你知道自己容易看起來有距離，你可以在語氣或表情裡多帶一點溫度。' },
        { speaker: 'b', speakerName: 'Jamie', en: "That makes first impressions feel less mysterious and more trainable.", zh: '那讓第一印象這件事聽起來比較不神祕，而比較像可以訓練。', vocab: [{ word: 'trainable', def: '可以訓練的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I think they are. You can't control them perfectly, but you can influence them consciously.", zh: '我覺得確實是。你不能完美控制它，但你可以有意識地影響它。', vocab: [{ word: 'consciously', def: '有意識地' }] },
      ],
    },
    {
      title: 'Part 5 — Giving People More Time',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "The older I get, the less I want to make strong judgments quickly.", zh: '我年紀越大，就越不想太快對人下定論。' },
        { speaker: 'b', speakerName: 'Jamie', en: "Because you've learned how often first impressions change?", zh: '因為你已經看過第一印象有多常會改變？' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. The second and third impression are often more useful. That's when consistency starts showing up.", zh: '正是。第二、第三印象通常更有用。因為那時候一致性才開始出現。' },
        { speaker: 'b', speakerName: 'Jamie', en: "So curiosity should probably come before certainty.", zh: '所以好奇心大概應該先於定論。', vocab: [{ word: 'certainty', def: '定論、確定感' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I think that's the kindest way to meet people — leave room for surprise.", zh: '我覺得那是遇見人的最善良方式：替驚喜保留空間。', vocab: [{ word: 'leave room for surprise', def: '替驚喜保留空間' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And probably the wisest way too. Most people are more layered than they first appear.", zh: '而且那大概也是最有智慧的方式。大多數人都比第一眼看起來更有層次。', vocab: [{ word: 'layered', def: '有層次的' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'factually accurate', zh: '在事實上準確的', example: "A first impression may feel right emotionally before it becomes factually accurate." },
    { en: 'reserved', zh: '內斂的', example: "She seems reserved at first, but opens up once she feels safe." },
    { en: 'charisma can be misleading', zh: '魅力可能會誤導人', example: "Charisma can be misleading if you mistake it for depth or reliability." },
    { en: 'project onto', zh: '投射到', example: "We often project our own assumptions onto quiet people." },
    { en: 'polished', zh: '圓滑成熟的', example: "A polished first impression does not always reveal real character." },
    { en: 'consistency', zh: '一致性', example: "Consistency tells you more than a charming first meeting." },
    { en: 'presentation', zh: '呈現方式', example: "You can adjust your presentation without becoming fake." },
    { en: 'trainable', zh: '可以訓練的', example: "Social warmth is trainable, even if it does not come naturally." },
    { en: 'certainty', zh: '定論', example: "Curiosity should come before certainty when meeting someone new." },
    { en: 'layered', zh: '有層次的', example: "People are more layered than they first appear." },
  ],
  },

  // Day 3
  {
  weekNumber: 15,
  dayOfWeek: 3,
  date: '2026-04-08',
  theme: 'Personality & Character',
  title: 'Introversion, Extroversion, and Social Energy',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — Beyond Simple Labels',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do you think people are really just introverts or extroverts, or is that too simple?", zh: '你覺得人真的就只是內向或外向兩種嗎，還是這樣太簡化了？' },
        { speaker: 'a', speakerName: 'Mira', en: "It's too simple. The labels are useful, but most people are much more situational than they realize.", zh: '那樣太簡化了。這些標籤有用，但大多數人其實比自己想的更受情境影響。', vocab: [{ word: 'situational', def: '受情境影響的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Meaning the same person can be lively in one setting and quiet in another.", zh: '意思是同一個人在某個場合很活躍，在另一個場合卻很安靜。' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Around close friends, someone may seem outgoing. In a loud unfamiliar room, the same person may shut down.", zh: '正是。和熟人相處時，一個人可能很外向；但在吵雜又陌生的場合，同一個人可能會整個安靜下來。', vocab: [{ word: 'outgoing', def: '外向的、健談的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So the real question is probably what gives you energy and what drains it.", zh: '所以真正的問題大概是，什麼給你能量，什麼耗掉你能量。', vocab: [{ word: 'drain', def: '耗盡' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes. That's much more useful than turning personality into a fixed identity.", zh: '對。那比把個性變成固定身分認同要有用得多。', vocab: [{ word: 'fixed identity', def: '固定身分認同' }] },
      ],
    },
    {
      title: 'Part 2 — Social Energy Is Real',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "How would you describe your social energy these days?", zh: '你會怎麼描述自己最近的社交能量？' },
        { speaker: 'b', speakerName: 'Jamie', en: "More limited than when I was younger. I still enjoy people, but I notice my social battery much more clearly now.", zh: '比年輕時更有限了。我還是喜歡人群，但我現在更清楚感受到自己的社交電量。', vocab: [{ word: 'social battery', def: '社交電量' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I relate to that. I used to think feeling tired after socializing meant something was wrong with me.", zh: '我很能理解。我以前以為社交完會累，代表我有什麼問題。' },
        { speaker: 'b', speakerName: 'Jamie', en: "But now you read that tiredness as information, not failure.", zh: '但現在你會把那個疲累看成資訊，而不是失敗。', vocab: [{ word: 'read as information', def: '把…視為資訊' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Once you stop judging yourself for needing recovery time, you can build a healthier social life.", zh: '正是。當你不再因為自己需要恢復時間而批評自己，你就能建立更健康的社交生活。', vocab: [{ word: 'recovery time', def: '恢復時間' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And that self-judgment is often worse than the tiredness itself.", zh: '而那種自我批評常常比疲倦本身更消耗人。', vocab: [{ word: 'self-judgment', def: '自我批判' }] },
      ],
    },
    {
      title: 'Part 3 — The Different Faces of Extroversion',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "People talk about extroverts like they all behave the same way, but that can't be right.", zh: '人們講外向的人，好像他們都表現得一模一樣，但那不可能是真的。' },
        { speaker: 'a', speakerName: 'Mira', en: "Definitely not. Some extroverts are loud and expressive. Others are calm but become more alive in interaction than in solitude.", zh: '當然不是。有些外向的人很外顯；另一些很沉穩，但在互動中會比在獨處時更有精神。', vocab: [{ word: 'expressive', def: '外顯的、表達豐富的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So extroversion isn't just about volume. Sometimes it's really about stimulation.", zh: '所以外向不只是音量大。有時候它其實更像對刺激的需求。', vocab: [{ word: 'stimulation', def: '刺激' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And introversion isn't the same as shyness. Plenty of introverts are socially skilled; they just prefer depth over frequency.", zh: '而內向也不等於害羞。很多內向的人社交能力很好；他們只是更偏好深度而不是頻率。', vocab: [{ word: 'depth over frequency', def: '重深度勝於頻率' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's important because people confuse introversion with insecurity all the time.", zh: '那很重要，因為人們一直在把內向和沒安全感搞混。', vocab: [{ word: 'insecurity', def: '缺乏安全感' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. These traits describe how we orient to energy, not how mature or capable we are.", zh: '正是。這些特質描述的是我們如何面對能量，而不是我們有多成熟或多有能力。', vocab: [{ word: 'orient to', def: '朝向、面對' }] },
      ],
    },
    {
      title: 'Part 4 — Designing a Social Life That Fits',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "One of the best adult skills is designing a social life that actually fits your temperament.", zh: '成年後很重要的一個技能，就是設計一個真正適合自己氣質的社交生活。', vocab: [{ word: 'temperament', def: '氣質' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Instead of copying whatever social life looks impressive from the outside.", zh: '而不是照抄那種從外面看起來很精彩的社交生活。', vocab: [{ word: 'impressive', def: '看起來很厲害、很令人羨慕的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Some people genuinely enjoy back-to-back events. Others do better with one quiet coffee and an early night.", zh: '正是。有些人真的喜歡一場接一場的活動；另一些人比較適合安靜喝杯咖啡，然後早點回家。', vocab: [{ word: 'back-to-back', def: '接連不斷的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The problem is that people often judge themselves by someone else's ideal rhythm.", zh: '問題是，人們常常用別人的理想節奏來評價自己。', vocab: [{ word: 'rhythm', def: '節奏' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And that creates shame for no reason. A smaller social life is not automatically a lesser one.", zh: '而那會製造很多沒必要的羞愧感。社交生活比較小，不代表它比較差。', vocab: [{ word: 'lesser', def: '較次等的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The goal isn't maximum activity. It's meaningful connection without chronic exhaustion.", zh: '目標不是把活動排到最大，而是有意義的連結，同時不讓自己長期耗盡。', vocab: [{ word: 'chronic exhaustion', def: '長期疲憊' }] },
      ],
    },
    {
      title: "Part 5 — Respecting Other People's Energy Too",
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Understanding your own social energy probably makes you kinder toward other people's limits too.", zh: '理解自己的社交能量，大概也會讓你更能體諒別人的界線。' },
        { speaker: 'a', speakerName: 'Mira', en: "Definitely. Once you stop moralizing personality differences, you stop taking everything personally.", zh: '絕對會。一旦你不再把個性差異道德化，你就不會把很多事情都往心裡去。', vocab: [{ word: 'moralizing', def: '道德化地評價' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So if a friend leaves early, you don't assume they're bored or rude.", zh: '所以如果朋友提早離開，你就不會立刻覺得他是無聊或沒禮貌。' },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. And if someone talks a lot, you don't automatically decide they're shallow or attention-seeking.", zh: '正是。而如果有人講很多，你也不會立刻認定他膚淺或愛出風頭。', vocab: [{ word: 'attention-seeking', def: '愛吸引注意的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That feels much more generous than trying to decide which personality style is better.", zh: '那比起一直想分出哪種個性比較好，真的寬厚得多。', vocab: [{ word: 'generous', def: '寬厚的、慷慨的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I think that's the mature version of personality talk: less labeling, more understanding.", zh: '我覺得那才是成熟版的個性討論：少一點標籤，多一點理解。', vocab: [{ word: 'labeling', def: '貼標籤' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'social battery', zh: '社交電量', example: "After a full day of meetings, my social battery is completely empty." },
    { en: 'recovery time', zh: '恢復時間', example: "I need recovery time after a big gathering, even if I enjoyed it." },
    { en: 'depth over frequency', zh: '重深度勝於頻率', example: "Some people prefer depth over frequency in their social lives." },
    { en: 'stimulation', zh: '刺激', example: "Extroversion is often more about stimulation than volume." },
    { en: 'temperament', zh: '氣質', example: "Life gets easier when your schedule matches your temperament." },
    { en: 'back-to-back', zh: '接連不斷的', example: "Back-to-back events can be fun for some people and exhausting for others." },
    { en: 'chronic exhaustion', zh: '長期疲憊', example: "A healthy social life should not lead to chronic exhaustion." },
    { en: 'moralizing', zh: '道德化地評價', example: "We should stop moralizing the difference between introverts and extroverts." },
    { en: 'attention-seeking', zh: '愛吸引注意的', example: "Talking a lot doesn't always mean someone is attention-seeking." },
    { en: 'less labeling, more understanding', zh: '少貼標籤，多理解', example: "The mature version of personality talk is less labeling, more understanding." },
  ],
  },

  // Day 4
  {
  weekNumber: 15,
  dayOfWeek: 4,
  date: '2026-04-09',
  theme: 'Personality & Character',
  title: 'Traits We Admire in Other People',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — What Stands Out First',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "When you meet someone you truly admire, what quality usually stands out first?", zh: '當你遇到一個你真心欣賞的人時，通常最先注意到的是什麼特質？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Calmness, actually. Not passivity — just that grounded feeling that they don't get thrown around by everything.", zh: '其實是沉穩。不是消極，而是那種很穩的感覺，不會被每一件事拉著跑。', vocab: [{ word: 'grounded', def: '沉穩踏實的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I know what you mean. Some people make you feel calmer just by the way they carry themselves.", zh: '我懂。有些人光是站在那裡，光是他們的狀態，就會讓你也一起冷靜下來。', vocab: [{ word: 'carry themselves', def: '展現自己的方式、舉止' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And I admire people who are quietly confident — people who don't need to dominate a room to have presence.", zh: '而且我也很欣賞安靜但有自信的人，就是那種不需要主導全場卻很有存在感的人。', vocab: [{ word: 'dominate a room', def: '主導全場氣氛' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Confidence without performance. That's one of the most attractive qualities there is.", zh: '那是一種不用表演的自信。那真的是最吸引人的特質之一。', vocab: [{ word: 'attractive quality', def: '吸引人的特質' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "For me, admiration often begins where ego is low and steadiness is high.", zh: '對我來說，欣賞常常始於自我感很低、穩定感很高的地方。', vocab: [{ word: 'steadiness', def: '穩定沉著' }] },
      ],
    },
    {
      title: 'Part 2 — Quiet Virtues',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Some of the best traits are quiet ones, don't you think?", zh: '你不覺得一些最好的特質其實都很安靜嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "Definitely. Humility, patience, reliability — they don't always look dramatic, but they shape everything.", zh: '絕對是。謙遜、耐心、可靠，這些不一定很搶眼，但它們會影響一切。', vocab: [{ word: 'humility', def: '謙遜' }, { word: 'reliability', def: '可靠性' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Society rewards charisma first, but real life depends on steadier qualities.", zh: '社會通常先獎勵魅力，但真實生活最後靠的是更穩定的品質。', vocab: [{ word: 'charisma', def: '魅力' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. A dazzling person can be exciting. A dependable person can change your life.", zh: '正是。耀眼的人也許很精彩，但可靠的人是真的會改變你的人生。', vocab: [{ word: 'dependable', def: '值得依靠的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "I also admire generosity when it isn't performative.", zh: '我也很欣賞那種不是做給人看的慷慨。', vocab: [{ word: 'generosity', def: '慷慨' }, { word: 'performative', def: '表演性的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Real generosity often looks like time, attention, patience, and remembering what matters to someone.", zh: '真正的慷慨常常看起來像時間、關注、耐心，還有記得別人在乎什麼。', vocab: [{ word: 'attention', def: '關注、注意力' }] },
      ],
    },
    {
      title: 'Part 3 — Admiration and Aspiration',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "Do you think the qualities we admire most are often the ones we want to grow in ourselves?", zh: '你覺得我們最欣賞的特質，常常也是我們想在自己身上長出來的嗎？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Absolutely. Admiration is often a clue. It points to something we feel the lack of in ourselves.", zh: '絕對是。欣賞常常是一種線索。它會指向我們在自己身上感到缺少的東西。', vocab: [{ word: 'clue', def: '線索' }] },
        { speaker: 'a', speakerName: 'Mira', en: "So admiration can be aspirational, not just appreciative.", zh: '所以欣賞可以是帶著嚮往的，不只是帶著欣賞的。', vocab: [{ word: 'aspirational', def: '帶有嚮往意味的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Yes, though it turns unhealthy the moment it becomes comparison instead of inspiration.", zh: '對，不過只要它變成比較而不是啟發，就會開始不健康。', vocab: [{ word: 'inspiration', def: '啟發' }] },
        { speaker: 'a', speakerName: 'Mira', en: "The point isn't to imitate someone else's personality. It's to understand what quality in them feels true and beautiful to you.", zh: '重點不是去模仿別人的個性，而是理解在對方身上，哪個品質讓你覺得真、覺得美。', vocab: [{ word: 'imitate', def: '模仿' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's a kinder framework. You can admire without shrinking yourself.", zh: '那是一個更善良的框架。你可以欣賞，而不用因此縮小自己。', vocab: [{ word: 'shrink yourself', def: '讓自己變得渺小' }] },
      ],
    },
    {
      title: 'Part 4 — Character Under Pressure',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "I think character becomes clearest when life gets difficult.", zh: '我覺得一個人的品格在生活變難時會最清楚。' },
        { speaker: 'a', speakerName: 'Mira', en: "Definitely. It's easy to be patient and kind when everything is going well.", zh: '絕對是。當一切都順時，要有耐心和善良並不難。', vocab: [{ word: 'going well', def: '進展順利' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The real test is who you become when you're stressed, disappointed, or afraid.", zh: '真正的考驗是，當你有壓力、失望或害怕時，你會成為怎樣的人。', vocab: [{ word: 'real test', def: '真正的考驗' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Pressure doesn't create character from nothing, but it does reveal what's already there.", zh: '壓力不會憑空創造品格，但它會揭露那裡原本就有的東西。', vocab: [{ word: 'reveal', def: '揭露、顯現' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's why I admire people who stay kind when they have every reason not to.", zh: '這就是為什麼我很欣賞那些即使完全有理由不那麼做，仍然保持善良的人。', vocab: [{ word: 'have every reason not to', def: '完全有理由不這麼做' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Same. Pride can look strong, but accountability is usually stronger.", zh: '我也是。驕傲有時看起來很強，但真正更強的通常是負責。', vocab: [{ word: 'accountability', def: '負責、擔當' }] },
      ],
    },
    {
      title: 'Part 5 — Qualities We Practice',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "I like thinking of admirable traits as things we practice, not just things we're born with.", zh: '我喜歡把那些令人欣賞的品質看成是可以練習的，不只是天生有沒有。' },
        { speaker: 'b', speakerName: 'Jamie', en: "That's hopeful. It means character isn't fixed — it's built.", zh: '那個想法很有希望。它代表品格不是固定的，而是被建造出來的。', vocab: [{ word: 'fixed', def: '固定不變的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Maybe no one becomes generous or brave all at once. Maybe it happens through repetition.", zh: '也許沒有人會一下子變得慷慨或勇敢。也許這些都是透過重複慢慢形成的。', vocab: [{ word: 'repetition', def: '反覆練習' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That takes some pressure off. You don't have to be perfect immediately. You just keep choosing in the right direction.", zh: '那會少很多壓力。你不需要立刻完美，只要持續往對的方向做選擇。', vocab: [{ word: 'take pressure off', def: '減輕壓力' }] },
        { speaker: 'a', speakerName: 'Mira', en: "The best people don't make you feel small. They make you want to become better.", zh: '最好的人不會讓你覺得自己變小，他們會讓你想變得更好。', vocab: [{ word: 'become better', def: '變得更好' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's probably the clearest sign of real character — it doesn't just impress people, it elevates them.", zh: '那大概就是真正品格最明顯的標誌：它不只是讓人印象深刻，它還會把別人一起往上帶。', vocab: [{ word: 'elevate', def: '提升' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'grounded', zh: '沉穩踏實的', example: "She has a grounded presence that makes other people feel calm." },
    { en: 'integrity', zh: '正直', example: "I admire people whose integrity stays consistent in private and in public." },
    { en: 'humility', zh: '謙遜', example: "Humility is one of the quietest and strongest forms of confidence." },
    { en: 'dependable', zh: '值得依靠的', example: "Exciting people are fun, but dependable people change your life." },
    { en: 'aspirational', zh: '帶有嚮往意味的', example: "Sometimes admiration is aspirational — it shows you what you want to grow into." },
    { en: 'accountability', zh: '負責擔當', example: "Accountability is often more impressive than pride." },
    { en: 'repetition', zh: '反覆練習', example: "Patience is usually built through repetition, not one dramatic breakthrough." },
    { en: 'take pressure off', zh: '減輕壓力', example: "Thinking of character as practice can take pressure off." },
    { en: 'become better', zh: '變得更好', example: "The best people make you want to become better." },
    { en: 'elevate', zh: '提升', example: "Real character does not just impress people — it elevates them." },
  ],
  },

  // Day 5
  {
  weekNumber: 15,
  dayOfWeek: 5,
  date: '2026-04-10',
  theme: 'Personality & Character',
  title: 'Flaws, Habits, and Personal Growth',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — Knowing Is Not the Same as Changing',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do you think most people know their main flaws pretty well?", zh: '你覺得大多數人其實都滿清楚自己的主要缺點嗎？' },
        { speaker: 'a', speakerName: 'Mira', en: "Some do, but knowing a flaw and changing it are very different things. Awareness is only the beginning.", zh: '有些人知道，但知道和改變是很不一樣的事。覺察通常只是開始。', vocab: [{ word: 'awareness', def: '覺察' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "A lot of people can say, 'I'm impatient' or 'I get defensive,' but they still don't know what to do with that information.", zh: '很多人可以說「我很沒耐心」或「我很容易防衛」，但還是不知道拿這個資訊怎麼辦。', vocab: [{ word: 'defensive', def: '防衛性的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Naming something can feel like progress, but sometimes it's just a more polished excuse.", zh: '正是。把問題說出來會讓人以為自己有進步，但有時那只是更精緻的藉口。', vocab: [{ word: 'polished excuse', def: '包裝得比較好看的藉口' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Like when someone says, 'That's just how I am,' and acts as if that settles everything.", zh: '就像有人說「我就是這樣」，然後好像事情就這樣結束了一樣。' },
        { speaker: 'a', speakerName: 'Mira', en: "Real self-knowledge should make you more responsible, not less.", zh: '真正的自我了解應該讓你更有責任感，而不是更少。', vocab: [{ word: 'self-knowledge', def: '自我了解' }] },
      ],
    },
    {
      title: 'Part 2 — Habits Protect Our Flaws',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "A lot of personality flaws are really habits repeated so often that they feel natural.", zh: '很多所謂的個性缺點，其實只是重複太久而看起來像天性的習慣。', vocab: [{ word: 'repeated so often', def: '因長期重複而固定下來' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That makes sense. If you've snapped under stress for years, it starts to feel like a trait instead of a pattern.", zh: '那說得通。如果你多年來都在壓力下急躁發火，它就會開始看起來像一種特質，而不是一個模式。', vocab: [{ word: 'snap under stress', def: '在壓力下突然發火' }] },
        { speaker: 'a', speakerName: 'Mira', en: "And habits happen quickly, which is why they protect the flaw. You act first and understand later.", zh: '而習慣發生得很快，這就是為什麼它會保護那個缺點。你先做了，之後才明白。', vocab: [{ word: 'act first, understand later', def: '先反應，後理解' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So change requires slowing down enough to interrupt something that feels automatic.", zh: '所以改變需要你放慢到足以打斷一個看起來像自動發生的東西。', vocab: [{ word: 'interrupt', def: '打斷' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Which usually means noticing triggers — fatigue, shame, insecurity, feeling ignored.", zh: '而那通常意味著你得留意觸發點：疲倦、羞愧、不安、被忽略感。', vocab: [{ word: 'triggers', def: '觸發點' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's why harsh self-judgment helps less than people think. It makes you tense, not flexible.", zh: '這也是為什麼苛刻的自我批評沒有大家想像中那麼有用。它會讓你緊繃，而不是更有彈性。', vocab: [{ word: 'self-judgment', def: '自我批判' }] },
      ],
    },
    {
      title: 'Part 3 — Blind Spots and Feedback',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What about the flaws we don't see at all? The real blind spots.", zh: '那那些我們根本看不見的缺點呢？真正的盲點那種。' },
        { speaker: 'a', speakerName: 'Mira', en: "Those are the hardest, because by definition you can't reach them alone. That's where feedback matters.", zh: '那是最難的，因為按定義來說，你自己一個人碰不到它們。那就是反饋重要的地方。', vocab: [{ word: 'blind spot', def: '盲點' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Feedback is especially hard when it feels like it's about your identity instead of one specific action.", zh: '如果反饋讓人覺得它是在講你整個人，而不是一個具體行為，就會特別難聽進去。', vocab: [{ word: 'specific action', def: '具體行為' }] },
        { speaker: 'a', speakerName: 'Mira', en: "That's why the most useful feedback is behavioral: 'You interrupt people when you're excited' is more helpful than 'You're selfish.'", zh: '這就是為什麼最有用的反饋通常是行為層面的：「你興奮時會打斷別人」比「你很自私」更有幫助。', vocab: [{ word: 'behavioral', def: '行為層面的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Because behavior gives you something to work with. Labels just make you defensive.", zh: '因為行為會給你一個可以處理的東西，而標籤只會讓你進入防衛。', vocab: [{ word: 'labels', def: '標籤化說法' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Useful feedback should create clarity, not just pain.", zh: '正是。有用的反饋應該帶來清晰，而不只是痛。', vocab: [{ word: 'clarity', def: '清楚明白' }] },
      ],
    },
    {
      title: 'Part 4 — Slow Growth Is Real Growth',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "People underestimate how slow personal growth usually is.", zh: '人們常常低估個人成長通常有多慢。', vocab: [{ word: 'underestimate', def: '低估' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "We want one breakthrough conversation and then to be different forever.", zh: '我們都想要一場突破性的對話，然後自己就從此完全不同。', vocab: [{ word: 'breakthrough', def: '突破性時刻' }] },
        { speaker: 'a', speakerName: 'Mira', en: "But most change looks like the same old situation handled slightly better than last time.", zh: '但大多數改變看起來更像是，同樣的老情境被你比上次處理得稍微好一點。', vocab: [{ word: 'slightly better', def: '稍微好一點' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That can feel discouraging while you're living it, because the progress is so small.", zh: '那在當下可能會讓人很洩氣，因為那種進步實在太小了。', vocab: [{ word: 'discouraging', def: '令人沮喪的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "But small progress compounds. One better apology, one extra pause, one less sharp comment — it adds up.", zh: '但小進步會累積。一句更好的道歉、一個多出來的停頓、少一句尖銳的話，久了就會加總起來。', vocab: [{ word: 'compound', def: '累積產生效果' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That makes growth less glamorous, but much more believable.", zh: '那讓成長聽起來沒那麼光鮮，但更可信。', vocab: [{ word: 'glamorous', def: '光鮮亮麗的' }] },
      ],
    },
    {
      title: 'Part 5 — Responsibility Over Perfection',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Maybe maturity isn't becoming flawless. Maybe it's becoming more responsible for your flaws.", zh: '也許成熟不是變得毫無缺點，也許是對自己的缺點更負責。', vocab: [{ word: 'maturity', def: '成熟' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I think that's exactly right. You may still have the same weak spots, but they stop running the whole room.", zh: '我覺得完全是這樣。你可能還是有一樣的弱點，但它們不再主導整個場子。', vocab: [{ word: 'weak spots', def: '弱點、脆弱處' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "And people trust you more, not because you're perfect, but because you're honest about your patterns.", zh: '而且人們會更信任你，不是因為你完美，而是因為你對自己的模式夠誠實。', vocab: [{ word: 'patterns', def: '慣性模式' }] },
        { speaker: 'a', speakerName: 'Mira', en: "There's something reassuring about people who know where they're difficult and are actively working on it.", zh: '當一個人知道自己哪裡難相處，而且真的有在處理它時，會給人很深的安心感。', vocab: [{ word: 'reassuring', def: '讓人安心的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So growth isn't self-erasure. It's honest management.", zh: '所以成長不是把自己抹掉，而是誠實地管理自己。', vocab: [{ word: 'self-erasure', def: '抹除自我' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes. You become more trustworthy not by having no rough edges, but by taking responsibility for them.", zh: '對。你變得更值得信任，不是因為你沒有稜角，而是因為你願意對那些稜角負責。', vocab: [{ word: 'rough edges', def: '稜角、讓人不舒服的部分' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'awareness is only the beginning', zh: '覺察只是開始', example: "Awareness is only the beginning; real change starts in behavior." },
    { en: 'defensive', zh: '防衛性的', example: "I get defensive when feedback feels like an attack rather than help." },
    { en: 'trigger', zh: '觸發點', example: "Understanding your trigger makes it easier to interrupt a bad habit." },
    { en: 'behavioral feedback', zh: '行為層面的反饋', example: "Behavioral feedback is more useful than vague labels." },
    { en: 'small progress compounds', zh: '小進步會累積', example: "Small progress compounds, even when it feels invisible day to day." },
    { en: 'maturity', zh: '成熟', example: "Maturity often means taking responsibility for your flaws." },
    { en: 'reassuring', zh: '讓人安心的', example: "Self-awareness is reassuring when it comes with responsibility." },
    { en: 'self-erasure', zh: '抹除自我', example: "Growth is not self-erasure; it's honest management." },
    { en: 'rough edges', zh: '稜角', example: "Everyone has rough edges, but not everyone takes responsibility for them." },
    { en: 'honest management', zh: '誠實地管理自己', example: "Personal growth is less about perfection and more about honest management." },
  ],
  },

  // Day 6
  {
  weekNumber: 15,
  dayOfWeek: 6,
  date: '2026-04-11',
  theme: 'Personality & Character',
  title: 'How Personality Shapes Relationships',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — Different People, Different Rhythms',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "Do you think relationships get easier once you understand personality differences better?", zh: '你覺得當你更懂個性差異之後，關係會變得比較容易嗎？' },
        { speaker: 'b', speakerName: 'Jamie', en: "Definitely. A lot of conflict is just misread personality. People assume bad intentions when it's often just a different rhythm.", zh: '絕對會。很多衝突其實只是對個性的誤讀。人們常常以為對方有惡意，但很多時候只是節奏不同。', vocab: [{ word: 'bad intentions', def: '惡意、不良意圖' }] },
        { speaker: 'a', speakerName: 'Mira', en: "One person needs space to process, and the other reads that space as withdrawal.", zh: '一個人需要空間整理，另一個人卻把那個空間讀成抽離。', vocab: [{ word: 'withdrawal', def: '抽離、退縮' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Or one person is very direct, and the other experiences that directness as harshness.", zh: '或者一個人很直接，另一個人卻把那份直接感受成尖銳。', vocab: [{ word: 'harshness', def: '尖銳、生硬' }] },
        { speaker: 'a', speakerName: 'Mira', en: "The same behavior can feel honest to one person and hurtful to another.", zh: '同一個行為，對一個人來說可能是誠實，對另一個人來說卻是傷人。' },
        { speaker: 'b', speakerName: 'Jamie', en: "That's why compatibility is partly about understanding how each person is wired.", zh: '這就是為什麼相容性有一部分是在於理解每個人是怎麼被組成的。', vocab: [{ word: 'compatibility', def: '相容性、合得來' }] },
      ],
    },
    {
      title: 'Part 2 — Similarity and Difference',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "Do we choose people who are like us, or people who balance us out?", zh: '我們會選跟自己像的人，還是會選能平衡自己的人？' },
        { speaker: 'a', speakerName: 'Mira', en: "Probably both. Similarity creates ease, but difference creates growth.", zh: '大概兩種都會。相似會帶來輕鬆感，差異則會帶來成長。', vocab: [{ word: 'similarity', def: '相似性' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Too much similarity can get stagnant, but too much difference can become exhausting.", zh: '太相似會停滯，太不同又會讓人很累。', vocab: [{ word: 'stagnant', def: '停滯不前的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "In friendship especially, people need enough overlap to feel understood and enough difference to stay interesting.", zh: '尤其在友誼裡，人需要有足夠重疊的地方來感到被理解，也需要有足夠不同來保持有趣。', vocab: [{ word: 'overlap', def: '重疊處、共同點' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "The healthiest relationships let difference become information instead of blame.", zh: '最健康的關係，會讓差異變成資訊，而不是責怪。', vocab: [{ word: 'blame', def: '責怪' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Better language often creates better relationships.", zh: '正是。更好的語言，常常會創造更好的關係。', vocab: [{ word: 'better language', def: '更好的表達方式' }] },
      ],
    },
    {
      title: 'Part 3 — Conflict Styles',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "Conflict style is one of the clearest ways personality shows up in relationships.", zh: '衝突風格是個性在關係裡最清楚顯現的一種方式。', vocab: [{ word: 'conflict style', def: '衝突風格' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Some people want to talk immediately. Others need hours before they can respond clearly.", zh: '有些人想立刻談清楚；另一些人則需要幾個小時，才能清楚回應。', vocab: [{ word: 'respond clearly', def: '清楚地回應' }] },
        { speaker: 'a', speakerName: 'Mira', en: "If those two people don't understand each other, both feel abandoned in different ways.", zh: '如果這兩種人彼此不理解，他們都會以不同方式感到被丟下。', vocab: [{ word: 'abandoned', def: '被拋下的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "One feels chased, the other feels shut out.", zh: '一個人覺得自己被逼著追著談，另一個人則覺得自己被關在門外。', vocab: [{ word: 'shut out', def: '被排除在外' }] },
        { speaker: 'a', speakerName: 'Mira', en: "That's why self-awareness is relational. You need to know what version of you appears under stress.", zh: '這就是為什麼自我覺察本身是關係性的。你得知道自己在壓力下會冒出哪個版本。', vocab: [{ word: 'relational', def: '與關係有關的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Relationships reveal parts of us we don't usually notice alone.", zh: '關係會揭露我們一個人時不會注意到的部分。', vocab: [{ word: 'reveal', def: '揭露' }] },
      ],
    },
    {
      title: 'Part 4 — Adapting Without Losing Yourself',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "How much should people adapt in relationships before it starts feeling false?", zh: '在關係裡，人應該調整到什麼程度，才不會開始感覺很假？' },
        { speaker: 'a', speakerName: 'Mira', en: "Adaptation is healthy when it comes from care, not fear. If it comes from fear, you start shrinking yourself.", zh: '如果調整是出於在乎，它就是健康的；如果是出於害怕，你就會開始縮小自己。', vocab: [{ word: 'adaptation', def: '調整、適應' }, { word: 'shrinking yourself', def: '縮小自己、壓抑自己' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So the question is whether the change still feels chosen.", zh: '所以關鍵是，那個改變是否仍然讓你覺得是自己選的。', vocab: [{ word: 'chosen', def: '出於自願選擇的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Saying something more gently is adaptation. Silencing yourself completely is self-betrayal.", zh: '正是。把話說得更柔和，是調整；把自己整個壓下去，就是背叛自己。', vocab: [{ word: 'self-betrayal', def: '背叛自己' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That line matters. A lot of people confuse kindness with self-erasure.", zh: '那條界線很重要。很多人會把善良和抹除自己搞混。', vocab: [{ word: 'self-erasure', def: '抹除自我' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Good adaptation keeps the truth and changes the delivery.", zh: '好的調整，是保留真實，但改變表達方式。', vocab: [{ word: 'delivery', def: '表達方式' }] },
      ],
    },
    {
      title: 'Part 5 — Loving People Realistically',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "One of the deepest forms of love is understanding someone's personality clearly without idealizing or condemning it.", zh: '愛的一種很深的形式，就是清楚理解一個人的個性，同時既不理想化它，也不譴責它。', vocab: [{ word: 'idealize', def: '理想化' }, { word: 'condemn', def: '譴責' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That sounds like realistic love — not pretending the differences aren't there, but learning how to hold them wisely.", zh: '那聽起來像是很現實的愛。不是假裝差異不存在，而是學會怎麼有智慧地承接它們。', vocab: [{ word: 'hold them wisely', def: '有智慧地承接它們' }] },
        { speaker: 'a', speakerName: 'Mira', en: "The fantasy version of love is 'You fit me perfectly.' The mature version is 'I understand where we differ, and I still choose this.'", zh: '愛的幻想版是「你完美地適合我」；成熟版則是「我知道我們哪裡不同，但我仍然選擇這段關係」。', vocab: [{ word: 'mature version', def: '成熟版本' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's harder, but it also sounds much more stable.", zh: '那難得多，但也聽起來穩定得多。', vocab: [{ word: 'stable', def: '穩定的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Relationships get deeper when personality differences stop being surprises and start becoming known terrain.", zh: '當個性差異不再像意外，而開始像熟悉地形時，關係就會更深。', vocab: [{ word: 'known terrain', def: '熟悉地形；比喻熟悉的相處模式' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Love gets calmer when people stop demanding sameness and start practicing understanding.", zh: '當人們不再要求彼此一模一樣，而開始練習理解時，愛會變得更平靜。', vocab: [{ word: 'sameness', def: '完全一樣' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'compatibility', zh: '相容性', example: "Compatibility is not just shared taste; it's also mutual understanding." },
    { en: 'different rhythm', zh: '不同節奏', example: "A lot of conflict comes from a different rhythm, not bad intentions." },
    { en: 'conflict style', zh: '衝突風格', example: "Understanding someone's conflict style can change a whole relationship." },
    { en: 'overlap', zh: '共同重疊處', example: "Friendships need enough overlap to feel easy and enough difference to stay alive." },
    { en: 'self-betrayal', zh: '背叛自己', example: "Adaptation is healthy until it turns into self-betrayal." },
    { en: 'self-erasure', zh: '抹除自我', example: "Kindness should never require self-erasure." },
    { en: 'delivery', zh: '表達方式', example: "Sometimes the truth is not the problem — the delivery is." },
    { en: 'idealize', zh: '理想化', example: "Loving someone well means not idealizing them." },
    { en: 'known terrain', zh: '熟悉地形', example: "Strong relationships turn personality differences into known terrain." },
    { en: 'sameness', zh: '完全一致', example: "Love gets calmer when people stop demanding sameness." },
  ],
  },

  // Day 7
  {
  weekNumber: 15,
  dayOfWeek: 7,
  date: '2026-04-12',
  theme: 'Personality & Character',
  title: 'Becoming More Fully Yourself',
  phase: 'p2',
  parts: [
    {
      title: 'Part 1 — The Gap Between Image and Self',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What do you think it means to become more fully yourself?", zh: '你覺得「變得更完整地成為自己」是什麼意思？' },
        { speaker: 'a', speakerName: 'Mira', en: "It means becoming less divided. Less split between who you are privately and who you perform publicly.", zh: '我覺得那代表你變得比較不分裂。比較不會在私下的自己和公開表演出的自己之間分裂。', vocab: [{ word: 'divided', def: '分裂的、不一致的' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Most people probably live with that split more than they realize.", zh: '大多數人活在那種分裂裡的程度，大概比自己意識到的還多。', vocab: [{ word: 'split', def: '分裂、落差' }] },
        { speaker: 'a', speakerName: 'Mira', en: "A lot of adulthood is about building identities that help us survive. The problem comes when those strategies stop fitting who we've become.", zh: '成年生活有很大一部分是在建立一些讓我們能活下去的身分。但問題是，當那些策略開始不再適合現在的自己時。', vocab: [{ word: 'survival strategies', def: '生存策略' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So sometimes what looks like personality is actually protection.", zh: '所以有時候看起來像個性的東西，其實只是保護機制。', vocab: [{ word: 'protection', def: '保護機制' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. Becoming more yourself often means figuring out which parts are true expression and which parts are old armor.", zh: '正是。更成為自己，常常意味著你要分辨哪些部分是真正的表達，哪些只是舊的盔甲。', vocab: [{ word: 'armor', def: '盔甲；比喻保護自己' }] },
      ],
    },
    {
      title: 'Part 2 — Self-Acceptance Before Improvement',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "I used to think growth meant fixing myself constantly. Now I think self-acceptance has to come first.", zh: '我以前以為成長就是不停修正自己。現在我覺得，自我接納必須先來。', vocab: [{ word: 'self-acceptance', def: '自我接納' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "Because otherwise growth becomes self-rejection in a nicer outfit.", zh: '因為不然的話，成長只是換了一件比較好看的外衣的自我否定。', vocab: [{ word: 'self-rejection', def: '自我否定' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Exactly. If the message underneath is 'I am unacceptable as I am,' improvement becomes desperate rather than healthy.", zh: '正是。如果底層訊息是「照我現在這樣是不被接受的」，那改進就會變得絕望，而不是健康。', vocab: [{ word: 'underneath', def: '底層、本質上' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "People often confuse self-criticism with honesty.", zh: '人們常常把自我批評和誠實搞混。', vocab: [{ word: 'self-criticism', def: '自我批評' }] },
        { speaker: 'a', speakerName: 'Mira', en: "But honesty without compassion can become cruelty, especially when it's turned inward.", zh: '但沒有同情的誠實，很容易變成殘忍，尤其是當那份殘忍是往自己身上去的時候。', vocab: [{ word: 'compassion', def: '體諒、同情' }, { word: 'turned inward', def: '朝向自己' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So self-acceptance isn't complacency. It's a kinder starting point for change.", zh: '所以自我接納不是自滿，而是改變的一個更善良的起點。', vocab: [{ word: 'complacency', def: '自滿、停滯不前' }] },
      ],
    },
    {
      title: 'Part 3 — Letting the Real Self Become Visible',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What helps someone become more visible as their real self?", zh: '什麼會幫助一個人讓真正的自己更看得見？' },
        { speaker: 'a', speakerName: 'Mira', en: "Usually safety. People reveal themselves more honestly when they don't feel they have to earn belonging every second.", zh: '通常是安全感。當人不覺得自己每一秒都得努力爭取歸屬時，就會更誠實地顯露自己。', vocab: [{ word: 'belonging', def: '歸屬感' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That explains why some people seem completely different depending on who they're with.", zh: '那也解釋了，為什麼有些人在不同的人面前看起來像完全不同的人。' },
        { speaker: 'a', speakerName: 'Mira', en: "Sometimes the truest version of someone only appears where they feel safe enough to stop managing perception.", zh: '有時一個人最真的版本，只會出現在他夠安全、可以不再一直管理別人怎麼看他的地方。', vocab: [{ word: 'perception', def: '他人觀感' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That's a little sad — how much energy people spend managing how they're seen.", zh: '那其實有點讓人難過，人花了那麼多力氣在管理自己被怎麼看。', vocab: [{ word: 'managing how they\'re seen', def: '管理自己被如何看待' }] },
        { speaker: 'a', speakerName: 'Mira', en: "It is, but it's understandable. Most of us learned early that some parts of us felt safer to show than others.", zh: '是有點難過，但也很能理解。我們大多數人都很早就學會，有些部分的自己比其他部分更安全地可以被展示出來。', vocab: [{ word: 'understandable', def: '可以理解的' }] },
      ],
    },
    {
      title: 'Part 4 — The Courage to Disappoint People',
      lines: [
        { speaker: 'a', speakerName: 'Mira', en: "I think becoming yourself also requires the courage to disappoint people sometimes.", zh: '我覺得更成為自己，也需要有時候敢讓別人失望的勇氣。', vocab: [{ word: 'disappoint people', def: '讓別人失望' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "If you're always trying to be liked, you're probably editing yourself constantly.", zh: '如果你一直想被喜歡，你大概就會一直不斷地修剪自己。', vocab: [{ word: 'editing yourself', def: '修剪自己以符合期待' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Kindness matters, but living entirely through approval usually makes a person less real over time.", zh: '善良很重要，但如果你完全活在別人的認可裡，久了反而會讓你變得沒那麼真。', vocab: [{ word: 'approval', def: '認可' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So authenticity requires some willingness to be misunderstood.", zh: '所以真實需要某種程度上願意被誤解。', vocab: [{ word: 'authenticity', def: '真實性' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes — not rebellion for its own sake, just enough courage to stop abandoning yourself for comfort.", zh: '對，不是為了反叛而反叛，而是有足夠的勇氣，不再為了舒適感而拋下自己。', vocab: [{ word: 'for its own sake', def: '為了它本身而已' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That makes authenticity sound less reckless and more like alignment.", zh: '那讓真實聽起來比較不像魯莽，而比較像一致。', vocab: [{ word: 'alignment', def: '內外一致' }] },
      ],
    },
    {
      title: 'Part 5 — A More Unified Life',
      lines: [
        { speaker: 'b', speakerName: 'Jamie', en: "What does a more fully lived self actually look like day to day?", zh: '一個更完整地活出自己的狀態，在日常裡實際上會是什麼樣子？' },
        { speaker: 'a', speakerName: 'Mira', en: "Less internal friction. Fewer moments where you leave and think, 'Why was I pretending so much just now?'", zh: '比較少內耗。比較少那種離開一個場景之後，心裡想著「我剛剛為什麼要演成那樣？」的時刻。', vocab: [{ word: 'internal friction', def: '內在拉扯、內耗' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That sounds peaceful. Not perfect, but more coherent.", zh: '那聽起來很平靜。不是完美，而是比較一致。', vocab: [{ word: 'coherent', def: '一致而連貫的' }] },
        { speaker: 'a', speakerName: 'Mira', en: "I don't think becoming yourself is a dramatic reinvention. It's usually a quieter process of removing what's false.", zh: '我不覺得更成為自己是一場戲劇性的重塑。它通常比較像是一個安靜的過程，把那些不真的東西慢慢拿掉。', vocab: [{ word: 'reinvention', def: '重新塑造自己' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "So not creating a new self, but uncovering a truer one.", zh: '所以不是創造一個新自我，而是揭開一個更真的自己。', vocab: [{ word: 'uncover', def: '揭開、顯露' }] },
        { speaker: 'a', speakerName: 'Mira', en: "Yes. A unified life may not look impressive from the outside, but it feels much more peaceful from within.", zh: '對。一個一致的生命，從外面看也許不特別驚人，但從裡面活起來會平靜得多。', vocab: [{ word: 'unified life', def: '內外一致的生活' }] },
        { speaker: 'b', speakerName: 'Jamie', en: "That kind of peace sounds more valuable than almost any polished image.", zh: '那種平靜聽起來比幾乎任何漂亮形象都更有價值。', vocab: [{ word: 'polished image', def: '包裝得很漂亮的形象' }] },
      ],
    },
  ],
  keyPhrases: [
    { en: 'self-acceptance', zh: '自我接納', example: "Self-acceptance should come before self-improvement." },
    { en: 'survival strategy', zh: '生存策略', example: "What looks like personality can sometimes be an old survival strategy." },
    { en: 'armor', zh: '盔甲；保護自己的外殼', example: "Humor can be genuine, but it can also become armor." },
    { en: 'turned inward', zh: '朝向自己', example: "Honesty without compassion can become cruelty turned inward." },
    { en: 'authenticity', zh: '真實性', example: "Authenticity requires some willingness to disappoint people." },
    { en: 'alignment', zh: '內外一致', example: "Authenticity is not recklessness; it is alignment." },
    { en: 'internal friction', zh: '內在拉扯、內耗', example: "A more honest life usually comes with less internal friction." },
    { en: 'coherent', zh: '一致而連貫的', example: "A coherent life may not look dramatic, but it feels peaceful." },
    { en: 'unified life', zh: '內外一致的生活', example: "A unified life feels calmer from the inside." },
    { en: 'polished image', zh: '包裝漂亮的形象', example: "A polished image is worth less than an honest life." },
  ],
  }
]
