import { Episode } from '../types'

export const WEEK_01: Episode[] = [
  // ─── Day 1 ─── Jan 1 ─────────────────────────────────────────────────────
  {
    weekNumber: 1,
    dayOfWeek: 1,
    date: '2026-01-01',
    theme: 'New Year & Fresh Starts',
    title: 'The First Day of Everything',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — What January First Actually Feels Like',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'Do you actually feel different on January first, or is it just a feeling you think you should have?', zh: '你在一月一日真的會感覺不一樣，還是只是覺得應該要有這種感覺？' },
          { speaker: 'a', speakerName: 'Mira', en: 'A bit of both, honestly. There is a real shift in energy that I notice the moment I wake up. But I have learned not to put too much pressure on that feeling.', zh: '說真的，兩者都有。我一醒來就能感受到一種能量上的轉換，這是真實的。但我也學會不要對這種感覺施加太大的壓力。', vocab: [{ word: 'pressure', def: '壓力；負擔' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What kind of pressure do you mean?', zh: '你說的壓力是什麼意思？' },
          { speaker: 'a', speakerName: 'Mira', en: 'If the only time I feel motivated is when the calendar resets, that is not a reliable foundation. So I try to use the energy while it is there and build something that outlasts the first week.', zh: '如果我有動力只是因為日曆翻新了，那這個基礎太不穩固。所以我試著善用這股能量，建立一個能撐過第一週的東西。', vocab: [{ word: 'motivated', def: '有動力的；充滿幹勁的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How do you actually use it on the day itself?', zh: '那你在當天具體怎麼做？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I keep January first simple — a short reflection in the morning, a walk, and one small action toward something that actually matters to me. Not a long list. Just one honest beginning.', zh: '我讓一月一日保持簡單——早上做一個簡短的回顧、散個步，然後朝一件對我真正重要的事邁出一小步。不是一長串清單，只是一個誠實的開始。', vocab: [{ word: 'reflection', def: '回顧；反思' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'That sounds almost too simple.', zh: '這聽起來幾乎太簡單了。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is kind of the point. Complicated plans usually collapse under the first ordinary day of the year.', zh: '這就是重點。複雜的計畫通常撐不過年初的第一個平凡日。' },
        ],
      },
      {
        title: 'Part 2 — The Weight of a Symbolic Date',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'Do you ever feel overwhelmed by how much January first is supposed to represent?', zh: '你有沒有因為一月一日「應該」代表這麼多東西而感到喘不過氣？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I used to. I would look at everything I wanted to change and feel exhausted before the year even started.', zh: '以前有。我會看著所有想改變的事，在年份還沒開始之前就已經覺得精疲力竭了。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'What shifted for you?', zh: '後來是什麼改變了？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I started treating it as a milestone rather than a verdict. A milestone marks where you are — not whether you have passed or failed.', zh: '我開始把它當成一個里程碑，而不是一個裁決。里程碑是標記你所在的位置，不是判定你過關還是失敗。', vocab: [{ word: 'milestone', def: '里程碑；重要時刻' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So it is more like a checkpoint than a test.', zh: '所以它更像是一個檢查點，而不是一場考試。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. And once I stopped treating it as a test, I could actually enjoy being at the beginning of something.', zh: '沒錯。一旦我不再把它當成考試，我才真正能享受站在一個新事物起點的感覺。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'That sounds like a much lighter way to enter the year.', zh: '這聽起來是一種輕鬆很多的方式來進入新的一年。' },
          { speaker: 'a', speakerName: 'Mira', en: 'It made a real difference. The day itself became something I looked forward to instead of something I needed to get right.', zh: '這真的讓情況截然不同。這一天變成了我期待的事，而不是必須做對的事。' },
        ],
      },
      {
        title: 'Part 3 — One Practice That Actually Works',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'What is one concrete thing you do on January first that you think genuinely helps?', zh: '一月一日你有什麼具體的做法，是你覺得真的有幫助的？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I write down three things: one thing I am genuinely proud of from last year, one pattern I want to shift, and one word I want to return to throughout the year.', zh: '我會寫下三件事：去年一件我真心感到驕傲的事、一個我想改變的習慣模式，以及一個我想在這一年中反覆回顧的詞。', vocab: [{ word: 'pattern', def: '習慣模式；規律' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Just one word for the whole year?', zh: '整年就只有一個詞？' },
          { speaker: 'a', speakerName: 'Mira', en: 'A word is more flexible than a goal. Last year my word was "steady." Every time I felt scattered, I came back to that word, and it helped more than any list I had ever made.', zh: '一個詞比一個目標更有彈性。去年我的詞是「穩定」。每次覺得心神渙散時，我就回到這個詞，它比我寫過的任何清單都更有幫助。', vocab: [{ word: 'scattered', def: '心神渙散的；注意力分散的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'I like that. It leaves room for the year to be what it actually is.', zh: '我喜歡這個做法。它留給了這一年空間去呈現它本來的樣子。' },
          { speaker: 'a', speakerName: 'Mira', en: 'And it gives you something to return to instead of something to fail at.', zh: '而且它讓你有個可以回歸的東西，而不是一個可以失敗的目標。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'Have you chosen your word for this year yet?', zh: '你今年的詞選好了嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Not yet. I am still sitting with a few options. Which is probably a good sign — it means I am not forcing it.', zh: '還沒。我還在幾個選項之間思考。這可能是個好跡象——代表我沒有強迫自己。' },
        ],
      },
      {
        title: 'Part 4 — What Gets in the Way',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'What do you think gets in the way most for people trying to make a genuine fresh start?', zh: '你覺得什麼最容易阻礙人們真正重新出發？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Carrying last year\'s story about themselves into the new one. If you spent the past year feeling undisciplined, it is easy to walk into January first already expecting to fall short.', zh: '把上一年給自己貼的標籤帶進新的一年。如果你整個去年都覺得自己缺乏自律，很容易在一月一日就已經預期自己會做不好。', vocab: [{ word: 'undisciplined', def: '缺乏自律的；散漫的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'And the date change does not automatically fix that?', zh: '換了日期不會自動解決這個問題？' },
          { speaker: 'a', speakerName: 'Mira', en: 'It can open a window — researchers actually call it the "fresh start effect." But the window closes quickly if the underlying pattern does not shift.', zh: '它可以打開一扇窗——研究人員稱之為「重新開始效應」。但如果深層的行為模式沒有改變，這扇窗很快就會關上。', vocab: [{ word: 'fresh start effect', def: '重新開始效應（心理學現象）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How do you actually shift the underlying pattern?', zh: '那要怎麼真正改變深層的行為模式？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Slowly, and with honesty. You have to look at what actually happened — not the story you have been telling — and decide what is worth keeping.', zh: '慢慢來，並且誠實地面對。你必須看清楚實際發生了什麼——而不是你一直在告訴自己的故事——然後決定什麼值得保留。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'That sounds harder than making a list of resolutions.', zh: '這聽起來比列一張新年願望清單要難多了。' },
          { speaker: 'a', speakerName: 'Mira', en: 'It is. But it is also more likely to actually work.', zh: '確實如此。但它也更有可能真正奏效。' },
        ],
      },
      {
        title: 'Part 5 — An Opening, Not a Deadline',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'If someone is feeling overwhelmed right now on January first, what would you tell them?', zh: '如果有人現在在一月一日感到壓力很大，你會對他說什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I would say: the pressure is optional. January first is a beginning, not a deadline.', zh: '我會說：壓力是可以選擇不承受的。一月一日是一個開始，不是一個截止日期。', vocab: [{ word: 'deadline', def: '截止日期；期限' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What does a good beginning actually look like?', zh: '一個好的開始實際上是什麼樣子？' },
          { speaker: 'a', speakerName: 'Mira', en: 'An honest one, even if it is small. Going to bed an hour earlier. Writing one paragraph in a journal. Calling someone you have been meaning to reconnect with.', zh: '一個誠實的開始，哪怕很小。早一個小時上床睡覺。在日記裡寫一段話。打電話給一個你一直想重新聯繫的人。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'What if nothing feels clear yet?', zh: '如果什麼都還不清晰怎麼辦？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Then clarity is the first thing worth looking for — not a plan, just a direction. Something that feels true even when the motivation is not there.', zh: '那麼清晰感就是第一個值得尋找的東西——不是計畫，只是一個方向。一個即使在沒有動力的時候也感覺真實的東西。', vocab: [{ word: 'clarity', def: '清晰感；明確' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'The first day of everything is just that — a first day.', zh: '萬事的第一天就只是第一天。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. What matters is what you do with the days after. That is where the year actually gets built.', zh: '沒錯。重要的是你怎麼度過接下來的日子。那才是這一年真正被建立起來的地方。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'fresh start effect', zh: '重新開始效應', example: 'The fresh start effect explains why people feel more motivated at the beginning of a new year.' },
      { en: 'milestone', zh: '里程碑；重要時刻', example: 'Finishing the project felt like a real milestone after months of work.' },
      { en: 'underlying pattern', zh: '深層的行為模式', example: 'Changing your habits means looking at the underlying pattern, not just the surface behavior.' },
      { en: 'feel scattered', zh: '感到心神渙散', example: 'On days when she felt scattered, she would pause and return to her one key word.' },
      { en: 'a beginning, not a deadline', zh: '一個開始，而不是截止日期', example: 'She reminded herself that a new project is a beginning, not a deadline for perfection.' },
      { en: 'walk into', zh: '帶著某種狀態進入', example: 'He walked into the meeting already expecting things to go wrong, and they did.' },
      { en: 'come back to', zh: '回歸；重新接觸', example: 'When she felt lost, she came back to the intention she had set at the start of the year.' },
      { en: 'fall short', zh: '未達標；不足', example: 'He was afraid of falling short again, so he set a smaller, more realistic goal this time.' },
    ],
  },

  // ─── Day 2 ─── Jan 2 ─────────────────────────────────────────────────────
  {
    weekNumber: 1,
    dayOfWeek: 2,
    date: '2026-01-02',
    theme: 'New Year & Fresh Starts',
    title: 'Intentions, Not Resolutions',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — Why Resolutions Often Fail',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'I always make New Year\'s resolutions and I always break them by February. Do you think there is something wrong with resolutions themselves?', zh: '我每年都會立新年目標，但總是撐不過二月。你覺得新年決心本身有什麼問題嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Not with the concept — but with the way most people frame them. A resolution is usually an outcome you commit to: "I will go to the gym three times a week." That sounds clear, but it is very brittle.', zh: '不是概念本身的問題——而是大多數人設定它的方式。新年決心通常是你承諾的一個結果：「我每週要去三次健身房。」這聽起來很明確，但其實非常脆弱。', vocab: [{ word: 'resolution', def: '決心；（年度）目標' }, { word: 'brittle', def: '脆弱的；容易崩潰的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Brittle how?', zh: '脆弱在哪裡？' },
          { speaker: 'a', speakerName: 'Mira', en: 'If you miss one week, you feel like you have already failed. The resolution becomes all-or-nothing, and most people choose nothing over imperfect progress.', zh: '如果你有一個禮拜沒做到，就會覺得自己已經失敗了。新年決心變成了全有或全無，而大多數人寧願放棄，也不要接受不完美的進步。', vocab: [{ word: 'all-or-nothing', def: '全有或全無（的思維）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So what is the alternative?', zh: '那替代方案是什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'An intention. It is less about what you will achieve and more about how you want to show up. The question is not "what will I accomplish" — it is "who do I want to be this year."', zh: '意圖。它不那麼關注你將達成什麼，而更關注你想以什麼樣的姿態去面對事情。問題不是「我要完成什麼」，而是「我今年想成為什麼樣的人」。', vocab: [{ word: 'intention', def: '意圖；目的；心意' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'That sounds more philosophical than practical.', zh: '這聽起來比實際更像是哲學思考。' },
          { speaker: 'a', speakerName: 'Mira', en: 'It sounds that way, but in practice it is actually more durable. Let me give you a concrete example.', zh: '聽起來是這樣，但實際上它更能持久。讓我給你一個具體的例子。' },
        ],
      },
      {
        title: 'Part 2 — Intentions in Real Life',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: 'Instead of "I will exercise three times a week," an intention might be: "I want to treat my body with more care this year." That is still directional, but it does not expire when you miss a day.', zh: '與其說「我每週要運動三次」，一個意圖可以是：「今年我想更善待自己的身體。」這仍然有方向性，但不會因為你有一天沒做到就失效。', vocab: [{ word: 'directional', def: '有方向性的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So when you miss the gym, the intention still holds.', zh: '所以當你沒去健身房，這個意圖仍然有效。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. You might miss Tuesday, but on Wednesday you choose a healthy lunch instead. The intention gives you a way back in that a broken resolution does not.', zh: '沒錯。你也許週二沒去，但週三你選了一頓健康的午餐。意圖給了你一條回頭路，而已經破裂的決心做不到這一點。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'I see. The resolution is a specific behavior. The intention is more like a value.', zh: '我明白了。決心是一個具體的行為；意圖更像是一種價值觀。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is a good way to put it. And values do not have failure states in the same way that behaviors do.', zh: '這是個很好的說法。而且價值觀不像行為那樣有明確的「失敗狀態」。', vocab: [{ word: 'value', def: '價值觀；原則' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What is an intention you have set for yourself this year?', zh: '你今年給自己設定了什麼意圖？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I want to be more present in conversations. Not just hearing words, but actually listening for what is underneath them. That is hard to measure, but I know when I am doing it and when I am not.', zh: '我想在對話中更加專注當下。不只是聽到詞語，而是真正聆聽詞語背後的東西。這很難衡量，但我自己知道我有沒有做到。', vocab: [{ word: 'present', def: '專注當下的；活在當下的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'And you find that more motivating than a measurable target?', zh: '你覺得這比一個可以量化的目標更有動力？' },
        ],
      },
      {
        title: 'Part 3 — When Intentions Are Hard to Hold',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: 'Not always more motivating in the short term — resolutions can feel exciting because they are so specific. But intentions tend to outlast that initial excitement.', zh: '短期來說不見得更有動力——決心因為非常具體，可以讓人感到興奮。但意圖往往能比那股初始的熱情撐得更久。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'What makes intentions hard to hold onto?', zh: '是什麼讓意圖難以堅持？' },
          { speaker: 'a', speakerName: 'Mira', en: 'They are invisible. Nobody gives you a gold star for being more patient or more present. You have to be your own witness.', zh: '它們是看不見的。沒有人會因為你更有耐心或更專注當下而給你金星。你必須成為自己的見證者。', vocab: [{ word: 'witness', def: '見證者；證人' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'That requires a kind of self-awareness that most people are still developing.', zh: '這需要一種大多數人仍在培養的自我覺察能力。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Completely. Which is actually why setting an intention is worth doing even if you forget about it most of the year. The act of setting it changes something.', zh: '完全正確。這也是為什麼設定一個意圖是值得做的，即使你大部分時候都忘了它。設定這個行為本身就改變了什麼。', vocab: [{ word: 'self-awareness', def: '自我覺察；自我意識' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What does it change?', zh: '它改變了什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'It gives you a frame. When something difficult happens, you have something to ask yourself: is this aligned with the person I said I wanted to be?', zh: '它給了你一個框架。當困難的事情發生時，你有一個可以問自己的問題：這和我說過我想成為的那個人一致嗎？' },
          { speaker: 'b', speakerName: 'Jamie', en: 'Like a compass rather than a map.', zh: '就像指南針，而不是地圖。' },
        ],
      },
      {
        title: 'Part 4 — Keeping an Intention Alive',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: 'That is exactly right. A map tells you the exact route. A compass tells you which direction to face. Intentions are compasses.', zh: '正是如此。地圖告訴你確切的路線。指南針告訴你應該面向哪個方向。意圖就是指南針。', vocab: [{ word: 'compass', def: '指南針；方向指引' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How do you keep an intention from becoming just a nice idea you forget about?', zh: '你怎麼讓一個意圖不只是變成一個你很快就忘記的美好想法？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I connect it to something I already do. My intention to be more present — I tie it to my morning coffee. While I drink it, I spend three minutes not looking at my phone.', zh: '我把它和我已經在做的事情連結起來。我想更專注當下的意圖——我把它和早晨的咖啡綁在一起。喝咖啡時，我花三分鐘不看手機。', vocab: [{ word: 'tie to', def: '與……連結；依附在……上' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So you anchor the intention to a habit that is already established.', zh: '所以你把意圖錨定在一個已經建立好的習慣上。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. The existing habit is the trigger. The intention becomes what you fill that time with.', zh: '沒錯。現有的習慣是觸發點。意圖變成了你用來填滿那段時間的東西。', vocab: [{ word: 'trigger', def: '觸發點；引發因素' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'And when the year gets busy and you drift away from it?', zh: '那當這一年變得忙碌，你偏離了它的時候呢？' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is actually where intentions beat resolutions. You can return to an intention any day. You cannot un-break a broken resolution.', zh: '這正是意圖勝過決心的地方。你任何一天都可以回到一個意圖。你卻無法讓一個已經破裂的決心重新完好。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'So the whole structure is built around the ability to return.', zh: '所以整個架構是圍繞著「能夠回歸」這個能力建立的。' },
        ],
      },
      {
        title: 'Part 5 — Why This Matters Beyond January',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: 'Intentions work beyond New Year because they are not tied to a date. A resolution lives and dies in January. An intention travels with you through the whole year.', zh: '意圖在新年之後仍然有效，因為它不依附於某個日期。一個決心在一月生，也在一月死。一個意圖則陪你走過整年。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'Have you ever had an intention that surprised you — that turned into something bigger than you expected?', zh: '你有沒有過一個意圖讓你感到驚訝——最後發展成比你預期更大的東西？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Yes, actually. A few years ago I set an intention to "ask more questions and give fewer opinions." It started as a work thing, but it changed how I relate to people in general. I became a better listener.', zh: '有，確實有。幾年前我設定了一個意圖：「多問問題，少給意見。」這一開始是工作上的事，但後來改變了我與人相處的方式。我變成了一個更好的聆聽者。', vocab: [{ word: 'relate to', def: '與……建立關係；和……相處' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'That is interesting. It generalized — it spread beyond where you originally aimed it.', zh: '這很有趣。它推廣了——它擴散到了你最初設定的範圍之外。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is what happens when an intention is genuine. It finds its way into corners of your life you were not expecting.', zh: '這就是當一個意圖是真誠的時候會發生的事。它會進入你生命中你沒有預料到的角落。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'So the most useful thing we can do this January is not to make a list, but to ask one real question about who we want to become.', zh: '所以這個一月我們能做的最有用的事，不是列一張清單，而是問一個真實的問題：我想成為什麼樣的人。' },
          { speaker: 'a', speakerName: 'Mira', en: 'And then trust that the answer will point you in the right direction, even when the year gets complicated.', zh: '然後相信這個答案會為你指出正確的方向，即使這一年變得複雜。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'resolution', zh: '決心；年度目標', example: 'Most resolutions fail because they rely on willpower alone rather than habit design.' },
      { en: 'intention', zh: '意圖；心意', example: 'Her intention to be kinder showed up in small choices throughout the day.' },
      { en: 'all-or-nothing thinking', zh: '全有或全無的思維', example: 'All-or-nothing thinking is why one missed workout can derail an entire month\'s effort.' },
      { en: 'show up', zh: '以某種姿態出現；面對', example: 'He focused on how he wanted to show up at work, not just on what he wanted to achieve.' },
      { en: 'tie to', zh: '與……連結；依附在……上', example: 'She tied her new reading habit to her existing bedtime routine.' },
      { en: 'anchor to', zh: '錨定於；連結至', example: 'Anchoring a new behavior to an existing one makes it much easier to maintain.' },
      { en: 'drift away from', zh: '偏離；漸漸疏遠', example: 'During busy seasons, it is easy to drift away from the things that matter most.' },
      { en: 'generalize', zh: '推廣；擴散至其他領域', example: 'A small change in how she communicated at work generalized to her personal relationships too.' },
    ],
  },

  // ─── Day 3 ─── Jan 3 ─────────────────────────────────────────────────────
  {
    weekNumber: 1,
    dayOfWeek: 3,
    date: '2026-01-03',
    theme: 'New Year & Fresh Starts',
    title: 'The Science of Starting Over',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — The Fresh Start Effect',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'You mentioned the fresh start effect yesterday. What is it exactly?', zh: '你昨天提到了重新開始效應。那到底是什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'It is a real psychological phenomenon. Researchers found that people are significantly more likely to pursue goals right after what they call "temporal landmarks" — dates that feel like a new beginning.', zh: '這是一個真實的心理現象。研究人員發現，在他們所謂的「時間地標」——那些感覺像是新開始的日期——之後，人們追求目標的可能性會大幅提高。', vocab: [{ word: 'temporal landmark', def: '時間地標（如新年、生日等感覺像新起點的日期）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Like January first, or your birthday.', zh: '比如一月一日，或者你的生日。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. But also Mondays, the first of a month, the start of a new season. Any date that feels like a reset can activate the effect.', zh: '沒錯。但也包括週一、一個月的第一天、新季節的開始。任何感覺像重置的日期都可以觸發這個效應。', vocab: [{ word: 'activate', def: '啟動；激活' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Why does that happen? Why does a date matter to our brains?', zh: '為什麼會這樣？為什麼一個日期對我們的大腦那麼重要？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Because these landmarks create a psychological boundary. They help us mentally separate our past self from our future self. The "old me" did not exercise enough. The "new me" — starting today — will.', zh: '因為這些地標創造了一個心理邊界。它們幫助我們在心理上把過去的自己和未來的自己分開。「過去的我」沒有足夠運動。「新的我」——從今天開始——會的。', vocab: [{ word: 'boundary', def: '邊界；界限' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So the date gives us permission to leave the past version behind.', zh: '所以這個日期讓我們有了拋下過去版本的許可。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Precisely. Which is why the feeling on January first is real, even if it fades. The science supports it.', zh: '正是如此。這就是為什麼一月一日的感覺是真實的，即使它會消退。科學支持這一點。' },
        ],
      },
      {
        title: 'Part 2 — Why Most Attempts Still Fail',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'But if this fresh start effect is real, why do most New Year changes not stick?', zh: '但如果這個重新開始效應是真實的，為什麼大多數新年的改變還是沒能持續？' },
          { speaker: 'a', speakerName: 'Mira', en: 'The effect creates a window of motivation, but motivation alone is not enough to change behavior long-term. You also need a system.', zh: '這個效應創造了一個動力窗口，但光靠動力不足以長期改變行為。你還需要一套機制。', vocab: [{ word: 'motivation', def: '動力；驅動力' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What do you mean by a system?', zh: '你說的機制是什麼意思？' },
          { speaker: 'a', speakerName: 'Mira', en: 'A habit loop. Research in behavioral science shows that lasting habits have three parts: a cue, a routine, and a reward. Most people try to change the routine without addressing the cue or the reward.', zh: '習慣迴路。行為科學研究顯示，持久的習慣有三個部分：提示、慣例和回報。大多數人試圖改變慣例，卻沒有處理提示或回報。', vocab: [{ word: 'habit loop', def: '習慣迴路（提示→慣例→回報的循環）' }, { word: 'cue', def: '提示；線索' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Can you give me an example of that?', zh: '你能給我一個例子嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Sure. Say I want to read more. The goal is "read thirty pages a day." But I have not identified a cue — when will I start? — or a reward — why does my brain care? Without those, the routine does not stick.', zh: '當然。假設我想多閱讀。目標是「每天讀三十頁」。但我沒有確定一個提示——我什麼時候開始？——也沒有一個回報——我的大腦為什麼在乎？沒有這些，這個慣例就不會持續。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'So how would you fix that?', zh: '那你會怎麼修正這個問題？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I would attach the reading to an existing cue — like after my morning coffee — and choose a book I genuinely enjoy, so the reading itself becomes the reward.', zh: '我會把閱讀附加到一個現有的提示上——比如喝完早晨咖啡之後——然後選一本我真正喜歡的書，這樣閱讀本身就成了回報。' },
        ],
      },
      {
        title: 'Part 3 — The Role of Identity in Change',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'Is there anything else science tells us about starting over?', zh: '科學在重新開始這個問題上還告訴了我們什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'One of the most interesting findings is about identity. People who succeed at lasting change tend to shift how they see themselves, not just what they do.', zh: '最有趣的發現之一是關於身份認同。成功實現持久改變的人，往往不只是改變了他們的行為，而是改變了他們看待自己的方式。', vocab: [{ word: 'identity', def: '身份認同；自我認知' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What do you mean by that?', zh: '你這是什麼意思？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Instead of saying "I am trying to exercise more," successful people say "I am someone who exercises." It sounds like a small distinction, but it changes how you make decisions.', zh: '成功的人不說「我在努力多運動」，而說「我是一個會運動的人」。這聽起來只是小小的差別，但它改變了你做決定的方式。', vocab: [{ word: 'distinction', def: '區別；差異' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Because your decisions flow from who you believe you are.', zh: '因為你的決定來自你相信自己是誰。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. If I believe I am someone who exercises, skipping a session feels like an exception. If I believe I am just someone trying to exercise, skipping feels like evidence that it was never going to work.', zh: '沒錯。如果我相信我是一個會運動的人，跳過一次訓練感覺只是個例外。如果我相信我只是在嘗試運動的人，跳過就感覺像是證明這從來都行不通。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'So the science is saying: change your story before you try to change your behavior.', zh: '所以科學在說：在試圖改變行為之前，先改變你的故事。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Change who you believe you are, and the behavior tends to follow. That is the sequence that actually works.', zh: '改變你相信自己是誰，行為往往會跟著改變。這才是真正有效的順序。' },
        ],
      },
      {
        title: 'Part 4 — Small Steps and the Brain',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'What does science say about the size of changes we try to make? Should we think big or think small?', zh: '科學對於我們試圖做出的改變的幅度有什麼說法？我們應該想得大還是想得小？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Think very small. Research consistently shows that tiny changes are more likely to become permanent than dramatic ones. There is even a term for it: minimum viable habit.', zh: '想得非常小。研究一致表明，微小的改變比戲劇性的改變更有可能變得持久。甚至有一個專門的術語：最小可行習慣。', vocab: [{ word: 'minimum viable habit', def: '最小可行習慣（能持續執行的最小行動）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What does that look like in practice?', zh: '這在實際中是什麼樣子？' },
          { speaker: 'a', speakerName: 'Mira', en: 'If you want to build a meditation practice, start with two minutes. Not twenty. Two. The brain resists effort it cannot predict will be worth it, so you start small to avoid triggering that resistance.', zh: '如果你想建立冥想練習，從兩分鐘開始。不是二十分鐘。是兩分鐘。大腦會抗拒它無法預測是否值得的努力，所以你從小的開始，以避免觸發那種抗拒。', vocab: [{ word: 'resistance', def: '抗拒；阻力' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'And then you gradually increase from there.', zh: '然後你再逐漸增加。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Or you do not. Sometimes two minutes a day, done consistently, is already valuable. The consistency matters more than the duration.', zh: '也可以不增加。有時候每天兩分鐘，只要保持一致性，本身就已經有價值了。一致性比持續時間更重要。', vocab: [{ word: 'consistency', def: '一致性；持之以恆' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'The goal is not to do more. The goal is to keep doing it.', zh: '目標不是做更多。目標是持續去做。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. Frequency builds the neural pathway faster than intensity does.', zh: '正是如此。頻率比強度更能快速建立神經通路。' },
        ],
      },
      {
        title: 'Part 5 — Using Science Without Overthinking It',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'This is all really useful, but I worry about people using it as an excuse to over-plan and never actually start.', zh: '這一切都非常有用，但我擔心人們用它作為過度計劃、永遠不真正開始的藉口。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is a real risk. The research is useful as a framework, not as a reason to delay. The most important thing is still to begin.', zh: '這是個真實的風險。研究作為框架是有用的，但不能作為拖延的理由。最重要的事情仍然是開始。', vocab: [{ word: 'framework', def: '框架；架構' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How would you apply all of this, practically, starting today?', zh: '你會怎麼實際應用這一切，從今天開始？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I would pick one thing I actually want to change. Just one. I would design the smallest possible version of it, identify when I will do it, and connect it to something I already do.', zh: '我會選一件我真正想改變的事。就一件。我會設計它最小的可能版本，確定我什麼時候去做，並把它和我已經在做的事情連結起來。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'And the identity piece?', zh: '那關於身份認同的部分呢？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I would start telling myself a slightly different story. Not "I am trying to be more organized" but "I am becoming someone who keeps things simple and clear."', zh: '我會開始給自己講一個稍微不同的故事。不是「我在努力變得更有條理」，而是「我正在成為一個讓事情簡單清晰的人」。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'The science is reassuring in a way. It says change is difficult but not mysterious. There are principles behind it.', zh: '科學在某種程度上令人放心。它說改變是困難的，但並不神秘。背後有規律可循。' },
          { speaker: 'a', speakerName: 'Mira', en: 'And the most important principle is the oldest one: begin. Everything else follows from that.', zh: '而最重要的規律是最古老的那個：開始。其他一切都從這裡展開。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'temporal landmark', zh: '時間地標', example: 'Mondays are mini temporal landmarks — they give us a weekly fresh start feeling.' },
      { en: 'habit loop', zh: '習慣迴路', example: 'Once she understood the habit loop, she could design routines that actually stuck.' },
      { en: 'identity shift', zh: '身份認同的轉變', example: 'The identity shift from "I am trying to run" to "I am a runner" changed how he made daily decisions.' },
      { en: 'minimum viable habit', zh: '最小可行習慣', example: 'Her minimum viable habit was to write one sentence in her journal every night before sleep.' },
      { en: 'resistance', zh: '抗拒；阻力', example: 'Starting small reduces the brain\'s resistance to a new routine.' },
      { en: 'consistency', zh: '一致性；持之以恆', example: 'Consistency over three months changed her relationship with exercise more than intensity ever had.' },
      { en: 'neural pathway', zh: '神經通路', example: 'Repeating a behavior frequently strengthens the neural pathway associated with it.' },
      { en: 'behavioral science', zh: '行為科學', example: 'Behavioral science has given us practical tools for understanding why habits form and why they break.' },
    ],
  },

  // ─── Day 4 ─── Jan 4 ─────────────────────────────────────────────────────
  {
    weekNumber: 1,
    dayOfWeek: 4,
    date: '2026-01-04',
    theme: 'New Year & Fresh Starts',
    title: 'Letting Go to Move Forward',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — What Letting Go Actually Means',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'People say "let go" all the time, but I am never quite sure what it actually means in practice. What does letting go mean to you?', zh: '人們常常說「放手」，但我從來不太確定這在實際中是什麼意思。對你來說，放手意味著什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'For me, letting go means choosing not to carry something forward. Not forgetting it happened, not pretending it did not hurt — just deciding it will not get to shape my next chapter.', zh: '對我來說，放手意味著選擇不把某件事帶往前走。不是忘記它發生過，不是假裝它沒有傷害——只是決定它不會塑造我的下一個篇章。', vocab: [{ word: 'letting go', def: '放手；放下' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So it is not about erasing the past.', zh: '所以這不是關於抹去過去。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Not at all. You cannot erase it. What you can do is stop giving it rent-free space in your head — stop letting it make decisions for you in the present.', zh: '完全不是。你無法抹去它。你能做的是停止讓它在你腦袋裡免費租房——停止讓它替你在當下做決定。', vocab: [{ word: 'rent-free', def: '免費佔用的（比喻某事不斷佔據腦海）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What kinds of things tend to take up that rent-free space?', zh: '什麼樣的事情往往會佔據那個免費的空間？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Regrets about things I did not do. Grudges about how I was treated. Old stories about my own limitations. These are the main ones.', zh: '對我沒有做到的事情的遺憾。對被如何對待的怨恨。關於自身局限性的舊故事。這些是主要的。', vocab: [{ word: 'grudge', def: '怨恨；積怨' }, { word: 'regret', def: '遺憾；悔恨' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How do you know when something needs to be let go?', zh: '你怎麼知道什麼時候有些事需要被放下？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I ask myself: is this still useful? Does thinking about this help me do better going forward, or is it just weight I am carrying out of habit?', zh: '我問自己：這還有用嗎？想著這件事是否能幫助我在接下來做得更好，還是它只是我出於習慣而背負的重量？' },
        ],
      },
      {
        title: 'Part 2 — The Cost of Holding On',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'What happens when people hold onto things they should let go of?', zh: '當人們緊抓著那些應該放手的事情時，會發生什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'They move through the year but the weight comes with them. It affects how they show up in new situations — they are half-present because part of their attention is still back there.', zh: '他們走過了這一年，但重量也跟著來了。這影響了他們在新情況中的表現——他們只有一半在當下，因為他們注意力的一部分仍然留在那裡。', vocab: [{ word: 'half-present', def: '只有一半專注當下的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Like driving while looking in the rearview mirror too much.', zh: '就像開車時太頻繁地看後視鏡。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is a great analogy. You need the rearview mirror — you should learn from the past — but if you stare at it, you will crash into what is in front of you.', zh: '這是個很好的比喻。你需要後視鏡——你應該從過去學習——但如果你一直盯著它，你就會撞上前方的東西。', vocab: [{ word: 'analogy', def: '比喻；類比' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What does that look like in real terms? What does someone who is holding on too tight actually do differently?', zh: '這在現實中是什麼樣子？一個抓得太緊的人實際上有什麼不同？' },
          { speaker: 'a', speakerName: 'Mira', en: 'They interpret new situations through the lens of old wounds. A new colleague reminds them of someone who hurt them, and they become defensive before anything has even happened.', zh: '他們透過舊傷的視角來解讀新的情況。一個新同事讓他們想起了一個曾經傷害他們的人，他們在任何事情發生之前就開始防衛了。', vocab: [{ word: 'defensive', def: '防衛性的；戒備的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'The past is filtering the present.', zh: '過去在過濾現在。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. And the person paying the price is you — not whoever hurt you in the first place.', zh: '正是如此。而付出代價的是你——不是那個最初傷害你的人。' },
        ],
      },
      {
        title: 'Part 3 — What Is Worth Keeping',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'Is there anything from the past year that you think we should hold onto rather than let go of?', zh: '去年有什麼是你認為我們應該保留而不是放手的嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Yes — the lessons. The feelings, the grievances, the identity of "person who failed at X" — let those go. But the learning? Keep that.', zh: '有的——那些教訓。感受、委屈、「在某件事上失敗的人」這個身份——這些可以放手。但學到的東西？留下來。', vocab: [{ word: 'grievance', def: '委屈；不滿；申訴' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'How do you separate the lesson from the emotional weight?', zh: '你怎麼把教訓和情感重量分開？' },
          { speaker: 'a', speakerName: 'Mira', en: 'I ask myself: what did this teach me about what I value, what I can handle, or what I need to do differently? If I can answer that clearly, I can let the rest go.', zh: '我問自己：這告訴了我什麼關於我重視什麼、我能承受什麼，或者我需要做什麼不同的事？如果我能清楚地回答這個問題，我就可以放下其餘的。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'So the process is: extract the lesson, then release the experience.', zh: '所以這個過程是：提取教訓，然後釋放那段經歷。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is a good way to think about it. The experience served its purpose. You do not need to keep reliving it to honor what it taught you.', zh: '這是個很好的思考方式。那段經歷已經發揮了它的作用。你不需要不斷重溫它，才能尊重它教給你的東西。', vocab: [{ word: 'relive', def: '重溫；再次經歷' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'That feels like real permission to move on.', zh: '這讓人感覺真正獲得了繼續前進的許可。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Because it is. The experience earned its lesson. Now it is free to go.', zh: '因為確實如此。那段經歷換來了它的教訓。現在它可以走了。' },
        ],
      },
      {
        title: 'Part 4 — Practical Ways to Actually Let Go',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'This sounds meaningful, but what does letting go actually look like in practice? Is there something concrete you can do?', zh: '這聽起來很有意義，但放手在實際中到底是什麼樣子？有什麼具體可以做的事嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: 'One thing that helps me is writing. I will write out what happened as honestly as I can — what I did, what others did, how it made me feel. Then I close the notebook and I tell myself: that is the complete record. It does not need to live in my head anymore.', zh: '有一件對我有幫助的事是寫作。我會盡可能誠實地寫下發生了什麼——我做了什麼、別人做了什麼、它讓我感覺如何。然後我合上筆記本，告訴自己：這是完整的記錄。它不需要再住在我腦袋裡了。', vocab: [{ word: 'record', def: '記錄；存檔' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'You are externalizing it — moving it from your mind to the page.', zh: '你是在將它外化——把它從你的腦海移到紙頁上。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Right. The brain keeps circling things it feels are unresolved. Writing gives it a sense of closure.', zh: '對。大腦會不斷繞回那些它覺得未解決的事情。寫作給了它一種了結的感覺。', vocab: [{ word: 'closure', def: '了結；告別；心結打開' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'What about things involving other people — when you are holding onto anger toward someone?', zh: '那涉及到其他人的事情呢——當你對某個人抱有憤怒的時候？' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is harder. I find it helps to distinguish between forgiving someone and excusing what they did. You can forgive without saying what happened was okay.', zh: '這更難。我發現區分原諒某人和為他們的所作所為開脫是有幫助的。你可以原諒而不說發生的事是可以接受的。', vocab: [{ word: 'forgive', def: '原諒；寬恕' }, { word: 'excuse', def: '為……開脫；找藉口' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Forgiveness is for you, not for them.', zh: '原諒是為了你自己，不是為了他們。' },
          { speaker: 'a', speakerName: 'Mira', en: 'Exactly. Holding a grudge is like drinking poison and expecting the other person to get sick. Letting go frees you.', zh: '沒錯。懷恨在心就像喝毒藥卻期望對方生病。放手解放的是你自己。' },
        ],
      },
      {
        title: 'Part 5 — What Becomes Possible',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: 'What actually opens up when you successfully let go of something?', zh: '當你成功地放手某件事時，什麼真正打開了？' },
          { speaker: 'a', speakerName: 'Mira', en: 'Attention. When something is not taking up space in the background of your mind, you suddenly have more capacity for what is in front of you.', zh: '注意力。當某件事不再佔據你腦海的背景時，你突然有了更多的能力來關注眼前的事情。', vocab: [{ word: 'capacity', def: '能力；容量' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'Like clearing RAM on a computer.', zh: '就像清理電腦的記憶體一樣。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is a good analogy. And once you have that space back, you can invest it in things that are actually alive — relationships, projects, ideas.', zh: '這是個好比喻。而一旦你重新獲得那個空間，你就可以把它投入到真正有生命力的事情上——關係、計畫、想法。' },
          { speaker: 'b', speakerName: 'Jamie', en: 'What is the best thing you have moved toward after letting something go?', zh: '你在放手某件事之後，你走向的最好的事情是什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: 'A friendship I had let go stale because I was still preoccupied with an old professional conflict. Once I stopped carrying that conflict, I had the emotional bandwidth to reach out and rebuild.', zh: '一段我因為還沉浸在舊的職業衝突中而讓它陷入停滯的友誼。一旦我不再背負那個衝突，我就有了情感上的餘裕去主動聯繫並重建它。', vocab: [{ word: 'preoccupied', def: '心神被佔據的；全神貫注於……的' }, { word: 'emotional bandwidth', def: '情感餘裕；心理承受力' }] },
          { speaker: 'b', speakerName: 'Jamie', en: 'So letting go is not really about the past at all — it is about making room for the future.', zh: '所以放手根本不是關於過去的——它是關於為未來騰出空間。' },
          { speaker: 'a', speakerName: 'Mira', en: 'That is the clearest way I can put it. You do not let go for the sake of the past. You let go for the sake of what comes next.', zh: '這是我能說得最清楚的方式。你放手不是為了過去。你放手是為了接下來要到來的東西。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'let go', zh: '放手；放下', example: 'She decided to let go of the disappointment and focus on what she could do now.' },
      { en: 'rent-free space', zh: '免費佔據腦海的空間', example: 'The argument was still living rent-free in his head three weeks later.' },
      { en: 'grudge', zh: '怨恨；積怨', example: 'Carrying a grudge is exhausting — it costs far more than the original hurt did.' },
      { en: 'closure', zh: '了結；告別', example: 'Writing out what happened gave her a sense of closure she had not been able to find before.' },
      { en: 'forgive without excusing', zh: '原諒但不為行為開脫', example: 'She forgave him for what he said, but that did not mean she found it acceptable.' },
      { en: 'preoccupied with', zh: '心神被……佔據', example: 'He was so preoccupied with the past project\'s failure that he struggled to engage with the new one.' },
      { en: 'emotional bandwidth', zh: '情感餘裕；心理承受力', example: 'After resolving the conflict, she had more emotional bandwidth for the people who mattered.' },
      { en: 'make room for', zh: '為……騰出空間', example: 'Finishing old tasks made room for new ideas she had been too busy to explore.' },
    ],
  },
]
