import { Episode } from '../types';

export const WEEK_48: Episode[] = [
  {
    weekNumber: 48,
    dayOfWeek: 1,
    date: '2026-11-23',
    theme: 'Language & Identity',
    title: 'Who Are You When You Speak?',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Language as Identity',
        lines: [
          { speaker: 'a', english: "I've been thinking about how much language is tied to who we are.", chinese: "我一直在思考語言與我們是誰有多深的聯繫。", vocabulary: [{ word: "tied to", definition: "與……緊密相連的" }] },
          { speaker: 'b', english: "It's profound. The language you grew up with shapes how you think and feel.", chinese: "這很深刻，你成長時使用的語言塑造了你的思考和感受方式。", vocabulary: [{ word: "shape", definition: "塑造；影響" }] },
          { speaker: 'a', english: "More than that — it carries the voices of your family, your culture, your history.", chinese: "不只如此——它承載著你的家人、文化和歷史的聲音。", vocabulary: [{ word: "carry", definition: "承載；攜帶" }] },
          { speaker: 'b', english: "When a language dies, an entire way of experiencing the world disappears with it.", chinese: "當一種語言消亡時，整個體驗世界的方式也隨之消失。", vocabulary: [] },
          { speaker: 'a', english: "And yet language also evolves, changes, borrows, adapts — it's alive.", chinese: "然而語言也在演化、改變、借鑑、適應——它是活的。", vocabulary: [{ word: "evolve", definition: "演化；發展" }] },
          { speaker: 'b', english: "The language I speak at home with family feels totally different from how I speak at work.", chinese: "我在家和家人說話的語言感覺與我在工作中說話的方式完全不同。", vocabulary: [] },
          { speaker: 'a', english: "We all have multiple linguistic registers — we code-switch constantly.", chinese: "我們都有多種語言表達方式——我們不斷地切換語碼。", vocabulary: [{ word: "code-switch", definition: "切換語碼；在不同語言或方言間切換" }] },
          { speaker: 'b', english: "And we're a different version of ourselves in each one, in subtle ways.", chinese: "在每種方式中，我們都是以微妙的方式成為不同版本的自己。", vocabulary: [{ word: "subtle", definition: "微妙的；細緻的" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Mother Tongue and Emotional Depth',
        lines: [
          { speaker: 'a', english: "There's something irreplaceable about your mother tongue, isn't there?", chinese: "母語有一些無可替代的東西，不是嗎？", vocabulary: [{ word: "mother tongue", definition: "母語" }] },
          { speaker: 'b', english: "Absolutely. The deepest emotions, the oldest memories — they live in that language.", chinese: "絕對的，最深刻的情感、最古老的記憶——它們生活在那種語言中。", vocabulary: [] },
          { speaker: 'b', english: "I dream in my first language. I count in it. I cry in it.", chinese: "我用我的第一語言做夢，用它計數，用它哭泣。", vocabulary: [] },
          { speaker: 'a', english: "Research shows that the same words trigger stronger emotional responses in a first language.", chinese: "研究顯示，相同的詞語在第一語言中會觸發更強的情感反應。", vocabulary: [{ word: "trigger", definition: "觸發；引起" }] },
          { speaker: 'b', english: "Because those words were learned in emotional contexts — with family, with love, with fear.", chinese: "因為這些詞是在情感語境中學習的——和家人一起、帶著愛、帶著恐懼。", vocabulary: [] },
          { speaker: 'a', english: "Second languages are often more intellectual and less visceral.", chinese: "第二語言通常更具智識性，而不那麼直覺性。", vocabulary: [{ word: "visceral", definition: "直覺性的；發自內心的" }] },
          { speaker: 'b', english: "Which can actually be useful — making difficult conversations easier in a second language.", chinese: "這實際上可以很有用——使第二語言中的困難對話更容易。", vocabulary: [] },
          { speaker: 'a', english: "There's so much complexity to how language and emotion are intertwined.", chinese: "語言和情感交織在一起有太多的複雜性。", vocabulary: [{ word: "intertwined", definition: "交織的；緊密相連的" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Dialect and Regional Identity',
        lines: [
          { speaker: 'a', english: "Within a single language, dialects carry enormous identity weight.", chinese: "在單一語言中，方言承載著巨大的身份認同重量。", vocabulary: [{ word: "dialect", definition: "方言；地區語言" }] },
          { speaker: 'b', english: "Your accent tells people where you're from before you say anything about yourself.", chinese: "你的口音在你說任何關於自己的事情之前就告訴了人們你來自哪裡。", vocabulary: [{ word: "accent", definition: "口音；腔調" }] },
          { speaker: 'a', english: "And accents carry social judgments — people make assumptions based on how you sound.", chinese: "而口音帶有社會評判——人們根據你的聲音做出假設。", vocabulary: [] },
          { speaker: 'b', english: "Accent discrimination is a real form of bias — and it's rarely called out.", chinese: "口音歧視是一種真實的偏見形式——而且很少被點名。", vocabulary: [{ word: "accent discrimination", definition: "口音歧視" }] },
          { speaker: 'a', english: "People modify their accents to be taken more seriously — especially immigrants and regional speakers.", chinese: "人們修改口音以獲得更認真的對待——尤其是移民和地區語者。", vocabulary: [{ word: "modify", definition: "修改；調整" }] },
          { speaker: 'b', english: "That's a real cost — suppressing your voice to fit someone else's standard.", chinese: "那是真實的代價——壓制你的聲音以符合別人的標準。", vocabulary: [{ word: "suppress", definition: "壓制；抑制" }] },
          { speaker: 'a', english: "But I also understand wanting to be heard and not dismissed based on how you sound.", chinese: "但我也理解想要被傾聽而不是根據你的聲音被忽視的心情。", vocabulary: [{ word: "dismissed", definition: "被忽視；被輕視" }] },
          { speaker: 'b', english: "It's a tension between authenticity and pragmatism that many navigates daily.", chinese: "這是許多人每天都在應對的真實性和實用主義之間的張力。", vocabulary: [{ word: "pragmatism", definition: "實用主義" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Language and Power',
        lines: [
          { speaker: 'a', english: "Language is never neutral — it reflects and reinforces power structures.", chinese: "語言從來都不是中立的——它反映並強化了權力結構。", vocabulary: [{ word: "power structure", definition: "權力結構" }] },
          { speaker: 'b', english: "Who gets to define 'correct' language often reflects who holds social power.", chinese: "誰有資格定義「正確」語言往往反映了誰擁有社會權力。", vocabulary: [] },
          { speaker: 'a', english: "Standard languages were often imposed to unify — but also to marginalize regional varieties.", chinese: "標準語言通常是為了統一而強加的——但也是為了邊緣化地區語言。", vocabulary: [{ word: "marginalize", definition: "邊緣化" }] },
          { speaker: 'b', english: "Children were sometimes punished for speaking their home language at school.", chinese: "孩子們有時因在學校說母語而受到懲罰。", vocabulary: [] },
          { speaker: 'a', english: "That's linguistic oppression. It strips people of their identity and dignity.", chinese: "那是語言壓迫，它剝奪了人們的身份認同和尊嚴。", vocabulary: [{ word: "linguistic oppression", definition: "語言壓迫" }] },
          { speaker: 'b', english: "There's a global movement now to revitalize endangered indigenous languages.", chinese: "現在有一個全球運動在振興瀕危的原住民語言。", vocabulary: [{ word: "revitalize", definition: "振興；使重新充滿活力" }] },
          { speaker: 'a', english: "Language revitalization is an act of cultural healing and self-determination.", chinese: "語言振興是文化治癒和自我決定的行為。", vocabulary: [{ word: "self-determination", definition: "自我決定；自決" }] },
          { speaker: 'b', english: "Protecting minority languages is protecting the diversity of human thought itself.", chinese: "保護少數語言就是保護人類思想本身的多樣性。", vocabulary: [{ word: "minority language", definition: "少數語言" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Your English Self',
        lines: [
          { speaker: 'a', english: "For those of us learning English, who are we in this new language?", chinese: "對於我們這些在學英語的人，在這種新語言中我們是誰？", vocabulary: [] },
          { speaker: 'b', english: "Good question. I feel like my English self is slightly different — more direct, more open.", chinese: "好問題，我感覺我的英語自我略有不同——更直接、更開放。", vocabulary: [] },
          { speaker: 'a', english: "Some people find they can express things in English they struggle to say in their first language.", chinese: "有些人發現他們可以用英語表達他們在第一語言中難以說出的事情。", vocabulary: [] },
          { speaker: 'b', english: "There's a kind of freedom in a second language — less burdened by expectations.", chinese: "第二語言中有一種自由——不那麼受期望的束縛。", vocabulary: [{ word: "burdened by", definition: "受……束縛；被……壓迫" }] },
          { speaker: 'a', english: "I find I'm more playful with language in English — more willing to experiment.", chinese: "我發現我在英語中對語言更有玩耍性——更願意嘗試。", vocabulary: [{ word: "playful", definition: "玩耍性的；輕鬆有趣的" }] },
          { speaker: 'b', english: "Because mistakes feel less personal. It's not your identity on the line, just your skill.", chinese: "因為錯誤感覺不那麼個人化，是技能而不是你的身份在受評判。", vocabulary: [] },
          { speaker: 'a', english: "But ultimately, who you are in any language is still fundamentally you.", chinese: "但最終，在任何語言中你是誰，從根本上仍然是你。", vocabulary: [] },
          { speaker: 'b', english: "Languages are lenses, not masks. You're still there behind every one of them.", chinese: "語言是鏡頭，而不是面具，在每一種語言後面你仍然在那裡。", vocabulary: [{ word: "lens", definition: "鏡頭；視角" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "mother tongue", meaning: "母語" },
      { phrase: "code-switch", meaning: "切換語碼" },
      { phrase: "accent discrimination", meaning: "口音歧視" },
      { phrase: "linguistic oppression", meaning: "語言壓迫" },
      { phrase: "language revitalization", meaning: "語言振興" },
      { phrase: "self-determination", meaning: "自我決定；自決" },
      { phrase: "power structure", meaning: "權力結構" },
      { phrase: "visceral", meaning: "直覺性的；發自內心的" },
      { phrase: "minority language", meaning: "少數語言" },
      { phrase: "intertwined", meaning: "交織的；緊密相連的" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 2,
    date: '2026-11-24',
    theme: 'Language & Identity',
    title: 'Slang, Jargon, and Belonging',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Why We Use Slang',
        lines: [
          { speaker: 'a', english: "Do you use a lot of slang? I find slang fascinating.", chinese: "你用很多俚語嗎？我覺得俚語很迷人。", vocabulary: [{ word: "slang", definition: "俚語；俗語" }] },
          { speaker: 'b', english: "I use different slang with different groups. It's like a tribal membership card.", chinese: "我和不同的群體用不同的俚語，就像部落會員卡一樣。", vocabulary: [{ word: "tribal", definition: "部落的；群體性的" }] },
          { speaker: 'a', english: "That's exactly it. Slang signals belonging — I'm one of you.", chinese: "正是這樣，俚語表示歸屬感——我是你們中的一員。", vocabulary: [{ word: "signal", definition: "表示；發信號" }] },
          { speaker: 'b', english: "When you know the latest slang in a community, you're in the loop.", chinese: "當你知道一個社群中最新的俚語時，你就在圈子裡了。", vocabulary: [{ word: "in the loop", definition: "在圈子裡；了解最新情況" }] },
          { speaker: 'a', english: "And when you use outdated slang, it can signal that you're out of touch.", chinese: "當你使用過時的俚語時，它可能表示你脫節了。", vocabulary: [{ word: "out of touch", definition: "脫節；不了解最新情況" }] },
          { speaker: 'b', english: "That's why slang changes so fast — the moment everyone uses it, it loses its exclusivity.", chinese: "這就是為什麼俚語變化如此快——一旦每個人都使用它，它就失去了獨特性。", vocabulary: [{ word: "exclusivity", definition: "獨特性；排他性" }] },
          { speaker: 'a', english: "Slang is living language — it captures what formal language is too slow to name.", chinese: "俚語是活的語言——它捕捉了正式語言太慢而無法命名的東西。", vocabulary: [] },
          { speaker: 'b', english: "Young people especially use slang to define themselves apart from older generations.", chinese: "年輕人尤其使用俚語來定義自己與老一代的不同。", vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Professional Jargon and Gatekeeping',
        lines: [
          { speaker: 'a', english: "Professional jargon is a different kind of in-group language.", chinese: "專業術語是一種不同的內群體語言。", vocabulary: [{ word: "jargon", definition: "術語；行話" }] },
          { speaker: 'b', english: "Every field has it — medicine, law, tech, finance. It can be necessary or obfuscating.", chinese: "每個領域都有——醫學、法律、科技、金融，它可以是必要的或模糊不清的。", vocabulary: [{ word: "obfuscating", definition: "使模糊不清的；晦澀的" }] },
          { speaker: 'a', english: "Necessary when precision matters — medical terms exist to be exact.", chinese: "在需要精確時是必要的——醫學術語的存在是為了準確。", vocabulary: [{ word: "precision", definition: "精確；準確" }] },
          { speaker: 'b', english: "But sometimes jargon is used to impress or exclude, not to clarify.", chinese: "但有時術語被用來留下印象或排除他人，而不是為了澄清。", vocabulary: [] },
          { speaker: 'a', english: "That's gatekeeping — using language to signal who belongs and who doesn't.", chinese: "那是守門——使用語言來表示誰屬於這個圈子，誰不屬於。", vocabulary: [{ word: "gatekeeping", definition: "守門；控制進入" }] },
          { speaker: 'b', english: "I've been in meetings where I felt lost in jargon that seemed more performative than useful.", chinese: "我曾在會議中迷失在看起來更多是表演性而非實用性的術語中。", vocabulary: [{ word: "performative", definition: "表演性的；展示性的" }] },
          { speaker: 'a', english: "Good communicators translate jargon when the audience doesn't need it.", chinese: "好的溝通者在聽眾不需要時會翻譯術語。", vocabulary: [] },
          { speaker: 'b', english: "Plain language is actually a skill. Making complex things simple is harder than making them complicated.", chinese: "平易近人的語言實際上是一種技能，把複雜的事情簡化比使它們複雜更難。", vocabulary: [{ word: "plain language", definition: "平易近人的語言；淺顯語言" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'How Language Evolves Online',
        lines: [
          { speaker: 'a', english: "The internet has revolutionized how language evolves and spreads.", chinese: "網路徹底改變了語言的演化和傳播方式。", vocabulary: [{ word: "revolutionize", definition: "革命性地改變；徹底變革" }] },
          { speaker: 'b', english: "Memes are a kind of micro-language — they compress complex meaning into an image and phrase.", chinese: "迷因是一種微型語言——它們將複雜的意義壓縮成圖像和短語。", vocabulary: [{ word: "meme", definition: "迷因；網路梗" }] },
          { speaker: 'a', english: "And they spread globally in hours. Language change that used to take decades happens overnight.", chinese: "而且它們在幾小時內傳播到全球，以前需要幾十年的語言變化一夜之間就發生了。", vocabulary: [] },
          { speaker: 'b', english: "Internet English has its own grammar — 'I can has', 'much wow', all-caps for emphasis.", chinese: "網路英語有自己的語法——「I can has」、「much wow」、全大寫表示強調。", vocabulary: [] },
          { speaker: 'a', english: "Linguists find it fascinating, even if traditionalists find it disturbing.", chinese: "語言學家覺得它很迷人，即使傳統主義者覺得它令人不安。", vocabulary: [{ word: "linguist", definition: "語言學家" }] },
          { speaker: 'b', english: "Every generation invents new ways to speak. It's always been this way.", chinese: "每一代人都發明新的說話方式，一直都是這樣的。", vocabulary: [] },
          { speaker: 'a', english: "What matters is whether communication is effective — and clearly, memes are very effective.", chinese: "重要的是溝通是否有效——而且顯然，迷因非常有效。", vocabulary: [] },
          { speaker: 'b', english: "They communicate tone and nuance in ways that plain text sometimes can't.", chinese: "它們以純文字有時無法做到的方式傳達語氣和細微差異。", vocabulary: [{ word: "nuance", definition: "細微差異；微妙之處" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Humor and Language',
        lines: [
          { speaker: 'a', english: "Humor is maybe the hardest thing to translate across languages.", chinese: "幽默也許是跨語言最難翻譯的東西。", vocabulary: [] },
          { speaker: 'b', english: "Because it often depends on wordplay, cultural references, or timing — all culturally specific.", chinese: "因為它通常依賴文字遊戲、文化指涉或時機——所有這些都是文化特有的。", vocabulary: [{ word: "wordplay", definition: "文字遊戲" }] },
          { speaker: 'a', english: "Nothing kills a joke like having to explain it. 'It's funny because...' never works.", chinese: "沒有什麼比必須解釋它更能殺掉一個笑話了，「它很有趣因為……」從來不奏效。", vocabulary: [] },
          { speaker: 'b', english: "Yet when you finally get the humor in a second language, it feels like a real achievement.", chinese: "然而當你終於明白了第二語言中的幽默，感覺像是一種真正的成就。", vocabulary: [] },
          { speaker: 'a', english: "I remember the first time a joke in English made me laugh instinctively. It felt like arriving.", chinese: "我記得第一次英語笑話讓我本能地笑的時候，感覺像是到達了。", vocabulary: [{ word: "instinctively", definition: "本能地；直覺地" }] },
          { speaker: 'b', english: "Like you'd passed through a door into deeper fluency.", chinese: "就像你穿過了一扇通向更深流利度的門。", vocabulary: [{ word: "fluency", definition: "流利度；流暢" }] },
          { speaker: 'a', english: "Sarcasm especially is very culturally loaded — it works very differently across cultures.", chinese: "諷刺尤其是非常文化負載的——它在不同文化中的運作方式差異很大。", vocabulary: [{ word: "sarcasm", definition: "諷刺；挖苦" }] },
          { speaker: 'b', english: "Some cultures love it; others find it rude or confusing. Context is everything.", chinese: "有些文化喜歡它；其他文化認為它粗魯或令人困惑，情境就是一切。", vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'Finding Your Voice',
        lines: [
          { speaker: 'a', english: "When learning a language, at what point do you develop your own authentic voice?", chinese: "在學習一種語言時，你在什麼時候發展出自己真實的聲音？", vocabulary: [{ word: "authentic voice", definition: "真實的聲音；本真的聲音" }] },
          { speaker: 'b', english: "I think it happens gradually — you start copying models and eventually mix them with yourself.", chinese: "我認為這是漸漸發生的——你開始模仿模範，最終將它們與你自己混合。", vocabulary: [] },
          { speaker: 'a', english: "Early on, you might feel like you're performing — putting on a linguistic costume.", chinese: "一開始，你可能感覺像是在表演——穿上語言的戲服。", vocabulary: [{ word: "linguistic costume", definition: "語言的戲服（比喻）" }] },
          { speaker: 'b', english: "But with use, it becomes more natural. The costume becomes part of you.", chinese: "但隨著使用，它變得更自然，戲服成為你的一部分。", vocabulary: [] },
          { speaker: 'a', english: "I think voice in any language is about confidence, not perfection.", chinese: "我認為任何語言中的聲音都是關於自信，而不是完美。", vocabulary: [] },
          { speaker: 'b', english: "Speaking boldly with mistakes is better than staying silent to avoid them.", chinese: "大膽地說話帶有錯誤，比保持沉默以避免錯誤要好。", vocabulary: [{ word: "boldly", definition: "大膽地；勇敢地" }] },
          { speaker: 'a', english: "Your unique perspective has value — people want to hear what you specifically think.", chinese: "你獨特的視角很有價值——人們想聽你具體的想法。", vocabulary: [] },
          { speaker: 'b', english: "Language is ultimately a tool for connection. Don't let fear of imperfection silence you.", chinese: "語言最終是連結的工具，不要讓對不完美的恐懼讓你沉默。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "slang", meaning: "俚語；俗語" },
      { phrase: "code-switch", meaning: "切換語碼" },
      { phrase: "jargon", meaning: "術語；行話" },
      { phrase: "gatekeeping", meaning: "守門；控制進入" },
      { phrase: "plain language", meaning: "平易近人的語言" },
      { phrase: "in the loop", meaning: "在圈子裡；了解最新情況" },
      { phrase: "authentic voice", meaning: "真實的聲音" },
      { phrase: "wordplay", meaning: "文字遊戲" },
      { phrase: "linguistic oppression", meaning: "語言壓迫" },
      { phrase: "fluency", meaning: "流利度；流暢" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 3,
    date: '2026-11-25',
    theme: 'Language & Identity',
    title: 'Bilingual Lives',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'The Bilingual Experience',
        lines: [
          { speaker: 'a', english: "What's it like to live bilingually — to move between two languages daily?", chinese: "雙語生活是什麼感覺——每天在兩種語言之間切換？", vocabulary: [{ word: "bilingually", definition: "以雙語方式；在兩種語言之間" }] },
          { speaker: 'b', english: "It's remarkably natural when you're immersed in both — you don't really think about it.", chinese: "當你沉浸在兩者中時，它是非常自然的——你根本不會想到它。", vocabulary: [{ word: "immersed", definition: "沉浸於；投入於" }] },
          { speaker: 'a', english: "But switching context — going from a work environment in one language to home in another — can feel like shifting gears.", chinese: "但切換情境——從一種語言的工作環境切換到另一種語言的家庭——可能感覺像換檔。", vocabulary: [{ word: "shifting gears", definition: "換檔；轉換模式" }] },
          { speaker: 'b', english: "There's a brief adjustment period where neither language feels quite right.", chinese: "有一個短暫的調整期，在那裡哪種語言都感覺不太對勁。", vocabulary: [{ word: "adjustment period", definition: "調整期" }] },
          { speaker: 'a', english: "Bilinguals sometimes mix languages in the same sentence — what linguists call code-mixing.", chinese: "雙語者有時在同一句話中混用語言——語言學家稱之為語碼混用。", vocabulary: [{ word: "code-mixing", definition: "語碼混用" }] },
          { speaker: 'b', english: "That's not confusion — it's actually sophisticated. You're using the best tool from each language.", chinese: "那不是困惑——它實際上很複雜，你在使用每種語言中最好的工具。", vocabulary: [{ word: "sophisticated", definition: "複雜的；成熟的" }] },
          { speaker: 'a', english: "There are words in one language that capture something the other can't.", chinese: "一種語言中有一些詞能捕捉到另一種語言無法表達的東西。", vocabulary: [] },
          { speaker: 'b', english: "Exactly. Why use a sentence when there's a perfect word in another language?", chinese: "正是，當另一種語言中有一個完美的詞時，為什麼要用一個句子？", vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Raising Bilingual Children',
        lines: [
          { speaker: 'a', english: "Many parents want to raise their children bilingually. What does research say?", chinese: "許多父母想要以雙語方式撫養孩子，研究怎麼說？", vocabulary: [] },
          { speaker: 'b', english: "The research is very positive. Bilingual children tend to have better cognitive development.", chinese: "研究非常正面，雙語兒童傾向於有更好的認知發展。", vocabulary: [{ word: "cognitive development", definition: "認知發展" }] },
          { speaker: 'a', english: "They're better at tasks requiring attention, multi-tasking, and switching perspectives.", chinese: "他們在需要注意力、多任務處理和切換視角的任務中表現更好。", vocabulary: [] },
          { speaker: 'b', english: "There's also a myth that bilingualism confuses children. The opposite is true.", chinese: "也有一個迷思說雙語會讓孩子感到困惑，事實恰恰相反。", vocabulary: [{ word: "myth", definition: "迷思；神話" }] },
          { speaker: 'a', english: "The key is consistency — one parent, one language, is a popular approach.", chinese: "關鍵是一致性——一個父母，一種語言，是一種流行的方法。", vocabulary: [{ word: "consistency", definition: "一致性" }] },
          { speaker: 'b', english: "And keeping the minority language strong takes conscious effort as kids get older.", chinese: "當孩子長大後，保持少數語言的強度需要有意識的努力。", vocabulary: [{ word: "minority language", definition: "少數語言" }] },
          { speaker: 'a', english: "Schools, media, and social life often pressure children toward the dominant language.", chinese: "學校、媒體和社交生活往往向孩子施壓，讓他們使用主導語言。", vocabulary: [] },
          { speaker: 'b', english: "Heritage language preservation is a meaningful act of cultural continuity.", chinese: "傳承語言保存是文化延續的一種有意義的行為。", vocabulary: [{ word: "heritage language", definition: "傳承語言" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'The Politics of Language Choice',
        lines: [
          { speaker: 'a', english: "Which language to use in a given situation can have political implications.", chinese: "在特定情況下使用哪種語言可能有政治含義。", vocabulary: [{ word: "political implications", definition: "政治含義" }] },
          { speaker: 'b', english: "Choosing to speak your minority language in public can be an act of identity assertion.", chinese: "在公共場合選擇說你的少數語言可以是一種身份認同的主張。", vocabulary: [{ word: "identity assertion", definition: "身份認同主張" }] },
          { speaker: 'a', english: "Conversely, always defaulting to the dominant language can feel like erasure.", chinese: "相反地，總是默認使用主導語言可能感覺像是抹除。", vocabulary: [{ word: "erasure", definition: "抹除；消除" }] },
          { speaker: 'b', english: "In multilingual societies, language policy is always politically charged.", chinese: "在多語言社會中，語言政策總是充滿政治性的。", vocabulary: [{ word: "politically charged", definition: "政治敏感的；充滿政治性的" }] },
          { speaker: 'a', english: "Taiwan has a rich and complex multilingual history — Mandarin, Taiwanese, Hakka, indigenous languages.", chinese: "台灣有豐富而複雜的多語言歷史——普通話、台語、客家話、原住民語言。", vocabulary: [] },
          { speaker: 'b', english: "Efforts to preserve and teach all those languages are deeply meaningful for identity.", chinese: "保存和教授所有這些語言的努力對身份認同非常重要。", vocabulary: [] },
          { speaker: 'a', english: "A truly pluralistic society values all its linguistic traditions.", chinese: "一個真正多元化的社會重視所有它的語言傳統。", vocabulary: [{ word: "pluralistic", definition: "多元化的；多元主義的" }] },
          { speaker: 'b', english: "Language diversity is biodiversity for culture — lose it and you lose something irreplaceable.", chinese: "語言多樣性是文化的生物多樣性——失去它，你就失去了一些不可替代的東西。", vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'Language Learning as Adults',
        lines: [
          { speaker: 'a', english: "Is it true that adults can never learn a language as well as children?", chinese: "成年人真的永遠無法像孩子一樣學好一門語言嗎？", vocabulary: [] },
          { speaker: 'b', english: "The critical period hypothesis says there's a window for native-like acquisition.", chinese: "關鍵期假說說有一個類母語習得的窗口期。", vocabulary: [{ word: "critical period hypothesis", definition: "關鍵期假說" }] },
          { speaker: 'a', english: "But adults have huge advantages too — they understand grammar better and have larger vocabularies to draw on.", chinese: "但成年人也有巨大優勢——他們更好地理解語法，並有更大的詞彙量可以借鑑。", vocabulary: [] },
          { speaker: 'b', english: "Adults tend to make faster progress in the early stages because of that foundation.", chinese: "成年人在早期階段往往因為這個基礎而進步更快。", vocabulary: [{ word: "foundation", definition: "基礎；根基" }] },
          { speaker: 'a', english: "The main disadvantage is accent — phonological plasticity decreases with age.", chinese: "主要劣勢是口音——語音可塑性隨年齡下降。", vocabulary: [{ word: "phonological plasticity", definition: "語音可塑性" }] },
          { speaker: 'b', english: "But having an accent doesn't mean being less fluent. Plenty of excellent speakers have accents.", chinese: "但有口音不代表不那麼流利，許多優秀的說話者都有口音。", vocabulary: [] },
          { speaker: 'a', english: "Motivation is honestly the biggest predictor of adult language learning success.", chinese: "說真的，動機是成人語言學習成功最大的預測因素。", vocabulary: [{ word: "predictor", definition: "預測因素；預測指標" }] },
          { speaker: 'b', english: "People who really want to connect in another language find ways to make it happen.", chinese: "真正想要用另一種語言連結的人會找到讓它發生的方法。", vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'Languages as Worlds',
        lines: [
          { speaker: 'a', english: "I believe every language you learn opens up a new universe.", chinese: "我相信你學習的每一種語言都打開了一個新宇宙。", vocabulary: [] },
          { speaker: 'b', english: "It's not just new words — it's new literature, humor, music, thought patterns.", chinese: "不只是新詞——是新的文學、幽默、音樂、思維模式。", vocabulary: [] },
          { speaker: 'a', english: "I want to someday read certain books in the language they were written in.", chinese: "我有一天想用原著語言閱讀某些書籍。", vocabulary: [] },
          { speaker: 'b', english: "Something is always different in translation — the original has a soul the translation can only approximate.", chinese: "翻譯中總有些東西不同——原著有一種靈魂，翻譯只能近似地呈現。", vocabulary: [{ word: "approximate", definition: "近似地呈現；接近" }] },
          { speaker: 'a', english: "Each language I learn makes me feel more connected to humanity as a whole.", chinese: "我學習的每一種語言都讓我感到與整個人類更緊密相連。", vocabulary: [] },
          { speaker: 'b', english: "Language learning is one of the most generous things you can do — for yourself and for others.", chinese: "語言學習是你可以為自己和他人做的最慷慨的事情之一。", vocabulary: [{ word: "generous", definition: "慷慨的；大方的" }] },
          { speaker: 'a', english: "It says: your world is worth entering. Your language matters. You matter.", chinese: "它說：你的世界值得進入，你的語言很重要，你很重要。", vocabulary: [] },
          { speaker: 'b', english: "That message — in any language — might be the most important one we can send.", chinese: "那個訊息——用任何語言——可能是我們能傳遞的最重要的訊息。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "heritage language", meaning: "傳承語言" },
      { phrase: "code-mixing", meaning: "語碼混用" },
      { phrase: "critical period hypothesis", meaning: "關鍵期假說" },
      { phrase: "identity assertion", meaning: "身份認同主張" },
      { phrase: "pluralistic society", meaning: "多元化社會" },
      { phrase: "minority language", meaning: "少數語言" },
      { phrase: "cognitive development", meaning: "認知發展" },
      { phrase: "phonological plasticity", meaning: "語音可塑性" },
      { phrase: "erasure", meaning: "抹除；消除" },
      { phrase: "immersed", meaning: "沉浸於；投入於" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 4,
    date: '2026-11-26',
    theme: 'Language & Identity',
    title: 'Storytelling and Narrative Identity',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Stories as Identity',
        lines: [
          { speaker: 'a', english: "Psychologists say we construct our identities through the stories we tell about ourselves.", chinese: "心理學家說我們通過我們對自己講述的故事來建構我們的身份認同。", vocabulary: [{ word: "construct", definition: "建構；構建" }] },
          { speaker: 'b', english: "The narrative self — you are the protagonist of a story you're constantly writing.", chinese: "敘事自我——你是你不斷撰寫的故事中的主角。", vocabulary: [{ word: "protagonist", definition: "主角；主人公" }] },
          { speaker: 'a', english: "And the story you tell about yourself shapes how you behave going forward.", chinese: "你對自己講述的故事塑造了你未來的行為方式。", vocabulary: [] },
          { speaker: 'b', english: "If you tell yourself 'I'm not good with technology,' that belief becomes self-fulfilling.", chinese: "如果你對自己說「我不擅長科技」，那個信念就會自我實現。", vocabulary: [{ word: "self-fulfilling", definition: "自我實現的" }] },
          { speaker: 'a', english: "Rewriting the story — changing the narrative — is how transformation happens.", chinese: "重寫故事——改變敘事——就是轉變發生的方式。", vocabulary: [{ word: "narrative", definition: "敘事；故事" }] },
          { speaker: 'b', english: "That's why therapy often focuses on how people are telling their own story.", chinese: "這就是為什麼治療通常聚焦於人們如何講述自己的故事。", vocabulary: [] },
          { speaker: 'a', english: "Narrative therapy — changing the frames around your experiences.", chinese: "敘事療法——改變你體驗周圍的框架。", vocabulary: [{ word: "narrative therapy", definition: "敘事療法" }] },
          { speaker: 'b', english: "The same experience can be a failure or a lesson depending on how you narrate it.", chinese: "同一個體驗可以是失敗或教訓，取決於你如何敘述它。", vocabulary: [{ word: "narrate", definition: "敘述；講述" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Cultural Stories and Mythology',
        lines: [
          { speaker: 'a', english: "Cultures also have collective stories — myths, legends, national narratives.", chinese: "文化也有集體故事——神話、傳說、國家敘事。", vocabulary: [{ word: "mythology", definition: "神話；神話學" }] },
          { speaker: 'b', english: "These stories explain where we came from, what we value, who our heroes are.", chinese: "這些故事解釋了我們從哪裡來、我們重視什麼、我們的英雄是誰。", vocabulary: [] },
          { speaker: 'a', english: "Every culture's founding stories shape its values in subtle but profound ways.", chinese: "每種文化的創始故事以微妙但深刻的方式塑造了它的價值觀。", vocabulary: [] },
          { speaker: 'b', english: "I love how the same archetypes appear across cultures — the hero's journey, the trickster, the wise elder.", chinese: "我喜歡同樣的原型如何在不同文化中出現——英雄的旅程、搗蛋鬼、智慧長者。", vocabulary: [{ word: "archetype", definition: "原型；典範" }] },
          { speaker: 'a', english: "Joseph Campbell called these universal structures the monomyth — the hero with a thousand faces.", chinese: "約瑟夫·坎貝爾稱這些普遍結構為單一神話——千面英雄。", vocabulary: [{ word: "monomyth", definition: "單一神話（英雄旅程的普遍結構）" }] },
          { speaker: 'b', english: "It suggests that beneath cultural differences, we share the same fundamental story templates.", chinese: "這表明在文化差異之下，我們共享相同的基本故事模板。", vocabulary: [{ word: "template", definition: "模板；範本" }] },
          { speaker: 'a', english: "That's reassuring — we may be more fundamentally alike than we appear.", chinese: "那讓人安心——我們可能在根本上比表面上看起來更相似。", vocabulary: [{ word: "reassuring", definition: "讓人安心的；令人放心的" }] },
          { speaker: 'b', english: "Good stories — from any culture — resonate because they touch something universally human.", chinese: "好故事——來自任何文化——能引起共鳴，因為它們觸動了普遍人性的東西。", vocabulary: [{ word: "resonate", definition: "引起共鳴" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'The Power of Personal Narrative',
        lines: [
          { speaker: 'a', english: "Telling your story — really articulating your life experience — is powerful.", chinese: "講述你的故事——真正表達你的生活體驗——是有力量的。", vocabulary: [{ word: "articulate", definition: "表達；清楚說明" }] },
          { speaker: 'b', english: "It helps you make sense of what happened and see patterns you might have missed.", chinese: "它幫助你理解發生的事情，看到你可能忽視的模式。", vocabulary: [] },
          { speaker: 'a', english: "Writing in a journal is one way. Talking to a trusted person is another.", chinese: "在日記中寫作是一種方式，與信任的人交談是另一種方式。", vocabulary: [] },
          { speaker: 'b', english: "I've found that when I can narrate a difficult experience coherently, it loses some of its power over me.", chinese: "我發現當我能夠連貫地敘述一個困難的體驗時，它對我的控制力就會減弱。", vocabulary: [{ word: "coherently", definition: "連貫地；條理清楚地" }] },
          { speaker: 'a', english: "There's research showing that writing about trauma actually accelerates healing.", chinese: "有研究表明，寫作關於創傷實際上能加速愈合。", vocabulary: [{ word: "trauma", definition: "創傷；心理創傷" }] },
          { speaker: 'b', english: "Because it converts raw emotion into structured meaning — that's how we process things.", chinese: "因為它將原始情感轉化為結構化意義——那是我們處理事情的方式。", vocabulary: [] },
          { speaker: 'a', english: "Storytelling is how humans have always made sense of the world.", chinese: "講故事是人類理解世界的方式。", vocabulary: [] },
          { speaker: 'b', english: "We are, fundamentally, the stories we tell — to ourselves and to each other.", chinese: "從根本上說，我們就是我們講述的故事——對自己和對彼此。", vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'Whose Stories Get Told?',
        lines: [
          { speaker: 'a', english: "There's an important question about whose stories get told and who gets to tell them.", chinese: "有一個重要的問題：誰的故事被講述，誰有資格講述它們。", vocabulary: [] },
          { speaker: 'b', english: "Historically, the stories of marginalized groups were suppressed or distorted by those in power.", chinese: "歷史上，被邊緣化群體的故事被當權者壓制或扭曲。", vocabulary: [{ word: "distorted", definition: "扭曲的；被歪曲的" }] },
          { speaker: 'a', english: "When only certain voices dominate media and literature, it warps our shared sense of reality.", chinese: "當只有某些聲音主導媒體和文學時，它扭曲了我們共同的現實感。", vocabulary: [{ word: "dominate", definition: "主導；支配" }] },
          { speaker: 'b', english: "The push for diverse representation in storytelling isn't just symbolic — it's epistemological.", chinese: "在故事講述中推動多元代表性不只是象徵性的——它是認識論的。", vocabulary: [{ word: "epistemological", definition: "認識論的；知識論的" }] },
          { speaker: 'a', english: "Having more perspectives means we know more, collectively. We understand more of reality.", chinese: "有更多視角意味著我們集體知道更多，我們理解更多的現實。", vocabulary: [] },
          { speaker: 'b', english: "Chimamanda Ngozi Adichie's TED Talk — the danger of a single story — articulates this beautifully.", chinese: "奇馬曼達·恩戈茲·阿迪契的 TED 演講——單一故事的危險——美麗地表達了這一點。", vocabulary: [] },
          { speaker: 'a', english: "When we hear only one story about a group, we lose the full, complex, human truth.", chinese: "當我們只聽到關於一個群體的一個故事時，我們失去了完整、複雜、人性的真相。", vocabulary: [] },
          { speaker: 'b', english: "Diverse voices in storytelling are an act of epistemic justice.", chinese: "故事講述中的多元聲音是一種認識論正義的行為。", vocabulary: [{ word: "epistemic justice", definition: "認識論正義；知識正義" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Your Story in English',
        lines: [
          { speaker: 'a', english: "As you learn English, you're also learning to tell your story in a new language.", chinese: "當你學習英語時，你也在學習用新語言講述你的故事。", vocabulary: [] },
          { speaker: 'b', english: "That's actually one of the most powerful exercises for language learners.", chinese: "那實際上是語言學習者最有力的練習之一。", vocabulary: [] },
          { speaker: 'a', english: "Telling autobiographical stories — your life, your family, your experiences.", chinese: "講述自傳性故事——你的生活、你的家庭、你的經歷。", vocabulary: [{ word: "autobiographical", definition: "自傳性的；關於自身經歷的" }] },
          { speaker: 'b', english: "Not just textbook scenarios — real things that happened to you and what they meant.", chinese: "不只是教科書情境——發生在你身上的真實事情以及它們的意義。", vocabulary: [] },
          { speaker: 'a', english: "When you bring your real self to language practice, it becomes meaningful, not just mechanical.", chinese: "當你把真實的自我帶入語言練習時，它變得有意義，而不只是機械性的。", vocabulary: [{ word: "mechanical", definition: "機械性的；缺乏感情的" }] },
          { speaker: 'b', english: "And your story is worth telling. Your experience has things to teach that no one else can offer.", chinese: "而且你的故事值得講述，你的體驗有其他人無法提供的東西可以教導。", vocabulary: [] },
          { speaker: 'a', english: "Every person who learns to tell their story in a new language expands what that language can hold.", chinese: "每個學會在新語言中講述自己故事的人，都擴展了那種語言所能容納的範圍。", vocabulary: [] },
          { speaker: 'b', english: "Language grows richer the more stories it carries. Yours adds to that richness.", chinese: "語言承載的故事越多就越豐富，你的故事為那種豐富性增添了一份。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "narrative identity", meaning: "敘事身份認同" },
      { phrase: "narrative therapy", meaning: "敘事療法" },
      { phrase: "monomyth", meaning: "單一神話（英雄旅程結構）" },
      { phrase: "archetype", meaning: "原型；典範" },
      { phrase: "self-fulfilling", meaning: "自我實現的" },
      { phrase: "epistemic justice", meaning: "認識論正義" },
      { phrase: "autobiographical", meaning: "自傳性的" },
      { phrase: "single story danger", meaning: "單一故事的危險" },
      { phrase: "resonate", meaning: "引起共鳴" },
      { phrase: "protagonist", meaning: "主角；主人公" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 5,
    date: '2026-11-27',
    theme: 'Language & Identity',
    title: 'Words That Shape Thinking',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Framing Effects in Language',
        lines: [
          { speaker: 'a', english: "Have you noticed how the words we use actually shape how we perceive situations?", chinese: "你有沒有注意到我們使用的詞語實際上如何塑造我們對情況的感知？", vocabulary: [{ word: "perceive", definition: "感知；認知" }] },
          { speaker: 'b', english: "Yes — it's called framing. The same fact described differently creates different responses.", chinese: "是的——這叫做框架效應，同一事實以不同方式描述會產生不同的反應。", vocabulary: [{ word: "framing", definition: "框架；框架效應" }] },
          { speaker: 'a', english: "Politicians use this all the time — 'tax relief' versus 'tax cuts' — same thing, different feel.", chinese: "政治家一直使用這個——「稅務減免」對「減稅」——同一件事，不同的感覺。", vocabulary: [] },
          { speaker: 'b', english: "Or 'collateral damage' instead of 'civilian casualties' — language that softens harsh realities.", chinese: "或者「附帶損害」而不是「平民傷亡」——軟化殘酷現實的語言。", vocabulary: [{ word: "collateral damage", definition: "附帶損害（戰爭術語）" }] },
          { speaker: 'a', english: "Euphemism is language's way of making difficult things easier to say.", chinese: "委婉語是語言使困難的事情更容易說出口的方式。", vocabulary: [{ word: "euphemism", definition: "委婉語；婉辭" }] },
          { speaker: 'b', english: "But it can also become a way of avoiding the truth.", chinese: "但它也可能成為迴避真相的方式。", vocabulary: [] },
          { speaker: 'a', english: "Awareness of framing helps you think more critically about how information is presented to you.", chinese: "對框架的意識幫助你更批判性地思考如何向你呈現信息。", vocabulary: [{ word: "critically", definition: "批判性地；批評性地" }] },
          { speaker: 'b', english: "It's a form of media literacy that everyone needs in the information age.", chinese: "這是信息時代每個人都需要的一種媒體素養形式。", vocabulary: [{ word: "media literacy", definition: "媒體素養" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Positive Language and Mindset',
        lines: [
          { speaker: 'a', english: "The language we use to talk to ourselves also shapes our mindset.", chinese: "我們用來對自己說話的語言也塑造了我們的心態。", vocabulary: [] },
          { speaker: 'b', english: "Cognitive behavioral therapy works partly by changing self-talk from destructive to constructive.", chinese: "認知行為療法部分地通過將自我對話從破壞性改變為建設性來發揮作用。", vocabulary: [{ word: "cognitive behavioral therapy", definition: "認知行為療法" }] },
          { speaker: 'a', english: "Instead of 'I'm terrible at this,' trying 'I haven't mastered this yet.'", chinese: "不是「我這方面很糟糕」，而是嘗試「我還沒有掌握這個」。", vocabulary: [] },
          { speaker: 'b', english: "The word 'yet' — from Carol Dweck's growth mindset — is remarkably powerful.", chinese: "「還」這個詞——來自卡蘿·德韋克的成長心態——是非常有力量的。", vocabulary: [{ word: "growth mindset", definition: "成長心態" }] },
          { speaker: 'a', english: "It implies possibility and future growth rather than fixed limitations.", chinese: "它暗示著可能性和未來成長，而不是固定的限制。", vocabulary: [{ word: "fixed limitations", definition: "固定的限制" }] },
          { speaker: 'b', english: "The language of resilience too — 'this is hard, and I can handle hard things.'", chinese: "韌性的語言也是——「這很難，而我能夠處理困難的事情。」", vocabulary: [] },
          { speaker: 'a', english: "What we say to ourselves when faced with challenge determines so much about the outcome.", chinese: "當面對挑戰時我們對自己說什麼，很大程度上決定了結果。", vocabulary: [] },
          { speaker: 'b', english: "Conscious language use is a form of self-care and self-empowerment.", chinese: "有意識地使用語言是一種自我照顧和自我賦權的形式。", vocabulary: [{ word: "self-empowerment", definition: "自我賦權；自我增能" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'The Language of Inclusion',
        lines: [
          { speaker: 'a', english: "Language evolves to become more inclusive — reflecting changing social values.", chinese: "語言演化得越來越具有包容性——反映了不斷變化的社會價值觀。", vocabulary: [{ word: "inclusive", definition: "包容的；含括各方的" }] },
          { speaker: 'b', english: "Gender-neutral language is one example — using 'they' as a singular pronoun.", chinese: "性別中立語言是一個例子——使用「they」作為單數代詞。", vocabulary: [{ word: "gender-neutral language", definition: "性別中立語言" }] },
          { speaker: 'a', english: "Some people embrace this as progress; others find it linguistically awkward.", chinese: "有些人把這視為進步；其他人認為在語言上有些尷尬。", vocabulary: [{ word: "linguistically", definition: "語言學上地；從語言角度" }] },
          { speaker: 'b', english: "Language changes often feel awkward at first but become natural with use.", chinese: "語言變化一開始常常感到尷尬，但隨著使用變得自然。", vocabulary: [] },
          { speaker: 'a', english: "How we name groups matters — what terms are preferred changes over time.", chinese: "我們如何命名群體很重要——首選的術語會隨時間改變。", vocabulary: [] },
          { speaker: 'b', english: "The principle is to use the terms preferred by the people themselves.", chinese: "原則是使用人們自己偏好的術語。", vocabulary: [] },
          { speaker: 'a', english: "It's a sign of respect — making the effort to use someone's preferred language.", chinese: "這是尊重的表示——努力使用某人偏好的語言。", vocabulary: [] },
          { speaker: 'b', english: "And language inclusion is about more than labels — it's about whose experiences get centered.", chinese: "語言包容不只是關於標籤——它關乎誰的體驗被放在中心。", vocabulary: [{ word: "centered", definition: "被放在中心；被重視" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Metaphors We Live By',
        lines: [
          { speaker: 'a', english: "Linguists Lakoff and Johnson argued that metaphors structure how we think.", chinese: "語言學家拉可夫和詹森認為隱喻構建了我們的思維方式。", vocabulary: [{ word: "metaphor", definition: "隱喻；比喻" }] },
          { speaker: 'b', english: "Like how we talk about argument as war — 'he attacked my position', 'she defended her idea.'", chinese: "就像我們把爭論說成戰爭——「他攻擊了我的立場」、「她捍衛了她的想法」。", vocabulary: [] },
          { speaker: 'a', english: "What if we talked about argument as a collaborative journey instead?", chinese: "如果我們把爭論說成協作的旅程會怎樣？", vocabulary: [] },
          { speaker: 'b', english: "The metaphor shifts the entire meaning — from combat to exploration.", chinese: "隱喻改變了整個意義——從戰鬥到探索。", vocabulary: [] },
          { speaker: 'a', english: "We also talk about time as money — 'spending time', 'wasting time', 'investing time.'", chinese: "我們也把時間說成金錢——「花時間」、「浪費時間」、「投資時間」。", vocabulary: [] },
          { speaker: 'b', english: "That framing influences our whole relationship with time — it has to be 'used productively.'", chinese: "那種框架影響了我們與時間的整個關係——它必須被「有效地使用」。", vocabulary: [] },
          { speaker: 'a', english: "Other cultures have very different metaphors for time — more cyclical, more relational.", chinese: "其他文化對時間有非常不同的隱喻——更循環的、更關係性的。", vocabulary: [{ word: "cyclical", definition: "循環的；週期性的" }] },
          { speaker: 'b', english: "Noticing the metaphors embedded in language gives you insight into deeply held cultural values.", chinese: "注意嵌入語言中的隱喻，讓你洞察深根蒂固的文化價值觀。", vocabulary: [{ word: "embedded", definition: "嵌入的；根深蒂固的" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Using Language with Intention',
        lines: [
          { speaker: 'a', english: "After this week's discussions, I'm thinking more carefully about the language I choose.", chinese: "經過這週的討論，我對我選擇的語言思考得更仔細了。", vocabulary: [] },
          { speaker: 'b', english: "It's a practice — noticing the words you default to and asking if they're serving you.", chinese: "這是一種實踐——注意你習慣使用的詞語，並問自己它們是否在為你服務。", vocabulary: [{ word: "default to", definition: "習慣性地使用；默認選擇" }] },
          { speaker: 'a', english: "Intentional language use — in speaking and writing — creates real change.", chinese: "有意識的語言使用——在說話和寫作中——創造真正的改變。", vocabulary: [{ word: "intentional", definition: "有意識的；刻意的" }] },
          { speaker: 'b', english: "Not perfectionism about language — just thoughtfulness about its power.", chinese: "不是對語言的完美主義——只是對其力量的深思熟慮。", vocabulary: [{ word: "thoughtfulness", definition: "深思熟慮；體貼" }] },
          { speaker: 'a', english: "The words you speak to others also have power — to encourage, to wound, to inspire.", chinese: "你對他人說的話也有力量——鼓勵、傷害、激勵。", vocabulary: [] },
          { speaker: 'b', english: "That's a huge responsibility. Our daily words are tiny but cumulative acts of shaping reality.", chinese: "那是巨大的責任，我們日常的話語是微小但累積的塑造現實的行為。", vocabulary: [{ word: "cumulative", definition: "累積的；逐漸增加的" }] },
          { speaker: 'a', english: "Choose words that lift people up. Be generous with affirmation.", chinese: "選擇能鼓舞人的話語，對肯定慷慨大方。", vocabulary: [{ word: "affirmation", definition: "肯定；確認" }] },
          { speaker: 'b', english: "And notice the stories you tell — about yourself and others. Make them true and kind.", chinese: "注意你講述的故事——關於你自己和他人，讓它們真實且善良。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "framing effect", meaning: "框架效應" },
      { phrase: "euphemism", meaning: "委婉語；婉辭" },
      { phrase: "growth mindset", meaning: "成長心態" },
      { phrase: "media literacy", meaning: "媒體素養" },
      { phrase: "gender-neutral language", meaning: "性別中立語言" },
      { phrase: "cognitive behavioral therapy", meaning: "認知行為療法" },
      { phrase: "self-empowerment", meaning: "自我賦權" },
      { phrase: "metaphors we live by", meaning: "我們賴以生存的隱喻" },
      { phrase: "intentional language", meaning: "有意識的語言使用" },
      { phrase: "affirmation", meaning: "肯定；確認" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 6,
    date: '2026-11-28',
    theme: 'Language & Identity',
    title: 'Writing and Self-Expression',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Why Writing Matters',
        lines: [
          { speaker: 'a', english: "I've started keeping a journal again. I'd forgotten how much writing helps me think.", chinese: "我又開始寫日記了，我忘記了寫作多麼幫助我思考。", vocabulary: [{ word: "journal", definition: "日記；日誌" }] },
          { speaker: 'b', english: "Writing is thinking made visible. It forces clarity that speech doesn't always require.", chinese: "寫作是可見的思考，它迫使出演講不總是需要的清晰度。", vocabulary: [{ word: "clarity", definition: "清晰；清楚" }] },
          { speaker: 'a', english: "When I try to write something down, I often realize I don't understand it as well as I thought.", chinese: "當我試圖把某事寫下來時，我常常意識到我對它的理解不如我以為的好。", vocabulary: [] },
          { speaker: 'b', english: "That's the great benefit — writing reveals the gaps in your thinking.", chinese: "那是巨大的好處——寫作揭示了你思維中的空缺。", vocabulary: [] },
          { speaker: 'a', english: "It also creates a record — a way to track your own evolution over time.", chinese: "它也創建了記錄——追蹤你自己隨時間演化的方式。", vocabulary: [{ word: "evolution", definition: "演化；演變" }] },
          { speaker: 'b', english: "Reading old journal entries is strange and wonderful — like meeting a younger version of yourself.", chinese: "閱讀舊日記條目既奇怪又美好——就像遇見一個更年輕的自己。", vocabulary: [] },
          { speaker: 'a', english: "Writing also processes emotion — it externalizes what's internal.", chinese: "寫作也處理情感——它使內在的東西外在化。", vocabulary: [{ word: "externalize", definition: "外在化；表達出來" }] },
          { speaker: 'b', english: "There's research showing regular expressive writing improves mental and even physical health.", chinese: "有研究顯示定期的表達性寫作能改善心理甚至身體健康。", vocabulary: [{ word: "expressive writing", definition: "表達性寫作" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Finding Your Writing Voice',
        lines: [
          { speaker: 'a', english: "Many people feel intimidated by writing because they think it has to be 'good.'", chinese: "許多人對寫作感到畏怯，因為他們認為它必須「好」。", vocabulary: [{ word: "intimidated", definition: "畏怯的；被嚇到的" }] },
          { speaker: 'b', english: "The blank page is genuinely intimidating. That's universal among writers.", chinese: "空白頁面確實令人畏怯，這在作家中是普遍的。", vocabulary: [] },
          { speaker: 'a', english: "The trick is to give yourself permission to write badly first.", chinese: "訣竅是先允許自己寫得不好。", vocabulary: [{ word: "permission", definition: "許可；許可" }] },
          { speaker: 'b', english: "Anne Lamott calls it the 'shitty first draft' — just get it down, don't judge it yet.", chinese: "安·拉莫特稱之為「爛透的初稿」——只需把它寫下來，還不要評判它。", vocabulary: [{ word: "first draft", definition: "初稿；草稿" }] },
          { speaker: 'a', english: "All good writing goes through revision. The first draft is just the beginning.", chinese: "所有好的寫作都要經過修改，初稿只是開始。", vocabulary: [{ word: "revision", definition: "修改；修訂" }] },
          { speaker: 'b', english: "Writing voice develops through writing — you can't find it by thinking about it.", chinese: "寫作聲音通過寫作來發展——你無法通過思考它來找到它。", vocabulary: [] },
          { speaker: 'a', english: "The more you write, the more you develop patterns that are distinctly yours.", chinese: "你寫得越多，你就越能發展出屬於你自己獨特的模式。", vocabulary: [{ word: "distinctly", definition: "明顯地；獨特地" }] },
          { speaker: 'b', english: "Reading widely also helps — you absorb styles and find what resonates with you.", chinese: "廣泛閱讀也有幫助——你吸收風格並找到什麼與你共鳴。", vocabulary: [{ word: "absorb", definition: "吸收；融入" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Writing in a Second Language',
        lines: [
          { speaker: 'a', english: "Writing in English when it's not your first language presents unique challenges.", chinese: "當英語不是你的第一語言時，用英語寫作面臨獨特的挑戰。", vocabulary: [] },
          { speaker: 'b', english: "You have fewer words at your disposal — but that constraint can actually force clarity.", chinese: "你手頭的詞語較少——但那種限制實際上可以迫使你表達清晰。", vocabulary: [{ word: "constraint", definition: "限制；約束" }] },
          { speaker: 'a', english: "Simple, clear sentences are often more powerful than complex ones.", chinese: "簡單、清晰的句子通常比複雜的句子更有力量。", vocabulary: [] },
          { speaker: 'b', english: "Some famous writers have said their best work came in their second language.", chinese: "一些著名作家說他們最好的作品是用第二語言寫成的。", vocabulary: [] },
          { speaker: 'a', english: "The distance from the mother tongue can create a clarity of expression.", chinese: "與母語的距離可以創造一種表達的清晰度。", vocabulary: [] },
          { speaker: 'b', english: "Writing in English also helps internalize grammar in a way speaking doesn't always do.", chinese: "用英語寫作也幫助以說話並不總能做到的方式內化語法。", vocabulary: [{ word: "internalize", definition: "內化；使內在化" }] },
          { speaker: 'a', english: "Keeping an English journal — even a few sentences a day — is excellent practice.", chinese: "保持英語日記——即使每天只有幾句話——是很好的練習。", vocabulary: [] },
          { speaker: 'b', english: "Write about real things that matter to you — not invented topics. That's where voice lives.", chinese: "寫關於對你真正重要的事情——不是虛構的主題，那是聲音所在之處。", vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'Storytelling Through Writing',
        lines: [
          { speaker: 'a', english: "When you write personal stories, you're doing something quite profound.", chinese: "當你寫個人故事時，你在做一件相當深刻的事情。", vocabulary: [] },
          { speaker: 'b', english: "You're making your life legible — not just to others, but to yourself.", chinese: "你讓你的生活變得可讀——不只是對他人，而是對你自己。", vocabulary: [{ word: "legible", definition: "可讀的；清晰的" }] },
          { speaker: 'a', english: "There's a difference between experiencing something and making sense of it.", chinese: "經歷某事和理解它之間有區別。", vocabulary: [] },
          { speaker: 'b', english: "Writing is how you move from raw experience to meaning.", chinese: "寫作是你從原始體驗移動到意義的方式。", vocabulary: [{ word: "raw experience", definition: "原始體驗；直接體驗" }] },
          { speaker: 'a', english: "Sharing personal writing — carefully — can also create deep connection.", chinese: "分享個人寫作——謹慎地——也可以創造深刻的連結。", vocabulary: [] },
          { speaker: 'b', english: "When someone shares a piece of writing that's true and vulnerable, it's an incredible gift.", chinese: "當有人分享一篇真實而脆弱的寫作作品時，那是一份令人難以置信的禮物。", vocabulary: [{ word: "vulnerable", definition: "脆弱的；敞開心扉的" }] },
          { speaker: 'a', english: "Reading someone else's honest account of their inner life makes you feel less alone.", chinese: "閱讀別人對其內心生活的誠實描述讓你感到不那麼孤獨。", vocabulary: [] },
          { speaker: 'b', english: "That's the deepest power of writing — it breaks the illusion of our separateness.", chinese: "那是寫作最深刻的力量——它打破了我們分離的幻象。", vocabulary: [{ word: "separateness", definition: "分離；獨立" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'An Invitation to Write',
        lines: [
          { speaker: 'a', english: "I want to invite anyone listening to try writing something personal this week.", chinese: "我想邀請任何在聽的人這週嘗試寫一些個人的東西。", vocabulary: [] },
          { speaker: 'b', english: "Even three sentences. Something true. Something you've never written before.", chinese: "即使三個句子，一些真實的東西，一些你從未寫過的東西。", vocabulary: [] },
          { speaker: 'a', english: "It doesn't have to be shown to anyone. It's for you first.", chinese: "它不必給任何人看，首先是為你自己。", vocabulary: [] },
          { speaker: 'b', english: "Writing for yourself — without audience pressure — is its own kind of freedom.", chinese: "為自己寫作——沒有讀者壓力——是一種自己特有的自由。", vocabulary: [] },
          { speaker: 'a', english: "In English, if you can. Let the language be your new canvas.", chinese: "如果可以的話，用英語，讓語言成為你的新畫布。", vocabulary: [{ word: "canvas", definition: "畫布；創作空間" }] },
          { speaker: 'b', english: "I'll commit to writing one paragraph in English tonight about something that surprised me recently.", chinese: "我承諾今晚用英語寫一段關於最近讓我驚訝的事情的段落。", vocabulary: [] },
          { speaker: 'a', english: "Perfect. That's language learning and self-discovery in the same act.", chinese: "完美，那是語言學習和自我發現在同一個行為中。", vocabulary: [{ word: "self-discovery", definition: "自我發現；自我探索" }] },
          { speaker: 'b', english: "Writing yourself into existence — in whatever language — is always worth doing.", chinese: "用文字讓自己存在——用任何語言——永遠值得去做。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "expressive writing", meaning: "表達性寫作" },
      { phrase: "shitty first draft", meaning: "爛透的初稿（強調放手去寫）" },
      { phrase: "writing voice", meaning: "寫作聲音；寫作風格" },
      { phrase: "revision", meaning: "修改；修訂" },
      { phrase: "self-discovery", meaning: "自我發現；自我探索" },
      { phrase: "legible", meaning: "可讀的；清晰的" },
      { phrase: "raw experience", meaning: "原始體驗；直接體驗" },
      { phrase: "vulnerable", meaning: "脆弱的；敞開心扉的" },
      { phrase: "constraint", meaning: "限制；約束" },
      { phrase: "internalize", meaning: "內化；使內在化" },
    ],
  },
  {
    weekNumber: 48,
    dayOfWeek: 7,
    date: '2026-11-29',
    theme: 'Language & Identity',
    title: 'The Gift of Expression',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Week Reflections',
        lines: [
          { speaker: 'a', english: "Language and identity — this might be my favorite week of all our conversations.", chinese: "語言與身份認同——這可能是我們所有對話中我最喜歡的一週。", vocabulary: [] },
          { speaker: 'b', english: "It touches everything we do. Every word, every choice to speak or stay silent.", chinese: "它觸及我們做的一切，每一個詞，每一個選擇說話或保持沉默。", vocabulary: [] },
          { speaker: 'a', english: "What's one thing from this week that you'll carry with you?", chinese: "這週你會帶走的一件事是什麼？", vocabulary: [] },
          { speaker: 'b', english: "That languages are lenses, not masks. You're still yourself in every language you speak.", chinese: "語言是鏡頭，而不是面具，在你說的每一種語言中你仍然是你自己。", vocabulary: [] },
          { speaker: 'a', english: "For me — the power of personal narrative. We are the stories we tell about ourselves.", chinese: "對我來說——個人敘事的力量，我們就是我們對自己講述的故事。", vocabulary: [] },
          { speaker: 'b', english: "And those stories can be rewritten — that's incredibly hopeful.", chinese: "而且那些故事可以被重寫——那是令人難以置信地充滿希望的。", vocabulary: [] },
          { speaker: 'a', english: "Language gives us the tools to change, to connect, to understand, and to create.", chinese: "語言給了我們改變、連結、理解和創造的工具。", vocabulary: [] },
          { speaker: 'b', english: "What a profound gift. And we're actively using it to grow.", chinese: "多麼深刻的禮物，而我們正在積極地使用它來成長。", vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'The Courage to Communicate',
        lines: [
          { speaker: 'a', english: "Learning a new language takes real courage. That deserves to be acknowledged.", chinese: "學習一種新語言需要真正的勇氣，這值得被肯定。", vocabulary: [{ word: "acknowledged", definition: "被肯定；被承認" }] },
          { speaker: 'b', english: "You're willing to be misunderstood, to make mistakes, to sound less articulate than you are.", chinese: "你願意被誤解，犯錯誤，聽起來比你實際上更不善於表達。", vocabulary: [{ word: "articulate", definition: "善於表達的；口齒清晰的" }] },
          { speaker: 'a', english: "That vulnerability is the price of admission to a wider world.", chinese: "那種脆弱是進入更廣闊世界的代價。", vocabulary: [{ word: "price of admission", definition: "入場代價；值得付出的代價" }] },
          { speaker: 'b', english: "And the rewards — new friendships, new opportunities, new ways of seeing — are priceless.", chinese: "而回報——新友誼、新機會、新的看世界方式——是無價的。", vocabulary: [] },
          { speaker: 'a', english: "I think every language learner is doing something brave every single day.", chinese: "我認為每一個語言學習者每天都在做一些勇敢的事情。", vocabulary: [] },
          { speaker: 'b', english: "And the brain is actually more flexible than most people think — we can keep learning throughout life.", chinese: "而且大腦實際上比大多數人想像的更靈活——我們可以終身持續學習。", vocabulary: [] },
          { speaker: 'a', english: "The older view of language learning — that it's only for the young — is outdated.", chinese: "語言學習的舊觀念——那只適合年輕人——已經過時了。", vocabulary: [{ word: "outdated", definition: "過時的；老舊的" }] },
          { speaker: 'b', english: "Effort and consistency matter more than age when it comes to language.", chinese: "在語言方面，努力和一致性比年齡更重要。", vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'Language as Connection',
        lines: [
          { speaker: 'a', english: "At its core, language is about connection — reaching across the space between people.", chinese: "從根本上說，語言是關於連結——跨越人與人之間的空間伸出手。", vocabulary: [] },
          { speaker: 'b', english: "Every time you form a sentence and someone understands you — that's a small miracle.", chinese: "每次你形成一個句子而有人理解你——那是一個小奇蹟。", vocabulary: [{ word: "miracle", definition: "奇蹟" }] },
          { speaker: 'a', english: "We take it for granted, but communication is genuinely remarkable.", chinese: "我們認為這是理所當然的，但溝通是真正非凡的。", vocabulary: [{ word: "take for granted", definition: "視為理所當然" }] },
          { speaker: 'b', english: "The fact that we can share thoughts, feelings, ideas — at all — is extraordinary.", chinese: "我們能夠分享想法、感受、觀念——這本身就是非凡的。", vocabulary: [] },
          { speaker: 'a', english: "And learning another language multiplies that capacity for connection.", chinese: "而學習另一種語言增倍了那種連結的能力。", vocabulary: [] },
          { speaker: 'b', english: "You can reach more people, understand more perspectives, be part of more worlds.", chinese: "你可以接觸更多的人，理解更多的視角，成為更多世界的一部分。", vocabulary: [] },
          { speaker: 'a', english: "English opens enormous doors in today's world — that's why your effort here matters.", chinese: "在今天的世界中，英語打開了巨大的門——這就是為什麼你在這裡的努力很重要。", vocabulary: [] },
          { speaker: 'b', english: "Every lesson, every conversation, every word practiced is building something real.", chinese: "每一課、每一次對話、每一個練習的詞語都在建造真實的東西。", vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'What We Express, We Become',
        lines: [
          { speaker: 'a', english: "There's a Sufi saying: 'The language you speak is the world you live in.'", chinese: "有一句蘇菲派說法：「你說的語言就是你生活的世界。」", vocabulary: [{ word: "Sufi", definition: "蘇菲派（伊斯蘭神秘主義）" }] },
          { speaker: 'b', english: "I like that. What we name, we claim. What we express, we shape.", chinese: "我喜歡那句話，我們命名的，我們主張，我們表達的，我們塑造。", vocabulary: [] },
          { speaker: 'a', english: "Expressing gratitude genuinely makes you more grateful.", chinese: "真誠地表達感謝讓你更加感恩。", vocabulary: [] },
          { speaker: 'b', english: "Expressing curiosity opens new pathways of inquiry.", chinese: "表達好奇心打開了探索的新途徑。", vocabulary: [{ word: "inquiry", definition: "探索；探究" }] },
          { speaker: 'a', english: "Expressing compassion practices compassion — the words reinforce the feeling.", chinese: "表達同情心練習了同情心——話語強化了感受。", vocabulary: [{ word: "reinforce", definition: "強化；加強" }] },
          { speaker: 'b', english: "Use language generously — kind words cost nothing but can change everything.", chinese: "慷慨地使用語言——善良的話語不花一文，卻可以改變一切。", vocabulary: [] },
          { speaker: 'a', english: "This week reminded me that every word I choose is a small act of world-building.", chinese: "這週提醒了我，我選擇的每個詞都是一個微小的建立世界的行為。", vocabulary: [{ word: "world-building", definition: "建立世界；世界建構" }] },
          { speaker: 'b', english: "Words create realities. Choose them wisely, generously, and with love.", chinese: "語言創造現實，明智地、慷慨地、帶著愛地選擇它們。", vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'Until Next Week',
        lines: [
          { speaker: 'a', english: "What a journey this week has been — from identity to bilingualism to metaphors to writing.", chinese: "這週是多麼精彩的旅程——從身份認同到雙語主義，到隱喻，到寫作。", vocabulary: [] },
          { speaker: 'b', english: "Each conversation opened a new dimension of what language really is.", chinese: "每次對話都打開了語言真正是什麼的新維度。", vocabulary: [] },
          { speaker: 'a', english: "Language isn't just a tool for communication — it's the medium of consciousness itself.", chinese: "語言不只是溝通的工具——它是意識本身的媒介。", vocabulary: [{ word: "medium", definition: "媒介；手段" }] },
          { speaker: 'b', english: "That's profound. And a little bit mind-bending.", chinese: "那很深刻，也有點令人思考翻轉。", vocabulary: [{ word: "mind-bending", definition: "令人思考翻轉的；令人驚嘆的" }] },
          { speaker: 'a', english: "The good kind of mind-bending. Growth usually feels that way.", chinese: "好的那種令人思考翻轉，成長通常就是那種感覺。", vocabulary: [] },
          { speaker: 'b', english: "Next week we're exploring rest and renewal — a topic I'm genuinely looking forward to.", chinese: "下週我們將探索休息和更新——一個我真正期待的主題。", vocabulary: [] },
          { speaker: 'a', english: "After all this mental gymnastics, maybe we need a rest!", chinese: "在所有這些腦力體操之後，也許我們需要休息！", vocabulary: [{ word: "mental gymnastics", definition: "腦力體操；複雜的思維活動" }] },
          { speaker: 'b', english: "Until then — keep using your words. They matter more than you know.", chinese: "在那之前——繼續使用你的語言，它們比你所知道的更重要。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "price of admission", meaning: "入場代價；值得付出的代價" },
      { phrase: "take for granted", meaning: "視為理所當然" },
      { phrase: "world-building", meaning: "建立世界；世界建構" },
      { phrase: "mind-bending", meaning: "令人思考翻轉的" },
      { phrase: "medium of consciousness", meaning: "意識的媒介" },
      { phrase: "consistency", meaning: "一致性" },
      { phrase: "acknowledged", meaning: "被肯定；被承認" },
      { phrase: "reinforce", meaning: "強化；加強" },
      { phrase: "inquiry", meaning: "探索；探究" },
      { phrase: "articulate", meaning: "善於表達的；口齒清晰的" },
    ],
  },
];
