import { Episode } from '../types';

export const WEEK_52: Episode[] = [
  {
    weekNumber: 52,
    dayOfWeek: 1,
    date: '2026-12-21',
    theme: 'Year in Review',
    title: 'Looking Back to Move Forward',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: The Year Behind Us',
        lines: [
          { speaker: 'a', english: "Can you believe it's almost the end of the year again?", chinese: '你能相信又快到年底了嗎？', vocabulary: [] },
          { speaker: 'b', english: 'I know — it feels like 2026 just started, and now we\'re reviewing it.', chinese: '我知道——感覺 2026 年才剛開始，現在我們就在回顧它了。', vocabulary: [{ word: 'reviewing', definition: '回顧' }] },
          { speaker: 'a', english: 'Do you do a year-end review? Some people find it really meaningful.', chinese: '你會做年終回顧嗎？有些人覺得這非常有意義。', vocabulary: [{ word: 'year-end review', definition: '年終回顧' }] },
          { speaker: 'b', english: "I started doing one a few years ago, and it's honestly changed how I approach each new year.", chinese: '我幾年前開始做，老實說，這改變了我迎接每個新年的方式。', vocabulary: [{ word: 'approach', definition: '面對；處理' }] },
          { speaker: 'a', english: 'What does your review process look like?', chinese: '你的回顧過程是什麼樣的？', vocabulary: [] },
          { speaker: 'b', english: 'I ask myself three questions: What went well? What could have gone better? What do I want more of?', chinese: '我問自己三個問題：什麼進行得很好？什麼可以更好？我想要更多什麼？', vocabulary: [{ word: 'process', definition: '過程；流程' }] },
          { speaker: 'a', english: "That's elegantly simple. No giant spreadsheet required.", chinese: '這優雅地簡單。不需要龐大的試算表。', vocabulary: [{ word: 'elegantly', definition: '優雅地' }] },
          { speaker: 'b', english: 'Exactly. The point is reflection, not data collection.', chinese: '正是。重點是反思，而不是資料收集。', vocabulary: [{ word: 'reflection', definition: '反思；思考' }] },
        ],
      },
      {
        partNumber: 2,
        title: 'What Went Well',
        lines: [
          { speaker: 'a', english: "Let's start with the wins. What went well for you this year?", chinese: '讓我們從收穫開始。這一年你有什麼進展順利的？', vocabulary: [{ word: 'wins', definition: '勝利；成就' }] },
          { speaker: 'b', english: 'I finally got into a consistent exercise habit. It took months, but it stuck.', chinese: '我終於養成了規律的運動習慣。花了幾個月，但它持續下來了。', vocabulary: [{ word: 'consistent', definition: '一致的；規律的' }] },
          { speaker: 'a', english: "That's huge. A lot of people try and give up within the first few weeks.", chinese: '那很了不起。很多人嘗試後在前幾週就放棄了。', vocabulary: [] },
          { speaker: 'b', english: 'What made the difference was starting very small — just ten minutes a day.', chinese: '關鍵在於從非常小的事情開始——每天只有十分鐘。', vocabulary: [{ word: 'made the difference', definition: '發揮了關鍵作用' }] },
          { speaker: 'a', english: 'The tiny habits approach. How about professionally?', chinese: '微習慣方法。那工作上呢？', vocabulary: [{ word: 'professionally', definition: '在職業上；專業地' }] },
          { speaker: 'b', english: 'I took on a project that scared me, and it turned out to be my proudest achievement.', chinese: '我接了一個讓我害怕的專案，結果它成了我最引以為豪的成就。', vocabulary: [{ word: 'achievement', definition: '成就；達成' }] },
          { speaker: 'a', english: "Discomfort really is the price of growth, isn't it?", chinese: '不舒適真的是成長的代價，不是嗎？', vocabulary: [{ word: 'discomfort', definition: '不舒適；不安' }] },
          { speaker: 'b', english: 'Every time I look back, the scary things became the best things.', chinese: '每次回顧，那些令人害怕的事情都成了最美好的事情。', vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'What Could Have Gone Better',
        lines: [
          { speaker: 'a', english: "Now the harder part — what could have gone better?", chinese: '現在是較難的部分——什麼可以更好？', vocabulary: [] },
          { speaker: 'b', english: 'I spread myself too thin in the first half of the year and burned out by June.', chinese: '我在上半年把自己分散得太薄了，到了六月就精疲力竭了。', vocabulary: [{ word: 'spread myself too thin', definition: '分散精力過度' }] },
          { speaker: 'a', english: 'That overcommitment trap is so easy to fall into.', chinese: '過度承諾的陷阱太容易陷入了。', vocabulary: [{ word: 'overcommitment', definition: '過度承諾' }] },
          { speaker: 'b', english: "I said yes to everything and then resented the things I'd agreed to.", chinese: '我對每件事都說是，然後開始怨恨那些我答應的事情。', vocabulary: [{ word: 'resented', definition: '怨恨；厭惡' }] },
          { speaker: 'a', english: "What did you learn from that?", chinese: '你從中學到了什麼？', vocabulary: [] },
          { speaker: 'b', english: 'That a slow yes is better than a fast yes you later regret.', chinese: '慢慢地說是，比後來後悔的快速說是要好得多。', vocabulary: [{ word: 'regret', definition: '後悔；遺憾' }] },
          { speaker: 'a', english: 'Pausing before committing. That takes practice.', chinese: '在承諾前暫停思考。這需要練習。', vocabulary: [{ word: 'committing', definition: '承諾；投入' }] },
          { speaker: 'b', english: 'It does. I now give myself at least one night to think before saying yes to anything big.', chinese: '確實。我現在在對任何大事說是之前，至少給自己一個晚上思考。', vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'Lessons and Patterns',
        lines: [
          { speaker: 'a', english: 'Do you notice any patterns when you look at the whole year?', chinese: '當你回顧整年時，你有注意到任何規律嗎？', vocabulary: [{ word: 'patterns', definition: '規律；模式' }] },
          { speaker: 'b', english: 'Yes — my best weeks were when I had protected time for deep work in the mornings.', chinese: '是的——我最好的週都是在早晨有受保護的深度工作時間時。', vocabulary: [{ word: 'protected time', definition: '受保護的時間；專用時間' }] },
          { speaker: 'a', english: 'And your worst?', chinese: '那最糟的呢？', vocabulary: [] },
          { speaker: 'b', english: 'When I let meetings fill every slot and had no time to actually think.', chinese: '當我讓會議填滿每個時段，沒有時間真正思考的時候。', vocabulary: [{ word: 'slot', definition: '時段；空格' }] },
          { speaker: 'a', english: 'Calendar design as life design. You are what your schedule reflects.', chinese: '日曆設計就是生活設計。你的行程安排反映了你是誰。', vocabulary: [{ word: 'reflects', definition: '反映；反射' }] },
          { speaker: 'b', english: "I also noticed I'm most energized when I'm helping people learn something new.", chinese: '我也注意到，當我幫助別人學習新事物時，我最有活力。', vocabulary: [{ word: 'energized', definition: '充滿活力的' }] },
          { speaker: 'a', english: "That's a huge clue about your values and purpose.", chinese: '這是關於你的價值觀和目標的重要線索。', vocabulary: [{ word: 'clue', definition: '線索；提示' }] },
          { speaker: 'b', english: 'Which is why I want to do more coaching and mentoring next year.', chinese: '這就是為什麼我明年想多做一些輔導和指導工作。', vocabulary: [{ word: 'mentoring', definition: '指導；輔導' }] },
        ],
      },
      {
        partNumber: 5,
        title: 'The Gift of Looking Back',
        lines: [
          { speaker: 'a', english: "Why do you think so many people skip the year-end review?", chinese: '你認為為什麼這麼多人跳過年終回顧？', vocabulary: [] },
          { speaker: 'b', english: "Fear, mostly. It can feel uncomfortable to face what didn't work out.", chinese: '主要是恐懼。面對那些沒有成功的事情可能會讓人不舒服。', vocabulary: [{ word: 'uncomfortable', definition: '不舒服的；不自在的' }] },
          { speaker: 'a', english: "But avoiding the look-back means missing the lessons.", chinese: '但是避免回顧就意味著錯過了那些教訓。', vocabulary: [{ word: 'avoiding', definition: '避免；逃避' }] },
          { speaker: 'b', english: "Exactly. Those so-called failures are often your richest teachers.", chinese: '正是。那些所謂的失敗往往是你最豐富的老師。', vocabulary: [{ word: 'so-called', definition: '所謂的' }] },
          { speaker: 'a', english: "I love that reframe. Failure as curriculum.", chinese: '我喜歡這種重新框架的方式。失敗作為課程。', vocabulary: [{ word: 'curriculum', definition: '課程；學習內容' }] },
          { speaker: 'b', english: 'And the wins deserve celebration too — we move on too fast without acknowledging them.', chinese: '成功也值得慶祝——我們在沒有承認它們的情況下就太快繼續前進了。', vocabulary: [{ word: 'acknowledging', definition: '承認；認可' }] },
          { speaker: 'a', english: 'So the review is both a celebration and a compass.', chinese: '所以回顧既是慶祝，也是指南針。', vocabulary: [{ word: 'compass', definition: '指南針；方向' }] },
          { speaker: 'b', english: "Perfectly said. It tells you where you've been and points to where you want to go.", chinese: '說得太好了。它告訴你去過哪裡，並指向你想去的地方。', vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'year-end review', meaning: '年終回顧' },
      { phrase: 'What went well?', meaning: '什麼進行順利？' },
      { phrase: 'spread myself too thin', meaning: '分散精力過度' },
      { phrase: 'made the difference', meaning: '發揮了關鍵作用' },
      { phrase: 'protected time', meaning: '受保護的專用時間' },
      { phrase: 'slow yes', meaning: '謹慎地答應' },
      { phrase: 'failure as curriculum', meaning: '失敗作為學習課程' },
      { phrase: 'calendar design as life design', meaning: '日曆設計就是生活設計' },
      { phrase: 'look back', meaning: '回顧；回望' },
      { phrase: 'a celebration and a compass', meaning: '既是慶祝也是指引方向' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 2,
    date: '2026-12-22',
    theme: 'Year in Review',
    title: 'Relationships and Connections',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: People Review',
        lines: [
          { speaker: 'a', english: 'What about reviewing the relationships in your life this year?', chinese: '那麼回顧今年生活中的人際關係呢？', vocabulary: [{ word: 'reviewing', definition: '回顧' }] },
          { speaker: 'b', english: "That's actually one of the most important parts of my year-end review.", chinese: '這實際上是我年終回顧中最重要的部分之一。', vocabulary: [] },
          { speaker: 'a', english: "Really? Most people focus only on career and finances.", chinese: '真的嗎？大多數人只關注職業和財務。', vocabulary: [{ word: 'finances', definition: '財務；財政' }] },
          { speaker: 'b', english: "But at the end of life, nobody wishes they'd worked more — they wish they'd connected more.", chinese: '但在生命的終點，沒有人希望自己工作得更多——他們希望自己與人連結得更多。', vocabulary: [{ word: 'connected', definition: '連結；建立關係' }] },
          { speaker: 'a', english: "That classic deathbed perspective again.", chinese: '又是那個經典的臨終視角。', vocabulary: [{ word: 'deathbed', definition: '臨終的；彌留之際' }] },
          { speaker: 'b', english: "It's cliché because it's true. So I ask: who was I glad to spend time with this year?", chinese: '它成為陳腔濫調是因為它是真的。所以我問：今年我很高興與誰共度時光？', vocabulary: [{ word: 'cliché', definition: '陳腔濫調；老生常談' }] },
          { speaker: 'a', english: 'And who did you neglect that you wish you hadn\'t?', chinese: '而你忽視了誰，希望自己沒有忽視的？', vocabulary: [{ word: 'neglect', definition: '忽視；疏忽' }] },
          { speaker: 'b', english: "That second question is harder to answer, but more important.", chinese: '第二個問題更難回答，但更重要。', vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Deepening vs. Drifting',
        lines: [
          { speaker: 'a', english: 'Did any friendships deepen significantly this year?', chinese: '今年有哪些友誼顯著加深了嗎？', vocabulary: [{ word: 'deepen', definition: '加深；深化' }] },
          { speaker: 'b', english: 'Yes — a few I had been slowly drifting from, I made the effort to reconnect.', chinese: '是的——有幾個我慢慢疏遠的，我努力重新連結了。', vocabulary: [{ word: 'drifting', definition: '漂離；疏遠' }] },
          { speaker: 'a', english: 'What prompted that reconnection?', chinese: '是什麼促使了那次重新連結？', vocabulary: [{ word: 'prompted', definition: '促使；激發' }] },
          { speaker: 'b', english: 'A conversation early in the year about how friendships need maintenance, like anything else.', chinese: '年初的一次對話，談到友誼需要維護，就像其他任何事情一樣。', vocabulary: [{ word: 'maintenance', definition: '維護；保養' }] },
          { speaker: 'a', english: "We don't teach that — that relationships are alive and need tending.", chinese: '我們沒有教這個——關係是有生命的，需要培養。', vocabulary: [{ word: 'tending', definition: '照料；培養' }] },
          { speaker: 'b', english: "Exactly. A friendship left untended will naturally fade, not because anyone is bad, just because life moves.", chinese: '正是。一段沒有培養的友誼自然會褪色，不是因為誰不好，只是因為生活在移動。', vocabulary: [{ word: 'fade', definition: '褪色；消退' }] },
          { speaker: 'a', english: "So the question becomes: which friendships are worth tending intentionally?", chinese: '所以問題變成：哪些友誼值得有意識地培養？', vocabulary: [{ word: 'intentionally', definition: '有意識地；刻意地' }] },
          { speaker: 'b', english: "The ones that energize you and challenge you to be better.", chinese: '那些讓你充滿活力並挑戰你變得更好的。', vocabulary: [{ word: 'energize', definition: '使充滿活力' }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Family Connections',
        lines: [
          { speaker: 'a', english: 'How about family relationships? Those can be complicated.', chinese: '那家庭關係呢？那些可能很複雜。', vocabulary: [{ word: 'complicated', definition: '複雜的' }] },
          { speaker: 'b', english: "Very. I had a falling-out with a family member early in the year that really shook me.", chinese: '非常複雜。我在年初與一位家庭成員鬧翻了，這讓我非常動搖。', vocabulary: [{ word: 'falling-out', definition: '鬧翻；爭吵' }] },
          { speaker: 'a', english: "Were you able to repair it?", chinese: '你們能夠修復它嗎？', vocabulary: [{ word: 'repair', definition: '修復；修好' }] },
          { speaker: 'b', english: "Partially. I reached out and we talked, but some things take longer to heal.", chinese: '部分地。我主動聯繫了，我們談了，但有些事情需要更長時間才能癒合。', vocabulary: [{ word: 'reached out', definition: '主動聯繫' }] },
          { speaker: 'a', english: "Reaching out was still the right move, even if it's not fully resolved.", chinese: '即使還沒有完全解決，主動聯繫仍然是正確的舉動。', vocabulary: [{ word: 'resolved', definition: '解決的' }] },
          { speaker: 'b', english: "Absolutely. Repair requires someone to go first. I chose to be that person.", chinese: '絕對。修復需要有人先邁出第一步。我選擇做那個人。', vocabulary: [{ word: 'repair', definition: '修復關係' }] },
          { speaker: 'a', english: "That takes courage. A lot of people wait for the other side to apologize first.", chinese: '這需要勇氣。很多人等著對方先道歉。', vocabulary: [{ word: 'apologize', definition: '道歉' }] },
          { speaker: 'b', english: "Pride is expensive. Humility is the better investment.", chinese: '傲氣代價昂貴。謙遜是更好的投資。', vocabulary: [{ word: 'humility', definition: '謙遜；謙卑' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'New Connections',
        lines: [
          { speaker: 'a', english: "Did you make any meaningful new connections this year?", chinese: '今年你有建立任何有意義的新連結嗎？', vocabulary: [] },
          { speaker: 'b', english: "A few — mostly through workshops and online communities around shared interests.", chinese: '有幾個——主要是通過圍繞共同興趣的工作坊和網路社群。', vocabulary: [{ word: 'workshops', definition: '工作坊；研討會' }] },
          { speaker: 'a', english: "Shared interest really is the best foundation for friendship.", chinese: '共同興趣真的是友誼的最佳基礎。', vocabulary: [{ word: 'foundation', definition: '基礎；根基' }] },
          { speaker: 'b', english: "Much better than forced proximity, like being in the same office.", chinese: '比被迫的接近好得多，比如在同一個辦公室。', vocabulary: [{ word: 'proximity', definition: '接近；鄰近' }] },
          { speaker: 'a', english: "Although proximity can still spark friendships if both people are open to it.", chinese: '雖然如果兩個人都願意，接近也仍然可以激發友誼。', vocabulary: [{ word: 'spark', definition: '激發；點燃' }] },
          { speaker: 'b', english: "True. One of my closest work friends started as a five-minute coffee chat.", chinese: '是的。我最親近的一個工作朋友就是從五分鐘的咖啡閒聊開始的。', vocabulary: [] },
          { speaker: 'a', english: "Small moments, big outcomes. It's often the casual conversations that grow into something deeper.", chinese: '小時刻，大結果。往往是那些隨意的對話發展成更深層的東西。', vocabulary: [{ word: 'casual', definition: '隨意的；非正式的' }] },
          { speaker: 'b', english: "Which is why showing up matters — you can't predict which moment will be the one.", chinese: '這就是為什麼出現很重要——你無法預測哪個時刻會成為那個關鍵時刻。', vocabulary: [{ word: 'showing up', definition: '現身；出現' }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Relationships Going Forward',
        lines: [
          { speaker: 'a', english: "As you head into the new year, what's your relationship intention?", chinese: '當你邁向新的一年，你的人際關係意圖是什麼？', vocabulary: [{ word: 'intention', definition: '意圖；目的' }] },
          { speaker: 'b', english: "Fewer, deeper. I want to invest more quality time in a smaller circle.", chinese: '更少，更深。我想在更小的圈子裡投入更多高質量的時間。', vocabulary: [{ word: 'invest', definition: '投入；投資' }] },
          { speaker: 'a', english: "The idea of a core circle — some researchers say five to ten really close people is the sweet spot.", chinese: '核心圈子的概念——一些研究人員說五到十個真正親近的人是最佳狀態。', vocabulary: [{ word: 'sweet spot', definition: '最佳狀態；甜蜜點' }] },
          { speaker: 'b', english: "I believe that. Spreading attention too widely dilutes the depth you can reach.", chinese: '我相信這點。注意力分散得太廣會稀釋你能達到的深度。', vocabulary: [{ word: 'dilutes', definition: '稀釋；沖淡' }] },
          { speaker: 'a', english: "Quality over quantity in relationships as in everything.", chinese: '人際關係和其他一切一樣，質量勝於數量。', vocabulary: [{ word: 'quantity', definition: '數量' }] },
          { speaker: 'b', english: "And vulnerability. You can't have depth without it.", chinese: '還有脆弱。沒有它，你無法達到深度。', vocabulary: [{ word: 'vulnerability', definition: '脆弱；易受傷害' }] },
          { speaker: 'a', english: "So the relationship review isn't just about who — it's about how you show up for people.", chinese: '所以人際關係回顧不只是關於誰——而是關於你如何為他人而在。', vocabulary: [] },
          { speaker: 'b', english: "Perfectly put. How present and open and honest you've been.", chinese: '說得太好了。你有多在場、多開放、多誠實。', vocabulary: [{ word: 'present', definition: '在場的；專注的' }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'relationships need tending', meaning: '關係需要培養' },
      { phrase: 'falling-out', meaning: '爭吵；鬧翻' },
      { phrase: 'repair requires someone to go first', meaning: '修復需要有人先邁出第一步' },
      { phrase: 'drifting apart', meaning: '逐漸疏遠' },
      { phrase: 'reached out', meaning: '主動聯繫' },
      { phrase: 'shared interest', meaning: '共同興趣' },
      { phrase: 'showing up', meaning: '現身；出現' },
      { phrase: 'fewer, deeper', meaning: '更少但更深入的關係' },
      { phrase: 'quality over quantity', meaning: '質量勝於數量' },
      { phrase: 'core circle', meaning: '核心圈子' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 3,
    date: '2026-12-23',
    theme: 'Year in Review',
    title: 'Health and Energy in Review',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: The Body Keeps Score',
        lines: [
          { speaker: 'a', english: "How was your health this year? That's often the last thing people think to review.", chinese: '今年你的健康狀況如何？這通常是人們最後才想到要回顧的事情。', vocabulary: [] },
          { speaker: 'b', english: "And yet it's the foundation everything else rests on.", chinese: '然而它是其他一切賴以建立的基礎。', vocabulary: [{ word: 'foundation', definition: '基礎；根基' }] },
          { speaker: 'a', english: "When your energy is depleted, nothing else goes well.", chinese: '當你的能量耗盡時，其他什麼事情都進行不順。', vocabulary: [{ word: 'depleted', definition: '耗盡的；消耗殆盡的' }] },
          { speaker: 'b', english: "I learned that the hard way. Ignoring my sleep for months caught up with me in autumn.", chinese: '我是通過慘痛教訓學到的。幾個月忽視我的睡眠，在秋天終於追上了我。', vocabulary: [{ word: 'caught up with me', definition: '追上了我；影響到我了' }] },
          { speaker: 'a', english: "What happened?", chinese: '發生了什麼？', vocabulary: [] },
          { speaker: 'b', english: "I got sick for three weeks and my productivity dropped to almost zero.", chinese: '我病了三週，生產力幾乎降到零。', vocabulary: [{ word: 'productivity', definition: '生產力；效率' }] },
          { speaker: 'a', english: "Sleep debt is a real thing. You can't borrow against your future self indefinitely.", chinese: '睡眠負債是真實存在的。你不能無限期地向未來的自己借貸。', vocabulary: [{ word: 'sleep debt', definition: '睡眠負債' }] },
          { speaker: 'b', english: "I finally understood what 'the body keeps score' means in a personal way.", chinese: '我終於以親身體驗理解了「身體記分」的意思。', vocabulary: [{ word: 'keeps score', definition: '記分；記錄帳目' }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Movement and Energy',
        lines: [
          { speaker: 'a', english: "What changes did you make after the burnout?", chinese: '在精疲力竭之後你做了什麼改變？', vocabulary: [{ word: 'burnout', definition: '精疲力竭；耗盡' }] },
          { speaker: 'b', english: "I started treating sleep as a non-negotiable appointment, not a luxury.", chinese: '我開始把睡眠視為不可妥協的約定，而不是奢侈品。', vocabulary: [{ word: 'non-negotiable', definition: '不可妥協的；不容商量的' }] },
          { speaker: 'a', english: "Sleep as a keystone habit — fix the sleep, fix a lot of other things.", chinese: '睡眠作為核心習慣——修復睡眠，修復許多其他事情。', vocabulary: [{ word: 'keystone habit', definition: '核心習慣；基石習慣' }] },
          { speaker: 'b', english: "Exactly. My mood, focus, and even appetite all improved when I slept better.", chinese: '正是。當我睡得更好時，我的情緒、注意力甚至食慾都改善了。', vocabulary: [{ word: 'appetite', definition: '食慾；欲望' }] },
          { speaker: 'a', english: "What about movement? Did you exercise consistently?", chinese: '那運動呢？你規律地鍛煉了嗎？', vocabulary: [{ word: 'consistently', definition: '一致地；持續地' }] },
          { speaker: 'b', english: "More than before, but still not as much as I'd like. Walking became my entry-level movement.", chinese: '比以前多，但仍然不如我希望的那麼多。步行成了我入門級別的運動。', vocabulary: [{ word: 'entry-level', definition: '入門級別的；基礎的' }] },
          { speaker: 'a', english: "Walking is underrated. Thirty minutes a day has significant health benefits.", chinese: '步行被低估了。每天三十分鐘有顯著的健康益處。', vocabulary: [{ word: 'underrated', definition: '被低估的' }] },
          { speaker: 'b', english: "And it's sustainable. I haven't missed a day in four months.", chinese: '而且它是可持續的。四個月來我沒有漏掉一天。', vocabulary: [{ word: 'sustainable', definition: '可持續的' }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Mental and Emotional Health',
        lines: [
          { speaker: 'a', english: "Beyond the physical — how was your mental and emotional health?", chinese: '除了身體之外——你的心理和情緒健康如何？', vocabulary: [{ word: 'mental health', definition: '心理健康' }] },
          { speaker: 'b', english: "Honestly, it was a mixed year. Some months I felt really grounded, others quite anxious.", chinese: '老實說，這是一個參差不齊的一年。有些月份我感覺很踏實，其他月份則相當焦慮。', vocabulary: [{ word: 'grounded', definition: '踏實的；穩定的' }] },
          { speaker: 'a', english: "What were the anxiety triggers, when you look back?", chinese: '回顧時，焦慮的觸發因素是什麼？', vocabulary: [{ word: 'triggers', definition: '觸發因素' }] },
          { speaker: 'b', english: "Uncertainty about big decisions. I had three major choices to make this year.", chinese: '對重大決策的不確定性。我今年必須做三個重大選擇。', vocabulary: [{ word: 'uncertainty', definition: '不確定性' }] },
          { speaker: 'a', english: "Decision fatigue is real, especially when the stakes feel high.", chinese: '決策疲勞是真實的，尤其是當賭注感覺很高時。', vocabulary: [{ word: 'decision fatigue', definition: '決策疲勞' }] },
          { speaker: 'b', english: "I started journaling through the decisions, which helped clarify my thinking.", chinese: '我開始通過日記思考這些決定，這有助於澄清我的思考。', vocabulary: [{ word: 'journaling', definition: '寫日記；記錄' }] },
          { speaker: 'a', english: "Writing forces clarity. You can't hide from your own words on the page.", chinese: '寫作迫使清晰。你無法在頁面上的自己的文字中躲藏。', vocabulary: [{ word: 'clarity', definition: '清晰；明確' }] },
          { speaker: 'b', english: "It also helped me see which worries were real and which were just noise.", chinese: '它也幫助我看清哪些擔憂是真實的，哪些只是雜音。', vocabulary: [{ word: 'noise', definition: '雜音；干擾' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Energy Management',
        lines: [
          { speaker: 'a', english: "Did you notice what activities gave you energy versus drained you?", chinese: '你有沒有注意到哪些活動給你能量，哪些讓你消耗能量？', vocabulary: [{ word: 'drained', definition: '消耗能量；令人精疲力竭' }] },
          { speaker: 'b', english: "Yes — that awareness became one of the most useful tools I have.", chinese: '是的——那種意識成為我擁有的最有用的工具之一。', vocabulary: [{ word: 'awareness', definition: '意識；覺察' }] },
          { speaker: 'a', english: "What energizes you most?", chinese: '什麼最能給你能量？', vocabulary: [] },
          { speaker: 'b', english: "Creative work, being in nature, and meaningful conversations like this one.", chinese: '創意工作、親近自然，以及像這樣有意義的對話。', vocabulary: [] },
          { speaker: 'a', english: "And what drains you?", chinese: '那什麼最讓你消耗能量？', vocabulary: [] },
          { speaker: 'b', english: "Scrolling social media, pointless meetings, and conflict I can't resolve.", chinese: '滾動瀏覽社交媒體、毫無意義的會議，以及我無法解決的衝突。', vocabulary: [{ word: 'pointless', definition: '毫無意義的；無用的' }] },
          { speaker: 'a', english: "That self-knowledge is gold. It lets you design your days more intentionally.", chinese: '那種自我認識是黃金。它讓你能更有意識地設計你的每一天。', vocabulary: [{ word: 'self-knowledge', definition: '自我認識；自我了解' }] },
          { speaker: 'b', english: "Which is exactly what I plan to do more of next year — design my schedule around my energy, not just tasks.", chinese: '這正是我計劃明年更多去做的——圍繞我的能量而不只是任務來設計我的時間表。', vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'Health Intentions for Next Year',
        lines: [
          { speaker: 'a', english: "So what are your health intentions going into the new year?", chinese: '那你進入新年的健康意圖是什麼？', vocabulary: [] },
          { speaker: 'b', english: "Protect my sleep fiercely. Move every day, even if just for a walk. And take mental health days before I need them.", chinese: '強烈保護我的睡眠。每天活動，即使只是散步。在需要之前就安排心理健康日。', vocabulary: [{ word: 'fiercely', definition: '強烈地；激烈地' }] },
          { speaker: 'a', english: "Prevention over cure — that's wise.", chinese: '預防勝於治療——這很明智。', vocabulary: [{ word: 'prevention', definition: '預防' }] },
          { speaker: 'b', english: "We never think we need the break until we're already breaking.", chinese: '我們從不認為我們需要休息，直到我們已經開始崩潰。', vocabulary: [{ word: 'breaking', definition: '崩潰；破裂' }] },
          { speaker: 'a', english: "Scheduling rest proactively rather than reactively.", chinese: '主動而不是被動地安排休息。', vocabulary: [{ word: 'proactively', definition: '主動地；積極地' }] },
          { speaker: 'b', english: "Exactly. And I want to get better at noticing early warning signs — when I'm starting to slip.", chinese: '正是。我想更善於注意早期警告信號——當我開始滑落的時候。', vocabulary: [{ word: 'early warning signs', definition: '早期警告信號' }] },
          { speaker: 'a', english: "Body literacy — learning the language your body uses to talk to you.", chinese: '身體素養——學習你的身體用來和你說話的語言。', vocabulary: [{ word: 'body literacy', definition: '身體素養；了解身體' }] },
          { speaker: 'b', english: "I love that phrase. My body has been talking to me for years — I'm finally learning to listen.", chinese: '我喜歡這個短語。我的身體已經和我說話多年了——我終於開始學著傾聽了。', vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'the body keeps score', meaning: '身體會記錄所有的壓力與創傷' },
      { phrase: 'sleep debt', meaning: '睡眠負債' },
      { phrase: 'caught up with me', meaning: '後果終於追上了我' },
      { phrase: 'keystone habit', meaning: '核心習慣' },
      { phrase: 'non-negotiable', meaning: '不可妥協的' },
      { phrase: 'decision fatigue', meaning: '決策疲勞' },
      { phrase: 'energy management', meaning: '能量管理' },
      { phrase: 'body literacy', meaning: '了解身體語言' },
      { phrase: 'proactively', meaning: '主動地；積極地' },
      { phrase: 'prevention over cure', meaning: '預防勝於治療' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 4,
    date: '2026-12-24',
    theme: 'Year in Review',
    title: 'Work and Purpose Review',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: Was This Year Meaningful at Work?',
        lines: [
          { speaker: 'a', english: "Christmas Eve — and we're reviewing our work year. How very on-brand for us.", chinese: '平安夜——我們在回顧我們的工作年。這對我們來說非常典型。', vocabulary: [{ word: 'on-brand', definition: '典型的；符合風格的' }] },
          { speaker: 'b', english: "Ha! But honestly, I think this time of year is perfect for it.", chinese: '哈！但老實說，我認為一年的這個時候非常適合做這件事。', vocabulary: [] },
          { speaker: 'a', english: "Things slow down, you have space to think.", chinese: '事情放慢了，你有空間思考。', vocabulary: [] },
          { speaker: 'b', english: "Exactly. So — was your work year meaningful to you?", chinese: '正是。那麼——你的工作年對你有意義嗎？', vocabulary: [{ word: 'meaningful', definition: '有意義的' }] },
          { speaker: 'a', english: "That's a deeper question than 'was it productive' or 'did you hit your targets'.", chinese: '這比「它是否有成效」或「你是否達到了目標」更深層的問題。', vocabulary: [{ word: 'productive', definition: '有成效的；有生產力的' }] },
          { speaker: 'b', english: "Because you can hit all your KPIs and still feel hollow.", chinese: '因為你可以達到所有的關鍵績效指標，但仍然感覺空洞。', vocabulary: [{ word: 'KPIs', definition: '關鍵績效指標' }, { word: 'hollow', definition: '空洞的；不真實的' }] },
          { speaker: 'a', english: "Productivity without purpose is just efficient busyness.", chinese: '沒有目標的生產力只是有效率的忙碌。', vocabulary: [{ word: 'busyness', definition: '忙碌' }] },
          { speaker: 'b', english: "That's a phrase I want to put on a sticky note.", chinese: '這是一個我想貼在便利貼上的短語。', vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Work Highlights',
        lines: [
          { speaker: 'a', english: "What were the highlights of your work year?", chinese: '你工作年度的亮點是什麼？', vocabulary: [{ word: 'highlights', definition: '亮點；精彩時刻' }] },
          { speaker: 'b', english: "The project I mentioned earlier — leading a cross-functional team for the first time.", chinese: '我之前提到的那個專案——第一次領導一個跨職能團隊。', vocabulary: [{ word: 'cross-functional', definition: '跨職能的；跨部門的' }] },
          { speaker: 'a', english: "First times are always significant — they reveal your capacity.", chinese: '第一次總是很重要——它們揭示了你的能力。', vocabulary: [{ word: 'capacity', definition: '能力；容量' }] },
          { speaker: 'b', english: "I discovered I'm better with people than I thought.", chinese: '我發現我在與人打交道方面比我想像的要好。', vocabulary: [] },
          { speaker: 'a', english: "That's a gift. A lot of people don't discover that until much later.", chinese: '這是一份禮物。很多人直到很晚才發現這一點。', vocabulary: [] },
          { speaker: 'b', english: "I also helped mentor two junior colleagues, which was incredibly rewarding.", chinese: '我也幫助指導了兩位初級同事，這非常有成就感。', vocabulary: [{ word: 'junior colleagues', definition: '初級同事；後輩' }] },
          { speaker: 'a', english: "Teaching others is one of the deepest forms of learning.", chinese: '教導他人是最深刻的學習形式之一。', vocabulary: [] },
          { speaker: 'b', english: "You realize how much you know — and also how much you still don't know.", chinese: '你意識到你知道多少——也意識到你仍然不知道多少。', vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'Work Challenges',
        lines: [
          { speaker: 'a', english: "What were the toughest work challenges this year?", chinese: '今年最艱難的工作挑戰是什麼？', vocabulary: [] },
          { speaker: 'b', english: "The organizational restructuring. It created a lot of uncertainty.", chinese: '組織重組。它製造了很多不確定性。', vocabulary: [{ word: 'restructuring', definition: '重組；重新架構' }] },
          { speaker: 'a', english: "Change at that level affects everyone's sense of security.", chinese: '那個層面的變化影響到每個人的安全感。', vocabulary: [{ word: 'security', definition: '安全感；保障' }] },
          { speaker: 'b', english: "I managed by focusing on what I could control and letting go of what I couldn't.", chinese: '我通過專注於我能控制的，放開我無法控制的來應對。', vocabulary: [{ word: 'letting go', definition: '放開；放下' }] },
          { speaker: 'a', english: "The Stoic practice — sphere of control.", chinese: '斯多葛主義的實踐——控制範圍。', vocabulary: [{ word: 'Stoic', definition: '斯多葛主義的；禁欲的' }] },
          { speaker: 'b', english: "Very helpful in turbulent times. Anxiety lives in the gap between what you worry about and what you can actually do.", chinese: '在動盪時期非常有幫助。焦慮存在於你擔心的事情和你實際能做的事情之間的差距中。', vocabulary: [{ word: 'turbulent', definition: '動盪的；混亂的' }] },
          { speaker: 'a', english: "Close that gap by acting on what you can.", chinese: '通過對你能做的事情採取行動來縮小那個差距。', vocabulary: [] },
          { speaker: 'b', english: "And release the rest with grace.", chinese: '並優雅地放開其餘的。', vocabulary: [{ word: 'release', definition: '釋放；放開' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Work–Life Integration',
        lines: [
          { speaker: 'a', english: "How was your work-life balance — or integration — this year?", chinese: '今年你的工作與生活的平衡——或整合——如何？', vocabulary: [{ word: 'integration', definition: '整合；融合' }] },
          { speaker: 'b', english: "I prefer the word integration. Balance implies a scale — one side goes up, the other goes down.", chinese: '我更喜歡「整合」這個詞。平衡暗示了一個天平——一邊上去，另一邊就下來。', vocabulary: [{ word: 'implies', definition: '暗示；意味著' }] },
          { speaker: 'a', english: "Integration suggests they can coexist and reinforce each other.", chinese: '整合意味著它們可以共存並相互強化。', vocabulary: [{ word: 'coexist', definition: '共存；並存' }] },
          { speaker: 'b', english: "My best days are when I'm energized at work and present at home.", chinese: '我最好的日子是在工作中充滿活力，在家裡全神貫注的時候。', vocabulary: [{ word: 'present', definition: '在場的；全神貫注的' }] },
          { speaker: 'a', english: "And the worst?", chinese: '那最糟的呢？', vocabulary: [] },
          { speaker: 'b', english: "When work stress bleeds into dinner and I'm physically there but mentally still at the office.", chinese: '當工作壓力滲入晚餐，我身體在那裡但精神還在辦公室的時候。', vocabulary: [{ word: 'bleeds into', definition: '滲入；蔓延到' }] },
          { speaker: 'a', english: "Presence is a skill, not a given. It takes effort to fully arrive somewhere.", chinese: '在場是一種技能，不是理所當然的。完全抵達某個地方需要努力。', vocabulary: [{ word: 'presence', definition: '在場；臨在' }] },
          { speaker: 'b', english: "A transition ritual helps — something to mark the end of work and the start of home.", chinese: '過渡儀式有幫助——某種東西來標誌工作的結束和家庭的開始。', vocabulary: [{ word: 'transition ritual', definition: '過渡儀式' }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Purpose and the Year Ahead',
        lines: [
          { speaker: 'a', english: "Do you feel like your work aligns with your sense of purpose?", chinese: '你覺得你的工作與你的目標感一致嗎？', vocabulary: [{ word: 'aligns', definition: '對齊；一致' }] },
          { speaker: 'b', english: "More than last year, which feels like progress.", chinese: '比去年更多，這感覺像是進步。', vocabulary: [] },
          { speaker: 'a', english: "Purpose alignment is a journey, not a destination you arrive at once and stay.", chinese: '目標一致是一段旅程，不是你到達一次就停留的目的地。', vocabulary: [{ word: 'alignment', definition: '一致；對齊' }] },
          { speaker: 'b', english: "I think I'm moving in the right direction. That matters more than being perfectly aligned.", chinese: '我認為我正在朝著正確的方向前進。這比完美對齊更重要。', vocabulary: [] },
          { speaker: 'a', english: "Direction over perfection. Another keeper phrase.", chinese: '方向勝於完美。又一個值得保留的短語。', vocabulary: [{ word: 'direction over perfection', definition: '方向比完美更重要' }] },
          { speaker: 'b', english: "Next year I want to take on more work that involves teaching — that's where I feel most alive.", chinese: '明年我想承擔更多涉及教學的工作——那是我感覺最有活力的地方。', vocabulary: [{ word: 'alive', definition: '充滿活力的；有生氣的' }] },
          { speaker: 'a', english: "Following your energy is one of the best career maps there is.", chinese: '跟隨你的能量是現有的最好的職業地圖之一。', vocabulary: [{ word: 'career map', definition: '職業地圖；職涯指引' }] },
          { speaker: 'b', english: "Happy Christmas Eve to us and to all who are working toward something meaningful.", chinese: '祝我們和所有努力追求有意義事物的人平安夜快樂。', vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'meaningful work', meaning: '有意義的工作' },
      { phrase: 'productivity without purpose', meaning: '沒有目標的生產力' },
      { phrase: 'cross-functional team', meaning: '跨職能團隊' },
      { phrase: 'sphere of control', meaning: '控制範圍' },
      { phrase: 'work-life integration', meaning: '工作與生活整合' },
      { phrase: 'transition ritual', meaning: '過渡儀式' },
      { phrase: 'bleeds into', meaning: '滲透蔓延到' },
      { phrase: 'presence is a skill', meaning: '在場是一種技能' },
      { phrase: 'direction over perfection', meaning: '方向比完美更重要' },
      { phrase: 'following your energy', meaning: '跟隨你的能量' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 5,
    date: '2026-12-25',
    theme: 'Year in Review',
    title: 'Growth and Learning This Year',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: Merry Christmas, Let\'s Review',
        lines: [
          { speaker: 'a', english: 'Merry Christmas! Learning English on Christmas morning — you\'re committed.', chinese: '聖誕快樂！在聖誕節早上學英語——你真的很投入。', vocabulary: [{ word: 'committed', definition: '投入的；有承諾的' }] },
          { speaker: 'b', english: "Learning doesn't take holidays. Besides, it's quiet and peaceful — perfect for reflection.", chinese: '學習不會放假。再說了，現在安靜平和——非常適合反思。', vocabulary: [{ word: 'reflection', definition: '反思；沉思' }] },
          { speaker: 'a', english: "Today let's talk about what we've learned this year — not just facts, but wisdom.", chinese: '今天讓我們談談今年我們學到了什麼——不只是事實，而是智慧。', vocabulary: [{ word: 'wisdom', definition: '智慧' }] },
          { speaker: 'b', english: "There's a difference. Facts are what you know. Wisdom is how you live.", chinese: '有區別。事實是你知道的。智慧是你如何生活。', vocabulary: [] },
          { speaker: 'a', english: "What was the biggest lesson 2026 taught you?", chinese: '2026 年教了你最大的教訓是什麼？', vocabulary: [] },
          { speaker: 'b', english: "That speed is not the same as progress.", chinese: '速度和進步不是一回事。', vocabulary: [{ word: 'progress', definition: '進步；前進' }] },
          { speaker: 'a', english: "Ooh. Say more.", chinese: '哦。多說一點。', vocabulary: [] },
          { speaker: 'b', english: "I moved fast on several things this year and ended up going backward on two of them.", chinese: '我今年在幾件事上行動很快，結果有兩件事反而倒退了。', vocabulary: [{ word: 'ended up', definition: '最終；結果' }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Lessons Learned',
        lines: [
          { speaker: 'a', english: "Can you give an example of going too fast?", chinese: '你能舉一個行動太快的例子嗎？', vocabulary: [] },
          { speaker: 'b', english: "I made a major purchase without enough research. Cost me both money and weeks of stress.", chinese: '我在沒有足夠研究的情況下做了一項重大購買。這讓我既損失了金錢又承受了幾週的壓力。', vocabulary: [{ word: 'major purchase', definition: '重大購買' }] },
          { speaker: 'a', english: "The urgency bias — feeling like you have to decide now.", chinese: '緊迫性偏見——感覺你必須現在就決定。', vocabulary: [{ word: 'urgency bias', definition: '緊迫性偏見' }] },
          { speaker: 'b', english: "Exactly. Very few things actually require immediate decisions.", chinese: '正是。實際上很少有事情需要立即做決定。', vocabulary: [{ word: 'immediate', definition: '立即的；即時的' }] },
          { speaker: 'a', english: "And the second thing that went backward?", chinese: '那倒退的第二件事呢？', vocabulary: [] },
          { speaker: 'b', english: "A relationship I rushed to repair before either of us was ready.", chinese: '一段我在我們都準備好之前急於修復的關係。', vocabulary: [{ word: 'rushed', definition: '倉促的；匆忙的' }] },
          { speaker: 'a', english: "Timing matters enormously in relationships.", chinese: '時機在關係中非常重要。', vocabulary: [{ word: 'enormously', definition: '非常地；巨大地' }] },
          { speaker: 'b', english: "And forcing healing before the wound is ready just reopens it.", chinese: '在傷口準備好之前強迫癒合只會重新打開它。', vocabulary: [{ word: 'wound', definition: '傷口；創傷' }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Skills and Knowledge Growth',
        lines: [
          { speaker: 'a', english: "What new skills or knowledge did you develop this year?", chinese: '今年你發展了哪些新技能或知識？', vocabulary: [] },
          { speaker: 'b', english: "I got significantly better at public speaking. That was a big goal at the start of the year.", chinese: '我在公開演講方面有了顯著的提升。這是年初的一個重要目標。', vocabulary: [{ word: 'public speaking', definition: '公開演講' }] },
          { speaker: 'a', english: "What was your practice method?", chinese: '你的練習方法是什麼？', vocabulary: [{ word: 'practice method', definition: '練習方法' }] },
          { speaker: 'b', english: "Recording myself, joining a speaking group, and volunteering to present whenever possible.", chinese: '錄下自己、加入演講小組，並盡可能自願演講。', vocabulary: [{ word: 'volunteering', definition: '自願；主動請纓' }] },
          { speaker: 'a', english: "Deliberate practice — seeking opportunities rather than waiting for them.", chinese: '刻意練習——尋求機會而不是等待它們。', vocabulary: [{ word: 'deliberate practice', definition: '刻意練習' }] },
          { speaker: 'b', english: "And being willing to be terrible at first. That's the hardest part.", chinese: '並且願意一開始很糟糕。那是最難的部分。', vocabulary: [] },
          { speaker: 'a', english: "The awkward stage is just a fee you pay for competence.", chinese: '尷尬階段只是你為能力所付的費用。', vocabulary: [{ word: 'competence', definition: '能力；勝任' }] },
          { speaker: 'b', english: "I love that. The tuition of discomfort.", chinese: '我喜歡這個。不舒適的學費。', vocabulary: [{ word: 'tuition', definition: '學費；教導' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Unlearning',
        lines: [
          { speaker: 'a', english: "What about unlearning — is there anything you had to let go of this year?", chinese: '那「去學習」呢——今年有什麼你必須放開的嗎？', vocabulary: [{ word: 'unlearning', definition: '去學習；放棄舊有知識' }] },
          { speaker: 'b', english: "The belief that I need to figure everything out before I start.", chinese: '在開始之前我需要把一切都弄清楚的信念。', vocabulary: [{ word: 'figure out', definition: '弄清楚；搞明白' }] },
          { speaker: 'a', english: "Analysis paralysis — it's the enemy of progress.", chinese: '分析癱瘓——它是進步的敵人。', vocabulary: [{ word: 'analysis paralysis', definition: '分析癱瘓' }] },
          { speaker: 'b', english: "I kept waiting to feel ready. But ready never comes — you have to start to get ready.", chinese: '我一直在等待感覺準備好了。但準備好的感覺從不來——你必須開始才能準備好。', vocabulary: [{ word: 'paralysis', definition: '癱瘓；停滯' }] },
          { speaker: 'a', english: "Clarity through action, not through thinking alone.", chinese: '通過行動獲得清晰，而不只是通過思考。', vocabulary: [{ word: 'clarity', definition: '清晰；明確' }] },
          { speaker: 'b', english: "Also unlearning the idea that asking for help is weakness.", chinese: '也是去學習請求幫助是軟弱的觀念。', vocabulary: [] },
          { speaker: 'a', english: "Where did that belief come from?", chinese: '那個信念從哪裡來的？', vocabulary: [] },
          { speaker: 'b', english: "Probably years of being praised for being self-sufficient. But no one succeeds alone.", chinese: '可能是多年來被稱讚為自給自足。但沒有人能獨自成功。', vocabulary: [{ word: 'self-sufficient', definition: '自給自足的；獨立的' }] },
        ],
      },
      {
        partNumber: 5,
        title: 'A Christmas Reflection',
        lines: [
          { speaker: 'a', english: "On Christmas Day, what's the one thing you're most grateful to have learned this year?", chinese: '在聖誕節，你最感激今年學到的一件事是什麼？', vocabulary: [] },
          { speaker: 'b', english: "That vulnerability is not weakness — it's the prerequisite for genuine connection.", chinese: '脆弱不是軟弱——它是真正連結的先決條件。', vocabulary: [{ word: 'prerequisite', definition: '先決條件；前提' }] },
          { speaker: 'a', english: "That's a profound one. How did you learn it?", chinese: '這是一個很深刻的領悟。你是怎麼學到的？', vocabulary: [{ word: 'profound', definition: '深刻的；深遠的' }] },
          { speaker: 'b', english: "By watching what happened when I finally opened up about something I'd been hiding.", chinese: '通過觀察當我終於敞開心扉談及一件我一直隱藏的事情時發生了什麼。', vocabulary: [{ word: 'opened up', definition: '敞開心扉；坦誠說出' }] },
          { speaker: 'a', english: "What happened?", chinese: '發生了什麼？', vocabulary: [] },
          { speaker: 'b', english: "People didn't pull away — they came closer. They shared their own hidden struggles.", chinese: '人們沒有疏遠——他們靠近了。他們分享了自己隱藏的掙扎。', vocabulary: [{ word: 'pull away', definition: '疏遠；退縮' }] },
          { speaker: 'a', english: "Vulnerability is magnetic. It gives others permission to be human too.", chinese: '脆弱是有磁力的。它給了他人也成為人類的許可。', vocabulary: [{ word: 'magnetic', definition: '有吸引力的；磁性的' }] },
          { speaker: 'b', english: "Merry Christmas. May we all grow a little braver next year.", chinese: '聖誕快樂。願我們明年都勇敢一點。', vocabulary: [{ word: 'braver', definition: '更勇敢的' }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'speed is not the same as progress', meaning: '速度不等於進步' },
      { phrase: 'urgency bias', meaning: '緊迫性偏見' },
      { phrase: 'deliberate practice', meaning: '刻意練習' },
      { phrase: 'unlearning', meaning: '放棄舊有信念' },
      { phrase: 'analysis paralysis', meaning: '分析癱瘓' },
      { phrase: 'clarity through action', meaning: '通過行動獲得清晰' },
      { phrase: 'tuition of discomfort', meaning: '不舒適是成長的學費' },
      { phrase: 'vulnerability is not weakness', meaning: '脆弱不是軟弱' },
      { phrase: 'opened up', meaning: '敞開心扉' },
      { phrase: 'prerequisite for genuine connection', meaning: '真正連結的先決條件' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 6,
    date: '2026-12-26',
    theme: 'Year in Review',
    title: 'Creativity and Joy in Review',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: The Joy Audit',
        lines: [
          { speaker: 'a', english: "Have you ever done a joy audit?", chinese: '你曾經做過喜悅審核嗎？', vocabulary: [{ word: 'joy audit', definition: '喜悅審核；快樂清點' }] },
          { speaker: 'b', english: "A joy audit — what's that?", chinese: '喜悅審核——那是什麼？', vocabulary: [] },
          { speaker: 'a', english: "Looking back at your year and identifying the moments that brought you genuine joy.", chinese: '回顧你的一年，找出帶給你真正喜悅的時刻。', vocabulary: [{ word: 'genuine', definition: '真正的；真誠的' }] },
          { speaker: 'b', english: "Not just 'it went well' but 'it lit me up'.", chinese: '不只是「進行得很順利」，而是「它讓我充滿光芒」。', vocabulary: [{ word: 'lit me up', definition: '讓我充滿活力；點燃我' }] },
          { speaker: 'a', english: "Exactly. Joy as a compass — what did your year tell you about what brings you alive?", chinese: '正是。喜悅作為指南針——你的這一年告訴了你什麼讓你充滿活力？', vocabulary: [] },
          { speaker: 'b', english: "Making things. Whether it's cooking, writing, or building something with my hands.", chinese: '創造東西。無論是烹飪、寫作，還是用雙手建造東西。', vocabulary: [{ word: 'with my hands', definition: '用雙手；親手' }] },
          { speaker: 'a', english: "The creative act. There's something deeply satisfying about making something from nothing.", chinese: '創作行為。從無到有地製作某些東西有一種深深的滿足感。', vocabulary: [{ word: 'creative act', definition: '創作行為' }] },
          { speaker: 'b', english: "And it's completely detached from outcome — I don't need anyone to see it or praise it.", chinese: '而且它完全脫離了結果——我不需要任何人看到它或讚美它。', vocabulary: [{ word: 'detached', definition: '脫離的；超然的' }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Creative Highlights',
        lines: [
          { speaker: 'a', english: "What was the most creative project you worked on this year?", chinese: '今年你做的最具創意的專案是什麼？', vocabulary: [] },
          { speaker: 'b', english: "I started building a miniature model of a historic building from scratch.", chinese: '我開始從零開始建造一個歷史建築的微縮模型。', vocabulary: [{ word: 'miniature', definition: '微型的；縮小的' }, { word: 'from scratch', definition: '從零開始' }] },
          { speaker: 'a', english: "That's so different from your day job. Intentionally?", chinese: '這和你的日常工作非常不同。是刻意的嗎？', vocabulary: [] },
          { speaker: 'b', english: "Completely. I wanted something where 'good enough' wasn't a spreadsheet metric.", chinese: '完全是。我想要一件「足夠好」不是試算表指標的事情。', vocabulary: [{ word: 'metric', definition: '指標；衡量標準' }] },
          { speaker: 'a', english: "Creative outlets that have nothing to do with performance or productivity are healing.", chinese: '與表現或生產力無關的創意出口是治癒的。', vocabulary: [{ word: 'creative outlets', definition: '創意出口；創作管道' }] },
          { speaker: 'b', english: "I also wrote a short story for the first time. Just for myself.", chinese: '我也第一次寫了一個短篇故事。只是為了我自己。', vocabulary: [] },
          { speaker: 'a', english: "How did that feel?", chinese: '那感覺如何？', vocabulary: [] },
          { speaker: 'b', english: "Terrifying and then incredibly freeing. Once I stopped trying to make it 'good', it flowed.", chinese: '一開始很可怕，然後難以置信地自由。一旦我停止試圖讓它「好」，它就流動了。', vocabulary: [{ word: 'freeing', definition: '自由的；解放的' }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Moments of Pure Joy',
        lines: [
          { speaker: 'a', english: "Beyond creativity, what were the moments of pure joy this year?", chinese: '除了創意之外，今年純粹喜悅的時刻是什麼？', vocabulary: [{ word: 'pure joy', definition: '純粹的喜悅' }] },
          { speaker: 'b', english: "A weekend trip to the mountains in spring. No agenda, no phone signals, just hiking and talking.", chinese: '春天一次去山上的週末旅行。沒有行程安排，沒有手機信號，只是徒步和聊天。', vocabulary: [{ word: 'agenda', definition: '議程；計畫' }] },
          { speaker: 'a', english: "The simplicity of being somewhere without obligations.", chinese: '在沒有義務的地方的簡單感。', vocabulary: [{ word: 'obligations', definition: '義務；責任' }] },
          { speaker: 'b', english: "Also, every Sunday morning I've made pancakes and listened to vinyl records. That tiny ritual.", chinese: '還有，每個週日早上我都會做煎餅，聽黑膠唱片。那個小小的儀式。', vocabulary: [{ word: 'vinyl records', definition: '黑膠唱片' }] },
          { speaker: 'a', english: "The small rituals are often the deepest sources of joy.", chinese: '小儀式往往是最深層的喜悅來源。', vocabulary: [{ word: 'rituals', definition: '儀式；例行事項' }] },
          { speaker: 'b', english: "They create a sense of continuity — anchors in a busy life.", chinese: '它們創造了一種連續感——在忙碌生活中的錨點。', vocabulary: [{ word: 'continuity', definition: '連續性；持續' }] },
          { speaker: 'a', english: "And playing the long game — tiny joys compound just like habits.", chinese: '長遠來看——小小的喜悅像習慣一樣複利增長。', vocabulary: [{ word: 'compound', definition: '複利增長；累積' }] },
          { speaker: 'b', english: "A life filled with small joys is richer than one big annual high.", chinese: '充滿小喜悅的生活比一年一次的高峰更豐富。', vocabulary: [{ word: 'annual high', definition: '年度高峰' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'What Blocked Joy',
        lines: [
          { speaker: 'a', english: "Were there things that blocked joy this year — activities or habits that dragged you down?", chinese: '今年有什麼阻礙了喜悅嗎——讓你沉下去的活動或習慣？', vocabulary: [{ word: 'dragged you down', definition: '拖垮你；使你沮喪' }] },
          { speaker: 'b', english: "Comparison. Scrolling and then comparing my life to what I saw.", chinese: '比較。滾動瀏覽然後把我的生活和我看到的比較。', vocabulary: [{ word: 'comparison', definition: '比較；對比' }] },
          { speaker: 'a', english: "The comparison trap. Theodore Roosevelt called it the thief of joy.", chinese: '比較陷阱。西奧多·羅斯福稱它為喜悅的小偷。', vocabulary: [{ word: 'thief of joy', definition: '喜悅的小偷' }] },
          { speaker: 'b', english: "You're measuring your insides against someone else's outsides.", chinese: '你在用你的內在來衡量別人的外在。', vocabulary: [{ word: 'insides', definition: '內在；內心' }] },
          { speaker: 'a', english: "What did you do about it?", chinese: '你對此做了什麼？', vocabulary: [] },
          { speaker: 'b', english: "Unfollowed a lot of accounts. Cut my time to fifteen minutes a day.", chinese: '取消關注了很多帳號。把時間削減到每天十五分鐘。', vocabulary: [{ word: 'unfollowed', definition: '取消關注' }] },
          { speaker: 'a', english: "And the joy came back when the comparison went away?", chinese: '當比較消失時，喜悅回來了嗎？', vocabulary: [] },
          { speaker: 'b', english: "Noticeably. The space that opened up was filled with actual living instead of watching others live.", chinese: '明顯地。那個空出來的空間被真正的生活填滿，而不是觀看別人的生活。', vocabulary: [{ word: 'noticeably', definition: '明顯地' }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Protecting Joy Going Forward',
        lines: [
          { speaker: 'a', english: "How will you protect and prioritize joy in the coming year?", chinese: '在接下來的一年，你將如何保護和優先考慮喜悅？', vocabulary: [{ word: 'prioritize', definition: '優先考慮；優先排序' }] },
          { speaker: 'b', english: "Schedule it. Joy that isn't scheduled gets squeezed out by urgency.", chinese: '安排它。沒有計劃的喜悅會被緊急事務擠出去。', vocabulary: [{ word: 'squeezed out', definition: '被擠出去；被排除' }] },
          { speaker: 'a', english: "Put it in the calendar first, not last.", chinese: '先把它放進日曆，而不是最後。', vocabulary: [] },
          { speaker: 'b', english: "Make the creative projects non-negotiable the way meetings are non-negotiable.", chinese: '讓創意專案像會議一樣是不可妥協的。', vocabulary: [] },
          { speaker: 'a', english: "The artist's date — protecting time to fill your own creative well.", chinese: '藝術家的約會——保護時間來填充你自己的創意之井。', vocabulary: [{ word: "artist's date", definition: '藝術家的約會；創意補充時間' }] },
          { speaker: 'b', english: "And protecting the small rituals from efficiency optimization.", chinese: '並保護小儀式不被效率優化所侵犯。', vocabulary: [{ word: 'efficiency optimization', definition: '效率優化' }] },
          { speaker: 'a', english: "The Sunday pancakes are sacred — do not let anyone schedule a brunch meeting over them.", chinese: '週日煎餅是神聖的——不要讓任何人在那時間安排早午餐會議。', vocabulary: [{ word: 'sacred', definition: '神聖的；不可侵犯的' }] },
          { speaker: 'b', english: "Ha! Exactly. Some things are worth being unproductive about.", chinese: '哈！正是。有些事情值得為之「低效」。', vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'joy audit', meaning: '喜悅審核' },
      { phrase: 'lit me up', meaning: '點燃我；讓我充滿活力' },
      { phrase: 'from scratch', meaning: '從零開始' },
      { phrase: 'creative outlets', meaning: '創意出口' },
      { phrase: 'comparison is the thief of joy', meaning: '比較是喜悅的小偷' },
      { phrase: 'insides vs outsides', meaning: '用內在比較別人的外在' },
      { phrase: 'small rituals', meaning: '小儀式' },
      { phrase: "artist's date", meaning: '藝術家的補充創意時間' },
      { phrase: 'squeezed out', meaning: '被擠出去' },
      { phrase: 'joy as a compass', meaning: '喜悅作為指引方向的指南針' },
    ],
  },
  {
    weekNumber: 52,
    dayOfWeek: 7,
    date: '2026-12-27',
    theme: 'Year in Review',
    title: 'A Letter to Your Future Self',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Opening: Year-End Ritual',
        lines: [
          { speaker: 'a', english: "Last Sunday of the year. How does that feel?", chinese: '一年中最後一個星期天。感覺如何？', vocabulary: [] },
          { speaker: 'b', english: "Reflective and a little bittersweet. There's so much I'm grateful for, and so much still undone.", chinese: '沉思而有些苦樂參半。有那麼多我感激的，也有那麼多還沒完成的。', vocabulary: [{ word: 'bittersweet', definition: '苦樂參半的' }] },
          { speaker: 'a', english: "That tension between gratitude and longing — that might just be the human condition.", chinese: '感恩和渴望之間的張力——這可能就是人類的狀況。', vocabulary: [{ word: 'longing', definition: '渴望；思念' }] },
          { speaker: 'b', english: "Perhaps. Today I want to talk about a ritual I do every December — writing a letter to my future self.", chinese: '也許吧。今天我想談談我每年十二月都會做的儀式——給未來的自己寫信。', vocabulary: [{ word: 'ritual', definition: '儀式；例行習俗' }] },
          { speaker: 'a', english: "A time capsule of your current self, delivered to your future self.", chinese: '你現在自己的時間膠囊，傳遞給未來的自己。', vocabulary: [{ word: 'time capsule', definition: '時間膠囊' }] },
          { speaker: 'b', english: "Exactly. And reading last year's letter is often the most powerful moment of my review.", chinese: '正是。而閱讀去年的信，通常是我回顧中最有力量的時刻。', vocabulary: [{ word: 'powerful', definition: '有力量的；強大的' }] },
          { speaker: 'a', english: "Why powerful?", chinese: '為什麼有力量？', vocabulary: [] },
          { speaker: 'b', english: "Because you see how much you've changed — and often how wrong your fears were.", chinese: '因為你看到你改變了多少——而且往往你的恐懼是多麼錯誤。', vocabulary: [{ word: 'fears', definition: '恐懼；害怕' }] },
        ],
      },
      {
        partNumber: 2,
        title: 'What Goes in the Letter',
        lines: [
          { speaker: 'a', english: "What do you write in your letter to your future self?", chinese: '你在給未來自己的信中寫什麼？', vocabulary: [] },
          { speaker: 'b', english: "What I'm proud of from this year. What I'm scared of for next year. And what I hope for.", chinese: '我為今年感到驕傲的事。明年我害怕的事。以及我希望的事。', vocabulary: [] },
          { speaker: 'a', english: "The hopes section must be vulnerable — you're committing to an aspiration in writing.", chinese: '希望部分一定很脆弱——你在以書面方式承諾一個渴望。', vocabulary: [{ word: 'aspiration', definition: '渴望；志向' }] },
          { speaker: 'b', english: "That's exactly what makes it meaningful. Saying it out loud — or on paper — changes your relationship to it.", chinese: '這正是它有意義的原因。大聲說出來——或寫在紙上——改變了你與它的關係。', vocabulary: [] },
          { speaker: 'a', english: "The written word as commitment mechanism.", chinese: '書面文字作為承諾機制。', vocabulary: [{ word: 'commitment mechanism', definition: '承諾機制' }] },
          { speaker: 'b', english: "I also include something I want to let go of — a belief or habit I'm consciously releasing.", chinese: '我還包括一件我想放開的事情——一個我有意識地放棄的信念或習慣。', vocabulary: [{ word: 'consciously', definition: '有意識地；刻意地' }] },
          { speaker: 'a', english: "A formal farewell to what no longer serves you.", chinese: '對不再為你服務的東西正式告別。', vocabulary: [{ word: 'farewell', definition: '告別；再見' }] },
          { speaker: 'b', english: "Naming it makes it real. And real things can be changed.", chinese: '命名它使它成為真實的。而真實的事情可以被改變。', vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'Reading Last Year\'s Letter',
        lines: [
          { speaker: 'a', english: "When you read the letter you wrote a year ago, what did you find?", chinese: '當你讀去年寫的信時，你發現了什麼？', vocabulary: [] },
          { speaker: 'b', english: "I was surprised how much I've grown in ways I didn't expect.", chinese: '我很驚訝我以自己沒有預期的方式成長了多少。', vocabulary: [] },
          { speaker: 'a', english: "Life rarely grows where we plant the seeds — it grows where the conditions are right.", chinese: '生活很少在我們種下種子的地方生長——它在條件合適的地方生長。', vocabulary: [{ word: 'conditions', definition: '條件；環境' }] },
          { speaker: 'b', english: "Past me was worried about a relationship that resolved itself beautifully.", chinese: '過去的我很擔心一段關係，但它自己美好地解決了。', vocabulary: [{ word: 'resolved itself', definition: '自己解決了' }] },
          { speaker: 'a', english: "Most fears don't materialize. The things that actually challenge us are usually surprises.", chinese: '大多數恐懼都不會成真。真正挑戰我們的事情通常是驚喜。', vocabulary: [{ word: 'materialize', definition: '成真；實現' }] },
          { speaker: 'b', english: "And past me didn't mention something that became hugely important this year.", chinese: '而過去的我沒有提到今年變得非常重要的某件事。', vocabulary: [] },
          { speaker: 'a', english: "What was it?", chinese: '那是什麼？', vocabulary: [] },
          { speaker: 'b', english: "Learning to ask for help. It wasn't on my radar as a goal, but it became my biggest growth.", chinese: '學會尋求幫助。它不在我的目標視野中，但它成了我最大的成長。', vocabulary: [{ word: "on my radar", definition: '在我的視野中；在我的考慮範圍內' }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Writing the New Letter',
        lines: [
          { speaker: 'a', english: "So what are you writing in this year's letter?", chinese: '那你今年的信裡寫了什麼？', vocabulary: [] },
          { speaker: 'b', english: "I'm proud of staying curious — I never stopped learning even when it was hard.", chinese: '我為保持好奇心感到驕傲——即使在困難的時候，我也沒有停止學習。', vocabulary: [{ word: 'curious', definition: '好奇的' }] },
          { speaker: 'a', english: "Curiosity is an underrated form of courage.", chinese: '好奇心是一種被低估的勇氣形式。', vocabulary: [{ word: 'underrated', definition: '被低估的' }] },
          { speaker: 'b', english: "For my hope — I hope I've kept the commitments to myself that feel scary right now.", chinese: '對於我的希望——我希望我保持了對自己的承諾，這些承諾現在感覺很可怕。', vocabulary: [{ word: 'commitments', definition: '承諾；投入' }] },
          { speaker: 'a', english: "Writing to yourself about fear is one of the bravest things you can do.", chinese: '給自己寫關於恐懼的信，是你能做的最勇敢的事情之一。', vocabulary: [] },
          { speaker: 'b', english: "And what I'm releasing: the need to be certain before I begin.", chinese: '而我要放開的：在開始之前需要確定的需求。', vocabulary: [{ word: 'releasing', definition: '放開；釋放' }] },
          { speaker: 'a', english: "Releasing certainty, embracing possibility.", chinese: '放開確定性，擁抱可能性。', vocabulary: [{ word: 'embracing', definition: '擁抱；接受' }] },
          { speaker: 'b', english: "That might be the theme of the year ahead.", chinese: '這可能是未來一年的主題。', vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'Closing the Year',
        lines: [
          { speaker: 'a', english: "As we close out this week and this year, what do you want to say to our listeners?", chinese: '當我們結束這一週和這一年時，你想對我們的聽眾說什麼？', vocabulary: [] },
          { speaker: 'b', english: "You showed up. Week after week, you chose to learn and grow — that's not small.", chinese: '你出現了。一週又一週，你選擇學習和成長——這不是小事。', vocabulary: [{ word: 'showed up', definition: '出現；現身' }] },
          { speaker: 'a', english: "Consistency over time is what creates transformation. Not one big day, but every ordinary day.", chinese: '長期的堅持才能創造轉變。不是一個大日子，而是每一個普通的日子。', vocabulary: [{ word: 'transformation', definition: '轉變；蛻變' }] },
          { speaker: 'b', english: "This year you expanded your English — but more than that, you expanded your world.", chinese: '今年你擴展了你的英語——但不只如此，你擴展了你的世界。', vocabulary: [{ word: 'expanded', definition: '擴展；擴大' }] },
          { speaker: 'a', english: "Language learning is world-building. Every new word is a new window.", chinese: '語言學習是世界建構。每個新詞都是一扇新窗戶。', vocabulary: [{ word: 'world-building', definition: '世界建構' }] },
          { speaker: 'b', english: "Write your letter to your future self this week. You won't regret it.", chinese: '這週寫信給未來的自己。你不會後悔的。', vocabulary: [] },
          { speaker: 'a', english: "And seal it. Don't peek — let December 2027 Mira be surprised by December 2026 Mira.", chinese: '然後封起來。不要偷看——讓 2027 年 12 月的 Mira 對 2026 年 12 月的 Mira 感到驚喜。', vocabulary: [{ word: 'seal', definition: '封住；密封' }] },
          { speaker: 'b', english: "Here's to a meaningful new year — for all of us, still curious, still becoming.", chinese: '敬一個有意義的新年——對我們所有人，仍然好奇，仍然在成長中。', vocabulary: [{ word: 'becoming', definition: '成為；在成長中' }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: 'letter to your future self', meaning: '給未來自己的信' },
      { phrase: 'time capsule', meaning: '時間膠囊' },
      { phrase: 'bittersweet', meaning: '苦樂參半的' },
      { phrase: 'commitment mechanism', meaning: '承諾機制' },
      { phrase: 'fears rarely materialize', meaning: '恐懼很少成真' },
      { phrase: 'on my radar', meaning: '在我的考慮範圍內' },
      { phrase: 'releasing certainty', meaning: '放開對確定性的需求' },
      { phrase: 'showed up', meaning: '出現；現身' },
      { phrase: 'language learning is world-building', meaning: '語言學習就是建構世界' },
      { phrase: 'still becoming', meaning: '仍然在成長的過程中' },
    ],
  },
];
