import { Episode } from '../types';

export const WEEK_46: Episode[] = [
  {
    weekNumber: 46,
    dayOfWeek: 1,
    date: '2026-11-09',
    theme: 'Community & Giving Back',
    title: 'The Power of Community',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'What Is Community?',
        lines: [
          { speaker: 'a', english: "Jamie, have you ever thought about what makes a real community?", chinese: "Jamie，你有沒有想過什麼是真正的社群？", vocabulary: [{ word: "community", definition: "社群；社區" }] },
          { speaker: 'b', english: "I think it's more than just living near each other. It's about shared values and support.", chinese: "我想不只是住在附近而已，是關於共同的價值觀和相互支持。", vocabulary: [{ word: "shared values", definition: "共同價值觀" }] },
          { speaker: 'a', english: "Exactly. Communities can be neighborhoods, workplaces, or even online groups.", chinese: "沒錯，社群可以是鄰里、職場，甚至是線上群組。", vocabulary: [{ word: "neighborhood", definition: "鄰里；社區" }] },
          { speaker: 'b', english: "I belong to a running club, and honestly, that feels like more of a community than my apartment building.", chinese: "我加入了一個跑步俱樂部，說真的，那感覺比我的公寓大樓更有社群感。", vocabulary: [{ word: "belong to", definition: "屬於；加入" }] },
          { speaker: 'a', english: "That's so true. Shared activities create stronger bonds than just proximity.", chinese: "說得真對，共同活動比單純的距離更能建立緊密的連結。", vocabulary: [{ word: "proximity", definition: "鄰近；接近" }] },
          { speaker: 'b', english: "And communities have this sense of mutual responsibility — you look out for each other.", chinese: "而且社群有一種共同責任感——你們互相照應。", vocabulary: [{ word: "mutual responsibility", definition: "共同責任" }] },
          { speaker: 'a', english: "What do you think is the biggest challenge for modern communities?", chinese: "你覺得現代社群最大的挑戰是什麼？", vocabulary: [] },
          { speaker: 'b', english: "Probably disconnection. Everyone's so busy that it's hard to invest time in building relationships.", chinese: "可能是疏離感吧，每個人都太忙，很難花時間建立關係。", vocabulary: [{ word: "disconnection", definition: "疏離；斷開" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Volunteering and Giving Time',
        lines: [
          { speaker: 'a', english: "Have you ever volunteered for anything?", chinese: "你曾經做過義工嗎？", vocabulary: [{ word: "volunteer", definition: "當義工；自願" }] },
          { speaker: 'b', english: "Yes! I used to help at a food bank on weekends. It was really eye-opening.", chinese: "有！我以前週末會去食物銀行幫忙，那真的讓我大開眼界。", vocabulary: [{ word: "food bank", definition: "食物銀行" }] },
          { speaker: 'a', english: "What was eye-opening about it?", chinese: "有什麼讓你大開眼界的地方？", vocabulary: [] },
          { speaker: 'b', english: "Seeing how many people in our city struggle with food insecurity. I had no idea.", chinese: "看到我們城市裡有這麼多人面臨糧食不安全問題，我完全不知道。", vocabulary: [{ word: "food insecurity", definition: "糧食不安全" }] },
          { speaker: 'a', english: "Volunteering really changes your perspective on the world around you.", chinese: "做義工真的會改變你對周遭世界的看法。", vocabulary: [{ word: "perspective", definition: "觀點；視角" }] },
          { speaker: 'b', english: "It also gave me a sense of purpose. Helping others feels genuinely rewarding.", chinese: "它也給了我一種使命感，幫助別人感覺真的很有意義。", vocabulary: [{ word: "sense of purpose", definition: "使命感" }] },
          { speaker: 'a', english: "Some companies even give employees paid time off for volunteering.", chinese: "有些公司甚至給員工帶薪假期去做義工。", vocabulary: [{ word: "paid time off", definition: "帶薪假" }] },
          { speaker: 'b', english: "That's a great policy. It shows that businesses can be part of the community too.", chinese: "這是個很好的政策，說明企業也可以是社群的一部分。", vocabulary: [{ word: "policy", definition: "政策；方針" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Giving Back in Small Ways',
        lines: [
          { speaker: 'a', english: "Not everyone has time to volunteer regularly. Are there smaller ways to give back?", chinese: "不是每個人都有時間定期做義工，有沒有更小的方式回饋社群？", vocabulary: [{ word: "give back", definition: "回饋" }] },
          { speaker: 'b', english: "Absolutely. Even simple things like mentoring a junior colleague make a difference.", chinese: "當然有，就連輔導資淺同事這樣簡單的事也能帶來改變。", vocabulary: [{ word: "mentor", definition: "輔導；指導" }] },
          { speaker: 'a', english: "Or holding the door open, or checking in on an elderly neighbor.", chinese: "或者幫人扶門、關心一下年長的鄰居。", vocabulary: [{ word: "check in on", definition: "探望；關心" }] },
          { speaker: 'b', english: "The concept of random acts of kindness is powerful. Small gestures ripple outward.", chinese: "隨機善舉的概念很有力量，小小的舉動會向外擴散。", vocabulary: [{ word: "random acts of kindness", definition: "隨機善舉" }] },
          { speaker: 'a', english: "I once left a positive note for the cleaning staff at my office and they said it made their week.", chinese: "我曾經留了一張感謝字條給辦公室的清潔人員，他們說這讓他們整週都很開心。", vocabulary: [] },
          { speaker: 'b', english: "That's beautiful. Recognition is a form of giving back that costs nothing.", chinese: "那真的很美，認可是一種回饋的方式，完全不需要任何代價。", vocabulary: [{ word: "recognition", definition: "認可；肯定" }] },
          { speaker: 'a', english: "I think we underestimate how much our words and attention mean to people.", chinese: "我覺得我們低估了自己的言語和關注對別人的意義。", vocabulary: [{ word: "underestimate", definition: "低估" }] },
          { speaker: 'b', english: "Giving back doesn't always mean money or big projects. Presence matters too.", chinese: "回饋不一定是錢或大型計畫，陪伴也很重要。", vocabulary: [{ word: "presence", definition: "陪伴；存在" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Community Organizations and NGOs',
        lines: [
          { speaker: 'a', english: "What do you know about NGOs and nonprofit organizations?", chinese: "你對非政府組織和非營利組織了解多少？", vocabulary: [{ word: "NGO", definition: "非政府組織" }] },
          { speaker: 'b', english: "They fill gaps that governments and businesses can't always address.", chinese: "它們填補了政府和企業無法始終照顧到的缺口。", vocabulary: [{ word: "fill gaps", definition: "填補缺口" }] },
          { speaker: 'a', english: "And they rely heavily on donations and volunteers to operate.", chinese: "而且它們很大程度上依賴捐款和義工來運作。", vocabulary: [{ word: "donation", definition: "捐款；捐贈" }] },
          { speaker: 'b', english: "I've been thinking about donating regularly to an environmental organization.", chinese: "我一直在考慮定期捐款給一個環保組織。", vocabulary: [{ word: "environmental organization", definition: "環保組織" }] },
          { speaker: 'a', english: "That's great. Even a small monthly donation adds up over time.", chinese: "很好，就算是小額的月捐，長期累積下來也很可觀。", vocabulary: [{ word: "add up", definition: "累積；加總" }] },
          { speaker: 'b', english: "I also like the idea of skills-based volunteering — using your professional skills to help.", chinese: "我也很喜歡技能型義工的概念——用你的專業技能來幫忙。", vocabulary: [{ word: "skills-based volunteering", definition: "技能型義工服務" }] },
          { speaker: 'a', english: "Like a lawyer offering free legal advice, or a designer creating logos for nonprofits.", chinese: "比如律師提供免費法律諮詢，或設計師為非營利組織設計標誌。", vocabulary: [] },
          { speaker: 'b', english: "Exactly. Everyone has something valuable to contribute to the community.", chinese: "沒錯，每個人都有寶貴的東西可以貢獻給社群。", vocabulary: [{ word: "contribute", definition: "貢獻；付出" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Building Stronger Bonds',
        lines: [
          { speaker: 'a', english: "What's the relationship between giving back and your own wellbeing?", chinese: "回饋社群和個人幸福感之間有什麼關係？", vocabulary: [{ word: "wellbeing", definition: "幸福感；健康狀態" }] },
          { speaker: 'b', english: "Research shows that helping others actually makes us happier and reduces stress.", chinese: "研究顯示，幫助別人實際上能讓我們更快樂、減少壓力。", vocabulary: [] },
          { speaker: 'a', english: "There's something called the 'helper's high' — a mood boost from acts of generosity.", chinese: "有一種叫做「助人高潮」的現象——來自慷慨行為的情緒提升。", vocabulary: [{ word: "helper's high", definition: "助人高潮（因助人而感到愉悅）" }] },
          { speaker: 'b', english: "I've definitely felt that. After a volunteer shift, I always feel lighter somehow.", chinese: "我絕對有這種感覺，做完義工後，我總覺得整個人輕盈了許多。", vocabulary: [{ word: "volunteer shift", definition: "義工班次" }] },
          { speaker: 'a', english: "Giving creates connection, and connection is what makes life meaningful.", chinese: "給予創造連結，而連結正是讓生命有意義的東西。", vocabulary: [{ word: "connection", definition: "連結；聯繫" }] },
          { speaker: 'b', english: "I want to get more involved in my local community this year. Maybe join a neighborhood group.", chinese: "我今年想更積極參與我的在地社群，也許加入一個鄰里團體。", vocabulary: [{ word: "get involved", definition: "參與；投入" }] },
          { speaker: 'a', english: "That sounds wonderful. Start small, and let it grow naturally from there.", chinese: "那聽起來很棒，從小處開始，讓它自然地成長。", vocabulary: [] },
          { speaker: 'b', english: "The world gets better one small act of giving at a time.", chinese: "世界因一次次小小的給予而變得更好。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "give back", meaning: "回饋社群" },
      { phrase: "sense of purpose", meaning: "使命感" },
      { phrase: "random acts of kindness", meaning: "隨機善舉" },
      { phrase: "fill gaps", meaning: "填補缺口" },
      { phrase: "skills-based volunteering", meaning: "技能型義工服務" },
      { phrase: "helper's high", meaning: "助人高潮" },
      { phrase: "mutual responsibility", meaning: "共同責任" },
      { phrase: "get involved", meaning: "參與；投入" },
      { phrase: "add up", meaning: "累積；加總" },
      { phrase: "check in on", meaning: "探望；關心" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 2,
    date: '2026-11-10',
    theme: 'Community & Giving Back',
    title: 'The Art of Listening',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Why Listening Matters',
        lines: [
          { speaker: 'a', english: "I think one of the most underrated ways to help someone is just to listen.", chinese: "我覺得幫助別人最被低估的方式之一就是傾聽。", vocabulary: [{ word: "underrated", definition: "被低估的" }] },
          { speaker: 'b', english: "You're right. People often want to be heard more than they want advice.", chinese: "你說得對，人們往往比想要建議更想被傾聽。", vocabulary: [{ word: "be heard", definition: "被傾聽；被理解" }] },
          { speaker: 'a', english: "We live in a world full of noise. True listening is rare and incredibly valuable.", chinese: "我們生活在一個充滿噪音的世界，真正的傾聽是稀有且無比珍貴的。", vocabulary: [{ word: "incredibly", definition: "難以置信地；非常" }] },
          { speaker: 'b', english: "I know I'm guilty of thinking about my response while someone is still talking.", chinese: "我知道我自己也常常在別人還在說話時就已經在想我的回應。", vocabulary: [{ word: "guilty", definition: "有罪的；慚愧的" }] },
          { speaker: 'a', english: "That's called listening to respond, not listening to understand. There's a big difference.", chinese: "那叫做「為了回應而聽」，不是「為了理解而聽」，兩者差別很大。", vocabulary: [] },
          { speaker: 'b', english: "Active listening involves giving your full attention and suspending judgment.", chinese: "積極傾聽包括給予完整的注意力和暫停評判。", vocabulary: [{ word: "active listening", definition: "積極傾聽" }] },
          { speaker: 'a', english: "It means making the other person feel genuinely seen and understood.", chinese: "這意味著讓對方真正感到被看見和被理解。", vocabulary: [] },
          { speaker: 'b', english: "That's a gift. Being truly listened to can be transformative for someone.", chinese: "那是一份禮物，被真心傾聽對一個人來說可能是轉化性的。", vocabulary: [{ word: "transformative", definition: "具有轉化力的；改變性的" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Listening Techniques',
        lines: [
          { speaker: 'a', english: "What are some techniques that make you a better listener?", chinese: "有哪些技巧能讓你成為更好的傾聽者？", vocabulary: [] },
          { speaker: 'b', english: "One is to maintain eye contact and nod — show you're engaged without interrupting.", chinese: "一個方法是保持眼神接觸和點頭——在不打斷的情況下表現出你在專注。", vocabulary: [{ word: "maintain eye contact", definition: "保持眼神接觸" }] },
          { speaker: 'a', english: "Paraphrasing is also powerful — repeating back what you heard in your own words.", chinese: "重述也很有效——用你自己的話重述你所聽到的。", vocabulary: [{ word: "paraphrase", definition: "重述；改述" }] },
          { speaker: 'b', english: "That shows the person that you actually processed what they said.", chinese: "這讓對方知道你真的消化了他們說的話。", vocabulary: [{ word: "process", definition: "消化；處理" }] },
          { speaker: 'a', english: "Asking open-ended questions also encourages people to share more deeply.", chinese: "問開放式問題也能鼓勵人們分享得更深入。", vocabulary: [{ word: "open-ended questions", definition: "開放式問題" }] },
          { speaker: 'b', english: "And sometimes silence is okay. You don't have to fill every pause.", chinese: "有時候沉默也沒關係，你不需要填補每一個停頓。", vocabulary: [{ word: "pause", definition: "停頓；暫停" }] },
          { speaker: 'a', english: "Silence gives the other person space to continue if they want to.", chinese: "沉默給了對方空間，讓他們可以在想繼續時繼續說。", vocabulary: [] },
          { speaker: 'b', english: "Good listening is actually a skill that can be developed with practice.", chinese: "良好的傾聽實際上是一種可以透過練習來培養的技巧。", vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'Listening in the Workplace',
        lines: [
          { speaker: 'a', english: "Listening is especially important in professional settings, right?", chinese: "在職場上傾聽特別重要，對嗎？", vocabulary: [{ word: "professional settings", definition: "職業環境；專業場合" }] },
          { speaker: 'b', english: "Definitely. Managers who listen well tend to have happier, more productive teams.", chinese: "絕對是的，善於傾聽的管理者通常擁有更快樂、更有生產力的團隊。", vocabulary: [] },
          { speaker: 'a', english: "I had a boss once who would check his phone while I was updating him. It felt so dismissive.", chinese: "我曾有過一位老闆，在我向他匯報時會查看手機，感覺非常不被重視。", vocabulary: [{ word: "dismissive", definition: "輕蔑的；不屑一顧的" }] },
          { speaker: 'b', english: "That's unfortunately common. It sends the message that your time isn't valuable.", chinese: "那很遺憾地很常見，這傳達了一個訊息：你的時間不重要。", vocabulary: [] },
          { speaker: 'a', english: "On the other hand, when someone really listens, you feel more motivated to do your best.", chinese: "另一方面，當有人真正傾聽你時，你會更有動力做到最好。", vocabulary: [] },
          { speaker: 'b', english: "Listening also helps avoid misunderstandings and costly mistakes in projects.", chinese: "傾聽也有助於避免誤解和計畫中代價高昂的錯誤。", vocabulary: [{ word: "costly mistakes", definition: "代價高昂的錯誤" }] },
          { speaker: 'a', english: "I've seen entire projects go wrong because someone didn't listen to the client's actual needs.", chinese: "我見過整個專案出錯，就是因為有人沒有傾聽客戶的實際需求。", vocabulary: [] },
          { speaker: 'b', english: "Listening is foundational to good communication, problem-solving, and leadership.", chinese: "傾聽是良好溝通、解決問題和領導力的基礎。", vocabulary: [{ word: "foundational", definition: "基礎性的；根本的" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Listening to Different Perspectives',
        lines: [
          { speaker: 'a', english: "How does listening connect to empathy and understanding others?", chinese: "傾聽與同理心和理解他人有什麼關聯？", vocabulary: [{ word: "empathy", definition: "同理心" }] },
          { speaker: 'b', english: "When we listen without judgment, we open ourselves to perspectives different from our own.", chinese: "當我們不帶評判地傾聽時，我們就對與自己不同的觀點敞開了心扉。", vocabulary: [{ word: "without judgment", definition: "不帶評判地" }] },
          { speaker: 'a', english: "That's how we grow as people — by genuinely hearing viewpoints that challenge us.", chinese: "這就是我們成長的方式——真誠地傾聽挑戰我們的觀點。", vocabulary: [{ word: "viewpoint", definition: "觀點；見解" }] },
          { speaker: 'b', english: "It's hard though. When someone says something we disagree with, our instinct is to debate.", chinese: "但這很難，當有人說了我們不同意的話，我們的本能是辯論。", vocabulary: [{ word: "instinct", definition: "本能；直覺" }] },
          { speaker: 'a', english: "The key is to listen to understand first, before forming a response.", chinese: "關鍵是先傾聽理解，再形成回應。", vocabulary: [] },
          { speaker: 'b', english: "That shift in mindset can transform a potential argument into a real conversation.", chinese: "這種心態的轉變可以把潛在的爭論轉化為真正的對話。", vocabulary: [{ word: "transform", definition: "轉化；改變" }] },
          { speaker: 'a', english: "I try to repeat back someone's position before I respond. It slows things down.", chinese: "我嘗試在回應之前重述對方的立場，這樣能讓事情慢下來。", vocabulary: [{ word: "position", definition: "立場；觀點" }] },
          { speaker: 'b', english: "That's a really mature approach. It de-escalates tension and builds trust.", chinese: "那是非常成熟的做法，它能緩和緊張情勢並建立信任。", vocabulary: [{ word: "de-escalate", definition: "緩和；降低緊張" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Listening as a Community Act',
        lines: [
          { speaker: 'a', english: "I wonder if communities could be stronger if people just listened more to each other.", chinese: "我想知道，如果人們多傾聽彼此，社群是否會更強大。", vocabulary: [] },
          { speaker: 'b', english: "Absolutely. So much conflict comes from people talking past each other, not really hearing.", chinese: "絕對是的，許多衝突都源於人們各說各話，而不是真正傾聽。", vocabulary: [{ word: "talking past each other", definition: "各說各話；無法溝通" }] },
          { speaker: 'a', english: "There are community initiatives that bring strangers together just to share their stories.", chinese: "有些社群倡議把陌生人聚集在一起，只是為了分享彼此的故事。", vocabulary: [{ word: "initiative", definition: "倡議；行動" }] },
          { speaker: 'b', english: "Like storytelling events or listening circles. I've heard great things about those.", chinese: "像是說故事活動或傾聽圈，我聽說過關於那些的很棒的事情。", vocabulary: [{ word: "listening circle", definition: "傾聽圈" }] },
          { speaker: 'a', english: "When you hear someone's full story, it's hard to remain indifferent to them.", chinese: "當你聽完某人完整的故事，很難對他們保持冷漠。", vocabulary: [{ word: "indifferent", definition: "冷漠的；漠不關心的" }] },
          { speaker: 'b', english: "Stories build bridges. That's the power of listening at a community level.", chinese: "故事建橋，這就是傾聽在社群層面的力量。", vocabulary: [{ word: "build bridges", definition: "架橋；建立連結" }] },
          { speaker: 'a', english: "I'm going to try to be a better listener this week. Starting with my family.", chinese: "我這週要努力做一個更好的傾聽者，從家人開始。", vocabulary: [] },
          { speaker: 'b', english: "Me too. It might be the most impactful thing we do all week.", chinese: "我也是，這可能是我們這整週最有影響力的事。", vocabulary: [{ word: "impactful", definition: "有影響力的；有衝擊性的" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "active listening", meaning: "積極傾聽" },
      { phrase: "be heard", meaning: "被傾聽" },
      { phrase: "talking past each other", meaning: "各說各話" },
      { phrase: "open-ended questions", meaning: "開放式問題" },
      { phrase: "listening to understand", meaning: "為了理解而傾聽" },
      { phrase: "without judgment", meaning: "不帶評判地" },
      { phrase: "de-escalate tension", meaning: "緩和緊張情勢" },
      { phrase: "build bridges", meaning: "架橋；建立連結" },
      { phrase: "paraphrase", meaning: "重述；改述" },
      { phrase: "transformative", meaning: "具有轉化力的" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 3,
    date: '2026-11-11',
    theme: 'Community & Giving Back',
    title: 'Local Heroes and Changemakers',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Everyday Heroes Among Us',
        lines: [
          { speaker: 'a', english: "I think we often overlook the people who quietly make our communities better.", chinese: "我覺得我們常常忽視那些默默讓社群變得更好的人。", vocabulary: [{ word: "overlook", definition: "忽視；忽略" }] },
          { speaker: 'b', english: "You mean like the neighbor who organizes trash clean-ups every month?", chinese: "你是指像那個每個月組織垃圾清理活動的鄰居嗎？", vocabulary: [{ word: "organize", definition: "組織；籌辦" }] },
          { speaker: 'a', english: "Exactly. Or the person who starts a community garden on an empty lot.", chinese: "沒錯，或者那個在空地上建立社區花園的人。", vocabulary: [{ word: "community garden", definition: "社區花園" }] },
          { speaker: 'b', english: "These are people who saw a problem and decided to do something about it.", chinese: "這些人看到了問題並決定採取行動。", vocabulary: [{ word: "take action", definition: "採取行動" }] },
          { speaker: 'a', english: "They're often called changemakers — ordinary people creating extraordinary impact.", chinese: "他們通常被稱為變革者——創造非凡影響的普通人。", vocabulary: [{ word: "changemaker", definition: "變革者；推動改變的人" }] },
          { speaker: 'b', english: "What I admire is that they don't wait for permission or resources to begin.", chinese: "我欽佩的是他們不等待許可或資源就開始行動。", vocabulary: [{ word: "permission", definition: "許可；許可" }] },
          { speaker: 'a', english: "They start with what they have and build from there.", chinese: "他們從現有的資源開始，並從那裡發展。", vocabulary: [] },
          { speaker: 'b', english: "That grassroots energy is really inspiring and contagious.", chinese: "那種草根能量真的很鼓舞人心且具有感染力。", vocabulary: [{ word: "grassroots", definition: "草根的；基層的" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Social Entrepreneurs',
        lines: [
          { speaker: 'a', english: "Have you heard of social entrepreneurs? They combine business with social impact.", chinese: "你聽說過社會企業家嗎？他們將商業與社會影響力結合起來。", vocabulary: [{ word: "social entrepreneur", definition: "社會企業家" }] },
          { speaker: 'b', english: "Yes! There are companies that hire marginalized communities or reinvest profits into social causes.", chinese: "是的！有些公司僱用邊緣化社群，或將利潤重新投資於社會公益。", vocabulary: [{ word: "marginalized", definition: "被邊緣化的" }] },
          { speaker: 'a', english: "The triple bottom line concept — people, planet, profit — guides these businesses.", chinese: "三重底線概念——人、地球、利潤——引導著這些企業。", vocabulary: [{ word: "triple bottom line", definition: "三重底線" }] },
          { speaker: 'b', english: "I like the idea that business can be a force for good, not just profit-making.", chinese: "我喜歡商業可以成為一股向善力量，而不僅僅是謀取利潤的概念。", vocabulary: [{ word: "force for good", definition: "向善的力量" }] },
          { speaker: 'a', english: "B Corporations are companies certified for their social and environmental performance.", chinese: "B型企業是因其社會和環境績效而獲得認證的公司。", vocabulary: [{ word: "B Corporation", definition: "B型企業" }] },
          { speaker: 'b', english: "I try to support those kinds of businesses when I can with my purchasing choices.", chinese: "我在購物選擇上盡量支持那類企業。", vocabulary: [{ word: "purchasing choices", definition: "購物選擇；消費選擇" }] },
          { speaker: 'a', english: "Consumer power is real. Where we spend our money sends a message.", chinese: "消費者的力量是真實的，我們把錢花在哪裡就傳遞了一個訊息。", vocabulary: [{ word: "consumer power", definition: "消費者力量" }] },
          { speaker: 'b', english: "Exactly. Giving back can even happen through conscious spending.", chinese: "沒錯，回饋甚至可以通過有意識的消費來實現。", vocabulary: [{ word: "conscious spending", definition: "有意識的消費" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Youth Activism and Civic Engagement',
        lines: [
          { speaker: 'a', english: "Young people are increasingly taking leadership roles in community change.", chinese: "年輕人越來越多地在社群變革中擔任領導角色。", vocabulary: [{ word: "civic engagement", definition: "公民參與" }] },
          { speaker: 'b', english: "I've seen teenagers organize environmental campaigns that actually led to policy changes.", chinese: "我見過青少年組織環保運動，實際上促成了政策改變。", vocabulary: [{ word: "policy changes", definition: "政策改變" }] },
          { speaker: 'a', english: "Young activists often have energy, idealism, and digital tools working in their favor.", chinese: "年輕行動者通常有能量、理想主義和數位工具為他們所用。", vocabulary: [{ word: "activism", definition: "行動主義；積極倡議" }] },
          { speaker: 'b', english: "Social media has amplified youth voices in ways that weren't possible before.", chinese: "社群媒體以前所未有的方式放大了年輕人的聲音。", vocabulary: [{ word: "amplify", definition: "放大；擴大" }] },
          { speaker: 'a', english: "The challenge is translating online momentum into real-world impact.", chinese: "挑戰在於將線上動能轉化為現實世界的影響。", vocabulary: [{ word: "momentum", definition: "動能；勢頭" }] },
          { speaker: 'b', english: "But when it happens, it's remarkable. Movements can shift culture and laws.", chinese: "但當它發生時，那是非凡的，運動可以改變文化和法律。", vocabulary: [{ word: "shift culture", definition: "改變文化" }] },
          { speaker: 'a', english: "Encouraging young people to get civically engaged is one of the best investments a community can make.", chinese: "鼓勵年輕人參與公民事務是社群能做的最好投資之一。", vocabulary: [{ word: "civically engaged", definition: "積極參與公民事務" }] },
          { speaker: 'b', english: "I want to mentor some young people in my field — pass on what I've learned.", chinese: "我想指導我領域中的一些年輕人——傳承我所學到的。", vocabulary: [{ word: "pass on", definition: "傳承；傳遞" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Recognizing Unsung Heroes',
        lines: [
          { speaker: 'a', english: "We talk about famous changemakers, but what about the unsung heroes?", chinese: "我們談論著名的變革者，但那些默默無聞的英雄呢？", vocabulary: [{ word: "unsung hero", definition: "默默無聞的英雄" }] },
          { speaker: 'b', english: "The person who picks up litter every morning, or the parent who tutors neighborhood kids.", chinese: "每天早上撿垃圾的人，或者輔導鄰居孩子的家長。", vocabulary: [{ word: "tutor", definition: "輔導；教授" }] },
          { speaker: 'a', english: "These people don't make headlines, but their impact is deeply felt.", chinese: "這些人不會上頭條，但他們的影響深刻地被感受到。", vocabulary: [{ word: "make headlines", definition: "上頭條；引起廣泛關注" }] },
          { speaker: 'b', english: "I think we should actively celebrate them. Give credit where it's due.", chinese: "我認為我們應該積極地稱讚他們，給予應得的肯定。", vocabulary: [{ word: "give credit", definition: "給予肯定；表揚" }] },
          { speaker: 'a', english: "Some communities have community hero awards or recognition programs.", chinese: "有些社群設有社群英雄獎或表彰計畫。", vocabulary: [{ word: "recognition program", definition: "表彰計畫" }] },
          { speaker: 'b', english: "Even a simple thank-you can mean the world to someone who gives so much.", chinese: "就算是一句簡單的謝謝，對那些付出這麼多的人來說也可以意義重大。", vocabulary: [] },
          { speaker: 'a', english: "I'm going to write a thank-you note to the janitor at my building this week.", chinese: "我這週要給我大樓的管理員寫一張感謝便條。", vocabulary: [{ word: "janitor", definition: "管理員；清潔工" }] },
          { speaker: 'b', english: "That's a beautiful impulse. Gratitude is itself a form of giving back.", chinese: "那是個美好的衝動，感恩本身就是一種回饋。", vocabulary: [{ word: "impulse", definition: "衝動；念頭" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Inspiring Each Other to Act',
        lines: [
          { speaker: 'a', english: "What inspires you personally to give back?", chinese: "什麼在個人層面上激勵你去回饋？", vocabulary: [] },
          { speaker: 'b', english: "Seeing someone else do something quietly kind. It makes me want to do the same.", chinese: "看到別人默默做出善舉，這讓我也想做同樣的事。", vocabulary: [] },
          { speaker: 'a', english: "That's the ripple effect — one act of generosity inspires another.", chinese: "那就是漣漪效應——一個慷慨行為激勵另一個。", vocabulary: [{ word: "ripple effect", definition: "漣漪效應" }] },
          { speaker: 'b', english: "I also think about legacy — what kind of footprint I'm leaving in my community.", chinese: "我也思考遺產——我在社群中留下什麼樣的足跡。", vocabulary: [{ word: "legacy", definition: "遺產；留下的影響" }] },
          { speaker: 'a', english: "Not everyone will be famous, but everyone can leave things a little better than they found them.", chinese: "不是每個人都會出名，但每個人都可以讓事情比發現時好一點點。", vocabulary: [] },
          { speaker: 'b', english: "That phrase — leave it better than you found it — should be a life motto.", chinese: "那句話——讓它比你發現時更好——應該成為生活格言。", vocabulary: [{ word: "motto", definition: "座右銘；格言" }] },
          { speaker: 'a', english: "This week I've been inspired to be more intentional about how I contribute.", chinese: "這週我受到啟發，要更有意識地思考我如何貢獻。", vocabulary: [{ word: "intentional", definition: "有意識的；刻意的" }] },
          { speaker: 'b', english: "Small, consistent actions. That's how communities are transformed.", chinese: "小而持續的行動，這就是社群被改變的方式。", vocabulary: [{ word: "consistent", definition: "持續的；一致的" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "changemaker", meaning: "變革者；推動改變的人" },
      { phrase: "grassroots energy", meaning: "草根能量" },
      { phrase: "unsung hero", meaning: "默默無聞的英雄" },
      { phrase: "ripple effect", meaning: "漣漪效應" },
      { phrase: "leave it better than you found it", meaning: "讓它比你發現時更好" },
      { phrase: "force for good", meaning: "向善的力量" },
      { phrase: "civic engagement", meaning: "公民參與" },
      { phrase: "give credit", meaning: "給予肯定；表揚" },
      { phrase: "triple bottom line", meaning: "三重底線" },
      { phrase: "conscious spending", meaning: "有意識的消費" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 4,
    date: '2026-11-12',
    theme: 'Community & Giving Back',
    title: 'Navigating Differences in Community',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Diversity Within Communities',
        lines: [
          { speaker: 'a', english: "Communities are rarely homogeneous. They're full of different people with different backgrounds.", chinese: "社群很少是同質化的，它們充滿了來自不同背景的不同人。", vocabulary: [{ word: "homogeneous", definition: "同質的；均一的" }] },
          { speaker: 'b', english: "And that diversity is actually a huge strength, even if it also creates friction sometimes.", chinese: "而那種多樣性實際上是巨大的優勢，即使它有時也會產生摩擦。", vocabulary: [{ word: "friction", definition: "摩擦；衝突" }] },
          { speaker: 'a', english: "I've noticed that the most vibrant neighborhoods I've been to are the most diverse ones.", chinese: "我注意到我去過的最充滿活力的社區是最多元化的。", vocabulary: [{ word: "vibrant", definition: "充滿活力的；生動的" }] },
          { speaker: 'b', english: "Different food, languages, art, celebrations — it enriches daily life.", chinese: "不同的食物、語言、藝術、慶典——它豐富了日常生活。", vocabulary: [{ word: "enrich", definition: "豐富；使充實" }] },
          { speaker: 'a', english: "But diversity also requires effort. You have to actively work to understand each other.", chinese: "但多樣性也需要努力，你必須主動努力去理解彼此。", vocabulary: [] },
          { speaker: 'b', english: "Inclusion doesn't happen automatically. It requires intentional design and openness.", chinese: "包容不會自動發生，它需要刻意的設計和開放的態度。", vocabulary: [{ word: "inclusion", definition: "包容；納入" }] },
          { speaker: 'a', english: "I think curiosity is the key — being genuinely curious about people who are different from you.", chinese: "我認為好奇心是關鍵——真正對與你不同的人感到好奇。", vocabulary: [{ word: "curiosity", definition: "好奇心" }] },
          { speaker: 'b', english: "Curiosity leads to conversation, and conversation leads to understanding.", chinese: "好奇心帶來對話，對話帶來理解。", vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Bridging Social Divides',
        lines: [
          { speaker: 'a', english: "There's a concept called bridging capital — building connections across social groups.", chinese: "有一個概念叫做橋接資本——在不同社會群體之間建立連結。", vocabulary: [{ word: "bridging capital", definition: "橋接資本（跨群體連結）" }] },
          { speaker: 'b', english: "As opposed to bonding capital — deep connections within your own group.", chinese: "相對於結合資本——在你自己群體內的深厚連結。", vocabulary: [{ word: "bonding capital", definition: "結合資本（群體內連結）" }] },
          { speaker: 'a', english: "Both are important, but bridging is what prevents communities from becoming fragmented.", chinese: "兩者都重要，但橋接才是防止社群變得碎片化的因素。", vocabulary: [{ word: "fragmented", definition: "碎片化的；分裂的" }] },
          { speaker: 'b', english: "Social bubbles are real. We often only interact with people just like us.", chinese: "社交泡泡是真實存在的，我們常常只與和自己相似的人互動。", vocabulary: [{ word: "social bubble", definition: "社交泡泡；同溫層" }] },
          { speaker: 'a', english: "Deliberately seeking out conversations with people outside your circle is valuable.", chinese: "刻意尋找與你圈子之外的人對話是很有價值的。", vocabulary: [{ word: "deliberately", definition: "刻意地；故意地" }] },
          { speaker: 'b', english: "Community events that bring different groups together are powerful for this.", chinese: "能將不同群體聚集在一起的社群活動對此非常有力。", vocabulary: [] },
          { speaker: 'a', english: "Like community potlucks, cultural festivals, or neighborhood sports leagues.", chinese: "比如社群百樂餐、文化節或社區運動聯盟。", vocabulary: [{ word: "potluck", definition: "百樂餐；各自帶菜的聚會" }] },
          { speaker: 'b', english: "Shared meals and games break down barriers in ways that formal events can't.", chinese: "共享餐食和遊戲能以正式活動無法做到的方式打破隔閡。", vocabulary: [{ word: "break down barriers", definition: "打破隔閡；消除障礙" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Conflict Resolution in Communities',
        lines: [
          { speaker: 'a', english: "Even close communities experience conflict. How should communities handle it?", chinese: "即使是關係密切的社群也會經歷衝突，社群應該如何處理？", vocabulary: [{ word: "conflict resolution", definition: "衝突解決" }] },
          { speaker: 'b', english: "With transparency and a willingness to hear all sides. Silence only makes things worse.", chinese: "以透明度和傾聽各方的意願，沉默只會讓事情更糟。", vocabulary: [{ word: "transparency", definition: "透明度" }] },
          { speaker: 'a', english: "Restorative practices are interesting — they focus on healing relationships, not punishing.", chinese: "修復性做法很有趣——它們關注修復關係，而不是懲罰。", vocabulary: [{ word: "restorative practices", definition: "修復性做法" }] },
          { speaker: 'b', english: "I've read about restorative circles in schools that helped kids work through disputes.", chinese: "我讀過關於學校中修復圈的內容，它幫助孩子們解決糾紛。", vocabulary: [{ word: "restorative circle", definition: "修復圈" }] },
          { speaker: 'a', english: "The same principles work in neighborhoods and workplaces.", chinese: "同樣的原則也適用於社區和工作場所。", vocabulary: [] },
          { speaker: 'b', english: "It requires a facilitator — someone neutral who guides the conversation.", chinese: "這需要一位引導者——一個引導對話的中立人士。", vocabulary: [{ word: "facilitator", definition: "引導者；調解人" }] },
          { speaker: 'a', english: "The goal isn't to win, but to restore trust and find a path forward together.", chinese: "目標不是要贏，而是要恢復信任並共同找到前進的道路。", vocabulary: [{ word: "restore trust", definition: "恢復信任" }] },
          { speaker: 'b', english: "That's a much more sustainable model than punishment or avoidance.", chinese: "那是比懲罰或迴避更可持續的模式。", vocabulary: [{ word: "sustainable", definition: "可持續的；可維持的" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Inclusive Community Design',
        lines: [
          { speaker: 'a', english: "Have you thought about how physical spaces affect community cohesion?", chinese: "你有沒有想過實體空間如何影響社群凝聚力？", vocabulary: [{ word: "cohesion", definition: "凝聚力；團結" }] },
          { speaker: 'b', english: "Urban design matters so much. Places with plazas and parks encourage people to gather.", chinese: "城市設計非常重要，有廣場和公園的地方鼓勵人們聚集。", vocabulary: [{ word: "urban design", definition: "城市設計" }] },
          { speaker: 'a', english: "Walkable neighborhoods also create natural opportunities for interaction.", chinese: "適合步行的社區也創造了自然的互動機會。", vocabulary: [{ word: "walkable", definition: "適合步行的" }] },
          { speaker: 'b', english: "When everything is car-dependent, you lose those spontaneous encounters.", chinese: "當一切都依賴汽車時，你就失去了那些自然發生的相遇。", vocabulary: [{ word: "spontaneous", definition: "自然發生的；自發的" }] },
          { speaker: 'a', english: "Inclusive design also means ensuring disabled people and elderly can fully participate.", chinese: "包容性設計也意味著確保殘障人士和老年人能夠充分參與。", vocabulary: [{ word: "inclusive design", definition: "包容性設計" }] },
          { speaker: 'b', english: "And affordable spaces — if only wealthy people can afford to live somewhere, you lose diversity.", chinese: "還有負擔得起的空間——如果只有富人才能負擔得起住在某地，你就失去了多樣性。", vocabulary: [{ word: "affordable", definition: "負擔得起的；合理的" }] },
          { speaker: 'a', english: "Gentrification is such a complex issue. It can revitalize but also displace.", chinese: "士紳化是個非常複雜的議題，它可以使地區活化，但也會造成流離失所。", vocabulary: [{ word: "gentrification", definition: "士紳化；仕紳化" }] },
          { speaker: 'b', english: "Keeping long-time residents involved in planning decisions is crucial.", chinese: "讓長期居民參與規劃決策至關重要。", vocabulary: [{ word: "long-time residents", definition: "長期居民" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Celebrating Community Identity',
        lines: [
          { speaker: 'a', english: "Every community has its own identity — things that make it unique and special.", chinese: "每個社群都有自己的身份認同——讓它獨特而特別的東西。", vocabulary: [{ word: "identity", definition: "身份認同；特質" }] },
          { speaker: 'b', english: "Like local food traditions, festivals, street art, or community sports teams.", chinese: "比如本地的飲食傳統、節慶、街頭藝術或社區運動隊。", vocabulary: [] },
          { speaker: 'a', english: "Celebrating these things creates a sense of pride and belonging.", chinese: "慶祝這些事情創造了一種自豪感和歸屬感。", vocabulary: [{ word: "sense of belonging", definition: "歸屬感" }] },
          { speaker: 'b', english: "When I moved to a new city, local events were how I started feeling at home.", chinese: "當我搬到一個新城市時，本地活動是讓我開始感覺像家的方式。", vocabulary: [] },
          { speaker: 'a', english: "Shared celebrations are powerful anchors for community identity.", chinese: "共同的慶典是社群身份認同的有力錨點。", vocabulary: [{ word: "anchor", definition: "錨點；穩定力量" }] },
          { speaker: 'b', english: "Even small things like a neighborhood mural or a local market create that connection.", chinese: "即使是社區壁畫或在地市集這樣的小事也能創造那種連結。", vocabulary: [{ word: "mural", definition: "壁畫" }] },
          { speaker: 'a', english: "I think documenting and sharing community stories is really valuable too.", chinese: "我認為記錄和分享社群故事也非常有價值。", vocabulary: [{ word: "documenting", definition: "記錄；文獻化" }] },
          { speaker: 'b', english: "Communities with strong identities are more resilient when things get hard.", chinese: "有強烈身份認同的社群在困難時期更有韌性。", vocabulary: [{ word: "resilient", definition: "有韌性的；能復原的" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "bridging capital", meaning: "橋接資本（跨群體連結）" },
      { phrase: "social bubble", meaning: "社交泡泡；同溫層" },
      { phrase: "break down barriers", meaning: "打破隔閡；消除障礙" },
      { phrase: "restorative practices", meaning: "修復性做法" },
      { phrase: "inclusive design", meaning: "包容性設計" },
      { phrase: "sense of belonging", meaning: "歸屬感" },
      { phrase: "community cohesion", meaning: "社群凝聚力" },
      { phrase: "restore trust", meaning: "恢復信任" },
      { phrase: "gentrification", meaning: "士紳化" },
      { phrase: "resilient", meaning: "有韌性的；能復原的" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 5,
    date: '2026-11-13',
    theme: 'Community & Giving Back',
    title: 'Technology for Social Good',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Digital Tools for Community',
        lines: [
          { speaker: 'a', english: "Technology has really changed how communities organize and connect.", chinese: "科技真的改變了社群組織和連結的方式。", vocabulary: [] },
          { speaker: 'b', english: "Neighborhood apps let residents report issues, share resources, and warn each other about safety.", chinese: "社區應用程式讓居民能夠回報問題、分享資源並互相提醒安全事項。", vocabulary: [{ word: "neighborhood app", definition: "社區應用程式" }] },
          { speaker: 'a', english: "I use a local community platform to find people who can lend tools or share skills.", chinese: "我使用一個在地社群平台尋找可以借用工具或分享技能的人。", vocabulary: [{ word: "platform", definition: "平台" }] },
          { speaker: 'b', english: "That's the sharing economy applied to community — it reduces waste and builds connections.", chinese: "那是應用於社群的共享經濟——它減少浪費並建立連結。", vocabulary: [{ word: "sharing economy", definition: "共享經濟" }] },
          { speaker: 'a', english: "Crowdfunding platforms have also enabled communities to raise money for local causes.", chinese: "眾籌平台也讓社群能夠為在地公益募款。", vocabulary: [{ word: "crowdfunding", definition: "眾籌；群眾募資" }] },
          { speaker: 'b', english: "I saw a community raised funds online to save their local library from closing.", chinese: "我看到一個社群在線上募款來拯救他們的在地圖書館免於關閉。", vocabulary: [] },
          { speaker: 'a', english: "That's technology enabling local action — not replacing human connection, but supporting it.", chinese: "那是科技賦能在地行動——不是取代人際連結，而是支持它。", vocabulary: [{ word: "enable", definition: "賦能；使能夠" }] },
          { speaker: 'b', english: "The tech is just a tool. What matters is the intention and energy behind it.", chinese: "科技只是工具，重要的是背後的意圖和能量。", vocabulary: [{ word: "intention", definition: "意圖；目的" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Online Communities and Their Impact',
        lines: [
          { speaker: 'a', english: "Online communities have grown enormously. Do they count as real communities?", chinese: "線上社群已大幅增長，它們算是真正的社群嗎？", vocabulary: [{ word: "enormously", definition: "巨大地；非常地" }] },
          { speaker: 'b', english: "I think yes — when they're built around shared purpose and genuine support.", chinese: "我認為算——當它們建立在共同目的和真誠支持的基礎上時。", vocabulary: [{ word: "shared purpose", definition: "共同目的" }] },
          { speaker: 'a', english: "I'm part of an online support group for caregivers. It's incredibly meaningful to me.", chinese: "我是一個照護者線上支持群組的成員，對我來說意義非凡。", vocabulary: [{ word: "caregiver", definition: "照護者；看護" }] },
          { speaker: 'b', english: "There are people in that group you might never meet, but they understand your experience.", chinese: "那個群組裡有些人你可能永遠不會見面，但他們理解你的經歷。", vocabulary: [] },
          { speaker: 'a', english: "The internet has allowed niche communities to form that couldn't exist locally.", chinese: "網路讓小眾社群得以形成，而這些社群在地方上是無法存在的。", vocabulary: [{ word: "niche", definition: "小眾；利基" }] },
          { speaker: 'b', english: "People with rare illnesses, unique hobbies, or specific life experiences can find their tribe online.", chinese: "患有罕見疾病、有獨特愛好或特定人生經歷的人可以在網路上找到他們的夥伴。", vocabulary: [{ word: "tribe", definition: "部落；同類人群" }] },
          { speaker: 'a', english: "Though we should be careful about echo chambers — staying only with people who agree.", chinese: "不過我們要小心迴音室效應——只待在同意你的人身邊。", vocabulary: [{ word: "echo chamber", definition: "迴音室；同溫層" }] },
          { speaker: 'b', english: "Online and offline communities both need diversity of thought to stay healthy.", chinese: "線上和線下社群都需要思想多樣性才能保持健康。", vocabulary: [{ word: "diversity of thought", definition: "思想多樣性" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Tech Solutions for Social Problems',
        lines: [
          { speaker: 'a', english: "Some innovators are using tech specifically to solve social problems.", chinese: "一些創新者正在使用科技專門解決社會問題。", vocabulary: [{ word: "innovator", definition: "創新者" }] },
          { speaker: 'b', english: "Like apps that connect surplus food from restaurants to people who need it.", chinese: "比如將餐廳剩餘食物與需要的人連結起來的應用程式。", vocabulary: [{ word: "surplus food", definition: "剩餘食物；多餘的食物" }] },
          { speaker: 'a', english: "Or platforms that match volunteers with local nonprofits in real time.", chinese: "或者即時將義工與在地非營利組織配對的平台。", vocabulary: [{ word: "in real time", definition: "即時；實時" }] },
          { speaker: 'b', english: "There are even AI tools being used to identify areas where people need support most.", chinese: "甚至有 AI 工具被用來識別最需要支援的地區。", vocabulary: [] },
          { speaker: 'a', english: "That could be powerful if it's designed with privacy and equity in mind.", chinese: "如果在設計時考慮隱私和公平性，那可能很有力量。", vocabulary: [{ word: "equity", definition: "公平；公正" }] },
          { speaker: 'b', english: "The risk is that tech solutions can feel cold and impersonal for vulnerable people.", chinese: "風險在於科技解決方案對脆弱的人來說可能感覺冷漠和缺乏人情味。", vocabulary: [{ word: "impersonal", definition: "缺乏人情味的；非個人的" }] },
          { speaker: 'a', english: "That's why human-centered design is so important — keep people at the center.", chinese: "這就是為什麼以人為本的設計如此重要——把人放在中心。", vocabulary: [{ word: "human-centered design", definition: "以人為本的設計" }] },
          { speaker: 'b', english: "Tech is a means, not an end. The goal is still human flourishing.", chinese: "科技是手段，不是目的，目標仍然是人類的繁榮。", vocabulary: [{ word: "flourishing", definition: "繁榮；蓬勃發展" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Digital Divides and Access',
        lines: [
          { speaker: 'a', english: "Not everyone has equal access to technology, which creates new inequalities.", chinese: "不是每個人都能平等獲得科技，這製造了新的不平等。", vocabulary: [{ word: "digital divide", definition: "數位落差" }] },
          { speaker: 'b', english: "The digital divide is real. Older adults, rural communities, and low-income families often miss out.", chinese: "數位落差是真實存在的，老年人、農村社群和低收入家庭往往被排除在外。", vocabulary: [{ word: "rural", definition: "農村的；鄉村的" }] },
          { speaker: 'a', english: "So community organizations working on digital access are doing critically important work.", chinese: "所以致力於數位普及的社群組織在做非常重要的工作。", vocabulary: [{ word: "digital access", definition: "數位普及；數位使用權" }] },
          { speaker: 'b', english: "Teaching digital literacy is another crucial piece — access alone isn't enough.", chinese: "教授數位素養是另一個關鍵部分——僅有使用機會是不夠的。", vocabulary: [{ word: "digital literacy", definition: "數位素養" }] },
          { speaker: 'a', english: "I volunteer at a community center teaching seniors how to use video calling apps.", chinese: "我在社區中心當義工，教長者如何使用視訊通話應用程式。", vocabulary: [] },
          { speaker: 'b', english: "That's so meaningful. Connecting seniors with family online can really improve their wellbeing.", chinese: "那非常有意義，讓長者在網路上與家人連結真的可以改善他們的幸福感。", vocabulary: [] },
          { speaker: 'a', english: "One of them told me that calling her daughter's family every week changed everything for her.", chinese: "其中一位告訴我，每週與女兒一家視訊通話改變了她的一切。", vocabulary: [] },
          { speaker: 'b', english: "Stories like that remind me why bridging the digital divide actually matters.", chinese: "這樣的故事提醒我為什麼彌合數位落差真的很重要。", vocabulary: [{ word: "bridge the digital divide", meaning: "彌合數位落差" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'Looking Ahead: Tech and Community',
        lines: [
          { speaker: 'a', english: "Where do you see the relationship between technology and community going in the future?", chinese: "你認為未來科技與社群之間的關係會走向何方？", vocabulary: [] },
          { speaker: 'b', english: "I hope we use tech to enhance human connection, not replace it.", chinese: "我希望我們用科技來增強人際連結，而不是取代它。", vocabulary: [{ word: "enhance", definition: "增強；提升" }] },
          { speaker: 'a', english: "The pandemic showed us how much we crave in-person connection even with all our digital tools.", chinese: "疫情讓我們看到即使有所有數位工具，我們多麼渴望面對面的連結。", vocabulary: [{ word: "crave", definition: "渴望；強烈需要" }] },
          { speaker: 'b', english: "I think hybrid models work best — using tech as infrastructure, but keeping the human center.", chinese: "我認為混合模式效果最好——用科技作為基礎設施，但保持人的核心。", vocabulary: [{ word: "hybrid model", definition: "混合模式" }] },
          { speaker: 'a', english: "Communities that leverage technology without losing their humanity will thrive.", chinese: "能夠利用科技而不失去人性的社群將會蓬勃發展。", vocabulary: [{ word: "leverage", definition: "利用；運用" }] },
          { speaker: 'b', english: "And we all have a role in shaping what that looks like.", chinese: "我們都在塑造那個樣貌中扮演著角色。", vocabulary: [] },
          { speaker: 'a', english: "Being intentional about how we use technology — especially social media — is part of giving back.", chinese: "有意識地使用科技——尤其是社群媒體——是回饋的一部分。", vocabulary: [] },
          { speaker: 'b', english: "Using our digital presence for good, not just scrolling — that's community too.", chinese: "用我們的數位存在做好事，不只是滑手機——那也是社群。", vocabulary: [{ word: "digital presence", definition: "數位存在；線上形象" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "digital divide", meaning: "數位落差" },
      { phrase: "digital literacy", meaning: "數位素養" },
      { phrase: "sharing economy", meaning: "共享經濟" },
      { phrase: "echo chamber", meaning: "迴音室；同溫層" },
      { phrase: "human-centered design", meaning: "以人為本的設計" },
      { phrase: "crowdfunding", meaning: "眾籌；群眾募資" },
      { phrase: "bridge the digital divide", meaning: "彌合數位落差" },
      { phrase: "hybrid model", meaning: "混合模式" },
      { phrase: "surplus food", meaning: "剩餘食物" },
      { phrase: "digital presence", meaning: "數位存在；線上形象" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 6,
    date: '2026-11-14',
    theme: 'Community & Giving Back',
    title: 'Generations of Service',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Learning from Elders',
        lines: [
          { speaker: 'a', english: "There's so much we can learn from older generations about community and service.", chinese: "關於社群和服務，我們可以從老一輩身上學到很多。", vocabulary: [{ word: "elder", definition: "長者；前輩" }] },
          { speaker: 'b', english: "My grandparents' generation had this deep sense of communal obligation — you helped because it was simply the right thing.", chinese: "我祖父母那一代有一種深刻的共同義務感——你幫忙是因為那就是對的事。", vocabulary: [{ word: "communal obligation", definition: "共同義務；集體責任" }] },
          { speaker: 'a', english: "Less transactional. They weren't thinking about what they'd get in return.", chinese: "不那麼交換性的，他們不考慮自己能得到什麼回報。", vocabulary: [{ word: "transactional", definition: "交換性的；交易性的" }] },
          { speaker: 'b', english: "Oral histories of communities show how people used to pool resources during hard times.", chinese: "社群的口述歷史顯示了人們過去在艱難時期如何共同分享資源。", vocabulary: [{ word: "oral history", definition: "口述歷史" }] },
          { speaker: 'a', english: "Barn-raising, harvest sharing, helping neighbors rebuild after disaster.", chinese: "建穀倉、分享收穫、幫助鄰居在災後重建。", vocabulary: [{ word: "barn-raising", definition: "集體建穀倉（社區合作傳統）" }] },
          { speaker: 'b', english: "That collective spirit is less visible today, but it's still there when crises happen.", chinese: "那種集體精神在今天不那麼明顯，但在危機發生時它仍然存在。", vocabulary: [{ word: "collective spirit", definition: "集體精神" }] },
          { speaker: 'a', english: "I've seen communities come together beautifully after natural disasters.", chinese: "我見過社群在自然災害後美麗地團結起來。", vocabulary: [] },
          { speaker: 'b', english: "Adversity has a way of reminding us of our interdependence.", chinese: "逆境讓我們想起我們的相互依存關係。", vocabulary: [{ word: "interdependence", definition: "相互依存" }] },
        ],
      },
      {
        partNumber: 2,
        title: 'Intergenerational Programs',
        lines: [
          { speaker: 'a', english: "Intergenerational programs that connect young and old are really impactful.", chinese: "將年輕人和老年人連結在一起的代際計畫真的很有影響力。", vocabulary: [{ word: "intergenerational", definition: "代際的；跨世代的" }] },
          { speaker: 'b', english: "I've heard of programs where seniors mentor teenagers in career skills.", chinese: "我聽說過長者指導青少年職業技能的計畫。", vocabulary: [] },
          { speaker: 'a', english: "And reverse mentorship where young people teach seniors about technology.", chinese: "還有反向指導，年輕人教長者使用科技。", vocabulary: [{ word: "reverse mentorship", definition: "反向指導" }] },
          { speaker: 'b', english: "Both sides benefit enormously. Seniors gain connection and purpose, youth gain wisdom.", chinese: "雙方都獲益匪淺，長者獲得連結和使命感，年輕人獲得智慧。", vocabulary: [] },
          { speaker: 'a', english: "Loneliness is actually a major health issue among the elderly. Social connection is medicine.", chinese: "孤獨感實際上是老年人的主要健康問題，社交連結就是良藥。", vocabulary: [{ word: "loneliness", definition: "孤獨；孤立感" }] },
          { speaker: 'b', english: "And young people today often feel disconnected from heritage and lived experience.", chinese: "而今天的年輕人常常感覺與傳承和生活經驗脫節。", vocabulary: [{ word: "heritage", definition: "傳承；遺產" }] },
          { speaker: 'a', english: "Having wise, experienced adults in their lives gives them roots and perspective.", chinese: "在生命中有智慧、有經驗的成年人給了他們根基和視角。", vocabulary: [] },
          { speaker: 'b', english: "Communities that honor their elders are communities that know who they are.", chinese: "尊重長者的社群是知道自己是誰的社群。", vocabulary: [{ word: "honor", definition: "尊重；尊敬" }] },
        ],
      },
      {
        partNumber: 3,
        title: 'Passing Down Skills and Traditions',
        lines: [
          { speaker: 'a', english: "One of the most meaningful forms of giving back is passing down knowledge.", chinese: "最有意義的回饋形式之一是傳授知識。", vocabulary: [{ word: "pass down", definition: "傳承；傳授" }] },
          { speaker: 'b', english: "Think of master craftspeople who take apprentices and keep traditional skills alive.", chinese: "想想那些收徒弟並保持傳統技藝存活的工藝大師。", vocabulary: [{ word: "apprentice", definition: "學徒" }] },
          { speaker: 'a', english: "Or grandparents teaching grandchildren to cook traditional recipes.", chinese: "或者祖父母教孫子烹飪傳統食譜。", vocabulary: [] },
          { speaker: 'b', english: "Those moments of transmission are so precious and increasingly rare.", chinese: "那些傳授的時刻是如此珍貴，且越來越稀少。", vocabulary: [{ word: "transmission", definition: "傳授；傳遞" }] },
          { speaker: 'a', english: "I learned how to make dumplings from my grandmother. I treasure that more than anything.", chinese: "我從祖母那裡學到了如何包餃子，我比任何事都珍視那段記憶。", vocabulary: [{ word: "treasure", definition: "珍視；珍惜" }] },
          { speaker: 'b', english: "It's not just the recipe — it's the stories, the laughter, the sense of continuity.", chinese: "不只是食譜——是故事、笑聲、那種連續感。", vocabulary: [{ word: "continuity", definition: "連續性；延續" }] },
          { speaker: 'a', english: "Documenting these traditions — through video, writing, archives — preserves them for future generations.", chinese: "記錄這些傳統——通過影片、寫作、檔案——為後代保存它們。", vocabulary: [{ word: "archive", definition: "檔案；存檔" }] },
          { speaker: 'b', english: "Every family and community is a living archive. We should treat it that way.", chinese: "每個家庭和社群都是一個活生生的檔案館，我們應該這樣對待它。", vocabulary: [{ word: "living archive", definition: "活的檔案館" }] },
        ],
      },
      {
        partNumber: 4,
        title: 'Youth Leading the Way',
        lines: [
          { speaker: 'a', english: "We talked about learning from elders, but young people are also driving so much change.", chinese: "我們談到了向長者學習，但年輕人也在推動很多改變。", vocabulary: [] },
          { speaker: 'b', english: "Climate activism, social justice movements — young voices are urgent and necessary.", chinese: "氣候行動主義、社會正義運動——年輕人的聲音是迫切且必要的。", vocabulary: [{ word: "urgent", definition: "迫切的；緊迫的" }] },
          { speaker: 'a', english: "Every generation inherits problems and has to figure out what to do with them.", chinese: "每一代人都繼承問題，並且必須想清楚如何應對。", vocabulary: [{ word: "inherit", definition: "繼承；遺傳" }] },
          { speaker: 'b', english: "What I admire is when different generations collaborate rather than clash.", chinese: "我欽佩的是不同世代合作而不是衝突的時候。", vocabulary: [{ word: "collaborate", definition: "合作；協作" }] },
          { speaker: 'a', english: "Elders bringing wisdom and networks, youth bringing energy and fresh perspectives.", chinese: "長者帶來智慧和人脈，年輕人帶來能量和新鮮視角。", vocabulary: [] },
          { speaker: 'b', english: "That combination is incredibly powerful. Movements need both.", chinese: "那種結合非常有力量，運動需要兩者。", vocabulary: [] },
          { speaker: 'a', english: "I feel hopeful when I see young people caring deeply about the communities they're inheriting.", chinese: "當我看到年輕人深深關心他們所繼承的社群時，我感到充滿希望。", vocabulary: [{ word: "hopeful", definition: "充滿希望的；樂觀的" }] },
          { speaker: 'b', english: "And they're not just talking — they're organizing, creating, and doing.", chinese: "而且他們不只是在說——他們在組織、創造和行動。", vocabulary: [] },
        ],
      },
      {
        partNumber: 5,
        title: 'A Legacy of Service',
        lines: [
          { speaker: 'a', english: "What kind of legacy do you want to leave in your community?", chinese: "你想在你的社群中留下什麼樣的遺產？", vocabulary: [] },
          { speaker: 'b', english: "I want people to say I was generous with my time and made others feel welcome.", chinese: "我希望人們說我在時間上很慷慨，讓別人感到受歡迎。", vocabulary: [{ word: "generous", definition: "慷慨的；大方的" }] },
          { speaker: 'a', english: "That's a beautiful legacy. Not about status or achievement, but about kindness.", chinese: "那是個美好的遺產，不是關於地位或成就，而是關於善良。", vocabulary: [] },
          { speaker: 'b', english: "I also hope to mentor a few people who go on to do meaningful work.", chinese: "我也希望指導幾個人，讓他們繼續做有意義的工作。", vocabulary: [] },
          { speaker: 'a', english: "The chain of service — being mentored, then mentoring others — that's how communities grow.", chinese: "服務的鏈條——被指導，然後指導他人——這就是社群成長的方式。", vocabulary: [{ word: "chain of service", definition: "服務的鏈條" }] },
          { speaker: 'b', english: "No one builds community alone. It's always a collective effort across time.", chinese: "沒有人能獨自建立社群，它始終是跨越時間的集體努力。", vocabulary: [{ word: "collective effort", definition: "集體努力" }] },
          { speaker: 'a', english: "I love that idea — community as something we inherit and pass forward.", chinese: "我喜歡那個想法——社群是我們繼承並傳遞下去的東西。", vocabulary: [] },
          { speaker: 'b', english: "We're all stewards of the communities we live in. What a responsibility and privilege.", chinese: "我們都是所居住社群的守護者，這是多麼大的責任和榮幸。", vocabulary: [{ word: "steward", definition: "守護者；管理者" }] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "intergenerational", meaning: "代際的；跨世代的" },
      { phrase: "reverse mentorship", meaning: "反向指導" },
      { phrase: "chain of service", meaning: "服務的鏈條" },
      { phrase: "collective effort", meaning: "集體努力" },
      { phrase: "communal obligation", meaning: "共同義務；集體責任" },
      { phrase: "steward", meaning: "守護者；管理者" },
      { phrase: "living archive", meaning: "活的檔案館" },
      { phrase: "interdependence", meaning: "相互依存" },
      { phrase: "pass down", meaning: "傳承；傳授" },
      { phrase: "legacy", meaning: "遺產；留下的影響" },
    ],
  },
  {
    weekNumber: 46,
    dayOfWeek: 7,
    date: '2026-11-15',
    theme: 'Community & Giving Back',
    title: 'This Week\'s Reflections',
    phase: 'p6',
    parts: [
      {
        partNumber: 1,
        title: 'Looking Back on the Week',
        lines: [
          { speaker: 'a', english: "What a week! Community and giving back — it's such a rich topic.", chinese: "真是精彩的一週！社群與回饋——這是個如此豐富的主題。", vocabulary: [] },
          { speaker: 'b', english: "I feel like every conversation this week opened a new door for me.", chinese: "我感覺這週的每次對話都為我打開了一扇新的門。", vocabulary: [] },
          { speaker: 'a', english: "What was most memorable for you from our discussions?", chinese: "我們討論中最讓你印象深刻的是什麼？", vocabulary: [{ word: "memorable", definition: "令人難忘的；值得記憶的" }] },
          { speaker: 'b', english: "The idea that listening itself is a form of giving back — that really shifted something for me.", chinese: "傾聽本身就是一種回饋的想法——這真的改變了我的某些看法。", vocabulary: [] },
          { speaker: 'a', english: "For me it was the helper's high — that giving back is genuinely good for our own health.", chinese: "對我來說是助人高潮——回饋對我們自己的健康真的有好處。", vocabulary: [] },
          { speaker: 'b', english: "So giving back isn't sacrifice — it's actually self-care in disguise.", chinese: "所以回饋不是犧牲——它實際上是偽裝的自我照顧。", vocabulary: [{ word: "self-care in disguise", definition: "偽裝的自我照顧" }] },
          { speaker: 'a', english: "That reframe completely changes the motivation. It's not about obligation.", chinese: "那種重新框架完全改變了動機，它不是關於義務。", vocabulary: [{ word: "reframe", definition: "重新框架；重新詮釋" }] },
          { speaker: 'b', english: "It's about recognizing that our wellbeing is tied to each other's wellbeing.", chinese: "而是認識到我們的幸福與彼此的幸福是相互連結的。", vocabulary: [] },
        ],
      },
      {
        partNumber: 2,
        title: 'Small Actions, Big Impact',
        lines: [
          { speaker: 'a', english: "One thing I want to take away is that you don't have to do grand gestures.", chinese: "我想帶走的一件事是你不必做出宏偉的姿態。", vocabulary: [{ word: "grand gesture", definition: "宏偉的姿態；大動作" }] },
          { speaker: 'b', english: "The accumulation of small, consistent acts of kindness changes communities.", chinese: "小而持續的善舉的積累改變了社群。", vocabulary: [{ word: "accumulation", definition: "積累；累積" }] },
          { speaker: 'a', english: "A smile, a note, a conversation — these things matter more than we think.", chinese: "一個微笑、一張便條、一次對話——這些事情比我們以為的更重要。", vocabulary: [] },
          { speaker: 'b', english: "I wrote that thank-you note to the janitor this week like you mentioned.", chinese: "我這週寫了那張感謝便條給管理員，就像你提到的。", vocabulary: [] },
          { speaker: 'a', english: "That's wonderful! Did you get a response?", chinese: "太棒了！你有得到回應嗎？", vocabulary: [] },
          { speaker: 'b', english: "He thanked me personally in the hallway and said no one had ever done that before.", chinese: "他在走廊親自感謝了我，說以前從來沒有人這樣做過。", vocabulary: [] },
          { speaker: 'a', english: "That single act probably made his whole week. Maybe longer.", chinese: "那個單一行動可能讓他整週都很開心，也許更長。", vocabulary: [] },
          { speaker: 'b', english: "It also made me feel wonderful. That ripple effect is real.", chinese: "它也讓我感覺很棒，那種漣漪效應是真實的。", vocabulary: [] },
        ],
      },
      {
        partNumber: 3,
        title: 'Community as a Practice',
        lines: [
          { speaker: 'a', english: "I've been thinking that community isn't just a noun — it's a verb.", chinese: "我一直在想，社群不只是一個名詞——它是一個動詞。", vocabulary: [] },
          { speaker: 'b', english: "You mean it's something you actively do, not just something you belong to.", chinese: "你的意思是它是你主動去做的事，而不只是你所屬的東西。", vocabulary: [] },
          { speaker: 'a', english: "Exactly. You community by showing up, listening, contributing, connecting.", chinese: "沒錯，你通過出現、傾聽、貢獻、連結來「社群」。", vocabulary: [{ word: "show up", definition: "出現；現身" }] },
          { speaker: 'b', english: "It's a daily practice, not a destination you arrive at.", chinese: "這是一種日常實踐，而不是你到達的目的地。", vocabulary: [{ word: "daily practice", definition: "日常實踐" }] },
          { speaker: 'a', english: "Like any relationship, it requires intention and energy to maintain.", chinese: "就像任何關係一樣，它需要意圖和能量來維護。", vocabulary: [] },
          { speaker: 'b', english: "And it gets easier the more you do it. Habits of giving build on themselves.", chinese: "而且你做得越多就越容易，給予的習慣會不斷積累。", vocabulary: [{ word: "habit", definition: "習慣" }] },
          { speaker: 'a', english: "Starting small is fine. What matters is starting.", chinese: "從小處開始是可以的，重要的是開始。", vocabulary: [] },
          { speaker: 'b', english: "Don't wait until you have more time, more money, more — just start with what you have now.", chinese: "不要等到你有更多時間、更多錢、更多——現在就用你已有的開始。", vocabulary: [] },
        ],
      },
      {
        partNumber: 4,
        title: 'Personal Commitments',
        lines: [
          { speaker: 'a', english: "What's one concrete commitment you're taking from this week?", chinese: "你從這週帶走的一個具體承諾是什麼？", vocabulary: [{ word: "concrete commitment", definition: "具體承諾" }] },
          { speaker: 'b', english: "I'm going to sign up to volunteer at a local literacy program once a month.", chinese: "我打算報名每月一次在當地的識字計畫擔任義工。", vocabulary: [{ word: "literacy program", definition: "識字計畫；閱讀計畫" }] },
          { speaker: 'a', english: "That's fantastic! Teaching reading is such a foundational act of giving.", chinese: "那太棒了！教閱讀是一種如此根本的給予行為。", vocabulary: [] },
          { speaker: 'b', english: "And you? What are you committing to?", chinese: "那你呢？你要承諾什麼？", vocabulary: [] },
          { speaker: 'a', english: "I'm going to reach out to my neighbor I've never properly talked to and introduce myself.", chinese: "我打算主動聯繫我從未正式說過話的鄰居，並自我介紹。", vocabulary: [] },
          { speaker: 'b', english: "Building community starts right there — with the person next door.", chinese: "建立社群就從那裡開始——從隔壁的人開始。", vocabulary: [] },
          { speaker: 'a', english: "And I'm going to keep practicing active listening, especially at home.", chinese: "我還要繼續練習積極傾聽，尤其是在家裡。", vocabulary: [] },
          { speaker: 'b', english: "Accountability helps. Good luck to both of us this week!", chinese: "責任感有幫助，祝我們這週都好運！", vocabulary: [{ word: "accountability", definition: "責任感；當責" }] },
        ],
      },
      {
        partNumber: 5,
        title: 'The Bigger Picture',
        lines: [
          { speaker: 'a', english: "I think this week reminded me of something fundamental about human nature.", chinese: "我認為這週讓我想起了關於人性的一些根本的東西。", vocabulary: [{ word: "fundamental", definition: "根本的；基本的" }] },
          { speaker: 'b', english: "That we're wired for connection and contribution — not just individual survival.", chinese: "我們天生就適合連結和貢獻——不只是個人生存。", vocabulary: [{ word: "wired for", definition: "天生適合；生來就是為了" }] },
          { speaker: 'a', english: "When we give, we're actually expressing something essential about what it means to be human.", chinese: "當我們給予時，我們實際上是在表達關於人的意義的某些本質性的東西。", vocabulary: [{ word: "essential", definition: "本質性的；基本的" }] },
          { speaker: 'b', english: "Belonging to something bigger than yourself is one of the deepest human needs.", chinese: "屬於比你自己更大的事物是人類最深層的需求之一。", vocabulary: [] },
          { speaker: 'a', english: "Community is how we meet that need — imperfectly, but persistently.", chinese: "社群是我們滿足那種需求的方式——不完美地，但持續地。", vocabulary: [{ word: "persistently", definition: "持續地；堅持地" }] },
          { speaker: 'b', english: "I feel grateful to be part of communities — this learning community included.", chinese: "我很感激成為社群的一部分——包括這個學習社群。", vocabulary: [] },
          { speaker: 'a', english: "Our weekly conversations are their own little community, aren't they?", chinese: "我們每週的對話是它自己的小社群，不是嗎？", vocabulary: [] },
          { speaker: 'b', english: "They really are. See you next week for more good conversations.", chinese: "真的是，下週見，繼續更多精彩的對話。", vocabulary: [] },
        ],
      },
    ],
    keyPhrases: [
      { phrase: "community as a verb", meaning: "社群作為動詞（主動實踐社群）" },
      { phrase: "daily practice", meaning: "日常實踐" },
      { phrase: "wired for connection", meaning: "天生適合連結" },
      { phrase: "concrete commitment", meaning: "具體承諾" },
      { phrase: "accountability", meaning: "責任感；當責" },
      { phrase: "self-care in disguise", meaning: "偽裝的自我照顧" },
      { phrase: "reframe", meaning: "重新框架；重新詮釋" },
      { phrase: "grand gesture", meaning: "宏偉的姿態；大動作" },
      { phrase: "show up", meaning: "出現；現身" },
      { phrase: "persistently", meaning: "持續地；堅持地" },
    ],
  },
];
