import { Episode } from '../../app/src/data/episode-sample'

export const WEEK_07: Episode[] = [
  {
  weekNumber: 7,
  dayOfWeek: 1,
  date: '2026-02-09',
  theme: 'Weather & Seasons',
  title: 'The Weather Today: Talking About Climate',
  phase: 'p1',
  parts: [
    {
      title: 'Part 1 — Checking the Forecast',
      lines: [
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Mira, did you check the weather forecast this morning? I totally forgot and now I'm standing here with no umbrella.",
          zh: 'Mira，你今天早上有看天氣預報嗎？我完全忘了，現在站在這裡，手上沒有傘。',
          vocab: [{ word: 'forecast', def: '天氣預報' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Ha, I did actually. It said there's a seventy percent chance of afternoon showers. I figured I'd rather be safe, so I grabbed my umbrella on the way out.",
          zh: '哈，我有。說下午有七成機率下陣雨。我想說寧可有備無患，出門就帶了傘。',
          vocab: [{ word: 'showers', def: '（短暫的）陣雨' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "That's so smart. I always mean to check but then I just forget. It's like the moment I wake up, I already know I'm going to be late.",
          zh: '好聰明。我每次都想查，然後就忘了。感覺一睜眼就知道自己要遲到了。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "I know that feeling. I've started keeping a weather app on my lock screen just so I don't even have to open my phone fully. Takes like three seconds.",
          zh: '我懂那種感覺。我現在把天氣 App 放在鎖定畫面，這樣連開手機都不用。三秒鐘就看完了。',
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Oh that's clever. So what's the weather like here most of the year? I know it rains a lot, but what else?",
          zh: '哦，好主意。那這裡一年四季大多是什麼天氣？我知道常常下雨，但還有什麼？',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Well, summers are extremely hot and humid — like, you step outside and you're sweating immediately. Winters are mild, but it can get quite damp and grey for weeks on end.",
          zh: '嗯，夏天超熱又超濕——一走出去就開始流汗。冬天比較溫和，但有時候會連著好幾個禮拜都陰濕灰暗。',
          vocab: [{ word: 'humid', def: '潮濕的' }, { word: 'damp', def: '濕冷的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "That does sound tough. Do you think the weather here has been getting more extreme over the years?",
          zh: '聽起來是挺難熬的。你覺得這裡的天氣這幾年有變得更極端嗎？',
          vocab: [{ word: 'extreme', def: '極端的' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Honestly, I think so. The summers feel longer and hotter than when I was growing up. And the typhoons seem to be stronger too. It's a little unsettling.",
          zh: '說真的，我覺得有。夏天感覺比我小時候更長更熱。颱風好像也越來越強。有點讓人不安。',
          vocab: [{ word: 'unsettling', def: '令人不安的' }],
        },
      ],
    },
    {
      title: 'Part 2 — Favorite Seasons',
      lines: [
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Speaking of seasons — do you have a favorite? I feel like most people here say autumn.",
          zh: '說到季節——你有最喜歡的嗎？我感覺很多人都說秋天。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "You're not wrong — autumn is great. The temperature is just right, not too hot and not too cold. And the sky is actually blue sometimes, which feels like a luxury after summer.",
          zh: '你說的沒錯——秋天很棒。氣溫剛剛好，不太熱也不太冷。而且天空偶爾真的是藍色的，夏天過後感覺像是一種奢侈。',
          vocab: [{ word: 'a luxury', def: '一種奢侈、難得的享受' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Ha! That's a good point. What about you personally?",
          zh: '哈！說得好。那你個人呢？',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Mine would probably be spring, actually. I love when things start blooming again after the grey winter. Plus the weather is still cool enough to walk around without feeling completely exhausted.",
          zh: '我可能是春天。我喜歡灰暗的冬天結束後，萬物重新開始開花的感覺。而且天氣還夠涼，出門走走不會累死。',
          vocab: [{ word: 'blooming', def: '開花、萬物復甦' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "That makes sense. I've always been more of a winter person myself. There's something about cold weather that I find really cozy — you have an excuse to stay in and be warm.",
          zh: '有道理。我自己比較喜歡冬天。冷天有種讓我覺得很舒適的感覺——你有理由待在室內、保持溫暖。',
          vocab: [{ word: 'cozy', def: '溫馨舒適的' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "That's the introvert's dream right there — legitimate reasons to cancel plans because it's cold outside.",
          zh: '那就是內向者的夢想——因為外面冷，有正當理由取消行程。',
          vocab: [{ word: 'legitimate', def: '正當的、合理的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Exactly! I call it 'weather-related social withdrawal' and I stand by it.",
          zh: '沒錯！我稱它為「天氣相關的社交退縮」，我支持這個說法。',
        },
      ],
    },
    {
      title: 'Part 3 — Weather and Mood',
      lines: [
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Do you ever feel like the weather seriously affects your mood? Because I swear, rainy days just drain all my energy.",
          zh: '你有沒有覺得天氣真的會影響你的心情？因為我發誓，下雨天就是會把我的精力全部抽乾。',
          vocab: [{ word: 'drain', def: '耗盡、抽乾（精力）' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Oh, absolutely. There's actually a name for it — 'seasonal mood changes'. A lot of people feel more tired and low during overcast days. You're not imagining it.",
          zh: '噢，絕對有。這其實有個名稱——「季節性情緒變化」。很多人在陰天會感到更疲倦、情緒低落。你不是在想像。',
          vocab: [{ word: 'overcast', def: '陰天的、多雲的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Good to know I'm not alone. What do you do when the weather is bringing you down?",
          zh: '很高興知道不只我這樣。天氣讓你心情低落的時候，你怎麼辦？',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "I try to find things that feel warm and comforting. A big bowl of hot soup, good lighting indoors, maybe some upbeat music. Little things that signal to your brain that everything's okay.",
          zh: '我會找一些讓自己感覺溫暖舒心的事。一大碗熱湯、室內的好燈光，或許再來一點輕快的音樂。一些小事，讓大腦知道一切都沒問題。',
          vocab: [{ word: 'comforting', def: '撫慰人心的、令人感到安慰的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "That's a really healthy approach. I usually just scroll on my phone for two hours and feel worse. Maybe I should try your method.",
          zh: '這個方法真的很健康。我通常就是在手機上滑兩個小時，然後感覺更糟。或許我應該試試你的方法。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Ha, we all do that sometimes. But yeah, I find that if I'm intentional about creating a cozy environment, the rainy day actually becomes kind of nice — like the perfect excuse to slow down.",
          zh: '哈，我們偶爾都會這樣。但我發現，如果我有意識地打造一個舒適的環境，下雨天其實會變得挺好的——就像是放慢腳步的完美理由。',
          vocab: [{ word: 'intentional', def: '有意識的、刻意的' }],
        },
      ],
    },
    {
      title: 'Part 4 — Dealing with Extreme Weather',
      lines: [
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Let's talk about typhoons for a second. How do you usually prepare when a big one is coming?",
          zh: '我們聊一下颱風吧。有大颱風要來的時候，你通常怎麼準備？',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "The first thing I do is stock up on food and water — enough for at least three days. Then I make sure anything on my balcony is secured or brought inside, because the wind can send things flying.",
          zh: '我第一件事是備好食物和水——至少三天份。然後確保陽台上的東西都固定好或搬進室內，因為強風會把東西吹飛。',
          vocab: [{ word: 'stock up on', def: '囤積、備足' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "That's smart. I've heard some people get really excited about typhoon days — like, it's a day off work, so they treat it like a holiday.",
          zh: '很聰明。我聽說有些人對颱風天很興奮——因為不用上班，就把它當假日過。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "I totally get that. There's something a bit thrilling about the whole thing — the wind howling, watching the rain lash against the windows. As long as you're safe inside, it can feel kind of exciting.",
          zh: '我完全懂。整件事有點刺激的感覺——風在嚎叫、看著雨打在窗上。只要你安全待在室內，感覺還挺刺激的。',
          vocab: [{ word: 'lash against', def: '猛打、拍打' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "But it can also be really dangerous, right? Especially for people who live in areas prone to flooding.",
          zh: '但也可以非常危險，對吧？尤其是住在容易淹水地區的人。',
          vocab: [{ word: 'prone to', def: '容易發生…的、傾向於' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Definitely. I think it's important to take the warnings seriously and not be complacent just because you've been through them before. Every typhoon is different.",
          zh: '當然。我覺得認真對待警告很重要，不要因為以前經歷過就掉以輕心。每個颱風都不一樣。',
          vocab: [{ word: 'complacent', def: '自滿的、掉以輕心的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Well said. Better safe than sorry.",
          zh: '說得好。寧可謹慎，不要後悔。',
        },
      ],
    },
    {
      title: 'Part 5 — Dressing for the Weather',
      lines: [
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Okay, last weather topic. Does the weather actually change what you wear, or do you just dress however you feel?",
          zh: '好，最後一個天氣話題。天氣真的會影響你穿什麼嗎，還是你隨心所欲就好？',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Oh, the weather completely dictates my outfits. During summer, it's all about light fabrics and darker colors near the armpits, if you know what I mean.",
          zh: '噢，天氣完全決定了我的穿著。夏天的話，全部都是輕薄的布料，腋下附近選深色，你懂我的意思的。',
          vocab: [{ word: 'dictates', def: '決定、支配' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Ha, the summer office worker struggle is real. What about winter? You mentioned it's not that cold here.",
          zh: '哈，夏天上班族的辛苦是真的。那冬天呢？你說這裡不太冷。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Right, it's not freezing cold like northern countries, but the damp cold here gets into your bones somehow. I layer up — like a base layer, a light sweater, and maybe a jacket.",
          zh: '對，不像北方國家那麼凍，但這裡的濕冷不知為何會滲進骨子裡。我會分層穿——內層、薄毛衣，可能再加一件外套。',
          vocab: [{ word: 'layer up', def: '分層穿衣' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "Layering is the key. I always see people carrying cardigans around in summer too, because of the air conditioning.",
          zh: '分層穿是關鍵。我也常看到夏天有人帶著外套，就是因為冷氣。',
          vocab: [{ word: 'cardigans', def: '開襟毛衣、針織外套' }],
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Oh, the office air con in summer is no joke. I basically have two outfits — one for the scorching heat outside, and one for the arctic tundra that is my workplace.",
          zh: '噢，夏天辦公室的冷氣是認真的。我基本上有兩套穿搭——一套應付外面的炎熱，一套對抗我辦公室這個北極凍原。',
          vocab: [{ word: 'scorching', def: '酷熱的、炙熱的' }],
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "The arctic tundra — that's exactly what it feels like. Maybe we should start a petition for reasonable indoor temperatures.",
          zh: '北極凍原——這正是那種感覺。也許我們該發起一個請願，要求合理的室內溫度。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "I would sign that so fast. But in the meantime, I'll just keep carrying a cardigan everywhere I go.",
          zh: '我會立刻簽名。但在那之前，我只好繼續到哪都帶著外套了。',
        },
        {
          speaker: 'b', speakerName: 'Jamie',
          en: "The eternal struggle of the office worker. Alright, I think I need to go find a vending machine umbrella before those afternoon showers hit.",
          zh: '上班族的永恆掙扎。好了，我想我得去找一把自動販賣機的傘，在下午的陣雨來臨之前。',
        },
        {
          speaker: 'a', speakerName: 'Mira',
          en: "Ha! Good luck. Next time, check the weather app first thing in the morning.",
          zh: '哈！祝你好運。下次，一起床就先看天氣 App。',
        },
      ],
    },
  ],
  keyPhrases: [
    { en: 'rather be safe', zh: '寧可有備無患', example: "I'd rather be safe and bring an umbrella just in case." },
    { en: 'on end', zh: '連續地、一直', example: "It rained for two weeks on end during the rainy season." },
    { en: 'a luxury', zh: '一種難得的享受', example: "Having a clear blue sky in summer feels like a luxury here." },
    { en: 'bringing you down', zh: '讓心情低落', example: "Don't let the bad weather bring you down." },
    { en: 'stock up on', zh: '囤積、備足', example: "We always stock up on food before a typhoon." },
    { en: 'prone to', zh: '容易發生…的', example: "This area is prone to flooding during heavy rain." },
    { en: 'complacent', zh: '掉以輕心的', example: "Don't get complacent — always check the typhoon warnings." },
    { en: 'layer up', zh: '分層穿衣', example: "It's cold in the morning, so make sure you layer up." },
    { en: 'scorching', zh: '酷熱的', example: "The scorching summer heat makes outdoor activities exhausting." },
    { en: 'in the meantime', zh: '在此期間、同時', example: "The solution is coming, but in the meantime, let's stay prepared." },
  ],
  },
  // Day 2
  {
    weekNumber: 7,
    dayOfWeek: 2,
    date: '2026-02-10',
    theme: 'Weather & Seasons',
    title: 'Surviving the Rainy Season',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — When Does Rainy Season Start?',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Jamie, you look a little soggy. Did you get caught in the rain again?", zh: 'Jamie，你看起來有點濕漉漉的。你又被雨淋了嗎？', vocab: [{ word: 'soggy', def: '濕透的、溼軟的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I did. I thought the rain had stopped but I was wrong. This rainy season is relentless.", zh: '是啊。我以為雨停了，但我錯了。這個梅雨季真的不間斷。', vocab: [{ word: 'relentless', def: '持續不斷的、無情的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "When did it start exactly? I feel like it snuck up on us this year.", zh: '到底是什麼時候開始的？我感覺今年它悄悄地就來了。', vocab: [{ word: 'snuck up on', def: '悄悄靠近、出乎意料地到來' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Late May officially, I think. But we started getting heavy rain way before that. The clouds just never fully cleared.", zh: '官方說是五月底，我想。但更早之前就開始下大雨了。雲層從來沒有真正散開過。' },
          { speaker: 'a', speakerName: 'Mira', en: "That's the thing about rainy season here — it's not just rain. It's the humidity that gets to me. Everything feels damp.", zh: '這裡梅雨季的問題不只是雨——濕度才是讓我崩潰的東西。什麼都感覺濕答答的。', vocab: [{ word: 'humidity', def: '濕度、潮濕' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Exactly. My clothes take forever to dry. I've been running the dryer more than ever.", zh: '就是這樣。我的衣服要花很長時間才能乾。我的烘乾機用得比以前多太多了。' },
          { speaker: 'a', speakerName: 'Mira', en: "I've resorted to a dehumidifier indoors. It helps a lot, actually. The air feels less heavy.", zh: '我已經在室內用除濕機了。其實很有用。空氣感覺沒那麼沉重了。', vocab: [{ word: 'dehumidifier', def: '除濕機' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's a good idea. I might need to invest in one before this season completely ruins my sanity.", zh: '好主意。在這個季節徹底摧毀我的理智之前，我可能需要買一台。', vocab: [{ word: 'sanity', def: '理智、神志正常' }] },
        ],
      },
      {
        title: 'Part 2 — Rainy Day Routines',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Do you have any routines that help you get through rainy season? Like coping strategies?", zh: '你有什麼幫助你撐過梅雨季的日常習慣嗎？像是應對策略？', vocab: [{ word: 'coping strategies', def: '應對策略、因應方法' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I try to embrace it rather than fight it. I stock up on good books and podcasts, and I tell myself it's the perfect time to stay in and be productive.", zh: '我嘗試去擁抱它而不是抵抗它。我備好好書和 Podcast，告訴自己這是待在家好好做事的最佳時機。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That's a very glass-half-full way of looking at it. I tend to just feel gloomy.", zh: '這是非常樂觀的看法。我通常就是感覺很陰鬱。', vocab: [{ word: 'gloomy', def: '陰沉的、憂鬱的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Honestly, mindset matters a lot. If you frame it as miserable, it will be. But if you treat rainy season like a built-in slow season, it's more bearable.", zh: '說真的，心態很重要。如果你把它定義為很痛苦，它就會是。但如果你把梅雨季當作內建的慢活季節，就比較能承受。', vocab: [{ word: 'bearable', def: '可承受的、還能忍受的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Built-in slow season. I like that. What about getting to work though? You still have to commute in the rain.", zh: '內建的慢活季節。我喜歡這個說法。但上班怎麼辦？你還是得在雨中通勤。' },
          { speaker: 'a', speakerName: 'Mira', en: "I leave earlier so I'm not rushing. And I always keep a spare umbrella at the office. Oh, and waterproof shoes — non-negotiable.", zh: '我提早出門，這樣就不會很趕。我也在辦公室放一把備用傘。噢，還有防水鞋——這是必要的。', vocab: [{ word: 'non-negotiable', def: '不可商量的、絕對必要的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Waterproof shoes are life-changing. I wore my canvas sneakers last week and regretted it immediately.", zh: '防水鞋真的很改變人生。我上週穿了帆布鞋，立刻後悔。', vocab: [{ word: 'canvas sneakers', def: '帆布鞋' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Oh no. Wet feet are the worst. That feeling of soggy socks all day is genuinely demoralizing.", zh: '噢不。腳濕是最糟的。那種整天穿著濕襪子的感覺真的很消磨鬥志。', vocab: [{ word: 'demoralizing', def: '消磨鬥志的、讓人洩氣的' }] },
        ],
      },
      {
        title: 'Part 3 — Umbrellas and Rain Gear',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Can we talk about umbrellas for a second? I feel like I go through so many of them. I keep losing them.", zh: '我們能聊一下雨傘嗎？我覺得我用掉了好多把。我一直弄丟它們。' },
          { speaker: 'a', speakerName: 'Mira', en: "Same! I think I've lost about six umbrellas this year. They disappear from the umbrella stand at the entrance and I never see them again.", zh: '一樣！我想我今年已經丟了大約六把傘。它們從門口的傘架消失，我再也看不到它們了。' },
          { speaker: 'b', speakerName: 'Jamie', en: "I've started buying slightly nicer umbrellas on purpose, thinking I'll be more careful. But I still lose them.", zh: '我開始故意買稍微好一點的傘，想說這樣我會更小心。但我還是會弄丟。' },
          { speaker: 'a', speakerName: 'Mira', en: "There's actually research showing that the more something costs, the less likely you are to lose it. Your instinct was right, but apparently we override it.", zh: '其實有研究顯示，東西越貴，你越不容易弄丟它。你的直覺是對的，但顯然我們還是克服不了習慣。', vocab: [{ word: 'override', def: '覆蓋、壓過（本能）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's frustrating. What about raincoats? Are they practical for commuting here?", zh: '真令人沮喪。那雨衣呢？在這裡通勤實際嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "They can be. A good lightweight packable raincoat is great. The problem is that it's often too warm to wear one — you end up sweaty inside it.", zh: '可以的。一件好的輕量可收折雨衣很棒。問題是天氣通常太熱，穿不住——你會在裡面流汗。', vocab: [{ word: 'packable', def: '可收折壓縮的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So you're wet either way — from the rain or from sweat.", zh: '所以不管怎樣你都是濕的——要嘛被雨淋，要嘛流汗。' },
          { speaker: 'a', speakerName: 'Mira', en: "That's basically rainy season in a nutshell. There's no perfect solution, just varying degrees of damp.", zh: '這基本上就是梅雨季的縮影。沒有完美的解決方法，只有不同程度的潮濕。', vocab: [{ word: 'in a nutshell', def: '簡而言之、簡單來說' }] },
        ],
      },
      {
        title: 'Part 4 — Mold and Home Maintenance',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "One thing I really dread about rainy season is mold. Have you had any issues with it at home?", zh: '梅雨季我最害怕的一件事是黴菌。你家有沒有遇到這個問題？', vocab: [{ word: 'mold', def: '黴菌' }, { word: 'dread', def: '非常害怕、恐懼' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Oh yes. I found mold in the bathroom last week. It grows so fast when it's humid.", zh: '噢，有。我上週在浴室發現黴菌。天氣潮濕的時候它長得好快。' },
          { speaker: 'a', speakerName: 'Mira', en: "I've started doing a weekly wipe-down of the bathroom walls and keeping the ventilation fan on after showers. It helps prevent it from taking hold.", zh: '我開始每週擦一次浴室牆壁，洗澡後繼續開換氣扇。這有助於防止它生根。', vocab: [{ word: 'take hold', def: '生根、站穩腳跟' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's smart. What about the rest of the apartment? My closet is starting to smell musty.", zh: '很聰明。那公寓其他地方呢？我的衣櫃開始有股霉味了。', vocab: [{ word: 'musty', def: '發霉的、霉味的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Silica gel packets are your best friend. Put them in your closet, your shoe rack, anywhere that gets stuffy. You can also buy reusable moisture absorbers.", zh: '矽膠乾燥劑是你最好的朋友。放在衣櫃裡、鞋架上，任何悶熱的地方。你也可以買可重複使用的除濕盒。', vocab: [{ word: 'silica gel', def: '矽膠乾燥劑' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I've seen those at the convenience store. The ones that fill up with water.", zh: '我在便利商店看過那個。就是那種會積水的。' },
          { speaker: 'a', speakerName: 'Mira', en: "Yes, exactly. It's kind of satisfying to see how much moisture they pull out of the air. And a little alarming too.", zh: '對，就是那個。看著它們從空氣中吸出多少水分，某種程度上還挺有滿足感的。但也有點嚇人。' },
          { speaker: 'b', speakerName: 'Jamie', en: "Right? Like, that water was just floating around in my living room. No wonder everything feels damp.", zh: '對吧？想說那些水就飄在我的客廳裡。難怪什麼都感覺濕。' },
        ],
      },
      {
        title: 'Part 5 — Finding Beauty in the Rain',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Okay, I want to end on a positive note. Is there anything you actually like about rainy season?", zh: '好，我想以正面的方式結束。梅雨季有什麼是你真正喜歡的嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "Honestly, yes. I love the sound of rain at night when I'm already inside. It's one of the most calming sounds in the world to me.", zh: '說真的，有。我喜歡當我已經待在室內時，夜晚的雨聲。對我來說，那是世界上最令人平靜的聲音之一。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That I can agree with. Rain on a rooftop or against a window — there's something almost meditative about it.", zh: '這一點我同意。雨打在屋頂上或窗戶上——有種幾乎像是冥想的感覺。', vocab: [{ word: 'meditative', def: '冥想般的、沉思的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "And everything smells so fresh after a heavy rain. That earthy scent — I think it's called petrichor.", zh: '而且大雨過後，一切聞起來如此清新。那股土壤的氣息——我想它叫做雨後土香（petrichor）。', vocab: [{ word: 'petrichor', def: '雨後土香（雨水落在乾燥地面的氣味）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Petrichor. I love that word. And the air does feel cleaner after rain — like everything's been washed.", zh: 'Petrichor。我喜歡這個詞。雨後空氣確實感覺更清新——就像一切都被洗過了。' },
          { speaker: 'a', speakerName: 'Mira', en: "And there's something cozy about being stuck inside together with people you like. Rainy days are good for long conversations.", zh: '而且和你喜歡的人一起被困在室內有種愜意。下雨天適合長時間的談話。' },
          { speaker: 'b', speakerName: 'Jamie', en: "Like this one! Okay, I'm feeling better about rainy season already. You have a talent for reframing things.", zh: '就像現在這樣！好，我已經對梅雨季感覺好多了。你很擅長重新框架事物。', vocab: [{ word: 'reframing', def: '重新框架、換個角度看待' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's basically my survival skill. When you can't change the weather, you change your perspective on it.", zh: '那基本上是我的生存技能。當你無法改變天氣，就改變你對它的看法。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'snuck up on us', zh: '悄悄地到來', example: "The rainy season snuck up on us before we were ready." },
      { en: 'relentless', zh: '持續不斷的', example: "The relentless rain made it hard to stay motivated." },
      { en: 'coping strategies', zh: '應對策略', example: "Everyone needs coping strategies to get through tough seasons." },
      { en: 'non-negotiable', zh: '絕對必要的', example: "Waterproof shoes are non-negotiable during rainy season." },
      { en: 'in a nutshell', zh: '簡而言之', example: "In a nutshell, there's no perfect solution to staying dry." },
      { en: 'take hold', zh: '生根、蔓延', example: "If you don't ventilate well, mold can quickly take hold." },
      { en: 'musty', zh: '有霉味的', example: "The closet smelled musty after weeks of humidity." },
      { en: 'petrichor', zh: '雨後土香', example: "I love the petrichor after the first heavy rain of the season." },
      { en: 'meditative', zh: '冥想般的', example: "The sound of rain can be quite meditative if you let it be." },
      { en: 'reframing', zh: '重新框架、換個角度', example: "Reframing rainy season as a slow season made it more bearable." },
    ],
  },

  // Day 3
  {
    weekNumber: 7,
    dayOfWeek: 3,
    date: '2026-02-11',
    theme: 'Weather & Seasons',
    title: 'How Weather Shapes Culture',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — Weather and Architecture',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Have you ever thought about how much weather shapes the way a culture builds things? Like, architecture is so tied to climate.", zh: '你有沒有想過天氣對一個文化建造事物的方式影響有多大？像是建築和氣候的關聯非常緊密。', vocab: [{ word: 'architecture', def: '建築風格、建築學' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's a fascinating point. I never really connected the two before. Can you give me an example?", zh: '這是個很有趣的觀點。我以前從來沒有把這兩個連在一起想過。你能給我一個例子嗎？', vocab: [{ word: 'fascinating', def: '迷人的、非常有趣的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Sure. The wide roof overhangs you see on traditional buildings here? Those are designed to block out the intense summer sun while letting air circulate underneath.", zh: '當然。你在這裡傳統建築上看到的大屋簷？那是設計來遮擋強烈的夏日陽光，同時讓空氣在下方流通。', vocab: [{ word: 'overhangs', def: '屋簷、懸挑' }, { word: 'circulate', def: '流通、循環' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Oh, that's clever. So the architecture is solving a weather problem that people have dealt with for centuries.", zh: '噢，很聰明。所以建築是在解決人們幾個世紀以來一直面對的天氣問題。' },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And in Scandinavian countries, roofs are steeply pitched so snow slides off. The shape of the roof is a direct response to the local climate.", zh: '正是。在北歐國家，屋頂的斜度很陡，這樣雪才能滑落。屋頂的形狀是對當地氣候的直接回應。', vocab: [{ word: 'steeply pitched', def: '坡度很陡的（屋頂）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "What about cities built around water — like Venice? Is that also weather-related?", zh: '那建在水邊的城市呢——像威尼斯？那也和天氣有關嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "More geography than weather, but the two are connected. The lagoon in Venice actually helped moderate the climate there — and it also protected against invaders.", zh: '這更多是地理而不是天氣，但兩者是有關聯的。威尼斯的潟湖其實有助於調節當地氣候——同時也保護免受入侵者攻擊。', vocab: [{ word: 'lagoon', def: '潟湖' }, { word: 'moderate', def: '調節、緩和' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I never thought about cities as being designed around survival. That reframes everything.", zh: '我從來沒有想過城市是圍繞著生存而設計的。這讓我重新看待一切。' },
        ],
      },
      {
        title: 'Part 2 — Food and Seasonal Eating',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "What about food? Does climate influence what a culture eats?", zh: '那食物呢？氣候會影響一個文化吃什麼嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "Massively. Think about spicy food — it's most common in hot climates. Some theories suggest that spiciness helps preserve food and also makes you sweat, which cools you down.", zh: '非常大。想想辛辣食物——它在炎熱氣候中最常見。一些理論認為辣味有助於保存食物，也讓你流汗，讓你涼快下來。', vocab: [{ word: 'preserve', def: '保存、防腐' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So eating spicy food in the tropics is actually practical, not just a preference.", zh: '所以在熱帶吃辛辣食物實際上是實際的，而不只是偏好。', vocab: [{ word: 'tropics', def: '熱帶地區' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And in colder climates, you see a lot of high-calorie, fatty foods — like stews, smoked meats, dairy. These help the body generate heat and store energy.", zh: '就是這樣。在寒冷氣候，你會看到很多高熱量、油脂豐富的食物——像是燉菜、煙燻肉類、乳製品。這些幫助身體產生熱量並儲存能量。', vocab: [{ word: 'stews', def: '燉菜' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "It's like the cuisine is a biological adaptation to the environment.", zh: '就像菜餚是對環境的生物適應。', vocab: [{ word: 'adaptation', def: '適應、適應物' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's a beautiful way to put it. And as globalization spreads food across cultures, we're kind of losing that local adaptation.", zh: '這說法很美。隨著全球化將食物傳播到各個文化，我們在某種程度上正在失去那種地方適應性。', vocab: [{ word: 'globalization', def: '全球化' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Is that a bad thing? I love being able to eat Thai food in January here.", zh: '這是壞事嗎？我喜歡能在這裡一月吃到泰式料理。' },
          { speaker: 'a', speakerName: 'Mira', en: "It's not bad at all — it's just interesting. Our food choices used to be dictated by nature. Now they're dictated by convenience and preference.", zh: '完全不壞——只是很有趣。我們的食物選擇過去被自然界決定。現在則被便利和偏好決定。' },
        ],
      },
      {
        title: 'Part 3 — Clothing and Tradition',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Traditional clothing is another great example. So many cultural garments evolved directly from weather needs.", zh: '傳統服裝是另一個很好的例子。很多文化服裝直接是從天氣需求演變而來的。', vocab: [{ word: 'garments', def: '服裝、衣物' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Like the Japanese yukata? It seems designed for hot, humid summers.", zh: '像日本的浴衣？它看起來是為炎熱潮濕的夏天設計的。', vocab: [{ word: 'yukata', def: '浴衣（日本傳統夏季服裝）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. Loose, lightweight cotton. It lets air flow around the body. Very practical. And the Mongolian deel coat is the opposite — thick and layered for harsh steppe winters.", zh: '正是。寬鬆的輕薄棉布。讓空氣在身體周圍流動。非常實用。而蒙古的 deel 外套則完全相反——厚實且分層，適合嚴酷的草原冬天。', vocab: [{ word: 'steppe', def: '草原（乾燥的大平原）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So traditional dress is like wearable technology — the technology just happened to be fabric.", zh: '所以傳統服裝就像是可穿戴的技術——只是那個技術恰好是布料。' },
          { speaker: 'a', speakerName: 'Mira', en: "I love that framing. And a lot of it was highly engineered — the patterns, the cuts, all optimized for the local environment.", zh: '我喜歡這個框架。其中很多都是高度設計過的——圖案、剪裁，全都針對當地環境優化。', vocab: [{ word: 'optimized', def: '優化的、使達到最佳狀態' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And now fast fashion has replaced most of that. Mass-produced clothes for an average climate that doesn't exist.", zh: '而現在快時尚取代了大部分這些東西。為一個不存在的平均氣候大量生產的衣服。', vocab: [{ word: 'fast fashion', def: '快時尚' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's a pretty sharp observation. Mass market clothes are designed for no specific climate, which is why they're often uncomfortable everywhere.", zh: '這是個非常犀利的觀察。大眾市場的衣服設計不針對任何特定氣候，這就是為什麼它們在每個地方通常都不舒適。', vocab: [{ word: 'sharp', def: '敏銳的、精準的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Maybe I should start shopping with climate in mind rather than just trends.", zh: '也許我應該開始以氣候為考量來購物，而不只是潮流。' },
        ],
      },
      {
        title: 'Part 4 — Work Culture and Weather',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "I've heard that in some countries, the pace of life slows down in summer. Like a siesta culture. Is that weather-driven?", zh: '我聽說在一些國家，夏天的生活節奏會放慢。像是午睡文化。那是受天氣驅動的嗎？', vocab: [{ word: 'siesta', def: '午休、午睡（尤指地中海地區文化）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Absolutely. In Mediterranean countries, the midday heat used to be so intense that working outdoors was dangerous. So people rested and worked earlier in the morning and later in the evening instead.", zh: '絕對是。在地中海國家，正午的炎熱過去非常強烈，在戶外工作很危險。所以人們休息，改在早上更早和晚上更晚工作。', vocab: [{ word: 'Mediterranean', def: '地中海的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That makes so much sense. I wish we had that here in summer. Working from two to four PM when it's thirty-five degrees outside feels unnatural.", zh: '這非常合理。我希望我們夏天這裡也這樣。外面三十五度的時候下午兩點到四點工作感覺很不自然。' },
          { speaker: 'a', speakerName: 'Mira', en: "Honestly same. And research shows that cognitive performance drops significantly in extreme heat. Taking a rest isn't laziness — it's efficiency.", zh: '說真的，我也一樣。而且研究顯示，在極端高溫下認知表現會顯著下降。休息不是懶惰——是效率。', vocab: [{ word: 'cognitive', def: '認知的' } ] },
          { speaker: 'b', speakerName: 'Jamie', en: "I should send that research to my manager. 'I'm not being unproductive — I'm heat-adapting.'", zh: '我應該把那個研究傳給我的主管。「我不是沒有生產力——我在適應高溫。」' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha! Let me know how that goes. But seriously, a lot of companies in hot climates now offer flexible hours for exactly this reason.", zh: '哈！讓我知道結果如何。但說真的，很多熱帶氣候的公司現在就是因為這個原因提供彈性工時。' },
          { speaker: 'b', speakerName: 'Jamie', en: "Working with nature rather than against it. That's basically what all of human civilization learned to do — until air conditioning.", zh: '與自然合作而不是對抗它。這基本上是人類文明學會做的事——直到冷氣出現。', vocab: [{ word: 'civilization', def: '文明' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Air conditioning is probably one of the most culturally disruptive inventions in history. It completely changed where people could live and how they worked.", zh: '冷氣可能是歷史上最具文化顛覆性的發明之一。它完全改變了人們可以在哪裡生活以及如何工作。', vocab: [{ word: 'disruptive', def: '顛覆性的、破壞性的' }] },
        ],
      },
      {
        title: 'Part 5 — Festivals and the Calendar',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "One more way weather shapes culture — festivals. So many traditional celebrations are tied to agricultural seasons.", zh: '天氣影響文化的另一個方式——節日。很多傳統慶典都與農業季節緊密相連。', vocab: [{ word: 'agricultural', def: '農業的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Like harvest festivals? Or things like Thanksgiving?", zh: '像豐收節？或者像感恩節之類的？', vocab: [{ word: 'harvest', def: '收穫、收割' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And Lunar New Year is tied to the end of winter and the hope for a good growing season. Even fireworks at New Year's were originally meant to scare away cold winter spirits.", zh: '正是。農曆新年與冬天的結束和對良好耕作季節的希望有關。甚至新年的煙火最初是為了趕走寒冬的靈魂。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That's amazing. So the calendar itself is basically a map of weather and seasons.", zh: '太神奇了。所以日曆本身基本上就是天氣和季節的地圖。' },
          { speaker: 'a', speakerName: 'Mira', en: "It really is. The original calendar was an agricultural tool — when to plant, when to harvest, when to rest. Everything revolved around the seasons.", zh: '真的是。原始的日曆是一種農業工具——何時播種、何時收割、何時休息。一切都圍繞著季節運轉。', vocab: [{ word: 'revolved around', def: '圍繞著…運轉' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And now our calendars are driven by fiscal quarters and meeting schedules. We've completely disconnected from natural rhythms.", zh: '而現在我們的日曆是由財務季度和會議時程表驅動的。我們已完全與自然節律脫節。', vocab: [{ word: 'fiscal quarters', def: '財務季度' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That disconnection might explain a lot of the anxiety and burnout people feel. We're living against our biology.", zh: '這種脫節可能解釋了很多人感到的焦慮和倦怠。我們在違逆自己的生理本能生活。', vocab: [{ word: 'burnout', def: '職業倦怠、精力耗盡' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Wow. I came in here thinking we were just talking about weather and ended up having a philosophical crisis about civilization.", zh: '哇。我以為我們只是在聊天氣，結果卻對文明產生了哲學危機。', vocab: [{ word: 'philosophical', def: '哲學的、深思熟慮的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's what happens when you start pulling the thread on weather. It connects to everything.", zh: '當你開始拉天氣這條線的時候就是這樣。它和一切都相連。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'connected to', zh: '與…相連、有關聯', example: "Weather is deeply connected to how cultures develop over time." },
      { en: 'biological adaptation', zh: '生物適應', example: "Local cuisine is often a biological adaptation to the climate." },
      { en: 'optimized for', zh: '針對…優化', example: "Traditional clothing was optimized for the local environment." },
      { en: 'revolved around', zh: '圍繞著…', example: "Ancient calendars revolved around the agricultural seasons." },
      { en: 'cognitive performance', zh: '認知表現', example: "Extreme heat can significantly reduce cognitive performance." },
      { en: 'siesta', zh: '午休文化', example: "The siesta tradition arose from the need to avoid midday heat." },
      { en: 'disruptive', zh: '顛覆性的', example: "Air conditioning was one of history's most disruptive inventions." },
      { en: 'pulling the thread', zh: '深入追究、拉線頭', example: "Once you start pulling the thread on climate, everything connects." },
      { en: 'disconnection', zh: '脫節、斷聯', example: "Modern life has created a disconnection from natural rhythms." },
      { en: 'fiscal quarters', zh: '財務季度', example: "Our calendars now follow fiscal quarters rather than seasons." },
    ],
  },

  // Day 4
  {
    weekNumber: 7,
    dayOfWeek: 4,
    date: '2026-02-12',
    theme: 'Weather & Seasons',
    title: 'Climate Anxiety and Everyday Action',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — What Is Climate Anxiety?',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Mira, I read an article this morning about climate anxiety. Apparently it's becoming a real mental health issue for a lot of people.", zh: 'Mira，我今天早上讀了一篇關於氣候焦慮的文章。顯然這對很多人來說正在成為一個真正的心理健康問題。', vocab: [{ word: 'climate anxiety', def: '氣候焦慮' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I've heard about this. It's also called eco-anxiety — a chronic sense of worry or dread about the future of the planet.", zh: '我聽說過這個。它也叫做生態焦慮——一種對地球未來的慢性憂慮或恐懼感。', vocab: [{ word: 'eco-anxiety', def: '生態焦慮' }, { word: 'chronic', def: '慢性的、長期存在的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Do you ever feel it? Like, when you see news about extreme weather events or melting ice caps?", zh: '你有感覺到嗎？像是，當你看到關於極端氣候事件或冰蓋融化的新聞？', vocab: [{ word: 'ice caps', def: '冰蓋、極地冰帽' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Honestly, yes. There are days when reading the news feels genuinely overwhelming. Like the scale of the problem is just too big to wrap your head around.", zh: '說真的，有。有些天讀新聞感覺真的讓人難以承受。就像問題的規模太大，根本無法理解。', vocab: [{ word: 'overwhelming', def: '難以承受的、壓倒性的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's exactly how I feel. And then I feel guilty for going about my normal life when such big things are happening.", zh: '這正是我的感覺。然後我對在這麼大的事情發生時繼續過正常生活感到內疚。', vocab: [{ word: 'guilty', def: '內疚的、罪惡感的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That guilt is part of climate anxiety. And researchers say it can be paralyzing — meaning people feel so hopeless they don't take any action at all.", zh: '那種內疚感是氣候焦慮的一部分。而研究人員說這可能讓人癱瘓——意思是人們感到如此絕望以至於完全不採取任何行動。', vocab: [{ word: 'paralyzing', def: '讓人癱瘓的、使人無法行動的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So the anxiety actually makes things worse by stopping people from acting.", zh: '所以焦慮實際上透過阻止人們行動而讓事情變得更糟。' },
          { speaker: 'a', speakerName: 'Mira', en: "In some cases, yes. That's why psychologists say it's important to channel that anxiety into productive action rather than letting it spiral.", zh: '在某些情況下，是的。這就是為什麼心理學家說重要的是把那種焦慮轉化為有建設性的行動，而不是讓它螺旋式下降。', vocab: [{ word: 'channel', def: '引導、轉化（情緒/能量）' }, { word: 'spiral', def: '螺旋式惡化' }] },
        ],
      },
      {
        title: 'Part 2 — Media and Doom-Scrolling',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "I think social media makes it worse. I'll be doom-scrolling through climate disaster news and then I can't sleep.", zh: '我認為社群媒體讓它更糟。我會不斷刷氣候災難的新聞，然後睡不著。', vocab: [{ word: 'doom-scrolling', def: '災難性刷螢幕（不斷看負面新聞）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I've been there. There's a difference between staying informed and being constantly bombarded with crisis content.", zh: '我也經歷過。保持知情和不斷被危機內容轟炸之間是有區別的。', vocab: [{ word: 'bombarded', def: '被轟炸、被大量資訊淹沒' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "How do you find that balance? I don't want to be ignorant, but I also can't absorb every piece of bad news.", zh: '你怎麼找到那個平衡點？我不想無知，但也無法吸收每一條壞消息。', vocab: [{ word: 'ignorant', def: '無知的、不了解的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I try to limit my news consumption to once or twice a day. And I've muted some accounts that are constantly catastrophizing — even if they're technically accurate.", zh: '我嘗試把看新聞的時間限制在每天一到兩次。我也靜音了一些不斷災難化的帳號——即使它們技術上是準確的。', vocab: [{ word: 'catastrophizing', def: '災難化、誇大危機' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Catastrophizing — that's the word for it. Turning every data point into evidence of imminent doom.", zh: '災難化——就是這個詞。把每一個數據點都變成即將到來的末日的證據。', vocab: [{ word: 'imminent', def: '即將發生的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Right. And it's worth asking: does consuming more disaster content actually motivate change? Or does it just make you feel worse?", zh: '對。而且值得問的是：消費更多災難內容真的能激勵改變嗎？還是只是讓你感覺更糟？' },
          { speaker: 'b', speakerName: 'Jamie', en: "In my experience, it mostly makes me feel worse. I read about it, feel helpless, and then close the app and eat biscuits.", zh: '以我的經驗，它主要讓我感覺更糟。我看了，感到無助，然後關掉 App 去吃餅乾。' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha. We've all been there. The biscuit response is very human.", zh: '哈。我們都有過那種經驗。餅乾反應非常人性化。' },
        ],
      },
      {
        title: 'Part 3 — Small Actions and Big Systems',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "So what do you actually do — or try to do — to reduce your own environmental impact?", zh: '那你實際上做了什麼——或嘗試做什麼——來減少你自己的環境影響？', vocab: [{ word: 'environmental impact', def: '環境影響' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I've cut back on meat — not completely, but significantly. And I try to take public transport instead of cabs when I can.", zh: '我減少了肉類攝取——不是完全不吃，但少了很多。而且我盡可能搭大眾運輸而不是計程車。' },
          { speaker: 'a', speakerName: 'Mira', en: "Those are actually two of the highest-impact personal choices. Reducing meat, especially beef, is massive in terms of carbon footprint.", zh: '這些其實是影響最大的個人選擇之一。減少肉類攝取，尤其是牛肉，在碳足跡方面影響巨大。', vocab: [{ word: 'carbon footprint', def: '碳足跡' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "But then I hear people say individual actions don't matter — it's corporations that need to change.", zh: '但我聽到有人說個人行動不重要——需要改變的是企業。', vocab: [{ word: 'corporations', def: '企業、大公司' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That tension is real. Both things are true — systemic change is necessary AND individual choices add up. It doesn't have to be either/or.", zh: '這種張力是真實存在的。兩件事都是真的——系統性的改變是必要的，而且個人選擇也會累積起來。這不必是非此即彼的選擇。', vocab: [{ word: 'systemic', def: '系統性的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I think framing it as either/or actually demotivates people. Like, if my choices don't matter, why bother?", zh: '我認為把它框架為非此即彼其實會讓人失去動力。就像，如果我的選擇不重要，為什麼要費心？', vocab: [{ word: 'demotivates', def: '使失去動力' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And beyond the direct impact, visible personal choices influence others. When your colleagues see you bringing a reusable lunch box, it normalizes it.", zh: '就是這樣。而且除了直接影響之外，可見的個人選擇會影響他人。當你的同事看到你帶可重複使用的便當盒，它就讓這件事正常化了。', vocab: [{ word: 'normalizes', def: '使正常化' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Social influence. That's probably more powerful than any individual carbon calculation.", zh: '社會影響力。這可能比任何個人的碳計算都更有力量。' },
        ],
      },
      {
        title: 'Part 4 — Coping Without Despairing',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "So how do you actually cope with climate anxiety without either ignoring the problem or being consumed by it?", zh: '那你實際上如何應對氣候焦慮，既不忽視問題又不被它吞噬？', vocab: [{ word: 'consumed by', def: '被…吞噬、完全被占據' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I try to focus on what I can control. I can't fix global emissions tonight, but I can make choices today that align with my values.", zh: '我嘗試專注於我能控制的事情。我今晚無法解決全球排放問題，但我今天可以做出符合我價值觀的選擇。', vocab: [{ word: 'align with', def: '符合、與…一致' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Values-based action. I like that. It's not about perfection — it's about consistency.", zh: '基於價值觀的行動。我喜歡這個。不是關於完美——是關於一致性。', vocab: [{ word: 'consistency', def: '一致性、持續性' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Right. And I find community helps. Being around people who care about the same things — even if it's just a small local group — makes you feel less alone.", zh: '對。我也發現社群很有幫助。和關心相同事物的人在一起——即使只是一個小型地方團體——讓你感覺不那麼孤單。' },
          { speaker: 'b', speakerName: 'Jamie', en: "There's something about collective action that feels more hopeful than individual action. Like you're part of something bigger.", zh: '集體行動有一種感覺比個人行動更有希望的東西。就像你是更大事物的一部分。', vocab: [{ word: 'collective', def: '集體的、共同的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's the antidote to despair. Action and community. Not doom-scrolling alone at midnight.", zh: '那是絕望的解藥。行動和社群。而不是午夜獨自刷災難新聞。', vocab: [{ word: 'antidote', def: '解藥、對策' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Noted. Less midnight doom-scrolling, more showing up to do things with people.", zh: '記下了。少一點午夜刷災難新聞，多一點與人一起參與行動。' },
          { speaker: 'a', speakerName: 'Mira', en: "That's the whole formula, honestly. You can't solve a global problem alone, but you can be one of many people doing their part.", zh: '說真的，那就是整個公式。你無法獨自解決全球問題，但你可以成為許多盡自己本分的人之一。' },
        ],
      },
      {
        title: 'Part 5 — Hope and the Long Game',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "I want to end on something I genuinely believe — there are reasons for hope.", zh: '我想以我真心相信的事情作結——是有理由抱持希望的。' },
          { speaker: 'b', speakerName: 'Jamie', en: "Tell me. I could use some.", zh: '告訴我。我正需要一些。' },
          { speaker: 'a', speakerName: 'Mira', en: "Renewable energy is growing faster than anyone predicted. Solar costs have dropped by like ninety percent in a decade. That's extraordinary.", zh: '再生能源的成長速度比任何人預測的都快。太陽能成本在十年內下降了大約百分之九十。這是非常了不起的。', vocab: [{ word: 'renewable energy', def: '再生能源' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Really? I didn't know it was that dramatic. The news never seems to cover the good stories.", zh: '真的嗎？我不知道有這麼驚人。新聞似乎從來不報導好消息。', vocab: [{ word: 'dramatic', def: '戲劇性的、驚人的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's because crisis gets clicks. But there's a lot of innovation happening — in carbon capture, in sustainable agriculture, in electric transport.", zh: '那是因為危機能獲得點擊。但有很多創新正在發生——在碳捕獲、永續農業、電動交通方面。', vocab: [{ word: 'carbon capture', def: '碳捕獲' }, { word: 'sustainable', def: '永續的、可持續的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So there's progress — it's just not headline-grabbing progress.", zh: '所以是有進展的——只是不是能搶頭條的進展。', vocab: [{ word: 'headline-grabbing', def: '搶頭條的、能引起大眾注意的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And generational change is real too. Younger people are much more mobilized around climate than any previous generation.", zh: '正是。而且世代變革也是真實的。年輕一代在氣候議題上比任何以前的世代都更加動員起來。', vocab: [{ word: 'mobilized', def: '動員起來的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That gives me hope. Alright, I'm going to make a deal with myself — less doom-scrolling, more learning about solutions.", zh: '這給了我希望。好，我要和自己達成協議——少刷災難新聞，多了解解決方案。' },
          { speaker: 'a', speakerName: 'Mira', en: "That's the most constructive shift you can make. Knowledge about solutions is energizing. Knowledge about only problems is depleting.", zh: '那是你能做的最有建設性的轉變。了解解決方案是振奮人心的。只了解問題則是耗盡精力的。', vocab: [{ word: 'depleting', def: '耗盡的、使精力流失的' }] },
        ],
      },
    ],
    keyPhrases: [
      { en: 'eco-anxiety', zh: '生態焦慮', example: "Many young people experience eco-anxiety when following climate news." },
      { en: 'doom-scrolling', zh: '不斷刷負面新聞', example: "Doom-scrolling before bed is a guaranteed way to ruin your sleep." },
      { en: 'carbon footprint', zh: '碳足跡', example: "Reducing meat consumption significantly lowers your carbon footprint." },
      { en: 'channel into', zh: '引導、轉化為', example: "Try to channel your anxiety into productive action." },
      { en: 'systemic change', zh: '系統性的改變', example: "Individual choices help, but systemic change is also essential." },
      { en: 'align with your values', zh: '符合你的價值觀', example: "Make daily choices that align with your values, even small ones." },
      { en: 'antidote to despair', zh: '絕望的解藥', example: "Community and action are the best antidote to climate despair." },
      { en: 'mobilized', zh: '動員起來的', example: "Younger generations are increasingly mobilized around climate issues." },
      { en: 'sustainable', zh: '永續的', example: "Sustainable agriculture aims to feed people without depleting the earth." },
      { en: 'depleting', zh: '耗盡的', example: "Constantly reading bad news is depleting rather than motivating." },
    ],
  },

  // Day 5
  {
    weekNumber: 7,
    dayOfWeek: 5,
    date: '2026-02-13',
    theme: 'Weather & Seasons',
    title: 'Storm Stories and Weather Memories',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — Memorable Weather Events',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Do you have a most memorable weather experience? Like, something where the weather really made an impression on you?", zh: '你有沒有最難忘的天氣經歷？像是，天氣真的讓你印象深刻的事？', vocab: [{ word: 'made an impression', def: '留下深刻印象' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Yes, actually. When I was a kid, there was a massive typhoon that knocked out power to our whole neighborhood for three days. I still remember the eerie silence afterward.", zh: '有，其實。我小的時候，有一個巨大的颱風讓我們整個社區停電三天。我還記得之後那種詭異的寂靜。', vocab: [{ word: 'eerie', def: '詭異的、令人毛骨悚然的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "The eerie silence — that's vivid. What did you do for three days without power?", zh: '詭異的寂靜——這很生動。沒電的三天你們怎麼過？', vocab: [{ word: 'vivid', def: '生動的、鮮明的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "We played board games by candlelight, cooked on a portable gas stove, and the whole family just... stayed together. In hindsight, it was one of the most connected times I remember.", zh: '我們在燭光下玩桌遊，在便攜式瓦斯爐上煮飯，整個家人就只是……待在一起。回想起來，那是我記憶中感覺最緊密連結的時刻之一。', vocab: [{ word: 'in hindsight', def: '事後回想起來' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's beautiful. The disaster brought everyone together.", zh: '這很美。那場災難把大家凝聚在一起。' },
          { speaker: 'a', speakerName: 'Mira', en: "It really did. I think major weather events strip away the usual distractions and remind us what matters.", zh: '真的是。我認為重大的天氣事件會剝去平常的干擾，提醒我們什麼才是重要的。', vocab: [{ word: 'strip away', def: '剝去、去除' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "What about you? Do you have a weather memory that stood out?", zh: '那你呢？你有哪個天氣記憶特別突出？' },
          { speaker: 'a', speakerName: 'Mira', en: "Oh wait, I should ask you! You brought it up.", zh: '喔等等，我應該問你！是你提起的。' },
        ],
      },
      {
        title: 'Part 2 — Jamie\'s Weather Memory',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Ha! Fair enough. Mine is actually a happy one — the first time I saw heavy snow. I grew up somewhere warmer, and seeing actual snowfall for the first time was surreal.", zh: '哈！說得對。我的其實是一個快樂的記憶——第一次看到大雪。我在更溫暖的地方長大，第一次看到實際的降雪感覺很超現實。', vocab: [{ word: 'surreal', def: '超現實的、不真實的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Surreal is the perfect word. Where were you when it happened?", zh: '超現實是完美的詞。你在哪裡的時候這發生的？' },
          { speaker: 'b', speakerName: 'Jamie', en: "I was visiting a friend in northern Japan in February. I stepped outside the train station and suddenly everything was white. It was completely silent too.", zh: '我二月在日本北部拜訪一個朋友。我走出火車站，突然一切都是白色的。也完全寂靜。' },
          { speaker: 'a', speakerName: 'Mira', en: "Snow creates this strange acoustic effect — it absorbs sound. The world genuinely becomes quieter.", zh: '雪創造了一種奇特的聲學效果——它吸收聲音。這個世界真的會變得更安靜。', vocab: [{ word: 'acoustic', def: '聲學的、聲音的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Yes! I stood there for ages just listening to the silence. Then I tried to catch snowflakes on my tongue like a child, which my friend found embarrassing.", zh: '是的！我站在那裡很久只是聆聽那種寂靜。然後我試著像個孩子一樣用舌頭接雪花，我朋友覺得很丟臉。' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha! That's very endearing. First snow is like a rebirth experience — everything familiar becomes magical.", zh: '哈！那非常可愛。第一場雪就像是重生的體驗——一切熟悉的事物都變得神奇了。', vocab: [{ word: 'endearing', def: '可愛的、令人喜愛的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "It really was. I understand now why people in cold countries can still find winter beautiful after years of it. There's something fundamentally enchanting about snow.", zh: '真的是。我現在理解為什麼寒冷國家的人在經歷多年後仍然覺得冬天美麗。雪有某種根本上迷人的東西。', vocab: [{ word: 'enchanting', def: '迷人的、令人著迷的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "It has that quality where even adults revert to childlike wonder. That's rare.", zh: '它有一種即使是大人也會回歸到孩子般驚奇的特質。這很罕見。', vocab: [{ word: 'revert to', def: '回歸、退回到' }] },
        ],
      },
      {
        title: 'Part 3 — Weather and Storytelling',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "It's interesting — weather shows up in so many stories and songs across every culture. Why do you think that is?", zh: '很有趣——天氣出現在每個文化的很多故事和歌曲中。你認為那是為什麼？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Because it's universal? Everyone experiences weather. It's one of the few things that crosses all borders.", zh: '因為它是普遍的？每個人都經歷天氣。它是少數跨越所有邊界的事物之一。' },
          { speaker: 'a', speakerName: 'Mira', en: "And writers use it to set mood instantly. A stormy night communicates tension before a single character speaks.", zh: '而且作家用它來立即設定情緒。一個暴風雨的夜晚在任何角色開口說話之前就傳達了緊張感。', vocab: [{ word: 'tension', def: '緊張感' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "The pathetic fallacy — that's the literary term, right? When weather mirrors a character's emotions.", zh: '情感謬誤——那是文學術語，對吧？當天氣反映角色的情感時。', vocab: [{ word: 'pathetic fallacy', def: '情感謬誤（文學手法，以天氣反映角色情緒）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. Dark clouds when the hero is grieving. Sunshine at the moment of reconciliation. It's a bit clichéd now, but it works because weather actually does affect our emotions.", zh: '正是。英雄悲傷時的烏雲。和解時刻的陽光。現在有點老套了，但它有效，因為天氣確實會影響我們的情緒。', vocab: [{ word: 'reconciliation', def: '和解' }, { word: 'clichéd', def: '老套的、陳腐的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "It's not just a literary device — it reflects real psychology.", zh: '這不只是文學手法——它反映了真實的心理學。' },
          { speaker: 'a', speakerName: 'Mira', en: "Right. Which is why weather is such powerful shorthand in communication. Even in everyday speech — 'he's under the weather', 'she was a ray of sunshine'.", zh: '對。這就是為什麼天氣在溝通中是如此有力的簡略說法。即使在日常說話中——「他身體不舒服」、「她是一道陽光」。', vocab: [{ word: 'shorthand', def: '簡略的表達方式' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Language is full of weather metaphors. We use them without even noticing.", zh: '語言裡充滿了天氣隱喻。我們使用它們甚至沒注意到。' },
        ],
      },
      {
        title: 'Part 4 — Extreme Weather Memories',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Have you ever been in a genuinely dangerous weather situation? Like, actually scared?", zh: '你有沒有過真正危險的天氣情況？像是，真的很害怕？' },
          { speaker: 'a', speakerName: 'Mira', en: "Once, yes. I was hiking when a thunderstorm came out of nowhere. I was on an exposed ridge and the lightning was very close. I've never moved so fast in my life.", zh: '有一次，是的。我在健行時，雷雨突然從天而降。我在一個暴露的山脊上，閃電非常近。我這輩子從來沒有移動得那麼快。', vocab: [{ word: 'thunderstorm', def: '雷雨' }, { word: 'exposed ridge', def: '暴露的山脊（無遮蔽）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That sounds terrifying. Were you with anyone?", zh: '聽起來很恐怖。你有和別人在一起嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "With a friend, thankfully. We crouched under a rock overhang until the worst passed. It lasted maybe twenty minutes but felt like hours.", zh: '謝天謝地，和朋友在一起。我們蹲在一個岩石懸挑下直到最糟糕的過去。大概持續了二十分鐘，但感覺像幾個小時。', vocab: [{ word: 'crouched', def: '蹲伏、蜷縮' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I had something similar on a boat once. The waves got huge and I was genuinely convinced the boat was going to capsize.", zh: '我有一次在船上有類似的經歷。浪變得很大，我真的確信船要翻了。', vocab: [{ word: 'capsize', def: '翻船、傾覆' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Oh no. Were you far from shore?", zh: '噢不。你離岸邊很遠嗎？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Far enough to be scary. The captain was calm though, which helped a lot. If he had looked worried, I think I would have completely panicked.", zh: '夠遠，令人害怕。但船長很冷靜，這很有幫助。如果他看起來擔心，我想我會完全恐慌。', vocab: [{ word: 'panicked', def: '恐慌' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's such a leadership lesson. In a crisis, the leader's calm is contagious. So is their panic.", zh: '這是很好的領導力教訓。在危機中，領導者的冷靜是有感染力的。他們的恐慌也是。', vocab: [{ word: 'contagious', def: '有感染力的、會傳染的' }] },
        ],
      },
      {
        title: 'Part 5 — What Extreme Weather Teaches Us',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Those intense weather experiences — do you think they change you in any lasting way?", zh: '那些強烈的天氣經歷——你認為它們以任何持久的方式改變了你嗎？', vocab: [{ word: 'lasting', def: '持久的、長期的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I think they give you perspective. After the boat thing, minor daily stresses felt much more manageable.", zh: '我認為它們給了你視角。在那次船的事情之後，日常的小壓力感覺更容易應對了。', vocab: [{ word: 'perspective', def: '視角、觀點' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Post-traumatic growth — that's actually a psychological concept. Extreme experiences can paradoxically make people more resilient and more grateful.", zh: '創傷後成長——那實際上是一個心理學概念。極端的經歷矛盾地可以讓人變得更有韌性且更感恩。', vocab: [{ word: 'paradoxically', def: '矛盾地、看似矛盾但實則如此' }, { word: 'resilient', def: '有韌性的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I definitely appreciate sunny days more now. They don't feel guaranteed.", zh: '我現在確實更珍惜晴天了。它們不感覺是理所當然的。' },
          { speaker: 'a', speakerName: 'Mira', en: "That's the gift of contrast. You can't fully appreciate comfort without having been cold. You can't fully appreciate calm without having known a storm.", zh: '那是對比的禮物。你無法在沒有寒冷過的情況下完全欣賞舒適。你無法在沒有經歷過風暴的情況下完全欣賞平靜。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That's almost philosophical. But it rings true.", zh: '這幾乎是哲學性的。但它感覺很真實。', vocab: [{ word: 'rings true', def: '感覺真實、聽起來真實' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Nature has always been one of humanity's greatest teachers. We've just gotten very good at insulating ourselves from it.", zh: '大自然一直是人類最偉大的老師之一。我們只是變得非常善於讓自己與它隔絕。', vocab: [{ word: 'insulating', def: '隔離、隔絕' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Between the air conditioning and the umbrellas and the weather apps, we've buffered ourselves from what people used to face directly.", zh: '在冷氣、雨傘和天氣 App 之間，我們緩衝了自己，遠離了人們過去直接面對的事物。', vocab: [{ word: 'buffered', def: '緩衝、保護免受衝擊' }] },
          { speaker: 'a', speakerName: 'Mira', en: "And that's not entirely bad — but occasionally facing the raw weather reminds you that you're a creature of this planet, not just a commuter on it.", zh: '這不完全是壞事——但偶爾面對原始的天氣會提醒你，你是這個星球的生物，而不只是在上面通勤的人。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'in hindsight', zh: '事後回想起來', example: "In hindsight, the power cut brought our family closer together." },
      { en: 'eerie silence', zh: '詭異的寂靜', example: "After the typhoon passed, an eerie silence fell over the neighborhood." },
      { en: 'strip away', zh: '剝去、去除', example: "Extreme weather strips away distractions and reveals what matters." },
      { en: 'pathetic fallacy', zh: '情感謬誤（文學手法）', example: "Writers often use pathetic fallacy to mirror a character's mood." },
      { en: 'shorthand', zh: '簡略的表達', example: "Weather is powerful shorthand for emotion in storytelling." },
      { en: 'contagious', zh: '有感染力的', example: "In a crisis, a leader's calm is contagious." },
      { en: 'rings true', zh: '聽起來真實、引起共鳴', example: "What you said about contrast and appreciation really rings true." },
      { en: 'post-traumatic growth', zh: '創傷後成長', example: "Facing hardship can lead to post-traumatic growth over time." },
      { en: 'paradoxically', zh: '矛盾地', example: "Paradoxically, difficult experiences often make people more resilient." },
      { en: 'resilient', zh: '有韌性的', example: "People who've faced adversity often become more resilient afterward." },
    ],
  },

  // Day 6
  {
    weekNumber: 7,
    dayOfWeek: 6,
    date: '2026-02-14',
    theme: 'Weather & Seasons',
    title: 'Weather and Romance',
    phase: 'p1',
    parts: [
      {
        title: "Part 1 — Valentine's Day Weather",
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Happy Valentine's Day, Mira. Perfect weather for romance today, don't you think?", zh: '情人節快樂，Mira。今天的天氣對浪漫來說很完美，你不覺得嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha! It's actually quite grey and drizzly. Not exactly what greeting cards show.", zh: '哈！今天其實相當陰灰且有點毛毛雨。不完全是賀卡上顯示的那種。', vocab: [{ word: 'drizzly', def: '毛毛雨的、細雨紛飛的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "But maybe that's the point? There's something about grey, rainy weather that's actually quite romantic. Very moody.", zh: '但也許這才是重點？陰灰的雨天有某種東西其實非常浪漫。很有氛圍。', vocab: [{ word: 'moody', def: '有氛圍的、陰鬱的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "You know, you have a point. Rain forces you inside, close together. It's very intimate.", zh: '你知道嗎，你說得有道理。雨天逼著你待在室內，靠在一起。這很親密。', vocab: [{ word: 'intimate', def: '親密的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And it gives you an excuse to cancel outdoor plans and just be cozy at home with someone.", zh: '而且它給了你理由取消戶外計劃，就在家裡和某人待得舒舒服服的。' },
          { speaker: 'a', speakerName: 'Mira', en: "Rainy day as a romantic backdrop. I think that's why so many romantic movies feature rain in the climactic scenes.", zh: '雨天作為浪漫背景。我想這就是為什麼很多浪漫電影在高潮場景中有雨的原因。', vocab: [{ word: 'climactic', def: '高潮的、最關鍵的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "The famous movie rain kiss. It never looks as romantic in real life when you're actually wet and cold.", zh: '著名的電影雨中吻。當你真正濕冷的時候，在現實生活中看起來從來沒那麼浪漫。' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha! The reality versus the cinematic version. Reality involves soggy hair and a cold nose.", zh: '哈！現實與電影版本的差距。現實包括濕漉漉的頭髮和冰冷的鼻子。' },
        ],
      },
      {
        title: 'Part 2 — Weather and Attraction',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "There's actually research on weather and attraction. People tend to rate others as more attractive on sunny days.", zh: '其實有關於天氣和吸引力的研究。人們在晴天傾向於把別人評為更有吸引力。', vocab: [{ word: 'attraction', def: '吸引力' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Really? So the weather is literally affecting how we perceive people?", zh: '真的嗎？所以天氣字面上影響著我們如何感知別人？', vocab: [{ word: 'perceive', def: '感知、察覺' }] },
          { speaker: 'a', speakerName: 'Mira', en: "It seems so. Good weather boosts mood, and good mood makes everything seem more positive — including the people around you.", zh: '似乎是這樣。好天氣提升心情，好心情讓一切看起來更正向——包括你周圍的人。' },
          { speaker: 'b', speakerName: 'Jamie', en: "So a first date should never be on a rainy, grey day. You're setting yourself up to seem less attractive.", zh: '所以第一次約會絕不應該在雨天、陰天。你在讓自己看起來不那麼有吸引力。' },
          { speaker: 'a', speakerName: 'Mira', en: "Unless you're specifically going for a cozy, intimate atmosphere. Then rain works in your favor.", zh: '除非你特別想要一種愜意、親密的氣氛。那麼雨天對你有利。', vocab: [{ word: 'in your favor', def: '對你有利' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Weather as a date planning tool. I'm adding this to my strategy.", zh: '天氣作為約會計劃工具。我要把這個加入我的策略。' },
          { speaker: 'a', speakerName: 'Mira', en: "Please don't call it a 'strategy'. That sounds very calculated for something that's supposed to be spontaneous.", zh: '請不要叫它「策略」。對於應該是自然發生的事情來說，這聽起來非常有計謀。', vocab: [{ word: 'spontaneous', def: '自然發生的、自發的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Fair point. Let's call it 'being mindful of environmental conditions'. Very organic.", zh: '說得對。我們叫它「留意環境條件」。非常有機自然。', vocab: [{ word: 'organic', def: '有機的、自然的' }] },
        ],
      },
      {
        title: 'Part 3 — Seasonal Rituals and Couples',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Do you have any seasonal rituals? Things you do at certain times of year that feel special?", zh: '你有什麼季節性儀式嗎？在一年中某些時候做的、感覺特別的事情？', vocab: [{ word: 'rituals', def: '儀式、固定習俗' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I love watching the first plum blossoms every February. It's become a tradition for me — going to the nearest park and just sitting with a tea, watching the blossoms.", zh: '我喜歡每年二月觀賞第一朵梅花。這對我來說已成為一種傳統——去最近的公園，帶著一杯茶，看著花開。', vocab: [{ word: 'plum blossoms', def: '梅花' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's lovely. Very Japanese — there's the whole tradition of hanami, right? Cherry blossom viewing.", zh: '那很美。很有日式風格——有整個賞花的傳統，對吧？賞櫻花。', vocab: [{ word: 'hanami', def: '賞花（日語，尤指賞櫻）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. And hanami is interesting because it's explicitly about appreciating something beautiful and temporary. Sakura blooms for maybe two weeks and then it's gone.", zh: '正是。而賞花很有趣，因為它明確地是關於欣賞美麗而短暫的事物。櫻花大概開兩個禮拜然後就消失了。', vocab: [{ word: 'explicitly', def: '明確地' }, { word: 'temporary', def: '短暫的、暫時的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "The Japanese concept of mono no aware — the beauty of impermanence.", zh: '日本的「物哀」概念——無常之美。', vocab: [{ word: 'mono no aware', def: '物哀（日語，感受到事物無常的淡淡哀愁）' }, { word: 'impermanence', def: '無常、短暫性' }] },
          { speaker: 'a', speakerName: 'Mira', en: "You know mono no aware! I'm impressed. Yes, exactly. It's not sadness about the ending — it's deepened appreciation because of the ending.", zh: '你知道物哀！我很佩服。是的，就是這樣。不是因為結束而悲傷——而是因為結束而加深的欣賞。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That applies to relationships too, doesn't it? Knowing that moments are finite makes you pay more attention to them.", zh: '這也適用於關係，不是嗎？知道時刻是有限的讓你更注意它們。', vocab: [{ word: 'finite', def: '有限的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. Presence is the real gift — more than any Valentine's Day dinner or bouquet of roses.", zh: '正是。臨在才是真正的禮物——比任何情人節晚餐或玫瑰花束都更重要。', vocab: [{ word: 'presence', def: '臨在、當下全心投入' }] },
        ],
      },
      {
        title: 'Part 4 — Ideal Weather for a Date',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "If you could choose the perfect weather for a date, what would it be?", zh: '如果你可以選擇約會的完美天氣，會是什麼？' },
          { speaker: 'a', speakerName: 'Mira', en: "Hmm. A warm spring evening — maybe around twenty-two degrees. A light breeze, not too hot. Golden hour light just as the sun is going down.", zh: '嗯。溫暖的春天傍晚——大概二十二度左右。微微的涼風，不太熱。日落時的黃金時刻光線。', vocab: [{ word: 'golden hour', def: '黃金時刻（日出或日落前後的柔和光線）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That sounds perfect. Almost like an outdoor dinner terrace situation.", zh: '聽起來很完美。幾乎像是戶外露台晚餐的情境。' },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly what I had in mind. Somewhere with outdoor seating, fairy lights coming on as the sky gets dark.", zh: '正是我想的。有戶外座位的地方，天色變暗時一串串燈光亮起來。', vocab: [{ word: 'fairy lights', def: '串燈、小彩燈' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Very specific. Have you rehearsed this in your head?", zh: '非常具體。你在腦子裡排練過這個嗎？', vocab: [{ word: 'rehearsed', def: '排練、演練' }] },
          { speaker: 'a', speakerName: 'Mira', en: "...maybe. What's your ideal?", zh: '……也許吧。你的理想是什麼？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Cozy indoors on a rainy day. Hot drinks, good food, no plans to go anywhere. The rain outside makes you feel like you're in a little private bubble.", zh: '雨天在室內愜意地待著。熱飲、好食物、沒有要去哪裡的計劃。外面的雨讓你感覺像是在一個小小的私密泡泡裡。', vocab: [{ word: 'bubble', def: '泡泡、小小的封閉世界' }] },
          { speaker: 'a', speakerName: 'Mira', en: "I love that description. It's the opposite of mine but equally romantic in its own way.", zh: '我喜歡那個描述。和我的相反，但以它自己的方式同樣浪漫。' },
        ],
      },
      {
        title: 'Part 5 — Love in Different Seasons',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Do you think relationships feel different in different seasons? Like, is summer romance different from winter romance?", zh: '你認為關係在不同季節感覺不同嗎？像是，夏日戀情和冬日戀情不同嗎？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Absolutely. Summer love feels more spontaneous and carefree — beach days, late evenings. Winter love feels more settled and domestic — staying in, cooking together.", zh: '絕對不同。夏日戀情感覺更自發、無憂無慮——海灘、傍晚很晚才回家。冬日戀情感覺更穩定、家常——待在家，一起做飯。', vocab: [{ word: 'carefree', def: '無憂無慮的' }, { word: 'domestic', def: '家常的、居家的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "There's a reason people talk about summer flings — they have this intensity because they're temporary, tied to the season.", zh: '人們談論夏日戀情是有原因的——它們有這種強度，因為它們是短暫的，與季節相連。', vocab: [{ word: 'flings', def: '短暫的戀愛、露水情緣' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And autumn relationships? What's the vibe there?", zh: '那秋天的戀情呢？那種感覺是什麼？', vocab: [{ word: 'vibe', def: '感覺、氛圍' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Autumn feels reflective. Things slowing down, leaves falling. There's a melancholy that can be beautiful if you're with the right person.", zh: '秋天感覺沉思。事物慢下來，落葉。有一種憂鬱，如果你和對的人在一起，可以是很美的。', vocab: [{ word: 'reflective', def: '沉思的、省思的' }, { word: 'melancholy', def: '憂鬱、淡淡的哀愁' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And spring is new beginnings — meeting someone new when everything is blooming feels hopeful.", zh: '而春天是新的開始——在一切都開花時遇見新的人感覺充滿希望。' },
          { speaker: 'a', speakerName: 'Mira', en: "You've thought about this more than I expected.", zh: '你對這件事想得比我預期的要多。' },
          { speaker: 'b', speakerName: 'Jamie', en: "It's Valentine's Day. I'm in the mood for romantic reflection.", zh: '今天是情人節。我在浪漫回想的情緒裡。', vocab: [{ word: 'reflection', def: '回想、省思' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Happy Valentine's Day, Jamie. May your weather — and your love life — be exactly what you need it to be.", zh: '情人節快樂，Jamie。願你的天氣——還有你的感情生活——恰好是你所需要的樣子。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'drizzly', zh: '毛毛雨的', example: "The drizzly weather actually made our walk feel more romantic." },
      { en: 'in your favor', zh: '對你有利', example: "Choose a sunny day — the weather will work in your favor." },
      { en: 'spontaneous', zh: '自然發生的、自發的', example: "The best moments in a relationship are often spontaneous." },
      { en: 'mono no aware', zh: '物哀（無常之美）', example: "Mono no aware teaches us to appreciate beauty because it doesn't last." },
      { en: 'impermanence', zh: '無常', example: "Cherry blossoms are loved partly because of their impermanence." },
      { en: 'presence', zh: '臨在、當下全心投入', example: "True romance is less about gifts and more about presence." },
      { en: 'golden hour', zh: '黃金時刻（光線）', example: "Golden hour light makes everything look more beautiful." },
      { en: 'melancholy', zh: '淡淡的憂鬱', example: "There's a beautiful melancholy to autumn that some people love." },
      { en: 'carefree', zh: '無憂無慮的', example: "Summer has a carefree energy that makes people more open." },
      { en: 'flings', zh: '短暫的戀愛', example: "Summer flings feel intense because they're tied to the season." },
    ],
  },

  // Day 7
  {
    weekNumber: 7,
    dayOfWeek: 7,
    date: '2026-02-15',
    theme: 'Weather & Seasons',
    title: 'Dream Destinations by Season',
    phase: 'p1',
    parts: [
      {
        title: 'Part 1 — Planning Around Weather',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "If you could travel anywhere right now for the perfect weather, where would you go?", zh: '如果你現在可以去任何地方享受完美的天氣，你會去哪裡？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Right now, in February? Somewhere warm but not sweltering. Maybe somewhere in Southeast Asia — like northern Thailand or Vietnam.", zh: '現在，二月？某個溫暖但不悶熱的地方。也許東南亞某處——像泰國北部或越南。', vocab: [{ word: 'sweltering', def: '悶熱的、酷熱難耐的' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Good choice. February is actually a great time for those areas — before the monsoon season arrives, still dry and warm.", zh: '好選擇。二月其實對那些地區是個好時機——季風季節到來之前，還是乾燥溫暖的。', vocab: [{ word: 'monsoon', def: '季風、雨季' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Have you ever timed your travel around weather specifically? Not just avoided bad weather, but actively sought out great weather?", zh: '你有沒有特別根據天氣規劃旅行時間？不只是避開壞天氣，而是主動尋找好天氣？', vocab: [{ word: 'sought out', def: '主動尋找' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Yes, actually. I once went to the Maldives specifically in February because it's the driest month. I was obsessive about it — checking rainfall data before booking.", zh: '有，其實。我有一次特地在二月去馬爾地夫，因為那是最乾燥的月份。我對此很執著——訂票前查降雨量數據。', vocab: [{ word: 'obsessive', def: '執著的、強迫性的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's very thorough. Did it pay off?", zh: '這非常徹底。有值得嗎？', vocab: [{ word: 'pay off', def: '有回報、值得' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Every single day was perfect. Blue sky, calm sea, twenty-eight degrees. I've never felt so in tune with the environment.", zh: '每一天都完美。藍天、平靜的海、二十八度。我從來沒有感覺和環境這麼合拍。', vocab: [{ word: 'in tune with', def: '和…合拍、與…和諧' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That makes me want to start researching my next trip with weather as the primary factor.", zh: '這讓我想要以天氣為主要考量，開始研究我的下一次旅行。' },
        ],
      },
      {
        title: 'Part 2 — Shoulder Season Travel',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "Have you heard of shoulder season? It's the periods just before and after peak tourist season, and it's often the best time to travel.", zh: '你聽說過肩季嗎？那是旅遊旺季前後的時期，通常是旅行的最佳時機。', vocab: [{ word: 'shoulder season', def: '肩季（旅遊旺季前後的淡旺之間）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I've heard the term but never really thought about it. What makes it better?", zh: '我聽過這個術語但從來沒有認真想過。什麼讓它更好？' },
          { speaker: 'a', speakerName: 'Mira', en: "Fewer crowds, lower prices, and often still very good weather. Like visiting Europe in late September — the summer heat is gone, but it's still beautiful and warm.", zh: '更少人潮、更低價格，而且天氣通常還是很好。像是九月下旬造訪歐洲——夏天的炎熱消退了，但仍然美麗溫暖。' },
          { speaker: 'b', speakerName: 'Jamie', en: "That's smart. I always assumed traveling in August was just what you did for Europe.", zh: '很聰明。我以前總以為去歐洲就是在八月旅行。' },
          { speaker: 'a', speakerName: 'Mira', en: "August is peak season — everything is packed, prices are high, and the heat can be brutal. September and October are genuinely better in most parts of Europe.", zh: '八月是旺季——到處都是人，價格高，而且熱可能非常難受。九月和十月在歐洲大多數地方真的更好。', vocab: [{ word: 'brutal', def: '殘酷的、非常嚴酷的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "And Japan in spring versus Japan in golden week?", zh: '那春天的日本對比黃金週的日本呢？', vocab: [{ word: 'golden week', def: '黃金週（日本連假）' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Early spring — late March, before the crowds discover cherry blossoms — is magical. Golden week is beautiful weather but completely packed.", zh: '初春——三月下旬，在人潮發現櫻花之前——非常迷人。黃金週天氣很美但完全擠滿了人。' },
          { speaker: 'b', speakerName: 'Jamie', en: "So timing is almost as important as the destination itself.", zh: '所以時機幾乎和目的地本身一樣重要。' },
        ],
      },
      {
        title: 'Part 3 — Dream Weather Experiences',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Is there a weather experience on your bucket list? Like, not just a place, but a specific weather moment you want to witness?", zh: '你的夢想清單上有沒有天氣體驗？像是，不只是一個地方，而是你想親眼見證的特定天氣時刻？', vocab: [{ word: 'bucket list', def: '遺願清單、夢想清單' }] },
          { speaker: 'a', speakerName: 'Mira', en: "The Northern Lights. I've seen photos but I want to actually stand under the aurora borealis and see it move. Preferably in Iceland or Norway.", zh: '北極光。我看過照片，但我想真正站在北極光下看著它移動。最好是在冰島或挪威。', vocab: [{ word: 'aurora borealis', def: '北極光' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "That's on my list too! I read that you need clear skies and darkness — so you have to time it perfectly.", zh: '那也在我的清單上！我讀到你需要晴空和黑暗——所以你要把時間抓得剛剛好。' },
          { speaker: 'a', speakerName: 'Mira', en: "And ideally no moon. The full moon actually washes out the aurora. It's a very specific combination of conditions.", zh: '而且最好沒有月亮。滿月實際上會洗掉北極光的顏色。這是非常特定的條件組合。', vocab: [{ word: 'washes out', def: '洗掉（顏色、光線）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "What else? Any other weather dreams?", zh: '還有什麼？還有其他天氣夢想嗎？' },
          { speaker: 'a', speakerName: 'Mira', en: "I'd love to experience the monsoon in India — not just a rainy day, but the full drama of the first monsoon rains hitting after a blazing hot dry season.", zh: '我很想體驗印度的季風——不只是下雨天，而是在炎熱乾燥的季節後，第一場季風雨到來的完整戲劇性場面。', vocab: [{ word: 'blazing', def: '灼熱的、極熱的' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "I've seen videos of people celebrating when the first monsoon rains hit — like it's a festival.", zh: '我看過第一場季風雨到來時人們慶祝的影片——就像是一個節日。' },
          { speaker: 'a', speakerName: 'Mira', en: "Because for many communities, it literally is. After months of heat and drought, rain means crops survive. It's life-giving.", zh: '因為對許多社群來說，它字面上就是。在幾個月的酷熱和乾旱之後，雨意味著農作物能生存。它是給予生命的。', vocab: [{ word: 'drought', def: '乾旱' }, { word: 'life-giving', def: '給予生命的' }] },
        ],
      },
      {
        title: 'Part 4 — Weather-Proofing Your Travel Plans',
        lines: [
          { speaker: 'b', speakerName: 'Jamie', en: "Have you ever had a trip ruined by bad weather? Like, you planned everything and then the weather just didn't cooperate?", zh: '你有沒有旅行被壞天氣毀掉過？像是，你計劃了一切，然後天氣就是不配合？' },
          { speaker: 'a', speakerName: 'Mira', en: "Once in a while, yes. I went to the Azores and it rained almost every day. But the thing is, the Azores are beautiful even in rain — the fog gives it this mysterious quality.", zh: '偶爾，有的。我去亞速爾群島，幾乎每天都下雨。但問題是，亞速爾群島即使在雨中也很美——霧氣給它一種神秘的氛圍。', vocab: [{ word: 'Azores', def: '亞速爾群島' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "So the backup question is: does the destination have something to offer regardless of weather?", zh: '所以備用問題是：無論天氣如何，目的地有什麼可以提供的？', vocab: [{ word: 'regardless of', def: '無論…如何' }] },
          { speaker: 'a', speakerName: 'Mira', en: "Exactly. Cities are generally safer bets than beach destinations when weather is unpredictable. You can always visit a museum, a café, explore covered markets.", zh: '正是。當天氣難以預測時，城市通常比海灘目的地更保險。你隨時可以參觀博物館、咖啡廳，探索有遮蓋的市場。', vocab: [{ word: 'safer bets', def: '更保險的選擇' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Beach holidays are the highest-stakes weather gambles. You go specifically for sun, and if it rains, there's nothing else to do.", zh: '海灘假期是賭注最高的天氣賭局。你特地去曬太陽，如果下雨，就沒有別的事可做了。', vocab: [{ word: 'stakes', def: '賭注、風險' }] },
          { speaker: 'a', speakerName: 'Mira', en: "My strategy now is: research average weather but plan activities that work in any weather. Then anything good is a bonus.", zh: '我現在的策略是：研究平均天氣，但計劃在任何天氣下都可以進行的活動。然後任何好天氣都是額外的驚喜。', vocab: [{ word: 'bonus', def: '額外的驚喜、意外收穫' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Lower your expectations, exceed them more easily. Works for weather, works for life.", zh: '降低期望，更容易超越它。對天氣有用，對生活也有用。' },
          { speaker: 'a', speakerName: 'Mira', en: "Ha! That's the most practical wisdom I've heard all week.", zh: '哈！那是我這週聽到的最實際的智慧。' },
        ],
      },
      {
        title: 'Part 5 — Making Peace with the Weather You Have',
        lines: [
          { speaker: 'a', speakerName: 'Mira', en: "We've spent a whole week talking about weather. What's the biggest thing you've taken from it?", zh: '我們花了整整一週談論天氣。你從中得到的最大收穫是什麼？' },
          { speaker: 'b', speakerName: 'Jamie', en: "Honestly? That weather isn't just background noise. It's shaped civilizations, cultures, moods, romance, food — everything.", zh: '說真的？天氣不只是背景噪音。它塑造了文明、文化、情緒、浪漫、食物——一切。', vocab: [{ word: 'background noise', def: '背景噪音' }] },
          { speaker: 'a', speakerName: 'Mira', en: "And how we relate to weather says a lot about how we relate to things we can't control in general.", zh: '而我們如何與天氣相處，說明了很多關於我們如何與一般無法控制的事物相處。' },
          { speaker: 'b', speakerName: 'Jamie', en: "If you fight it and resent it, you're miserable. If you adapt and find the beauty in it, life is better.", zh: '如果你抵抗它、怨恨它，你就會很痛苦。如果你適應它，找到其中的美，生活就更好了。', vocab: [{ word: 'resent', def: '怨恨、不滿' }] },
          { speaker: 'a', speakerName: 'Mira', en: "That's literally a philosophy for life. The Japanese call it shikata ga nai — 'it cannot be helped'. Acceptance of what you can't change.", zh: '那字面上就是一種人生哲學。日本人稱它為「仕方がない」——「事情就是這樣」。接受你無法改變的事情。', vocab: [{ word: 'shikata ga nai', def: '仕方がない（日語，事情就是這樣、沒辦法）' }] },
          { speaker: 'b', speakerName: 'Jamie', en: "Acceptance, adaptation, and then finding what's beautiful in it. That could apply to weather, to work, to relationships.", zh: '接受、適應，然後找到其中的美。這可以適用於天氣、工作、關係。' },
          { speaker: 'a', speakerName: 'Mira', en: "I think that's exactly why weather is such a rich topic. On the surface it's just rain and sun. But underneath it's everything.", zh: '我認為這正是為什麼天氣是如此豐富的話題。表面上只是雨和陽光。但在底層是一切。' },
          { speaker: 'b', speakerName: 'Jamie', en: "Well said. Same time next week for a whole new topic?", zh: '說得好。下週同一時間換一個全新的話題？' },
          { speaker: 'a', speakerName: 'Mira', en: "I'll be here. Whatever the weather.", zh: '我會在這裡。無論天氣如何。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'shoulder season', zh: '肩季', example: "Traveling in shoulder season means fewer crowds and better prices." },
      { en: 'in tune with', zh: '和…合拍、和諧', example: "Perfect weather made me feel completely in tune with my surroundings." },
      { en: 'bucket list', zh: '夢想清單', example: "Seeing the Northern Lights is on my weather bucket list." },
      { en: 'aurora borealis', zh: '北極光', example: "The aurora borealis requires clear skies and no moonlight to be visible." },
      { en: 'regardless of', zh: '無論…如何', example: "Choose destinations that are worth visiting regardless of the weather." },
      { en: 'safer bets', zh: '更保險的選擇', example: "Cities are safer bets than beaches when weather is unpredictable." },
      { en: 'background noise', zh: '背景噪音', example: "We often treat weather as background noise, but it shapes everything." },
      { en: 'resent', zh: '怨恨', example: "Resenting the rain only makes a rainy day worse." },
      { en: 'shikata ga nai', zh: '仕方がない（沒辦法）', example: "Shikata ga nai — some things can't be helped, so we adapt." },
      { en: 'whatever the weather', zh: '無論天氣如何', example: "True friendship means showing up, whatever the weather." },
    ],
  },
]
