import { Episode } from '../../app/src/data/episode-sample'

export const WEEK_27: Episode[] = [
  {
    weekNumber: 27,
    dayOfWeek: 1,
    date: '2026-06-29',
    theme: 'Travel',
    title: 'Going Somewhere: The Joy and Challenge of Travel',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — Why Travel Still Matters',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Travel means different things to different people, but it still has a strange power over the imagination.', zh: '旅行對每個人的意義都不太一樣，但它對人的想像力始終有一種很特別的吸引力。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Even the idea of leaving your usual environment can make you feel more alive.', zh: '對。光是離開熟悉環境這件事，有時就已經會讓人覺得自己又活了一點。', vocab: [{ word: 'usual environment', def: '平常熟悉的生活環境' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'I think travel interrupts autopilot. It makes you notice again.', zh: '我覺得旅行會打斷自動駕駛模式，讓人重新開始注意周圍。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. At home, routine often makes us stop seeing what is right in front of us.', zh: '沒錯。在家裡，日常很容易讓人對眼前的一切失去感覺。', vocab: [{ word: 'autopilot', def: '習慣性運作、不太需要有意識思考的狀態' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'But in a new place, even buying coffee can feel slightly vivid again.', zh: '但到了新地方，連買杯咖啡這種小事都可能重新變得很鮮明。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That is part of why travel can feel restorative even when it is tiring.', zh: '這也是旅行明明有時很累，卻還是會讓人覺得被更新的原因之一。' },
        ],
      },
      {
        title: 'Part 2 — Discovery Outside and Inside',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'People often say they travel to see the world, but I think they also travel to see themselves differently.', zh: '很多人說自己旅行是為了看看世界，但我覺得其實也是為了重新看見自己。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That sounds true. A new place can reveal habits you did not know you had.', zh: '這聽起來很對。新地方有時會把你自己原本沒發現的習慣也照出來。', vocab: [{ word: 'reveal', def: '顯露、讓原本不明顯的東西被看見' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Like how patient you are, how flexible you are, or how quickly you panic when things are unfamiliar.', zh: '像是你到底有多有耐心、多有彈性，或遇到不熟悉的事時有多容易慌。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Travel can make a person feel very capable and very small in the same week.', zh: '旅行常常會讓一個人在同一週裡，同時感到自己很有能力，也很渺小。', vocab: [{ word: 'feel small', def: '感受到世界很大，自己不是中心' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Which is probably healthy. It gives you perspective without needing a lecture.', zh: '而那大概是健康的。它不用說教，卻自然會把視角拉開。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Some lessons are easier to receive when your body has actually been somewhere else.', zh: '對。有些道理是當你的身體真的去過別的地方之後，才比較容易進到心裡。' },
        ],
      },
      {
        title: 'Part 3 — What Photos Cannot Hold',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'One reason travel still matters is that digital life cannot fully replace it.', zh: '旅行仍然重要的一個原因，是數位生活真的無法完全取代它。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Photos and videos can show you a place, but they cannot fully carry atmosphere.', zh: '對。照片和影片可以把一個地方展示給你看，但它們沒辦法完整帶來那個地方的氛圍。', vocab: [{ word: 'atmosphere', def: '一個地方整體的感覺、氣氛與節奏' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'They cannot give you the temperature, the smell after rain, or the pace of people walking on the street.', zh: '它們給不了你當下的溫度、下雨後的味道，或街上人們走路的節奏。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And those details are often what stay in memory the longest.', zh: '而偏偏最容易留在記憶裡很久的，常常就是那些細節。', vocab: [{ word: 'stay in memory', def: '長時間留在記憶中、不容易忘記' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Which means travel is not only visual. It is full-body learning.', zh: '那也代表旅行不只是看見，它其實是一種全身都在學習的經驗。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. A place becomes real when it moves through more than your eyes.', zh: '沒錯。一個地方只有在穿過你的眼睛之外，也穿過其他感官時，才真的變得真實。' },
        ],
      },
      {
        title: 'Part 4 — Travel Is Not Always Easy',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'Of course, travel is also uncomfortable in ways people do not always mention.', zh: '當然，旅行也有很多不舒服的地方，只是大家不一定都會提。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Delayed trains, wrong turns, language confusion, bad sleep, carrying bags everywhere.', zh: '像是火車誤點、走錯路、語言不通、睡不好，還要一直拖著行李走。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes, and being a stranger all day can be strangely tiring.', zh: '對，而且整天都活在「自己是外地人」的狀態裡，有時也會讓人很累。', vocab: [{ word: 'be a stranger', def: '身處不熟悉環境、什麼都不是自己平常的樣子' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'But maybe that is part of its value too. Travel stretches your comfort zone without asking your permission first.', zh: '但也許那也正是旅行有價值的一部分。它會在你還來不及準備好之前，就先把舒適圈拉開。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And sometimes that stretch becomes confidence later.', zh: '而那些被拉開的時刻，後來往往會慢慢變成信心。', vocab: [{ word: 'stretch your comfort zone', def: '把舒適圈往外拉，進入新的適應範圍' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Not because everything went well, but because you learned you could handle more than you thought.', zh: '對。不是因為事情都很順，而是你慢慢發現，自己能處理的其實比原本以為的更多。' },
        ],
      },
      {
        title: 'Part 5 — What Travel Leaves Behind',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'The best trips do not end when you come home. They leave something behind in you.', zh: '最好的旅行不會在你回家那天就結束，它會在你心裡留下某些東西。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'A wider perspective, a humbler attitude, maybe a different sense of what matters.', zh: '可能是更寬的視角、更謙卑的態度，或對什麼重要有了不同的感覺。', vocab: [{ word: 'wider perspective', def: '更寬廣、不只停在原本角度的看法' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Sometimes you even come back and notice your own city differently.', zh: '有時你回來之後，連自己的城市都會重新被你看見。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That may be one of travel’s quietest gifts. It does not only show you other places. It refreshes the place you already live.', zh: '那也許就是旅行很安靜的一份禮物。它不只帶你看別的地方，也會刷新你原本生活的地方。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And maybe that is why people keep wanting to go somewhere, even when they cannot fully explain why.', zh: '也許也正因如此，就算說不清原因，人還是會一直想去某個地方。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Sometimes movement helps the mind remember that life is larger than routine.', zh: '對。有時候，移動會幫助人的心重新記得：人生其實比日常還要大。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'interrupt autopilot', zh: '打斷自動駕駛模式', example: 'Travel can interrupt autopilot and make daily life feel vivid again.' },
      { en: 'see yourself differently', zh: '重新看見自己', example: 'A good trip can help you see yourself differently.' },
      { en: 'full-body learning', zh: '全身都在學習的經驗', example: 'Travel is a form of full-body learning.' },
      { en: 'stretch your comfort zone', zh: '把舒適圈拉開', example: 'Being in an unfamiliar place can stretch your comfort zone.' },
      { en: 'life is larger than routine', zh: '人生比日常還要大', example: 'Travel reminds people that life is larger than routine.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 2,
    date: '2026-06-30',
    theme: 'Travel',
    title: 'Why Travel Changes Your Perspective',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — Leaving Familiar Assumptions',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Perspective changes most when you leave a place where everything feels obvious.', zh: '當你離開一個什麼都看起來理所當然的地方時，視角通常最容易改變。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. At home, your assumptions blend into the background because everyone around you shares many of them.', zh: '對。在家裡，你的很多假設會融進背景裡，因為身邊的人常常也都和你共享差不多的前提。', vocab: [{ word: 'assumptions', def: '你默默相信、卻不一定有檢查過的前提' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'But once you are somewhere else, even small differences start asking questions of you.', zh: '但一旦到了別的地方，連很小的差異都會開始對你提出問題。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Like why meals happen differently, why people queue differently, or why silence means something else.', zh: '像是為什麼吃飯方式不同、排隊方式不同，或安靜在別的文化裡代表別的意思。', vocab: [{ word: 'queue differently', def: '排隊方式和自己熟悉的習慣不一樣' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That does not automatically make one way better. It just makes your own way less invisible.', zh: '那並不會自動代表哪一種比較好，但它會讓你自己的方式不再那麼隱形。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And that alone can be intellectually freeing.', zh: '而光是這一點，有時就已經很能解放人的思考。' },
        ],
      },
      {
        title: 'Part 2 — Humility Through Difference',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'Travel can also make people more humble, especially if they are used to feeling competent.', zh: '旅行也會讓人變得比較謙卑，尤其是那些平常很習慣自己很能幹的人。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Because suddenly you cannot read signs, order food smoothly, or understand what is happening around you.', zh: '因為突然之間，你可能看不懂指標、沒辦法順利點餐，也不知道周圍到底發生了什麼。', vocab: [{ word: 'competent', def: '熟練、有能力、很知道怎麼應對的人' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. You are reminded that intelligence is not the same thing as familiarity.', zh: '沒錯。你會被提醒，聰明和熟悉，其實不是同一件事。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That is such a good distinction. Many people confuse confidence with being on home ground.', zh: '這個區分真的很好。很多人會把自信，誤以為是自己本來就在熟悉地盤上的結果。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And once you realize that, you become slower to judge other people in your own country too.', zh: '而一旦你意識到這件事，你回到自己國家之後，也會比較不那麼快去評斷別人。', vocab: [{ word: 'home ground', def: '自己熟悉、很有掌握感的環境' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'So perspective is not only about seeing more. It is also about judging less quickly.', zh: '所以視角改變不只是看到更多，也包括不那麼快下判斷。' },
        ],
      },
      {
        title: 'Part 3 — Seeing Scale Differently',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Another thing travel changes is scale. Your own concerns stop being the whole horizon.', zh: '旅行還會改變另一件事，就是尺度。你原本的煩惱不再是整個地平線。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. When you stand in a huge city or a remote landscape, your personal drama often shrinks a little.', zh: '對。當你站在一個很大的城市，或很遼闊的自然景色裡，自己的小劇場常常就會縮小一點。', vocab: [{ word: 'shrink a little', def: '不再那麼巨大、那麼佔滿心裡' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Not because your life stops mattering, but because it returns to proportion.', zh: '不是因為你的人生 suddenly 不重要，而是它回到了比較合理的比例。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That proportional feeling can be deeply calming.', zh: '而那種「回到比例」的感覺，其實很能安定人。', vocab: [{ word: 'return to proportion', def: '從過度放大中回到比較合理的尺度' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'I think many adults need that. They need reminders that they are not carrying the entire universe alone.', zh: '我覺得很多大人都需要這件事。他們需要被提醒：自己並不是一個人扛著整個宇宙。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Travel does that without words sometimes.', zh: '而旅行有時候根本不用言語，就能做到這件事。' },
        ],
      },
      {
        title: 'Part 4 — Perspective That Stays After the Trip',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'The interesting question is whether that perspective lasts after you come back.', zh: '有趣的問題是，那種視角在你回來之後，到底能不能留下來。' },
          { speaker: 'a', speakerName: 'Nina', en: 'I think some of it fades, but some of it becomes part of how you think.', zh: '我覺得一部分會淡掉，但也有一部分真的會進入你的思考方式裡。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Especially if you reflect on it instead of immediately rushing back into speed.', zh: '尤其如果你有花時間消化，而不是一回來就立刻衝回原來的節奏。', vocab: [{ word: 'reflect on it', def: '對經驗做整理、思考它帶來了什麼' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe keeping a few notes helps. Not just where you went, but what changed in how you saw things.', zh: '也許記一些筆記會有幫助。不是只記你去了哪裡，而是記你看事情的方式有什麼改變。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Otherwise the trip becomes a memory album instead of a lived lesson.', zh: '對。不然那趟旅程最後就只會變成一本相簿，而不是一個真的活過的功課。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And that would be a loss, because perspective is one of travel’s deepest returns.', zh: '而那其實很可惜，因為視角改變本來就是旅行最深的回報之一。' },
        ],
      },
      {
        title: 'Part 5 — Letting Travel Change You',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe the people most changed by travel are not the ones who go the farthest, but the ones who stay open.', zh: '也許真正被旅行改變最多的人，不一定是去得最遠的人，而是最願意保持開放的人。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'I think that is true. You can fly very far and still stay closed.', zh: '我覺得是真的。你可以飛很遠，但心還是完全沒有打開。', vocab: [{ word: 'stay open', def: '對差異、經驗和改變保持開放' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Whereas someone else can take a short trip and come back genuinely transformed.', zh: '相反地，有些人就算只是短短出去一下，回來也可能真的變了。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'So perspective is not guaranteed by geography. It depends on attention and humility.', zh: '所以視角改變不是地理位置自動保證的，它還是要看注意力和謙卑。', vocab: [{ word: 'not guaranteed by geography', def: '不是因為去得遠就一定會發生' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That makes travel sound less like consumption and more like practice.', zh: '這樣一說，旅行就比較不像消費，反而更像一種練習。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. A practice in seeing more, assuming less, and living a little wider than before.', zh: '對。那是一種練習，練習看得更多、預設更少，並且活得比以前更寬一點。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'leave familiar assumptions', zh: '離開熟悉的假設', example: 'Travel helps you leave familiar assumptions for a while.' },
      { en: 'familiarity is not intelligence', zh: '熟悉不等於聰明', example: 'A trip can remind you that familiarity is not intelligence.' },
      { en: 'return to proportion', zh: '回到合理比例', example: 'Travel can help your worries return to proportion.' },
      { en: 'a lived lesson', zh: '真正活過的功課', example: 'Reflection can turn a trip into a lived lesson.' },
      { en: 'not guaranteed by geography', zh: '不是去得遠就自動得到', example: 'Perspective is not guaranteed by geography.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 3,
    date: '2026-07-01',
    theme: 'Travel',
    title: 'Planning vs. Spontaneity on a Trip',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — The Need for Structure',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Do you think a good trip should be carefully planned, or mostly left open?', zh: '你覺得，一趟好的旅行應該仔細規劃，還是大部分留白比較好？' },
          { speaker: 'b', speakerName: 'Marcus', en: 'I think most trips need some structure, especially if time is limited.', zh: '我覺得大部分旅行還是需要一些結構，尤其當時間很有限的時候。', vocab: [{ word: 'some structure', def: '有基本安排與方向，但不是塞滿' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Flights, trains, where you sleep, and maybe one or two key places. Those things matter.', zh: '對。像航班、車票、住哪裡，還有一兩個真的很想去的地方，這些還是重要。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Without that, the trip can become stressful in a very preventable way.', zh: '如果連這些都沒有，一趟旅行很容易因為本來可以避免的事而變得很焦慮。' },
          { speaker: 'a', speakerName: 'Nina', en: 'So planning is not the enemy. It can actually protect your energy.', zh: '所以規劃本身不是敵人，它反而可能是在保護你的能量。', vocab: [{ word: 'protect your energy', def: '避免把體力和心力浪費在不必要的混亂裡' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Good planning should support experience, not suffocate it.', zh: '沒錯。好的規劃應該支持體驗，而不是把體驗悶死。' },
        ],
      },
      {
        title: 'Part 2 — When Planning Becomes Too Much',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'The problem starts when planning turns into control.', zh: '真正的問題，是當規劃慢慢變成控制。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Some people build such a full itinerary that they have no room left to feel the place.', zh: '對。有些人把行程排得太滿，滿到最後根本沒有空間真的去感受那個地方。', vocab: [{ word: 'itinerary', def: '旅行行程表、安排清單' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Then the trip becomes a checklist instead of an encounter.', zh: '那樣一來，旅行就會變成打勾清單，而不是一場相遇。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And ironically, people can return from a packed trip feeling like they were rushing through their own vacation.', zh: '而且很諷刺的是，有些人從超滿行程的旅行回來時，會覺得自己像是在趕自己的假。', vocab: [{ word: 'rushing through', def: '匆忙掠過，沒有真的停留' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'I have had trips like that. Too many plans, too little breathing room.', zh: '我真的有過那種旅行。計畫很多，但能呼吸的空間太少。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That is when efficiency starts defeating the purpose of travel.', zh: '那就是效率開始反過來毀掉旅行本來目的的時候。' },
        ],
      },
      {
        title: 'Part 3 — The Beauty of Leaving Room',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Some of the best travel memories happen in the unplanned parts.', zh: '很多最好的旅行記憶，反而發生在沒有規劃的部分。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. The random street you walked down, the café you found by accident, the extra hour you stayed because it felt right.', zh: '對。像是你隨便走進的一條街、意外找到的咖啡店，或因為感覺對了就多待了一小時。', vocab: [{ word: 'by accident', def: '不是刻意安排，而是剛好碰到' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Those moments usually cannot be optimized into existence.', zh: '那些時刻通常不是靠優化行程就能製造出來的。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. They require a bit of slack in the schedule and a willingness to follow curiosity.', zh: '沒錯。它們需要行程裡有一點餘裕，也需要你願意跟著好奇心走。', vocab: [{ word: 'slack in the schedule', def: '行程裡保留一點彈性和空白' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Which means spontaneity is not the absence of care. It is trust in the day.', zh: '那也代表，隨興不是不在乎，而是對當天的流動有一種信任。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'I like that. It makes spontaneity sound thoughtful instead of careless.', zh: '我喜歡這個說法。它讓隨興聽起來不是隨便，而是有感覺的。' },
        ],
      },
      {
        title: 'Part 4 — Different People Need Different Travel Styles',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'I also think travel style depends a lot on personality and stage of life.', zh: '我也覺得，旅行風格和個性、人生階段真的很有關。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Definitely. Some people feel calm only when they know the plan. Others feel trapped by too much structure.', zh: '真的。有些人只有知道計畫時才會安心，另一些人則會被太多安排困住。', vocab: [{ word: 'feel trapped', def: '覺得被卡住、沒有自由空間' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'And the same person may travel differently at twenty-five and at forty.', zh: '而且同一個人，在二十五歲和四十歲時，也可能會想要完全不同的旅行方式。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That is true. Energy, priorities, and tolerance for uncertainty all change over time.', zh: '這是真的。體力、優先順序，以及對不確定性的承受度，都是會變的。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'So maybe there is no ideal style, only a style that fits this trip and this season of life.', zh: '所以也許根本沒有最理想的旅行方式，只有適合這趟旅程、適合這個人生階段的方式。', vocab: [{ word: 'this season of life', def: '此刻的人生階段與狀態' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That feels much more realistic than trying to imitate someone else’s perfect trip online.', zh: '那聽起來比照著別人網路上的完美旅行去模仿，現實得多。' },
        ],
      },
      {
        title: 'Part 5 — Planning Enough, Then Letting Go',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe the best travel skill is planning enough, and then letting go at the right time.', zh: '也許最好的旅行能力，就是先規劃到剛剛好，然後在對的時候放手。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Build the frame, then leave room for reality to enter.', zh: '對。先把框架搭好，然後留一點空間讓真實發生。', vocab: [{ word: 'build the frame', def: '先建立基本框架和安排' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Because reality is where travel actually lives, not on the spreadsheet.', zh: '因為旅行真正活著的地方，是現場，不是在試算表上。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. A good trip is not the one where every plan succeeds. It is the one where you remain available to the experience.', zh: '沒錯。一趟好的旅行，不是每個計畫都成功，而是你整個人都仍然對體驗保持可用。', vocab: [{ word: 'remain available', def: '保持開放，不把自己封死在既定計畫裡' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That sounds like a useful lesson beyond travel too.', zh: '這聽起來其實也是旅行以外的人生課。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'It probably is. Good planning gives shape, and good spontaneity gives life.', zh: '大概真的是。好的規劃給了形狀，好的隨興則給了生命。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'some structure', zh: '基本結構', example: 'Most trips benefit from some structure.' },
      { en: 'protect your energy', zh: '保護自己的能量', example: 'Planning well can protect your energy.' },
      { en: 'slack in the schedule', zh: '行程裡的餘裕', example: 'Leave some slack in the schedule for surprises.' },
      { en: 'this season of life', zh: '此刻的人生階段', example: 'Your travel style may change with this season of life.' },
      { en: 'build the frame', zh: '先搭好框架', example: 'Build the frame, then stay open to the trip.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 4,
    date: '2026-07-02',
    theme: 'Travel',
    title: 'Traveling on a Budget Without Losing the Experience',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — The Money Question',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'A lot of people say they want to travel, but money becomes the immediate reason they do not.', zh: '很多人說自己想旅行，但一談到錢，這件事就立刻停住了。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That concern is real. Travel can be expensive. But people also sometimes assume the most expensive version is the only real one.', zh: '那個擔心當然是真的。旅行可以很花錢，但很多人也會不自覺地以為，最貴的版本才算真正的旅行。', vocab: [{ word: 'the money question', def: '和預算、花費直接相關的現實問題' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Which is a pity, because cost and depth are not always connected.', zh: '那其實很可惜，因為花費和深度，並不一定真的連在一起。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Some expensive trips are superficial, and some simple trips become unforgettable.', zh: '有些很貴的旅行其實很表面，有些很簡單的旅行反而讓人一輩子難忘。' },
          { speaker: 'a', speakerName: 'Nina', en: 'So maybe the better question is not only, "How much can I spend?" but also, "What kind of experience do I actually want?"', zh: '所以更好的問題，不只是「我能花多少」，還有「我真正想要的是哪一種體驗」。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Clarity about desire often saves more money than random cutting.', zh: '對。對自己想要什麼夠清楚，常常比亂砍預算更能省錢。' },
        ],
      },
      {
        title: 'Part 2 — Simpler Can Be Better',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'Budget travel often works best when people stop trying to copy luxury expectations cheaply.', zh: '平價旅行最有效的方式，常常是停止用低預算去硬模仿高級版本。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That is such a good point. Simpler travel becomes better once it stops apologizing for itself.', zh: '這真的說得很好。簡單的旅行一旦不再一直對自己道歉，反而會變得更好。', vocab: [{ word: 'luxury expectations', def: '高消費、高服務、高舒適度的期待' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Taking local transport, staying somewhere small, eating where ordinary people eat. That can be part of the richness.', zh: '搭當地交通、住小地方、去一般人吃飯的地方吃東西，這些其實都可以是旅行的豐富感。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And it often brings you closer to the actual rhythm of the place.', zh: '而且它往往會讓你更接近那個地方真實的節奏。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Budget choices sometimes create contact that comfort would have protected you from.', zh: '沒錯。有時平價的選擇反而會帶來更多接觸，而太舒適的選擇可能會把那些接觸隔開。', vocab: [{ word: 'actual rhythm', def: '一個地方真實的生活節奏與感覺' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'So cheaper does not automatically mean poorer. It can simply mean closer.', zh: '所以便宜不一定代表比較差，它有時只是代表比較靠近。' },
        ],
      },
      {
        title: 'Part 3 — Choosing What Matters Most',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'I think budget travel gets easier when people choose one or two things to care about deeply and let the rest stay simple.', zh: '我覺得，當一個人只挑一兩件自己真的很在意的事，其他部分簡單就好，平價旅行就會容易很多。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Maybe you care about food, or maybe you care about where you sleep, or maybe you care about staying longer.', zh: '對。也許你最在意的是食物，也許是在住宿，也許是在能待得比較久。', vocab: [{ word: 'stay simple', def: '保持簡單，不讓每個部分都變得很複雜或昂貴' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'But trying to maximize everything is usually what makes travel expensive and exhausting.', zh: '但如果每個部分都想一次拉到最高，通常就會讓旅行既貴又累。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'This is true in so many parts of life actually. Priorities create freedom.', zh: '這其實在很多人生場景都成立。當你知道優先順序時，反而比較自由。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And once you know what matters most, spending becomes more intentional instead of reactive.', zh: '而當你知道什麼最重要之後，花錢就會變得比較有意識，而不是被反應牽著走。', vocab: [{ word: 'intentional spending', def: '有選擇地花錢，而不是看到什麼就加什麼' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'That probably matters more than having a huge budget in the first place.', zh: '而這件事的重要性，大概比一開始預算有多大還更高。' },
        ],
      },
      {
        title: 'Part 4 — Slow Travel and Real Value',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'I also think slow travel is one of the best ways to make money go further.', zh: '我也覺得，慢旅行是最能讓預算發揮得更遠的方法之一。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Moving less often usually saves money and gives you a better feel for the place.', zh: '對。移動次數少一點，通常會更省錢，也比較能感受到地方本身。', vocab: [{ word: 'slow travel', def: '少跑幾個地方、每個地方待更久的旅行方式' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'It also reduces the stress of always checking out, re-packing, and rushing to the next station.', zh: '而且它也會減少那種一直退房、重新整理行李、趕下一站的壓力。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And maybe the deeper experience comes from staying long enough to stop being only a visitor.', zh: '而且也許真正比較深的體驗，就是從你待得夠久，久到不再只像觀光客開始。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. The first day is often surface. The later days are where texture appears.', zh: '沒錯。第一天通常都只是表面，後面幾天才會開始出現層次。', vocab: [{ word: 'texture appears', def: '更細膩、更多層次的感受開始浮現' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'So budget travel is not only about paying less. It can also be about experiencing more honestly.', zh: '所以平價旅行不只是花得少，它也可能是一種更誠實地體驗地方的方式。' },
        ],
      },
      {
        title: 'Part 5 — Experience Is Not the Same as Price',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe the biggest mindset shift is realizing that experience is not the same as price.', zh: '也許最大的心態轉換，就是意識到：體驗不等於價格。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Price can buy comfort, speed, and convenience, but not necessarily meaning.', zh: '對。價格可以買到舒適、速度和方便，但不一定買得到意義。', vocab: [{ word: 'convenience', def: '方便、省事、節省麻煩' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Meaning often comes from attention, openness, and the quality of how you move through a place.', zh: '意義常常是從注意力、開放程度，以及你怎麼穿過一個地方的方式裡長出來的。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That is good news for anyone who wants to travel without turning it into a luxury project.', zh: '這對那些想旅行、卻不想把旅行變成奢華專案的人來說，其實是個好消息。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. It means a meaningful trip may be more accessible than people think.', zh: '對。那表示有意義的旅行，可能比很多人想像中還更可接近。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And that makes the world feel a little less far away.', zh: '而這也會讓整個世界感覺沒有那麼遙遠。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'the money question', zh: '預算問題', example: 'The money question stops many people from traveling.' },
      { en: 'actual rhythm', zh: '真實節奏', example: 'Simple travel can bring you closer to the actual rhythm of a place.' },
      { en: 'intentional spending', zh: '有意識地花錢', example: 'Budget trips improve with intentional spending.' },
      { en: 'texture appears', zh: '層次開始出現', example: 'When you stay longer, the texture appears.' },
      { en: 'experience is not the same as price', zh: '體驗不等於價格', example: 'A good traveler learns that experience is not the same as price.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 5,
    date: '2026-07-03',
    theme: 'Travel',
    title: 'Culture Shock and How to Handle It',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — The Strange Feeling of Difference',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Culture shock is such a common part of travel, but it still surprises people every time.', zh: '文化衝擊明明是旅行裡很常見的一部分，但它每次發生時，還是會讓人很意外。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. People expect difference in theory, but living inside difference feels very different from imagining it.', zh: '對。人會在概念上預期差異，但真的活在差異裡，和想像差異是完全不同的事。', vocab: [{ word: 'culture shock', def: '進入不同文化後產生的不適應、困惑或衝擊感' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Even small things can be tiring. How loudly people speak, how much eye contact they use, when shops close.', zh: '有時連很小的事都會讓人累。像是大家說話多大聲、眼神接觸有多少，或店什麼時候關。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. The mind is constantly translating, comparing, and trying not to make mistakes.', zh: '沒錯。你的腦子會一直在翻譯、比較，而且還努力不要做錯。', vocab: [{ word: 'constantly translating', def: '一直把陌生環境轉換成自己能理解的方式' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Which means culture shock is not weakness. It is often just overload.', zh: '所以文化衝擊不是脆弱，它很多時候只是資訊過載。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That is an important reframe, especially for people who are hard on themselves.', zh: '這個重新理解很重要，尤其對那些很容易苛責自己的人。' },
        ],
      },
      {
        title: 'Part 2 — Curiosity Helps More Than Judgment',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'I think the healthiest response to culture shock is curiosity.', zh: '我覺得，面對文化衝擊最健康的反應，其實是好奇。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. If your first reaction is judgment, the whole place becomes irritating very quickly.', zh: '對。如果第一個反應是批判，那整個地方很快就會變得處處讓人煩。', vocab: [{ word: 'first reaction', def: '最先冒出來的本能反應' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'But if the question becomes, "Why is it done this way here?" then the discomfort turns into information.', zh: '但如果你的問題變成「這裡為什麼會這樣做」，那份不舒服就會開始變成資訊。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That does not mean you have to like everything. It just means you stay teachable.', zh: '這不代表你一定要喜歡每件事，它只是代表你讓自己保持可學習。', vocab: [{ word: 'teachable', def: '願意學、願意理解，而不是立刻封閉自己' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'And teachability is often what separates a rich trip from a shallow one.', zh: '而這種可學習性，常常正是把一趟旅行變深或變淺的差別。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. A curious traveler gets more than a comfortable traveler sometimes.', zh: '對。有時候，好奇的旅人得到的，真的會比舒服的旅人更多。' },
        ],
      },
      {
        title: 'Part 3 — Taking Care of Yourself Too',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'At the same time, I think people need to be kind to themselves when they are overwhelmed.', zh: '但同時，我也覺得當一個人真的被壓得太滿時，還是要對自己好一點。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Absolutely. Being open-minded does not mean forcing yourself to be endlessly adaptable.', zh: '完全同意。心胸開放，不代表你要逼自己永遠都適應得很好。', vocab: [{ word: 'overwhelmed', def: '被太多感受或資訊壓得很滿、快要承受不了' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Sometimes you need familiar food, some quiet time, or one evening without trying to understand everything.', zh: '有時候，你就是需要熟悉的食物、一點安靜時間，或一個晚上不要再努力理解所有事。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That is not failure. That is regulation.', zh: '那不是失敗，那其實是在調節自己。', vocab: [{ word: 'regulation', def: '幫助自己回到穩定狀態的調整' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'And once your nervous system settles, you can usually return to the difference with more grace.', zh: '而當你的神經系統稍微穩下來，你通常也比較能帶著餘裕重新面對那些差異。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Good adaptation needs recovery, not just effort.', zh: '沒錯。好的適應需要恢復，不只是硬撐。' },
        ],
      },
      {
        title: 'Part 4 — Learning Without Romanticizing',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'I also think it is important not to romanticize every cultural difference.', zh: '我也覺得，不要把每一種文化差異都浪漫化，這也很重要。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Respect does not mean pretending you understand everything immediately.', zh: '對。尊重不代表你得假裝自己立刻就什麼都懂。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Or pretending everything different is automatically wise or beautiful.', zh: '也不代表所有和你不同的東西，就自動比較有智慧或比較美。', vocab: [{ word: 'romanticize', def: '把某件事過度美化，忽略它真正的複雜性' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'A mature traveler can appreciate another culture while still noticing discomfort honestly.', zh: '一個成熟的旅人，可以一邊欣賞另一個文化，一邊誠實看見自己的不舒服。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That balance matters. Otherwise learning becomes performance again.', zh: '那個平衡很重要。不然學習最後又會變回一種表演。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And travel becomes less real when you are trying too hard to be the perfect global person.', zh: '而當你太努力想變成那種完美的世界公民時，旅行反而會變得沒那麼真。' },
        ],
      },
      {
        title: 'Part 5 — What Culture Shock Can Teach',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe culture shock is useful because it shows you where you are rigid.', zh: '也許文化衝擊之所以有用，是因為它會照出你在哪些地方其實很僵硬。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes, and also where you are afraid, where you are curious, and where you are more flexible than you thought.', zh: '對，還會照出你在哪裡害怕、哪裡好奇，以及哪裡其實比自己以為的更有彈性。', vocab: [{ word: 'rigid', def: '很固定、不容易鬆動或調整的' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'So it is not just a problem to get through. It is part of the education.', zh: '所以它不只是要熬過去的問題，它本身也是旅程教育的一部分。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Discomfort often marks the place where deeper learning begins.', zh: '沒錯。不舒服很多時候正是更深學習開始的地方。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That makes me think culture shock is almost a sign that the trip is doing real work on you.', zh: '這讓我覺得，文化衝擊某種程度上幾乎像是一個訊號，代表這趟旅程真的正在對你做功。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. If you let it teach you, discomfort can become one of the most valuable souvenirs you bring home.', zh: '對。如果你願意讓它教你，不舒服本身也可能成為你帶回家最有價值的紀念品之一。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'information overload', zh: '資訊過載', example: 'Culture shock is often information overload, not weakness.' },
      { en: 'stay teachable', zh: '保持可學習', example: 'A good traveler tries to stay teachable.' },
      { en: 'regulation', zh: '調節自己', example: 'Quiet time can be a form of regulation.' },
      { en: 'do not romanticize it', zh: '不要把它過度浪漫化', example: 'Respect a culture, but do not romanticize it.' },
      { en: 'part of the education', zh: '旅程教育的一部分', example: 'Culture shock can be part of the education.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 6,
    date: '2026-07-04',
    theme: 'Travel',
    title: 'Traveling With Other People',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — Compatibility Matters',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Traveling with other people can be wonderful, but it can also expose differences very quickly.', zh: '和別人一起旅行可以很棒，但也會很快把彼此的差異全部攤出來。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Some people like slow mornings, some want to leave at seven, and some need a lot of alone time.', zh: '對。有些人喜歡慢慢的早晨，有些人七點就要出門，也有些人需要很多獨處時間。', vocab: [{ word: 'compatibility', def: '彼此在節奏、習慣和需求上能不能合得來' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'A friendship can be strong and still not travel well.', zh: '一段友誼可以很好，但還是不一定適合一起旅行。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Travel compatibility is its own category.', zh: '沒錯。旅行合拍本身就是一個獨立的類別。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And people often learn that only after booking everything.', zh: '而很多人都是等到都訂完了，才發現這件事。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Which is why honest expectations matter before the trip, not only during it.', zh: '所以出發前先把期待講清楚真的很重要，不是等到旅途中才處理。' },
        ],
      },
      {
        title: 'Part 2 — Talking About Expectations',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'I think people avoid practical conversations because they want the trip to feel easy and exciting.', zh: '我覺得很多人會避開那些實際的討論，因為他們希望旅行一開始感覺輕鬆又興奮。' },
          { speaker: 'a', speakerName: 'Nina', en: 'But then they arrive with totally different expectations about budget, pace, and free time.', zh: '但結果到了現場，才發現彼此對預算、節奏和自由時間的想像完全不同。', vocab: [{ word: 'expectations', def: '對旅程安排、花費和感受的預想' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. One person thinks every meal should be shared, another wants flexibility. One wants museums, another wants cafés.', zh: '沒錯。一個人覺得每餐都應該一起吃，另一個人想保留彈性；一個想逛博物館，另一個只想去咖啡店。' },
          { speaker: 'a', speakerName: 'Nina', en: 'None of those preferences are wrong. The trouble is when nobody says them out loud.', zh: '那些偏好本身都沒有錯，真正麻煩的是沒有人把它們講出來。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'A short conversation beforehand can prevent so much resentment later.', zh: '出發前短短的一段對話，往往就能避免後面很多怨氣。', vocab: [{ word: 'say them out loud', def: '直接把心裡的需求說出來' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Travel gets easier when people stop assuming closeness means automatic agreement.', zh: '對。當人不再以為親近就等於自動會合拍，旅行就會容易很多。' },
        ],
      },
      {
        title: 'Part 3 — Togetherness and Space',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'I also think good travel with others includes some room to separate.', zh: '我也覺得，一趟好的同遊旅行，其實要包含一點分開的空間。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Absolutely. Being together all day every day is a lot, even for people who love each other.', zh: '完全同意。即使是彼此很喜歡的人，整天每一天都綁在一起，還是很多。', vocab: [{ word: 'room to separate', def: '允許彼此暫時分開、保有個人空間' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Sometimes one person wants to shop while another wants to rest. That should not be treated like rejection.', zh: '有時候一個人想逛街，另一個人想休息，這不應該被理解成拒絕。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. A little space often makes the time together warmer later.', zh: '對。一點點分開，反而會讓之後重新在一起時更有溫度。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That requires maturity though. Some people panic when togetherness is not constant.', zh: '但這還是需要成熟度。有些人只要發現不是一直黏在一起，就會開始不安。', vocab: [{ word: 'constant togetherness', def: '一直待在一起，幾乎沒有分開的時間' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'And travel quickly shows who can respect space without taking it personally.', zh: '而旅行真的很快就會照出，誰能尊重空間，而不把它理解成針對自己。' },
        ],
      },
      {
        title: 'Part 4 — Conflict on the Road',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'Travel conflict can get intense fast because everyone is tired, out of routine, and sometimes overstimulated.', zh: '旅行中的衝突很容易迅速升高，因為大家都累、離開日常，而且常常還被刺激得很滿。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. A small disagreement about directions can suddenly become a much bigger emotional argument.', zh: '對。像走錯路這種小事，有時突然就會膨脹成很大的情緒爭吵。', vocab: [{ word: 'overstimulated', def: '受到太多感官或情緒刺激，變得容易煩躁' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'That is why timing matters. Some conversations should wait until people have eaten and sat down.', zh: '所以時機很重要。有些對話應該等大家吃過東西、坐下來之後再談。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Hungry people are not usually wise people.', zh: '肚子餓的人通常不太會是有智慧的人。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Good travel communication is often very practical.', zh: '沒錯。好的旅行溝通，很多時候其實非常務實。', vocab: [{ word: 'timing matters', def: '選對談事情的時機很重要' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'And a little humor can save a lot too, especially when the mistake is already made.', zh: '而且一點幽默感也很救命，尤其是在錯已經發生之後。' },
        ],
      },
      {
        title: 'Part 5 — What Good Travel Together Feels Like',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'When travel with other people works well, what do you think makes it feel so good?', zh: '當和別人一起旅行真的很順時，你覺得那種好感到底是怎麼來的？' },
          { speaker: 'b', speakerName: 'Marcus', en: 'I think it is a mix of flexibility, generosity, and not making every preference into a principle.', zh: '我覺得是一種彈性、慷慨，還有不要把每個偏好都上升成原則。', vocab: [{ word: 'make every preference into a principle', def: '把每個小喜好都變成不能動的規矩' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That is such a good phrase.', zh: '這句話真的很好。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Because shared travel is not about winning every tiny decision. It is about protecting the spirit of the trip.', zh: '因為一起旅行不是要贏每一個小決定，而是要保住整趟旅程的氣氛和精神。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And maybe also remembering that the relationship matters more than whether you see one extra attraction.', zh: '而且也許還要記得，關係本身的重要性，常常比多去一個景點還更高。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. The best shared trips usually leave people feeling more connected, not more managed.', zh: '對。最好的同遊旅行，通常最後會讓人覺得彼此更連結，而不是更像彼此在管理彼此。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 'travel compatibility', zh: '旅行上的合拍程度', example: 'A strong friendship does not always guarantee travel compatibility.' },
      { en: 'say it out loud', zh: '直接說出來', example: 'Good travel starts when people say expectations out loud.' },
      { en: 'room to separate', zh: '分開一下的空間', example: 'Healthy group trips include room to separate.' },
      { en: 'timing matters', zh: '時機很重要', example: 'When people are tired and hungry, timing matters even more.' },
      { en: 'protect the spirit of the trip', zh: '保住整趟旅程的感覺', example: 'Sometimes you need to protect the spirit of the trip.' },
    ],
  },
  {
    weekNumber: 27,
    dayOfWeek: 7,
    date: '2026-07-05',
    theme: 'Travel',
    title: 'Coming Home After a Trip',
    phase: 'p4',
    parts: [
      {
        title: 'Part 1 — The Return Is Part of the Journey',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'People focus so much on leaving that they sometimes forget returning is part of the trip too.', zh: '大家太專注在出發，反而有時會忘記：回來其實也是旅程的一部分。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Coming home can feel comforting, but also slightly disorienting.', zh: '對。回家會讓人覺得安心，但同時也可能帶著一點微妙的不適應。', vocab: [{ word: 'disorienting', def: '讓人有點失去方向感、不太適應' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Especially after a meaningful trip. Part of you is back, but part of you is still catching up.', zh: '尤其是旅行很有感的時候。你的身體回來了，但內在有一部分還在慢慢追上。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Exactly. Re-entry has its own emotional weather.', zh: '沒錯。重新進入原本生活，也有它自己的情緒天氣。', vocab: [{ word: 're-entry', def: '從旅途重新回到日常生活的過程' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'And if people rush through that transition, they sometimes lose part of what the trip gave them.', zh: '而如果一個人太快略過那個轉換，有時就會把旅行帶回來的某些東西也一起弄丟。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Which is a shame, because the return is where meaning can settle.', zh: '那其實很可惜，因為回來之後，正是意義有機會沉澱下來的時候。' },
        ],
      },
      {
        title: 'Part 2 — Why Home Can Look Different',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'Have you noticed that home often looks different after travel?', zh: '你有沒有發現，旅行回來之後，家常常會看起來有點不一樣？' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Sometimes it feels more beautiful, and sometimes it feels strangely small.', zh: '有。有時會覺得它變得更可愛，有時又會覺得它突然變得有點小。', vocab: [{ word: 'look different', def: '因為自己的視角改變，而對原本熟悉事物產生不同感受' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'I think travel resets your eyes. You stop taking home completely for granted.', zh: '我覺得旅行會重置你的眼睛，讓你不再那麼理所當然地看待自己的家。' },
          { speaker: 'a', speakerName: 'Nina', en: 'And you also notice what you missed, and what you did not miss at all.', zh: '而且你也會開始發現，哪些東西你真的很想念，哪些東西你其實一點都沒想念。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'That contrast can be useful. It tells you something about your actual life.', zh: '那種對比很有用，它其實會告訴你一些你真實生活的線索。', vocab: [{ word: 'take for granted', def: '把原本擁有的東西視為理所當然' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. Sometimes a trip shows you what needs more appreciation, and sometimes it shows you what needs change.', zh: '對。有時一趟旅行會讓你看見什麼值得更珍惜，有時則讓你看見什麼其實需要改變。' },
        ],
      },
      {
        title: 'Part 3 — Keeping the Trip From Becoming Only Content',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'I also think people sometimes turn trips into content too quickly after coming back.', zh: '我也覺得，很多人一回來就太快把旅行變成內容在整理。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. They start selecting photos, posting highlights, and packaging the experience before they have even absorbed it.', zh: '對。他們會開始選照片、發精華、包裝經驗，但自己其實都還沒真正吸收完。', vocab: [{ word: 'absorb it', def: '把經驗慢慢消化成自己的理解' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'That is not always bad, but it can flatten something that was richer in real life.', zh: '那不一定是壞事，但它有時會把原本很豐富的經驗壓扁。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Because a post usually wants a clean story, while real travel is full of mixed feelings.', zh: '因為貼文通常想要一個乾淨的故事，但真實旅行常常充滿混雜的感受。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe that is why it helps to keep some part of the trip private for a while.', zh: '也許也正因如此，保留一部分旅程先不要公開，反而比較好。', vocab: [{ word: 'keep it private for a while', def: '先不急著分享，讓自己有時間消化' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Not every meaningful experience needs instant visibility.', zh: '對。不是每一段有意義的經驗，都需要立刻被看見。' },
        ],
      },
      {
        title: 'Part 4 — Bringing Something Back Intentionally',
        lines: [
          { speaker: 'b', speakerName: 'Marcus', en: 'What do you think is the best thing to bring back from a trip?', zh: '你覺得，一趟旅行最值得帶回來的是什麼？' },
          { speaker: 'a', speakerName: 'Nina', en: 'Not only souvenirs. I think the best thing to bring back is one change in how you live.', zh: '不只是紀念品。我覺得最值得帶回來的，是一個你真的願意放進生活裡的小改變。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'I love that. Maybe a slower breakfast, more walking, fewer assumptions, or more courage to explore nearby places too.', zh: '我很喜歡這樣說。可能是更慢地吃早餐、多走路、少一點預設，或者更願意探索自己附近的地方。', vocab: [{ word: 'bring back intentionally', def: '有意識地把旅途中得到的某種感受或習慣帶回生活' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'Exactly. Otherwise the trip stays separate from the rest of your life.', zh: '沒錯。不然旅行就只會和你其他的人生分得很開。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And maybe that is the real difference between consumption and transformation.', zh: '而也許，這正是消費和轉化之間真正的差別。' },
          { speaker: 'a', speakerName: 'Nina', en: 'Yes. A meaningful trip changes not only where you were, but how you return.', zh: '對。一趟有意義的旅行改變的，不只是你去過哪裡，還包括你怎麼回來。' },
        ],
      },
      {
        title: 'Part 5 — Staying Open at Home',
        lines: [
          { speaker: 'a', speakerName: 'Nina', en: 'Maybe the hardest part is keeping some of that openness after normal life resumes.', zh: '也許最難的部分，是在日常重新開始之後，還能保留一部分旅途中的開放感。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. Because routine quickly closes the mind again if you are not careful.', zh: '對。因為如果不小心，日常很快又會把人的心關回去。', vocab: [{ word: 'normal life resumes', def: '原本的日常節奏重新開始運作' }] },
          { speaker: 'a', speakerName: 'Nina', en: 'But maybe travel leaves a trace. A small reminder that there are always other ways to live, see, and move.', zh: '但也許旅行還是會留下一點痕跡。提醒你，世界永遠還有別的活法、看法和走法。' },
          { speaker: 'b', speakerName: 'Marcus', en: 'And if that reminder stays active, then the trip keeps working long after it ends.', zh: '而只要那個提醒還活著，旅行其實就會在結束很久之後，繼續對你發生作用。' },
          { speaker: 'a', speakerName: 'Nina', en: 'That may be why people keep leaving and coming back. Not to escape life, but to keep refreshing it.', zh: '也許這就是為什麼人會一直離開又回來。不是為了逃離生活，而是為了不斷刷新它。', vocab: [{ word: 'refresh it', def: '讓原本的生活重新變得有感、有新鮮度' }] },
          { speaker: 'b', speakerName: 'Marcus', en: 'Yes. A good trip ends, but the better way of seeing can remain.', zh: '對。一趟好的旅行會結束，但一種更好的看法可以留下來。' },
        ],
      },
    ],
    keyPhrases: [
      { en: 're-entry', zh: '重新進入日常的過程', example: 'Re-entry can be emotional after a meaningful trip.' },
      { en: 'take it for granted', zh: '把它視為理所當然', example: 'Travel can stop you from taking home for granted.' },
      { en: 'keep it private for a while', zh: '先保留一下，不急著公開', example: 'Sometimes it is better to keep a trip private for a while.' },
      { en: 'bring back intentionally', zh: '有意識地帶回生活', example: 'Try to bring back one lesson intentionally.' },
      { en: 'refresh your life', zh: '刷新自己的生活', example: 'A meaningful trip can refresh your life.' },
    ],
  },
]
